### ISSUE TITLE
ATP and CO2 production from Pi and O2

### ISSUE THREAD

**Issue by avlant** [SysBioChalmers/Human-GEM#102]
### Description of the issue:
The model is able to  produce infinite ATP and CO2 from Pi and O2. This can be prevented by blocking the flux through the pool reaction 'HMR_0686'.

#### Expected feature/value/output:
A model that does not produce infinite ATP and CO2 from Pi and O2.

**Comment by JonathanRob** [comment]
Ok, thanks for pointing this out. This fix will be implemented into the model.
