### ISSUE TITLE
Extracellular metabolites without exchange reactions

### ISSUE THREAD

**Issue by avlant** [SysBioChalmers/Human-GEM#117]
### Description of the issue:
There seems to be 4 extracellular metabolites that lack exchange reactions.

 20-hydroxy-arachidonate[Extracellular] 
 chenodiol[Extracellular] 
 LacCer pool[Extracellular] 
 Chylomicron Lipoprotein[Extracellular] 

Since they are outside of the cell they should be able to escape over the boundary.

#### Expected feature/value/output:
I would expect that each extracellular metabolite has an exchange reaction.

**Comment by Hao-Chalmers** [comment]
Here are the corresponding met ids:

`m00591`:   20-hydroxy-arachidonate
`m01435`:   chenodiol
`m02328`:   LacCer pool
`chylo_hs`:   Chylomicron Lipoprotein

**Comment by avlant** [comment]
@Hao-Chalmers I think this is all. I compared all metabolites in the extracellular compartment with the metabolites associated with exchange reactions identified using getExchangeRxns(model); But the test can be written as a single line:
setdiff(model.metNames(model.metComps == 1), model.metNames(model.metComps == 9))

**Comment by JonathanRob** [comment]
I also ran another check and found the same set of metabolites. I've written a script to implement these exchange reactions into the model, but I will first wait until PR #113 is incorporated before pushing the files.

**Comment by Hao-Chalmers** [comment]
@JonathanRob okay, let's hold this until #113 is done.

**Comment by JonathanRob** [comment]
Now PR #123 has added new exchange reactions for the 4 metabolites listed above. In addition, five reactions (`HMR_9736`, `xenobiotics`, `arachidonates`, `steroids`, and `others`) were found to involve transport between the boundary and a non-extracellular compartment. 

These reactions were revised to transport to the extracellular compartment, and a new reaction was added for those that did not have a corresponding exchange reaction from extracellular to boundary.

**Comment by Hao-Chalmers** [comment]
A
