### ISSUE TITLE
Additional gene associations for mitochondrial transport reactions

### ISSUE THREAD

**Issue by avlant** [SysBioChalmers/Human-GEM#119]
### Description of the issue:
I was looking into mitochondrial transport reactions and noticed that 4 reactions are missing the following gene associations. For the function I refer to the UniProt annotation and for the pubmed ID I copied the source in UniProt.

Reaction | Function | Gene | Uniprot | Name | PMID
-- | -- | -- | -- | -- | --
HMR_5124 | mitochondrial import of glycine | ENSG00000144659 | Q96DW6 | Mitochondrial glycine transporter | 27476175
HMR_4914 | mitochondrial import of COA | ENSG00000181035 | Q86VD7 | Mitochondrial coenzyme A transporter SLC25A42 | 19429682
HMR_9015 | mitochondrial import of SAM | ENSG00000144741 | Q70HW3 | S-adenosylmethionine mitochondrial carrier protein | 14674884
HMR_9020 | mitochondrial import of FAD | ENSG00000164933 | Q9H2D1 | Mitochondrial folate transporter/carrier | N/A

#### Expected feature/value/output:
It would be nice to also have these gene associations since several (3) of the reactions miss gene rules altogether.

**Comment by Hao-Chalmers** [comment]
This issue has been fixed in #163.
