### ISSUE TITLE
Invalid BiGG IDs

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#124]
### Description of the issue:
Many metabolite and reaction BiGG IDs in the association files (`humanGEMMetAssoc.JSON` and `humanGEMRxnAssoc.JSON`) are invalid, meaning they do not correspond to an ID in the BiGG database (version 1.5 at the time this issue was created).

For example, `ala_L` is the BiGG ID associated with L-alanine. However, the correct BiGG ID is `ala__L`.

This seems to have largely been due to the use of invalid BiGG IDs in Recon3D, from which many of HumanGEM BiGG IDs originated. Others are old or expired BiGG IDs, errors carried over from previous reconstructions, and other miscellaneous sources.

Regardless of the cause, all BiGG IDs in the model annotation files should either be valid, or removed.

#### Expected feature/value/output:
Association files with 100% valid metabolite and reaction BiGG IDs.

#### Current feature/value/output:
Based on comparison with BiGG database v1.5:
- Invalid/old metBiGGIDs: 2,874
- Invalid/old rxnBiGGIDs: 687

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@JonathanRob how many invalid BiGG ids were found here, if you have the specific numbers?

**Comment by JonathanRob** [comment]
- Invalid/old metBiGGIDs: 2,874
- Invalid/old rxnBiGGIDs: 687

**Comment by Hao-Chalmers** [comment]
Since the BiGG database has been continously changing and regularly updated, it would be better to explicitly indicate the database version onto the issue description, together with these invalid numbers.

**Comment by JonathanRob** [comment]
Good point. I have updated the description to include the database version (1.5) as well as the numbers I provided above.

**Comment by JonathanRob** [comment]
These BiGG ID updates have now been implemented (PR #135), so this issue can be considered solved.
