### ISSUE TITLE
Possible missing KEGG reactions

### ISSUE THREAD

**Issue by pinarkocabas** [SysBioChalmers/Human-GEM#126]
### Description of the issue:
Comparison of Homo sapiens reactions from KEGG with reaction KEGG IDs in HumanGEM suggested that the model might be missing some reactions from the KEGG database. For example, 

R00967: `UTP + Uridine <=> UDP + UMP`
R00589: `L-Serine <=> D-Serine`

were found as KEGG Homo sapiens reactions, but are not in the model. A complete analyses should be done to find all reactions that are in KEGG but missing from the model.

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
Closing this issue in favour of creating a plan of action under #253.
