### ISSUE TITLE
Create an "install" function for easy repo installation

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#136]
### Description of the issue:
Currently, there is no automated **"install"** function for the Human-GEM repo, and instead relies on users to manually add the directories to their MATLAB path. Creating an explicit install function to automatically add the (relevant) directories to the user's path would simplify the use of HumanGEM.

Since the repo contains many functions, scripts, datafiles, etc. that were only used once for implementing a curation/fix/update, this install function should not add directories containing such files (e.g., ComplementaryScripts/modelCuration). In doing so, we should also ensure that there are no important functions in these directories, and move them somewhere else if they are.

#### Expected feature/value/output:
A simple install function, e.g., `installHumanGEM.m` placed in the parent directory of the repository that users can run after downloading/cloning the repository and automatically add the relevant directories to their MATLAB path.

#### Current feature/value/output:
Currently, the user must manually add HumanGEM directories to their path.

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
@JonathanRob isn't this achieved through https://github.com/SysBioChalmers/Human-GEM-guide ?

**Comment by JonathanRob** [comment]
Yes, and I think now that we have deprecated the curation scripts/data, then my original concern and rationale for having this install function is largely resolved.
