### ISSUE TITLE
feat: lost annotation field in .yml file

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/Human-GEM#137]
### Description of the issue:
I noticed that the `annotation` field in the .yml file, which is parsed from RAVEN's fields `metMiriams` & `rxnMiriams`, is skipped in `writeHumanYaml.m`, even though RAVEN's `writeYaml.m` has it. Any reasons for skipping it? Any plans of introducing it? I find it very useful when quickly querying annotation data. See below how it looks for yeast-GEM:

* Metabolites:
![image](https://user-images.githubusercontent.com/9384349/66398312-d5788380-e9dd-11e9-8207-5a9a8af5411b.png)

* Reactions:
![image](https://user-images.githubusercontent.com/9384349/66398880-da8a0280-e9de-11e9-9f93-5a70cb8411d3.png)

**I hereby confirm that I have:**
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@BenjaSanchez the annotation information in `Human-GEM` is not lost, but preserved in JSON annotation [files](https://github.com/SysBioChalmers/Human-GEM/tree/master/data/annotation), as explained in #75.

This solution is a workaround to the pending [spec](https://github.com/SysBioChalmers/RAVEN/issues/184) of RAVEN/COBRA model fields, and the uncertainties of SBML libraries.

**Comment by mihai-sysbio** [comment]
A new `TSV` annotation format has been adopted through https://github.com/SysBioChalmers/Human-GEM/pull/212 .

As far as I can tell, there is no current plan of moving the annotation back into the `yml` file. That being said, the PMIDs are stored in the `yml` under `- references: `.

**Comment by Hao-Chalmers** [comment]
No plan for moving annotation from `tsv` to `yml`, so this issue is closed for now. Feel free to reopen.
