### ISSUE TITLE
Subsystems of r1146 and r1135

### ISSUE THREAD

**Issue by pecholleyc** [SysBioChalmers/Human-GEM#151]
### Description of the issue:
The subsystems assigned to reactions r1146 and r1135 seems incorrect. The (main) metabolites involve in these reactions are reactant/product of reactions in exclusively the Cholesterol metabolism subsystem.

#### Expected feature/value/output:
Assign the reactions to the Cholesterol metabolism subsystem.

#### Current feature/value/output:
Currently r1146 is assigned to the "Transport reactions" subsystem and r1135 is assigned to "Miscellaneous"

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
Thanks for posting the issue. I assume this suggestion is based on the metabolic network maps from [Metabolic Atals](https://metabolicatlas.org). If you can add a photo or a link to the map that provides this association.

**Comment by pecholleyc** [comment]
![image](https://user-images.githubusercontent.com/26245751/71092184-1099ee80-21a7-11ea-863a-1a6cffc9fc19.png)
Actually I suggested this based on the GEM Browser pages of the main metabolites:
https://www.metabolicatlas.org/explore/gem-browser/human1/metabolite/m00968r
https://www.metabolicatlas.org/explore/gem-browser/human1/metabolite/m03158r
https://www.metabolicatlas.org/explore/gem-browser/human1/metabolite/m00809r

The map is actually incorrect since r1146 is already assigned to the Cholesterol metabolism subsystem, but it helps to notice the problem. Indeed, it seems r1134 should also be assigned to that subsystem.

**Comment by Hao-Chalmers** [comment]
This map is a piece of strong evidence. The proposed change will be applied as soon as possible. Thanks @pecholleyc

**Comment by Hao-Chalmers** [comment]
Now this has been fixed in `devel`.
