### ISSUE TITLE
Connect the protein 3D structure data with human-GEM

### ISSUE THREAD

**Issue by hongzhonglu** [SysBioChalmers/Human-GEM#155]
The current human-GEM does not have protein 3D structures information for each protein, which limits its application in studying the function of mutation based on structures aided mutation cluster analysis and the model simulation.

**Comment by pecholleyc** [comment]
We have generated a GEM-PRO version of the model, using the GEM-PRO pipeline from the ssbio package (https://ssbio.readthedocs.io/en/latest/getting_started.html). It contains protein sequences and associate them to PDB IDs (but more could have been added).

This GP model is not stored in the Human-GEM repo, we have uploaded some of the data - including the GP model - to a Zenodo repository which will become public upon publication of the human1 model.

One may run the GEM-PRO pipeline (assuming this pipeline can add the 3D structures information you requested) right away with the model, no need to wait for publication.

**Comment by hongzhonglu** [comment]
@pecholleyc  Thanks for your information!

**Comment by Hao-Chalmers** [comment]
@hongzhonglu how do you to plan to connect GEMs with protein 3D structures information?

**Comment by hongzhonglu** [comment]
@Hao-Chalmers The human model connected with protein 3D structures has been done already. So we don't need to do it.
