### ISSUE TITLE
ec-code URI annotations often contain invalid characters

### ISSUE THREAD

**Issue by smoretti** [SysBioChalmers/Human-GEM#164]
### Description of the issue:
Lots of ec-code URI annotations are not valid because they contain invalid characters.
But also sometimes multiples EC that should be split in different annotations I guess.
This is linked with #93 and #127 but not only.
**INVALID resolution request**

#### Expected feature/value/output:
Should be something like
"http://identifiers.org/ec-code/1.1.1.141"

#### Current feature/value/output:
"http://identifiers.org/ec-code/1.1.1.141,1.1.1.196"
"http://identifiers.org/ec-code/:3.1.1.23"
"http://identifiers.org/ec-code/TCDB:4.C.1.1.5"
"http://identifiers.org/ec-code/ TCDB:4.C.1.1.8"
"http://identifiers.org/ec-code/1.3.3.6 4.2.1.17"
"http://identifiers.org/ec-code/ 3.6.3.1"
"http://identifiers.org/ec-code/1.3.99.- "
"http://identifiers.org/ec-code/  4.2.1.17 "

#### Reproducing these results:
Test one of the previous URI.

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@smoretti thanks for reporting the issues.

> Lots of ec-code URI annotations are not valid because they contain invalid characters

Can you give some examples of the invalid characters.

> But also sometimes multiples EC that should be split in different annotations I guess. 

Yes, multiple EC numbers will be splitted into separate URLs.

**Comment by mihai-sysbio** [comment]
Thanks @smoretti for reporting. This was at leat partly dealt with by @JonathanRob in #162.
A minor comment:
> "http://identifiers.org/ec-code/1.3.99.- "
seems to work fine for me.

**Comment by smoretti** [comment]
Invalid characters are " ", ":", "," as in examples I provided

**Comment by Hao-Chalmers** [comment]
Okay, all these cases will hopefully be resolved #162.

**Comment by JonathanRob** [comment]
Yes, these should all be fixed in #162.

**Comment by JonathanRob** [comment]
Closing this issue because it has now been fixed in [v1.3.2](https://github.com/SysBioChalmers/Human-GEM/pull/168).
