### ISSUE TITLE
Remove the boundary compartment from Human-GEM

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#172]
### Description of the issue:
The default Human-GEM model currently contains a boundary compartment [x], used to close mass balances on exchange reactions. For example, the exchange of oxygen between the extracellular compartment [s] and the boundary is formulated as:

`O2[s] <=> O2[x]`

However it is generally more common among the modeling community to formulate exchange reactions without the balancing boundary metabolite:

`O2[s] <==>  `

I propose that we change the "default" state of the model such that the boundary compartment is **removed**. Users can then choose to add it back when needed (e.g., for `checkTasks` or running tINIT) using the `addBoundaryMets` function:

`model = addBoundaryMets(model);`

The reason for my suggestions is that the boundary compartment is not really standard practice in the modeling community, and is often a source of confusion and compatibility problems. For example, if FBA is run on the model with boundary metabolites still present, flux through the biomass reaction (`biomass_human`) will be zero because the model is essentially in "closed" form. Users therefore need to go through the extra step of removing the boundary metabolites before running FBA and many other common analysis methods.

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@JonathanRob sounds good. How about start with a to-do list regarding this change?

**Comment by JonathanRob** [comment]
It's actually pretty straightforward; just need to run `simplifyModel` and remove the empty compartment. I've implemented it on the `removeBoundaryComp` branch, but I will wait to make a pull request until we've taken a bit of time to consider other potential necessary changes/effects, and to complete existing PRs.

**Comment by Hao-Chalmers** [comment]
I wonder if this removal affects any model manipulation and simulation functions from RAVEN?

**Comment by JonathanRob** [comment]
I'm only aware of two affected functions that rely on the presence of boundary metabolites (an `unconstrained` field): `checkTasks` and `getINITModel`. The `checkTasks` function gives a warning if its missing, and the `getINITModel` function gives an error.

Maybe @edkerk can confirm, but as far as I am aware, RAVEN is designed to work without boundary metabolites.

**Comment by edkerk** [comment]
RAVEN simulations indeed assume that no boundary compartment is present. @simas232 I remember there was an exercise at a course that relied on the boundary compartment being included, do you remember which RAVEN function was not working without boundary?

Regardless, we can also write a small function that adds a boundary compartment, takes the output of `getExchangeRxns` and add the corresponding metabolite in the new boundary compartment. Will be super easy to code, as metabolite ID for the [b] metabolite we could take the metabolite ID that is already present in the exchange reaction and append `_b`?

**Comment by JonathanRob** [comment]
Ok, that's what I thought, thanks @edkerk.

We actually have a function in this Human-GEM repo that adds boundary metabolites: `addBoundaryMets`. One option is to move this into RAVEN instead.

**Comment by simas232** [comment]
@JonathanRob, @edkerk, RAVEN already has a function which adds a boundary compartment (i.e. _closes_ the model), called `closeModel`.

@edkerk, I think that only tINIT related functionalities, including `fitTasks` require a boundary compartment. So we may simply enable `closeModel` automatically, if an input GEM does not have a boundary compartment.

**Comment by edkerk** [comment]
@simas232 Excellent, `closeModel` does exactly what I had in mind. So the changes @simas232 suggested can be applied to RAVEN, and then there is no problem whatsoever to remove boundary mets from Human-GEM.

**Comment by JonathanRob** [comment]
Ah ok, I didn't even know about `closeModel`, nice.

@edkerk, I'm not sure it's necessary to make any changes to RAVEN to accommodate the change. Or maybe simply update the existing error/warning messages that are thrown when the `unconstrained` field is missing so that they mention the `closeModel` function.

**Comment by JonathanRob** [comment]
Addressed in #179.
