### ISSUE TITLE
style/doc: cleanup authorship and timestamps

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/Human-GEM#176]
### Description of the issue:
I've seen the practice of including author names at the top of code files in `Human-GEM`. I'd like to open a discussion around this.
I feel author names at the top of a file can look prohibitive. But more importantly, I don't think this practice serves its purpose that well. To figure out who authored a file with git one can use [git blame](https://www.git-scm.com/docs/git-blame) or even easier [GitHub Blame](https://help.github.com/en/github/managing-files-in-a-repository/tracking-changes-in-a-file).
Perhaps this would also be a good time to reconsider the need for lines such as:
> % DATE CREATED:
%      MODIFIED:

#### Expected feature/value/output:
Removal of authorship and timestamp lines.

#### Current feature/value/output:
Logging of authorship and timestamp in code files.

#### Reproducing these results:
```
grep -nr "keyword" *  
```
where possible keywords are: Hao, Jonathan, DATE

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
Thanks @mihai-sysbio for bring up this issue that could be relevant to all GEM-type repos.

**Comment by Hao-Chalmers** [comment]
Would be nice to have a broader participation to this discussion @JonathanRob @simas232 @edkerk @BenjaSanchez

**Comment by JonathanRob** [comment]
> where possible keywords are: Hao, Jonathan, DATE
Hah! I like the idea of my name being used as a keyword to find lines of code to remove.

But yes, I think this system is outdated and I support the removal of such lines.

**Comment by BenjaSanchez** [comment]
I also don't think it makes sense to keep that info, I usually Github blame anyways.

**Comment by mihai-sysbio** [comment]
If authorship stats are ever needed, the [Contributors page](https://github.com/SysBioChalmers/Human-GEM/graphs/contributors) allows for time interval selection, but is limited to the master branch. One can also install `git-extras` and run [git summary](https://github.com/tj/git-extras/blob/master/Commands.md#git-summary) on any branch. That being said, the repository is quite noisy in the number of lines so I would other metrics.

**Comment by edkerk** [comment]
Agree to remove authorships and timestamps, just have a good look at the diff to make sure that not too many lines are deleted.

**Comment by Hao-Chalmers** [comment]
With full consensus, this has been implemented in #177 and fixe in `devel`.
