### ISSUE TITLE
Delete inactivated reactions

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#183]
### Description of the issue:
During the development of Human-GEM, many reactions were inactivated (lower and upper bounds set to zero) based on a lack of evidence and/or violation of mass balances. These reactions were not completely removed from the model to allow time to properly evaluate their removal (as suggested in #44), as undoing the removal can become complicated.

Now that we have had sufficient time to evaluate these **315** inactivated reactions, and because the yaml workflow is in place allowing easier tracking of such changes, I propose that we fully delete these reactions.

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
It's really cool that the `yaml` based workflow supports the removal of reactions. I'm wondering, does the reverse process hold, ie adding new content to the yaml file is sufficient to import new information into the model? You maybe see where I'm getting at: a GitHub Action to automatically create pull requests with new content identified from various databases.

**Comment by Hao-Chalmers** [comment]
It seems rather convenient and smooth to add/remove reactions through `yaml`, if there is no addition/deletion of metabolites.

**Comment by JonathanRob** [comment]
Yes, but keep in mind that we also need to update the corresponding annotation JSONs to keep them synced with the model, which at the moment is unfortunately a manual process.
