### ISSUE TITLE
Identical metabolites with slightly different names

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#184]
### Description of the issue:
There are currently several metabolites in Human-GEM that are duplicated due to very minor differences in their name (such as capitalization differences). For example, the following pairs of metabolites currently exist in the model:

Metabolite 1 | Metabolite 2
------------ | -------------
1,2-Dihydroxy-5-(Methylthio)Pent-1-En-3-One | 1,2-dihydroxy-5-(methylthio)pent-1-en-3-one
21-Hydroxypregnenolone | 21-hydroxypregnenolone
5Beta-Cholestane-3Alpha,7Alpha,27-Triol | 5beta-cholestane-3alpha,7alpha,27-triol
D-Alanyl-D-Alanine | D-alanyl-D-alanine
Homocarnosine | homocarnosine
Indole-5,6-Quinone | indole-5,6-quinone
Iso-A2E(11-Cis) | iso-A2E(11-cis)
Iso-A2E(9-Cis) | iso-A2E(9-cis)
Maltoheptaose | maltoheptaose
Maltohexaose | maltohexaose
Maltopentaose | maltopentaose
Maltotetraose | maltotetraose
Nifedipine | nifedipine
Phenylacetylglycine | phenylacetylglycine
Phytosphingosine | phytosphingosine
Thromboxane B2 | thromboxane B2

#### Expected feature/value/output:
Duplicated metabolites should be merged into a single metabolite entity.

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
Nice to catch them!

**Comment by mihai-sysbio** [comment]
I presume the preference is for lowercase naming?

**Comment by Hao-Chalmers** [comment]
The #213 exemplified a practical and clear workflow in dealing with duplicate metabolites, and the derived duplicate reactions. 

Some steps were summarized below and probably could serve as guidelines for checking and merging in the future:
- identify the pairs of duplicated metabolites by names or external ids
- solve the duplicated metabolites as pairs, focus on one pair at a time
- for a given pair, decide which to remove, preferably the one from other sources (e.g. Recon3D)
- replace one set of met ids (could be several if found in multiple compartments) with another set in the model, if possible add deleted one(s) as external ids to the `metabolite.tsv` annotation file
- identify duplicate reactions based on the S matrix
- for duplicate reaction pairs, usually keep HMR version and remove the others from the model (yaml file)
- update `reactions.tsv` annotation file with the reaction changes

**Comment by Hao-Chalmers** [comment]
This issue had been fixed by #213.
