### ISSUE TITLE
Empty MIRIAM cells in Excel file

### ISSUE THREAD

**Issue by pecholleyc** [SysBioChalmers/Human-GEM#189]
### Description of the issue:
As I understand it, the external identifiers / MIRIAM fields have been removed from the Matlab model, and are stored in JSON files now. The function to export the model to Excel format uses a RAVEN function that still expect to read the fields from the model. Consequently all MIRIAM columns in the exported Excel file are now empty.

#### Expected feature/value/output:
Add back the MIRIAM data to the Excel sheets. One way to do it would be to re-populate a temporary Matlab model object with the MIRIAM data before exporting into Excel.

#### Current feature/value/output:
Empty cells in MIRIAM columns in the Excel file

By comparing the Yeast-GEM Excel file with the Human-GEM one I found additional differences:
 - no SHORT NAME for genes in Human
 - reaction REFERENCE are only PMID numbers e.g. '21623372; 7765825' in Yeast but are prefixed and not necessary PMID in Human (e.g. 'PMID:367367;PMID:4203909;UNIPROT:P00558')
 - looks like values are separated with '; '  in Yeast but ';' in Human

So it is possible to have both Excel files formatted the same way? Following the standards if any. I am asking this because since Yeast do not use JSON for annotations, I am considering using the Excel to extract such information.

**I hereby confirm that I have:**
- [x] Tested my code on my own computer for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
Looking forward to see what others think. In the meantime, here's a random idea: it might be possible to extract annotation from an SBtab file, which can be obtained by using a [converter from SBML](https://www.sbtab.net/sbtab/default/converter.html).

**Comment by JonathanRob** [comment]
Export of the SBML version has the same issue, in that RAVEN draws annotation information from the MIRIAM fields. This [is addressed](https://github.com/SysBioChalmers/Human-GEM/blob/7e5212625f1068b6f4519114c83d8b393ce4444f/code/io/exportHumanGEM.m#L109) by calling the `annotateModel` function prior to exporting the SBML version.

A quick fix would be to call the `annotateModel` function prior to the .xlsx export as well. This actually should have been done in the first place, but I missed it.

As for the differing fields, I'm not sure if there are standards defined somewhere, but we can work together to migrate to a common format.

**Comment by JonathanRob** [comment]
This issue was addressed in #212 by updating the `exportHumanGEM` function (ec78d67) to add MIRIAM fields to the model before exporting to the `.xlsx` format.
