### ISSUE TITLE
duplicate metabolites in the model(take 2)

### ISSUE THREAD

**Issue by raphyz** [SysBioChalmers/Human-GEM#191]
Hi
I am aware of the case that JonathanRob wrote on duplicate metabolites.

#### Expected feature/value/output:

Here is the list of duplicate metabolites I found I think they are the same but I wrote them in met_id format:

M_m01094m:M_CE0233_m=5Beta-Cholestane-3Alpha,7Alpha,27-Triol_C27H48O3,
M_m02179c:M_CE5775_c=Iso-A2E(9-Cis)_C42H58NO,
M_m02587c:M_nfd_c=Nifedipine_C17H18N2O6,
M_m03164c:M_alaala_c=D-Alanyl-D-Alanine_C6H12N2O3,
M_m03163c:M_ind56qn_c=Indole-5,6-Quinone_C8H5NO2,
M_m02995s:M_txb2_s=Thromboxane B2_C20H33O6,
M_m02749c:M_phsphings_c=Phytosphingosine_C18H40NO3,
M_m02451s:M_maltttr_s=Maltotetraose_C24H42O21,
M_m00605c:M_21hprgnlone_c=21-Hydroxypregnenolone_C21H32O3,
M_m02587s:M_nfd_s=Nifedipine_C17H18N2O6,
M_m02447s:M_malthx_s=Maltohexaose_C36H62O31,
M_m02446s:M_malthp_s=Maltoheptaose_C42H72O36,
M_m02449s:M_maltpt_s=Maltopentaose_C30H52O26,
M_m02995c:M_txb2_c=Thromboxane B2_C20H33O6,
M_m02176c:M_CE5776_c=Iso-A2E(11-Cis)_C42H58NO,
M_m02451c:M_maltttr_c=Maltotetraose_C24H42O21,

I listed the ones with m02 as the ones that should stay and the others as the ones that should be removed.
I matched the metabolites by their names
the format of the lines is:
metabolite_that should stay:the metabolite that should be removed=metabolite name_formula

THe following list:
R_EX_maltpt__91__e__93__
R_NFDtd
R_RE2203C
R_PCRNtr
R_RE2202C
R_ELAIDCRNtd
R_C181CPT1
R_HMR_2608
R_EX_HC02180__91__e__93__
R_HMR_7262
R_EX_M02447__91__e__93__
R_LNLCCRNtd
R_HMR_1940
R_EX_malthp__91__e__93__
R_EX_maltttr__91__e__93__
R_HMR_1687
R_HMR_6621
R_WHARACHDtd

is of reactions that should be removed due to the duplication of the metabolites

As far as I can see the duplicate metabolites match the list given by JonathanRob in his comment although the names in a few cases do not match

I am running the model after converting it to sbml v2 so I think my code cant help you

Thank you 
Raphy zarecki

**Comment by Hao-Chalmers** [comment]
@raphyz many thanks for reporting these duplicated metabolites.

Since a similar issue is already existed - most of them had already been listed under #184, here I locked this issue. Could you please move the incremental findings there and keep everything in one place, assisting the follow-up fixing and tracking.
