### ISSUE TITLE
feat: tag Human-GEM releases to Zenodo

### ISSUE THREAD

**Issue by Hao-Chalmers** [SysBioChalmers/Human-GEM#194]
### Description of the issue:
* According to the [Zenodo discussion](https://github.com/MetabolicAtlas/standard-GEM/issues/14) on `standard-GEM`, a number of advantages could be taken through tagging the model releases to Zenodo. This feature therefore should be included to Human-GEM.

#### Expected feature/value/output:
* [x] Added a DOI badge that always points to the latest release in Zenodo 
* [x] Update `README.md` file to adapt to this change

**I hereby confirm that I have:**
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
Zenodo is now enabled for the next release. Old releases are not added automatically. To add the badge, a release must be first up on Zenodo. Releases can also be created manually. Any suggestions?

**Comment by Hao-Chalmers** [comment]
This suppose to be automatically tagged.

**Comment by mihai-sysbio** [comment]
Good, then I propose for this issue to remain open until the next release, when a DOI will be obtained and the badge can be added.

**Comment by mihai-sysbio** [comment]
I can now see the Zenodo badge on `devel`, so I'm closing this issue.
