### ISSUE TITLE
Gene-Reaction annotation correction

### ISSUE THREAD

**Issue by TunahanCakir** [SysBioChalmers/Human-GEM#198]
Hi,
Reaction HMR_8177 shows the formation of ganglioside GP1C from GQ1C. Currently, it is associated with the gene ST6GALNAC2. The gene name is "ST6 N-acetylgalactosaminide alpha-2,6-sialyltransferase 2". As the name suggests, the corresponding enzyme adds sialic acid into 2,6 position.

My biochemist colleague says that the conversion of GP1C to GQ1C  is by adding sialic acid into 2,8 position, not 2,6. Therefore, this reaction should be associated with the gene ST8SIA5 ("ST8 alpha-N-acetyl-neuraminide alpha-2,8-sialyltransferase 5"), not gene ST6GALNAC2.
Regards

**Comment by Hao-Chalmers** [comment]
@TunahanCakir Fantastic! Thank you very much for posting this message.

**Comment by Hao-Chalmers** [comment]
@TunahanCakir the PR #199 was prepared to correct the gene-reaction association to HMR_8177 as you reported. Could you please review the changes, and let us know if you have any other concerns.
