### ISSUE TITLE
Curate subsystems

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/Human-GEM#205]
### Description of the issue:
There is an overlap between these two subsystems:
- Metabolism of xenobiotics by cytochrome P450
- Xenobiotics metabolism

It might be good to combine these two subsystems.

#### Expected feature/value/output:
Only one xenobiotics subsystem.
Also, `Alkaloids Biosynthesis` should be `Alkaloids biosynthesis`.

#### Current feature/value/output:
By looking at the reaction ids, these subsystems seem to be inherited from different models.

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio can you specify the numbers of `Xenobiotics metabolism` subsystem before and after the proposed combining?

**Comment by mihai-sysbio** [comment]
I believe there are [131 replacements](https://github.com/SysBioChalmers/Human-GEM/pull/206/commits/33a8cc94ce4125a7634829c732f87d5c923dc00f#diff-3bcecb48b6715ebe7a47ee8984aa5a1d03945d005ca3f9f6e4f8a926e1644eb2).

**Comment by Hao-Chalmers** [comment]
Very good, so the numbers of `Xenobiotics metabolism` subsystem before and after #206 are **27** and **158**.
