### ISSUE TITLE
Subsystems missing from XML

### ISSUE THREAD

**Issue by Benfeitas** [SysBioChalmers/Human-GEM#209]
### Description of the issue:
While the [Human-GEM.xlsx](https://github.com/SysBioChalmers/Human-GEM/blob/master/model/Human-GEM.xlsx) and [Human-GEM.yaml](https://github.com/SysBioChalmers/Human-GEM/blob/master/model/Human-GEM.yml) contain `subsystem` information, this field appears to be missing from the [Human-GEM.xml](https://github.com/SysBioChalmers/Human-GEM/blob/master/model/Human-GEM.xml).

#### Expected feature/value/output:
Subsystem field in `Human-GEM.xml`.

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@Benfeitas thanks for posting the issue, which might also be helpful to others who have a similar question.

The `subsystem` information was provided in the `xml` file under the `<groups:listOfGroups>` slot with sboTerm: "SBO:0000633".

**Comment by Benfeitas** [comment]
Right! Sorry that I missed that, was looking for the term "subsystem" and missed SBO.

**Comment by JonathanRob** [comment]
To clarify @Hao-Chalmers response, the SBO terms are unrelated to subsystems.

**Comment by Hao-Chalmers** [comment]
@JonathanRob it seems that the SBO term "SBO:0000633" was designed for `subsystem` annotation according to the [scheme](http://www.ebi.ac.uk/sbo/exports/Main/SBO_OBO_lite.obo).

**Comment by Benfeitas** [comment]
@Hao-Chalmers It was probably my poor phrasing of my initial question. I meant the `Subsystem` field as in "Glycolysis", "Acyl-CoA hydrolysis" etc, as you find them in the excel version of the model. I can see that @JonathanRob 's answers my question

**Comment by JonathanRob** [comment]
@Hao-Chalmers SBO (Systems Biology Ontology) terms are not the same as subsystems (pathways) in our model. If you check the scheme you linked, you will see that those terms are quite different than pathways.

**Comment by Hao-Chalmers** [comment]
In my understanding, `xml` (or SBML) format evolves with the SBO scheme, which sometimes changes. So the associations defined by SBO terms would help in finding corresponding information in `xml` file.
