### ISSUE TITLE
mistaken GPR annotation of pyruvate dehydrogenase 

### ISSUE THREAD

**Issue by XuhangLi** [SysBioChalmers/Human-GEM#214]
### Description of the issue:
It seems the GPR annotation of HMR_4137 (pyruvate dehydrogenase) is mistaken. According to the GPR annotation of Recon3D (http://bigg.ucsd.edu/models/Recon3D/reactions/PDHm) and literature search (i.e,PMID: 22675509), the PDHA2 gene functions as an isoenzyme of PDHA1. Therefore, the GPR should be revised to DLD and PDHX and (PDHA1 or PDHA2) and DLAT and PDHB.

The current GPR resulted in false predictions in the application of gene expression integration. 
#### Expected feature/value/output:
DLD and PDHX and (PDHA1 or PDHA2) and DLAT and PDHB

#### Current feature/value/output:
DLD and PDHX and PDHA1 and DLAT and PDHA2 and PDHB

#### Reproducing these results:
NA

**I hereby confirm that I have:**
- [x] Tested my code on my own computer for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

*Note: replace [ ] with [X] to check the box. PLEASE DELETE THIS LINE*

**Comment by Hao-Chalmers** [comment]
@XuhangLi thank you very much for reporting this!

This GEM repository aims to serve, and also welcome contributions from, the research community.

The `Human-GEM` applies a `yaml-based` curation workflow that can be easily implemented by any participants. You can conduct the proposed changes by following steps:
1. fork `Human-GEM` repo to your local 
2. first switch to `devel` branch, and then start a new fixing branch
3. make the GPR change and update the reference directly to the `Human-GEM.yml` file within the fixing branch
4. generate a pull request for merging your fixing branch to the `devel` branch of `Human-GEM`

Thank you again and look forward to your pull request.

**Comment by JonathanRob** [comment]
Thank you for identifying this, @XuhangLi! I agree that the GPR annotation you have proposed looks correct.

To add to @Hao-Chalmers's comment, just let us know if you would prefer that we implement this fix for you.

**Comment by XuhangLi** [comment]
Hi Hao and Jonathan, 

Thanks your timely response! I am glad that I could help with the human model development. 

Per @JonathanRob's response, does it mean you guys will do the pull request for me? It would be great that I don't need to learn the yaml-based workflow, but I would be happy to do so if it is needed.

**Comment by Hao-Chalmers** [comment]
@XuhangLi yes we can do the modification and make the PR, which will include the proposed changes that can also be reviewed by you.

Btw, the yaml-based curation is convenient and straightforward.

**Comment by XuhangLi** [comment]
> @XuhangLi yes we can do the modification and make the PR, which will include the proposed changes that can also be reviewed by you.
> 
> Btw, the yaml-based curation is convenient and straightforward.

Great! Please go ahead and I will follow the process. 

Thanks again!

**Comment by Hao-Chalmers** [comment]
@XuhangLi please review this [GPR change](https://github.com/SysBioChalmers/Human-GEM/pull/216/files), which was modified as you requested.

**Comment by XuhangLi** [comment]
> @XuhangLi please review this [GPR change](https://github.com/SysBioChalmers/Human-GEM/pull/216/files), which was modified as you requested.

I followed up with a comment on the GPR change page. Please let me know if this is what you are looking for. Thanks!

**Comment by mihai-sysbio** [comment]
A new PR #222 was opened to resolve the additional feedback.
