### ISSUE TITLE
Invalid InChI identifiers

### ISSUE THREAD

**Issue by pecholleyc** [SysBioChalmers/Human-GEM#220]
### Description of the issue:
The InChI identifiers stored in the YAML file do not start with 'InChI=', which is normally the prefix of all InChI identifiers.
I think they were extracted from the MetaNetX chem_prop.tsv, but the prefix is present in that source file when downloaded directly from MetaNetX.

Also, the following InChI is duplicated/associated with 2 metabolites:
"1S/C27H46O2/c1-18(2)7-6-14-27(5,29)24-11-10-22-21-9-8-19-17-20(28)12-15-25(19,3)23(21)13-16-26(22,24)4/h8,18,20-24,28-29H,6-7,9-17H2,1-5H3/t20-,21-,22-,23-,24-,25-,26-,27-/m0/s1"
 Associated with m00592m (20-hydroxycholesterol) and m01183c (7alpha-hydroxycholesterol)

In addition, I wonder why the field is named 'inchis' and not just 'inchi' in the files/codes.

#### Expected feature/value/output:
 - all InChI identifiers to be prefixed with 'InChI='.
 - 1-to-1 association between metabolite names and InChI identifiers

#### Current feature/value/output:
- missing prefix 'InChI='
- InChI "1S/C27H46O2/c1-18(2)7-6-14-27(5,29)24-11-10-22-21-9-8-19-17-20(28)12-15-25(19,3)23(21)13-16-26(22,24)4/h8,18,20-24,28-29H,6-7,9-17H2,1-5H3/t20-,21-,22-,23-,24-,25-,26-,27-/m0/s1" is duplicated

#### Reproducing these results:
-

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ x] Done this analysis in the `master` branch of the repository
- [ x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
These existing InChI strings in the model were inherited from `HMR2`, not from the `MetaNetX`.

**Comment by pecholleyc** [comment]
Okay, good to know. When I search in the repo I saw that InChI strings were pulled out from 'chem_prop.xlsx' or chem_prop.tsv', but I was not sure how or if they are used then.
How do you suggested to fix the problem? I thought about modifying the annotations files, but looks like the InChIs are not stored there or maybe I'm missing something.

**Comment by Hao-Chalmers** [comment]
No, `InChI` strings are not included in the metabolite annotation file. They probably don't fit there either - their strings are usually extremely long in format.

**Comment by pecholleyc** [comment]
About the duplicated InChI, it seems straightforward, according to CHEBI, the 7α-hydroxycholesterol should have an other InChI ID.

**Comment by Hao-Chalmers** [comment]
Yes, the InChI string of `7α-hydroxycholesterol` can be assigned through the associated ChEBI id [17500](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17500).

**Comment by JonathanRob** [comment]
The reason that the `inchis` field was removed before exporting Human-GEM to SBML is because if a metabolite has an InChI entry, it (the RAVEN SBML export function) will **not** export its formula from the `metaboliteFormulas` field. In Human-GEM, the `metaboliteFormula` field has been heavily curated to ensure mass and energy balances, whereas the `inchis` field has not been curated. Therefore, when possible, the `metaboliteFormulas` field should always be treated with higher confidence than the `inchis` field.

As an additional note, many entries in the `metaboliteFormulas` field differ from those of other databases, such as MetaNetX. So any plans to update or replace metabolite formulas using an automated approach should be done with caution.

**Comment by Hao-Chalmers** [comment]
@JonathanRob with the high-confident values in the `metFormulas` field, are you suggesting to remove the inconsistent InChI strings from the model?

**Comment by JonathanRob** [comment]
@Hao-Chalmers essentially, yes - if the `inchi` formula disagrees with the `metFormulas` entry, then the `metFormulas` entry should be used.

**Comment by pecholleyc** [comment]
I checked, there are only 2 minor conflicts on `inchi` formula versus `metFormula`.  The order is just different in both cases:
C16H13ClN2O != C16ClH13N2O and C15H11ClN2O != C15ClH11N2O. Will fix this using CHEBI, in the same PR.

**Comment by Hao-Chalmers** [comment]
According to the [Hill system](https://en.wikipedia.org/wiki/Chemical_formula#Hill_system), chemical formulas should begin with carbon atoms, hydrogen atoms next and all others are then listed in alphabetical order. So `C16H13ClN2O` and `C15H11ClN2O` are correct.
