### ISSUE TITLE
Pubchem compound id duplicated/wrong

### ISSUE THREAD

**Issue by jorgemlferreira** [SysBioChalmers/Human-GEM#239]
Hello,

### Description of the issue:
m01778c and m02646c share the same pubchem.compound ID.

#### Expected feature/value/output:
m01778c should be 5461071 and m02646c should be 445639.

#### Current feature/value/output:
"**m01778c**"	"m01778"	"elaid"	"C00712"	"HMDB00573"	"CHEBI:27997"	"**445639**"	"LMFA01030073"	""	"HC00830"	"elaid"	"MNXM11476;MNXM306;MNXM92305"	"m01778c"

"**m02646c**"	"m02646"	"ocdcea"	"C00712"	"HMDB00207"	"CHEBI:16196"	"**445639**"	"LMFA01030002"	""	"HC00510"	"ocdcea"	"MNXM306"	"m02646c"

#### Reproducing these results:
NA

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@jorgemlferreira the correction of PubChem ids can be made to the metabolite annotation [file](https://github.com/SysBioChalmers/Human-GEM/blob/master/model/metabolites.tsv).
