### ISSUE TITLE
Compare the flux generated by Human gem model 

### ISSUE THREAD

**Issue by studymeow** [SysBioChalmers/Human-GEM#242]
Thank you very much for developing such a great model and it's really helpful. I am new to FBA and I recently used this model to generate some results of flux balance analysis. 

I hope I could get some suggestion on the model results process. To be more specific, I want to compare the fluxes with experimental fluxes and I have read the human gem paper "atlas of human metabolism".  I encountered the following figure. 

![07678CA7-C1B8-4114-96FB-57A8948E1792](https://user-images.githubusercontent.com/58016194/112114487-1fc7d300-8b86-11eb-9855-3d9efd24593f.jpeg)

I was just wondering why would we want to take the absolute value of fluxes to compare given the directionality of fluxes does matter. Do we have to it to compare the two fluxes? Can we just look at the original fluxes to calculate the correlation measure? 

Thank you so much!

**Comment by Hao-Chalmers** [comment]
@studymeow thanks for your interests to our work.

A brief answer to your question: this comparison demonstrates the capability of `ecHuman` models in predicting nutrient uptake rates by evaluating with some experimental measurements.

**Comment by JonathanRob** [comment]
Good question, @studymeow. Since I think it's more fitting as a Discussion rather than an Issue, I will convert this Issue to a Discussion.
