### ISSUE TITLE
Some of exchange reactions annotated as Miscellaneous

### ISSUE THREAD

**Issue by pranasag** [SysBioChalmers/Human-GEM#255]
### Description of the issue:
Some of metabolite exchange reactions are listed under "Miscellaneous" subsystem, while they should be moved to "Exchange/demand reactions".

#### Expected feature/value/output:
Would be simpler to mimic defined media with all exchange reactions present in the "Exchange/demand reactions" subsystem.

#### Current feature/value/output:
Reactions ('EX_pail_hs[e]', 'EX_CE1243[e]', 'EX_CE5026[e]', 'EX_5cysgly34dhphe[e]', 'EX_CE1261[e]', 'EX_galgluside_hs[e]', 'EX_ga1_hs[e]', 'EX_gm1a_hs[e]', 'EX_gm2a_hs[e]', 'EX_gm1_hs[e]', 'EX_gm1b_hs[e]', 'EX_gd1b_hs[e]', 'EX_gt1b_hs[e]', 'EX_nadh[e]') are listed in the wrong subsystem.

#### Reproducing these results:
See Excel version of the model, search for reactions mentioned above.

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@pranasag thanks for reporting this.

Please go ahead to make the proposed changes directly to the `Human-GEM.yml` file in a fixing branch after forking Human-GEM repo to your local.

**Comment by Hao-Chalmers** [comment]
@pranasag your PR has been merged, and this issue is thus closed.

We really appreciate your contribution to the community, and keep up with the great work!
