### ISSUE TITLE
Reaction HMR_8759 should have the GPR FMO1

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/Human-GEM#257]
### Description of the issue:
The GPR for [HMR_8759](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/HMR_8759)
```
2 hypotaurine[c] + O2[c] => 2 taurine[c]
```
should be `FMO1`, possibly `(FMO1 or  FMO3)`, but I doubt the latter is the right choice. source: https://www.biorxiv.org/content/10.1101/750273v1.full
This reaction forms a loop with [HMR_3911](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/HMR_3911)
```
H+[c] + NADH[c] + taurine[c] <=> H2O[c] + hypotaurine[c] + NAD+[c]
```
which also is missing a GPR. I don't think this GPR is known, but googling says that it shows Michaelis-Menten behaviors and is thus probably facilitated by an enzyme. The problem is that this loop is a way to regenerate NAD+ for glycolysis, and replaces lactate production in ec models, since it is for free. Making HMR_3911 unidirectional would solve the issue, but I don't know if that is ok to do. But it seems that the direction from hypotaurine to taurine is what everybody is talking about.

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@johan-gson thanks for the post.

Two questions:
1. Which GPR rule do you suggest for `HMR_8759`, `FMO1` or `FMO1 or FMO3`?
2. Can you double check if there is any reference that can be associated with `HMR_3911`?

**Comment by johan-gson** [comment]
So, I think the GRP rule should simply be FMO1, because this is the main gene doing this reaction. In the preprint, they saw that FMO3 also catalyses this reaction, but at much lower rate, and FMO5 at really low rate.

As for the other reaction, it seems it is directed both ways. But it is problematic, I'm pretty sure that this does not replace lactate production. But I don't know if we can do anything about it right now.

**Comment by johan-gson** [comment]
And, I didn't find a GPR reference for HMR_3911

**Comment by Hao-Chalmers** [comment]
@johan-gson thanks for the clarification, will start a branch for this fix.

**Comment by johan-gson** [comment]
The more I look at this, the more confused I get. It may be valuable if you also looked through the preprint, it is not that long. What I wonder is if these two reactions should be replaced by one that uses NAPDH as cofactor. I'm not so sure what to do with this anymore :)

**Comment by Hao-Chalmers** [comment]
The preprint was recently published in `Drug Metabolism and Disposition` ([32156684](https://pubmed.ncbi.nlm.nih.gov/32156684/)). Given the provided evidence demonstrating the catalysing role of `FMO1` in the production of taurine from hypotaurine, a fixing [branch](https://github.com/SysBioChalmers/Human-GEM/tree/issue257) was created for updating these changes.

@johan-gson as you suggested, `HMR_3911` was also modified to irreversible in this branch, in which please test out the feasiblity of the reaction direction change.

**Comment by johan-gson** [comment]
So, after some thinking, it is probably the reaction HMR_3911 that should have this GPR. And maybe we don't change anything else.

**Comment by Hao-Chalmers** [comment]
Yes, it does appear that the changes introduced in the [paper](https://pubmed.ncbi.nlm.nih.gov/32156684/) should be applied to `HMR_3911` according to the cofactor utilization.

**Comment by Hao-Chalmers** [comment]
As illustrated in [Fig3B](https://dmd.aspetjournals.org/content/48/5/378.long#F3) and the `Enzyme Assays` section, the reactants are **hypotaurine** and **NADH** (or **NADPH**). However, this contradicts the equation of [HMR_3911](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/HMR_3911) and all others: KEGG: [R01681](https://identifiers.org/kegg.reaction:R01681), MetaNetX: [MNXR107116](https://identifiers.org/metanetx.reaction:MNXR107116), Recon3D: [r0381](https://identifiers.org/vmhreaction:r0381).

**Comment by johan-gson** [comment]
I'm lost here now, I still don't from the evidence provided understand if NADH is really consumed, it just says it is a cofactor. Doesn't that mean that it is not consumed? My guess would be that the NADH should not be part of the reaction? But I'm not sure.

**Comment by JonathanRob** [comment]
This turned out to be a bit of an interesting case. From the [paper](https://pubmed.ncbi.nlm.nih.gov/32156684/) abstract:

> Despite the discovery in 1954 that the oxygenation of hypotaurine produces taurine, the identification of an enzyme catalyzing this reaction has remained elusive. In large part, this is due to the **incorrect assignment, in 1962, of the enzyme as an NAD-dependent hypotaurine dehydrogenase**.

So the dehydrogenase reaction (actually the reverse of [HMR_3911](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/HMR_3911) lacks evidence, and is actually a monooxygenase reaction, which I would assume has the (irreversible) stoichiometry:

O2 + hypotaurine + NADH + H+ --> taurine + NAD+ + H2O

So either HMR_3911 or HMR_8759 should be replaced with this equation, and the other removed. But I would suggest double checking the references for each reaction (also on Recon3D and VMH pages), to be sure that we're not missing something.

@Hao-Chalmers, your proposed reaction for HMR_8759 is unbalanced in protons.

@johan-gson cofactors can be changed by a reaction, the difference is that they are regenerated in a cycle (either with another reaction or within the same reaction). In this case, NADH is oxidized to NAD+, but can be reduced back to NADH by some other electron donor/enzyme elsewhere.

**Comment by Hao-Chalmers** [comment]
@JonathanRob thanks for the correction.

So the paper suggested such a reaction: `O2 + hypotaurine + NADH + H+ => taurine + NAD+ + H2O`, by which `HMR_8759` should be modified. 

While the other reaction `HMR_3911`: `H+[c] + NADH[c] + taurine[c] <=> H2O[c] + hypotaurine[c] + NAD+[c]`, should be removed (or blocked), given the conclusion that its assignment to `NAD-dependent hypotaurine dehydrogenase` is incorrect. 

And the `Oxidation of hypotaurine` references ([13979247](https://pubmed.ncbi.nlm.nih.gov/13979247/), [7295801](https://pubmed.ncbi.nlm.nih.gov/7295801/)), which previously were associated to `HMR_3911`, should be moved to `HMR_8759`.

**Comment by JonathanRob** [comment]
Since the newly proposed reaction is quite different from HMR_3911 and HMR_8759, I'm thinking that the correct approach may actually be to create a new reaction with the formula proposed above, and inactivate HMR_3911 and HMR_8759 (and eventually delete).

Again though, I would strongly suggest we first look into the databases/references associated with HMR_3911 and HMR_8759 to make sure that they really should be removed, since they are present in many other databases (MNX, Recon3D/VMH, BiGG, HMR2, etc.).

**Comment by Hao-Chalmers** [comment]
> Since the newly proposed reaction is quite different from HMR_3911 and HMR_8759, I'm thinking that the correct approach may actually be to create a new reaction with the formula proposed above, and inactivate HMR_3911 and HMR_8759 (and eventually delete).

sounds good to me

> Again though, I would strongly suggest we first look into the databases/references associated with HMR_3911 and HMR_8759 to make sure that they really should be removed, since they are present in many other databases (MNX, Recon3D/VMH, BiGG, HMR2, etc.).

Their common presence is a result copy/past between different data sources. Based on this new study, `HMR_8759` should be modified and `HMR_3911` should be removed. We can just block them first (ub = lb = 0), as we did before.
