### ISSUE TITLE
Fix reaction references (PMIDs)

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/Human-GEM#259]
### Description of the issue:
The yml file contains a `references` field for the biological/biochemical evidence of reactions. This field's content varied a bit in terms of formatting and quality. Through PR #254 the straightforward fixes have already been done with the goal of relying solely on PMIDs, with the `PMID:` prefix and separated by semicolon.

#### Current feature/value/output:
Some harder-to-fix references were only identified, highlighted with `??` and not fixed in the aforementioned PR.

#### Expected feature/value/output:
All `references`fields starting with `??` should have their content revised so that it adheres to the format `PMID:\d+`.

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
Very good point!

Any specific plan in fixing those with `??` symbols?

**Comment by mihai-sysbio** [comment]
I think it needs the attention of someone more familiar with the modelling. For example, does it make sense to keep as references text saying "added during gap filling"? Or what to do about references that are books without specific chapters or pages (which imho are not so useful)?

**Comment by Hao-Chalmers** [comment]
Sounds good to exclude all book references without specific chapters or pages.

**Comment by mihai-sysbio** [comment]
```
$ grep -inr "??" Human-GEM.yml | wc -l       
     196
```

Can somebody volunteer to finish looking at these cases? A fair number of these are duplicated (eg 10+ occurrences).

**Comment by Hao-Chalmers** [comment]
After excluding vaguely cited literature, non-PMID references can be moved to the `rxnNotes` field (#272) as a section (surrounded by semicolon).

Here I close this, and feel free to reopen if needed.

**Comment by mihai-sysbio** [comment]
I think this issue should be left open until there would be no `??` in the `references field.

**Comment by mihai-sysbio** [comment]
With #296 merged, I am going ahead and closing this issue.

An idea for future work is to improve the `- references` field by including some of the other identifiers that have been moved to the `- rxnNotes` field, e.g. `DOI:` and `ISBN:`. If somebody sees this and agrees, please create another issue and we can continue the discussion there.
