### ISSUE TITLE
spontaneous field is quoted if it is a 1, not quoted if zero

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/Human-GEM#262]
### Description of the issue:
It is just annoying when you read it in, you have to do some formatting, convert to number etc.

#### Reproducing these results:

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `master` branch of the repository
- [ ] Checked that a similar issue does not exist already

*Note: replace [ ] with [X] to check the box. PLEASE DELETE THIS LINE*

**Comment by johan-gson** [comment]
just to be clear, no quotes would be preferrable

**Comment by Hao-Chalmers** [comment]
@johan-gson the `spontaneous ` info was introduced by #162 as a numeric field

**Comment by Hao-Chalmers** [comment]
you will get the field as double type, if using the `importTsvFile` function provided by Human-GEM.

**Comment by JonathanRob** [comment]
@johan-gson is right, the file currently has quotes around `1`s. Someone must have accidentally modified this at some point.

It should be easily fixable by importing/re-exporting using the `importTsvFile` and `exportTsvFile` functions, respectively.

**Comment by johan-gson** [comment]
So, I can use the proper import function, I just think it is weird, and it messes things up a bit if you want to load it in R or something.

**Comment by JonathanRob** [comment]
Yes, it's not supposed to be like that, and should be fixed such that they're all numeric.

**Comment by Hao-Chalmers** [comment]
Ah, that's weird.

Some considerations:
- Add introduction of `tsv` structure and manipulation to README
- Add tests to `tsv` structure in `sanityCheck`

**Comment by mihai-sysbio** [comment]
With a bit of `git bisect`, it looks like the extra quoates slipped through in commit 98eb520aac6137aa013265f37f29fb490c669226 . @Hao-Chalmers good idea to also test the `tsv` files.

**Comment by Hao-Chalmers** [comment]
resolved in #263
