### ISSUE TITLE
redundant metabolite 'Undecanoyl-CoA'

### ISSUE THREAD

**Issue by ANiknejad** [SysBioChalmers/Human-GEM#268]
### Description of the issue:
Undecanoyl-CoA, is reported twice in human_gem:

- M_m03116m (also M_m03116c)

- M_undcoa_m

M_undcoa_m is identical to chebi:77547 which has correct stereo, while M_m03116 is actually hmdb:HMDB0013114, with incorrect stereo. We propose you map and conserve M_undcoa to represent 'Undecanoyl-CoA' in your human model.

Best regards,

Anne

Anne Niknejad
SIB, Vital-IT, MetaNetX curator

**I hereby confirm that I have:**

- [ X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@ANiknejad thanks for reporting this.

**Comment by Hao-Chalmers** [comment]
@ANiknejad are you suggesting to merge the duplicated `m03116m` and `undcoa_m` into one?

In addition to `Undecanoyl-CoA` reported here and `Tridecanoyl-CoA` reported in #269, there are other **5** similar cases as tabulated below:

| Metabolite name    |  id1   |      Name1        |      id2       |        Name2              |
|:-------------------|--------|:-------------------|-----------|:--------------------------|
| 5-Tetradecenoyl-CoA| m01141p| 5-tetradecenoyl-CoA| tetde5coa_p| 5-Tetradecenoyl Coenzyme A|
| 7-Hexadecenoyl-CoA | m01191p| 7-hexadecenoyl-CoA | hexde7coa_p| 7-Hexadecenoyl Coenzyme A |
| Heptanoyl-CoA      | m02107m| heptanoyl-CoA      | hepcoa_m   | Heptanoyl Coenzyme A      |
| Nonanoyl-CoA       | m02616m| nonanoyl-CoA       | noncoa_m   | Nonanoyl Coenzyme A       |
| Pentanoyl-CoA      | m02694m| pentanoyl-CoA      | pentcoa_m  | Pentanoyl Coenzyme A      |
| Tridecanoyl-CoA    | m03050m| tridecanoyl-CoA    | tridcoa_m  | Tridecanoyl Coenzyme A    |
| Undecanoyl-CoA     | m03116m| undecanoyl-CoA     | undcoa_m   | Undecanoyl Coenzyme A     |

Each pair appears to point to the same metabolite according to their names. Do you think should they all be merged?

**Comment by JonathanRob** [comment]
Thank you for identifying this duplication, @ANiknejad, as well as the similar case in #269. And good spotting, @Hao-Chalmers, it seems that this duplication extends to 7 pairs - an unfortunate remnant of the difficult de-duplication process after merging HMR2 and Recon3D.

@ANiknejad, I don't quite understand your comment on the difference in stereo between the metabolites. As far as I can tell, the stereo for [hmdb:HMDB0013114](https://hmdb.ca/metabolites/HMDB0013114) and [chebi:77547](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:77547) are the same. Let me know if I'm misunderstanding - and if so, is there a "correct" HMDB ID we can use instead?

**Comment by ANiknejad** [comment]
hi @JonathanRob , I guess, the answer was given during the meeting, right? I mean, we told we are focusing in using Chebi metabolites as the representative one for a given group of metabolites, whenever it is possible.

**Comment by JonathanRob** [comment]
Yes, @ANiknejad, after our discussion we decided it is not critical at this time to identify a replacement HMDB ID for this case.
