### ISSUE TITLE
xref in 'pool' metabolite

### ISSUE THREAD

**Issue by ANiknejad** [SysBioChalmers/Human-GEM#273]
Hello HumanGEM team,

There are xref of defined metabolites into 'pool metabolite' see this example:

M_MAM00535 1-lysolecithin pool M_MAM00535c C9H19NO7PR 0 chebi:71980;kegg:C04233;lipidmaps:LMGP0105AA00;mnx:MNXM447;vmhmetabolite:M00535

Maybe better to have xref of other pool metabolites from other models? Because with these xref into 'pool' during the reconciliation process we get a group of metabolites that at the end do not belong to the same group of metabolites:

chebi:71980   N-retinylidene-N-retinylethanolamine

kegg:C04233  1-Lysolecithin

LMGP0105AA00     2-acyl-sn-glycero-3-phosphocholine 

I checked other issues, and maybe this one is related to issue #197 ? sorry in advance.

best regards,

Anne

**I hereby confirm that I have:**
- [ X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@ANiknejad sorry for the late response. What do you suggest here specially?

**Comment by ANiknejad** [comment]
Hi @Hao-Chalmers, no worries of course!

M_MAM00535 1-lysolecithin pool M_MAM00535c C9H19NO7PR 0 chebi:71980;kegg:C04233;lipidmaps:LMGP0105AA00;mnx:MNXM447;vmhmetabolite:M00535

Actually, I guess, the issue is that chebi:71980 is a wrong xref for 1-lysolecithin, right? then the other xrefs sound ok to report '1-lysolecithin pool'. My bad about a wrong description of the problem in my first message, sorry about that!

**Comment by Hao-Chalmers** [comment]
@ANiknejad it does appear so. Please move on to fix this by removing the chebi id.

**Comment by ANiknejad** [comment]
@Hao-Chalmers  but this is in your side, right?
https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00535c

"
External databases

ChEBI | CHEBI:71980
"

how can I remove this xref?

**Comment by Hao-Chalmers** [comment]
the annotation revisions can be directly made to [`metabolites.tsv`](https://github.com/SysBioChalmers/Human-GEM/blob/main/model/metabolites.tsv) or [`reactions.tsv`](https://raw.githubusercontent.com/SysBioChalmers/Human-GEM/main/model/reactions.tsv) files first in the `develop` branch of this repo. And then these changes will be incorporated into **Met Atlas** web portal later once new version is released.

**Comment by Hao-Chalmers** [comment]
fixed in #302
