### ISSUE TITLE
Error: could not retrieve gene annotation from Ensembl

### ISSUE THREAD

**Issue by Hao-Chalmers** [SysBioChalmers/Human-GEM#278]
### Description of the issue:
* Errors occurred when updating `genes.tsv` using script `fetch_ensembl_gene_annotations.py` with the latest Ensembl release **104** (default parameters) as below:
 
```
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000100101'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000189366'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000240224'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000243135'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000255730'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000259916'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000272916'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000284844'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000285043'
Error: could not retrieve Ensembl annotations for gene ID 'ENSG00000285269'
```

These errors could be due to format changes in annotation data (extracted by `retrieve_ensembl_gene_annotations`) and deprecated IDs ([ENSG00000240224](https://www.ensembl.org/Homo_sapiens/Gene/Idhistory?g=ENSG00000240224) was replaced with [ENSG00000288705](https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000288705), [ENSG00000243135](https://www.ensembl.org/Homo_sapiens/Gene/Idhistory?g=ENSG00000243135) was replaced with [ENSG00000288702](https://www.ensembl.org/Homo_sapiens/Transcript/Idhistory?g=ENSG00000288702)). There won't be errors if specifying to release 103 (`--ensembl-version 103 --genome-version 38`).

#### Expected feature/value/output:
* There should be format changes to the annotation information of genes uniquely annotated by Ensembl, the `fetch_ensembl_gene_annotations` script therefore should be modified to adapt to these changes
* A mechanism could be potentially formulated for routine replacement of deprecated gene IDs

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by pecholley** [comment]
Regarding the deprecated IDs, I'm not sure it is the first time such cases occurred, perhaps it was fixed manually in the past? I think that having an automatic way to fetch the replacement IDs is possible and a good idea. It should probably be done prior running the `fetch_ensembl_gene_annotations.py` script.

About the other errors, indeed there were changes in Ensembl causing them:
- Ensembl removed some of the gene names/symbols (described [here](https://www.ensembl.info/2021/03/15/retirement-of-clone-based-gene-names/)). I can fix the script to allow empty values in the `geneSymbols` column, doing so the following 7 IDs will be empty: ENSG00000285043, ENSG00000255730, ENSG00000259916, ENSG00000272916, ENSG00000100101, ENSG00000284844, ENSG00000285269. Will it break other scripts in the repo?

- ENSG00000189366 is a different case, the gene was [previously](http://feb2021.archive.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000189366;r=3:125929275-125937039) a `Protein coding` gene, but has been [changed](http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000189366;r=3:125928840-125990565) to `Transcribed unprocessed pseudogene` with not Translation ID (ENSP IDs) associated to it. I can also allow empty values in the `geneENSPID` column but does it make sense? If not, checking the gene type can possibly be done along with the verification of the deprecated IDs in a new script.

**Comment by Hao-Chalmers** [comment]
My quick answers:

> Regarding the deprecated IDs, I'm not sure it is the first time such cases occurred, perhaps it was fixed manually in the past?

Yes, it happened [before](https://github.com/SysBioChalmers/Human-GEM/issues/7) and was fixed manually.

> I think that having an automatic way to fetch the replacement IDs is possible and a good idea. It should probably be done prior running the fetch_ensembl_gene_annotations.py script.

Agree, that would be an ideal. While a light-weight fix could be enabling `fetch_ensembl_gene_annotations.py` script to report such cases that often are just a few.

**Comment by Hao-Chalmers** [comment]
> - Ensembl removed some of the gene names/symbols (described here). I can fix the script to allow empty values in the geneSymbols column, doing so the following 7 IDs will be empty: ENSG00000285043, ENSG00000255730, ENSG00000259916, ENSG00000272916, ENSG00000100101, ENSG00000284844, ENSG00000285269. Will it break other scripts in the repo?

> - ENSG00000189366 is a different case, the gene was previously a Protein coding gene, but has been changed to Transcribed unprocessed pseudogene with not Translation ID (ENSP IDs) associated to it. I can also allow empty values in the geneENSPID column but does it make sense? If not, checking the gene type can possibly be done along with the verification of the deprecated IDs in a new script.

Currently, the Ensembl IDs are used as gene identifiers in Human-GEM. For other columns (e.g. geneSymbols, ENSP IDs), IMO it is therefore okay to allow empty values.
