### ISSUE TITLE
wrong gene annotation?

### ISSUE THREAD

**Issue by PkiwiBird** [SysBioChalmers/Human-GEM#279]
The Human-GEM model seems to have a gene (SLC22A5) that is incorrectly annotated to reaction HMR_2590. At least in the articles I have read, SLC22A5 codes for OCTN2 that transports carnitine from outside cell to inside cell (cellular uptake), whereas HMR_2590 transports carnitine between mitochondria and cytosol. If I am wrong I would kindly ask you to provide the name of the article proving otherwise.
Best Regards.

**Comment by Hao-Chalmers** [comment]
@PkiwiBird thank you very much for reporting this.

You claimed that gene SLC22A5 (OCTN2) should not be assigned to reaction `HMR_2590` (now renamed to [MAR02590](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02590)). Could you please help to clarify following questions:
1. What is the literature reference that contradicts against the above assignment?
2. In addition, should SLC22A5 be replaced with another gene? if so, what would be the new gene, and any supporting literature?
3. Should SLC22A5 be assigned to any other reaction(s) in Human-GEM?

**Comment by PkiwiBird** [comment]
> @PkiwiBird thank you very much for reporting this.
> 
> You claimed that gene SLC22A5 (OCTN2) should not be assigned to reaction `HMR_2590` (now renamed to [MAR02590](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02590)). Could you please help to clarify following questions:
> 
> 1. What is the literature reference that contradicts against the above assignment?
> 2. In addition, should SLC22A5 be replaced with another gene? if so, what would be the new gene, and any supporting literature?
> 3. Should SLC22A5 be assigned to any other reaction(s) in Human-GEM?

1. there is no literature contradicting, but there is also not supporting (at least that I know). [Here](https://www.genecards.org/cgi-bin/carddisp.pl?gene=SLC22A5) states that it is involved in 'active **cellular uptake** of carnitine', so in the cell membrane. In table 1 of [this article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6982704/) it also says it is in cell membrane. [Here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7530336/) says: 'General Features of OCTN2 (SLC22A5). The **membrane** transporter OCTN2 is one of the upstream players of the carnitine network'. Carnitine itself is involved in transport of metabolites between cytosol and mitochondria, as it is part of carnitine shuttle, but SLC22A5 does not seem to belong to the carnitine shuttle in mitochondria.

2. The protein that carriers carnitine between mitochondria and nucleus is: CAC and the gene that codes it is SLC25A20, which is already associated with reaction [MAR02590](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02590). [Here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6982704/) says 'Acyl-carnitines are further transported through the inner mitochondrial membrane by carnitine-acylcarnitine carrier (CAC/SLC25A20) in an exchange reaction with free l-carnitine leaving the mitochondrial matrix'.

3. It is already correctly associated in the model with carnitine transport between extracelular compartment and cytoplasm: [MAR08676](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08676)

**Comment by Hao-Chalmers** [comment]
@PkiwiBird thanks for your thorough inspection!

> 1. there is no literature contradicting, but there is also not supporting (at least that I know). Here states that it is involved in 'active cellular uptake of carnitine', so in the cell membrane. In table 1 of this article it also says it is in cell membrane. Here says: 'General Features of OCTN2 (SLC22A5). The membrane transporter OCTN2 is one of the upstream players of the carnitine network'. Carnitine itself is involved in transport of metabolites between cytosol and mitochondria, as it is part of carnitine shuttle, but SLC22A5 does not seem to belong to the carnitine shuttle in mitochondria.

Based on above answer, it makes sense to remove gene assignment of SLC22A5 (ENSG00000197375) from reaction MAR02590. Would you like to move forward to implementing the changes you proposed?
