### ISSUE TITLE
cytosolic proton in in non-cytosolic reactions

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/Human-GEM#282]
### Description of the issue:
Reaction [MAR05259](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05259) is pumping out a proton in cytosol, according to its reaction equation. Because of this, all of the reaction associated genes end up also being associated to the cytosol.

#### Expected feature/value/output:
[MAR05259](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05259) would be expected to have all metabolites in one compartment (lyososme) by using [MAM02039l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02039l).

#### Current feature/value/output:
MAR05259 produces [MAM02039c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02039c).

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
It does appear that the proton should be lysosomal version instead of cytosol one (MAM02039), which probably was added via charge balancing?

**Comment by JonathanRob** [comment]
Not sure whether it was added during charge balancing or some other reason, but I agree that the compartment should be changed as @mihai-sysbio suggests.

**Comment by Hao-Chalmers** [comment]
Yes, go ahead with the change if it's mass- and charge-balanced.

**Comment by mihai-sysbio** [comment]
It is hard to find the change so way back before the `yml`-based workflow was in place. As far as I can see in the `yml` file, the change was introduced as part of the commit fe8d50e46d3056324eb20c0e03dfc0bbae42b8d1 which was the last commit before merging `1.2` via #148. It does look like the change was part of the rebalancing process since it shows up in a file named [rebalance_modelChanges_rxns.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/fe8d50e46d3056324eb20c0e03dfc0bbae42b8d1/ComplementaryData/modelCuration/fullRebalance/rebalance_modelChanges_rxns.tsv#L546).

**Comment by mihai-sysbio** [comment]
I would also want to mention that there is a related reaction [MAR05258](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05258) taking place fully in the cytosol.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio the reaction MAR05259 most likely is not the only case of mixing cytosol proton with rxns in another compartment. Could a thorough check be conducted for this?

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio the reaction MAR05259 most likely is not the only case of mixing cytosol proton with rxns in another compartment. Could a thorough check be conducted for this?

The cytosol proton is involved in over 1k reactions, but I did look at all reactions where the coefficient was large, ie. not +-1, and could not find any similar cases.

**Comment by Hao-Chalmers** [comment]
Apart from MAR05259, there are two additional similar cases [MAR02041](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02041) (from ER) and [MAR04758](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04758) (Mitochondrion) that have: i) cytosol proton involved; ii) but all other metabolites in another compartment.

**Comment by Hao-Chalmers** [comment]
The cytosol proton in these three reactions (MAR05259: lysosome; MAR02041: ER; MAR04758: Mitochondrion) may be fixed together.

**Comment by mihai-sysbio** [comment]
While I see how MAR02041 should be fixed by using a different proton, I'm not sure what to say about MAR04758, especially after looking at the reactions facilitated by gene [`FACH`](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000066926). I am more tempted to simply delete MAR04758 since it would otherwise duplicate MAR01044.

**Comment by Hao-Chalmers** [comment]
> I am more tempted to simply delete MAR04758 since it would otherwise duplicate MAR01044.

makes sense

**Comment by mihai-sysbio** [comment]
Actually, it looks like [MAR02041](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02041) should also be carefully merged with [MAR01459](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR01459).

**Comment by Hao-Chalmers** [comment]
will look into this

**Comment by Hao-Chalmers** [comment]
After looking into the MAR04758 and MAR02041 reactions, it is found that each is duplicated with another as detailed below:

- MAR04758   <=>  MAR01044

|    rxn ID     | MAR04758           | MAR01044  |
| ------------- |:-------------:|:------:|
| compartment   | mitochondrion | mitochondrion |
| cytosolic H+      | yes     |   no |
| GPR     | ENSG00000066926     |   ENSG00000066926 |
| source | HMR     |    Recon |
| planned action | remove    |    keep |

- MAR02041   <=>  MAR01459

|    rxn ID     | MAR02041           | MAR01459  |
| ------------- |:-------------:|:------:|
| compartment   | ER | ER |
| cytosolic H+      | yes     |   no |
| GPR     | ENSG00000025423 or ENSG00000086696 or ENSG00000108786 or ENSG00000132196 or ENSG00000149084 or ENSG00000198189 or ENSG00000204228     |   ENSG00000132196 |
| source | HMR     |    Recon |
| planned action |    |   |

**Comment by mihai-sysbio** [comment]
Sounds good to me, I'll go ahead and implement this.

**Comment by mihai-sysbio** [comment]
I think this issue can be closed, since #283 was merged.
