### ISSUE TITLE
ATP maintenance in the biomass equation imbalanced

### ISSUE THREAD

**Issue by pranasag** [SysBioChalmers/Human-GEM#289]
### Description of the issue:
The equation `MAR13082` ("Generic human cell biomass reaction"), to be more precise, the ATP hydrolysis part, is imbalanced - ADP is not retrieved as a reaction product, only inorganic phosphate and protons are listed as reaction products.

#### Expected feature/value/output:
Correct ATP hydrolysis stoichiometry, `45 ATP[c] + 45 H2O[c] => 45 ADP[c] + 45 Pi[c] + 45 H+[c]`.

#### Current feature/value/output:
Rxn equation:
`45 ATP[c]` + 0.0267 DNA[n] + `45 H2O[c]` + 0.1124 RNA[c] + 0.4062 glycogen[c] + 0.0012 cofactor_pool_biomass[c] + 5.3375 protein_pool_biomass[c] + 0.2212 lipid_pool_biomass[c] + 0.4835 metabolite_pool_biomass[c] => `45 H+[c]` + `45 Pi[c]` + biomass[c]

#### Reproducing these results:
N/A

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@pranasag good spot! Please move on to fix it.

**Comment by Hao-Chalmers** [comment]
@pranasag nice job, and you've been granted writing access to Human-GEM. Welcome!
