### ISSUE TITLE
wrong xref for MAM02679c pantetheine

### ISSUE THREAD

**Issue by ANiknejad** [SysBioChalmers/Human-GEM#297]
Hi @Hao-Chalmers 

https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02679c

this page talks about 'pantetheine' but displays 'palmitoyl-coA' as in 
https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02678c

I guess, there is a typo issue between MAM0267**8** and MAM0267**9**

there are strange 'Related metabolite(s)' in this page of MAM02679c, that at the end make conflicting reports in MetaNetX for M_MAM02678 and M_MAM02679: trying to solve a conflict between 'palmitoyl-coA' and 'pantetheine' for metatlas_HumanGEM, see here (not sure I can access directly this link, but if you import the model and go to page 'Import' you will see this page)

https://beta.metanetx.org/cgi-bin/mnxweb/result?analysis=Import&model=metatlas_HumanGEM

Thank you in advance for your help in solving this issue

**Comment by Hao-Chalmers** [comment]
@ANiknejad nice spot!

This error is due to the wrong annotation of ChEBI association to [MAM02679c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02679c). Please go ahead with the investigation and do let us know there are more such cases.

**Comment by mihai-sysbio** [comment]
As far as I can see #325 has completely resolved this issue, which is why I am closing it.
