### ISSUE TITLE
adding chebi as a xref to MAM00003(c)

### ISSUE THREAD

**Issue by ANiknejad** [SysBioChalmers/Human-GEM#299]
https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00003c

would be good to have CHEBI:78990 as 'External databases' xref

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:78990

**Comment by mihai-sysbio** [comment]
As far as I can see, PR #325 completely resolved this issue, which is why I am closing it.
