### ISSUE TITLE
list of MAMids that can have new chebi xref

### ISSUE THREAD

**Issue by ANiknejad** [SysBioChalmers/Human-GEM#300]
(issue in progress, I will report here the MAMids that can have a External database ref to chebi)

______________________________________________

would be good to have CHEBI:77551 as xref for

https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00046m

please see
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:77551

_____________________________________________

would be good to have CHEBI:34127 as xref for

https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00005c

please see:

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=34127

------------------------------------------------

**Comment by Hao-Chalmers** [comment]
@ANiknejad good idea.

**Comment by mihai-sysbio** [comment]
Again, as far as I can see PR #325 completely resolves this issue, which is why I am closing it.
