### ISSUE TITLE
A metabolite appears on both sides of an equation 

### ISSUE THREAD

**Issue by mpagni12** [SysBioChalmers/Human-GEM#308]
### Description of the issue:

A metabolite or its xrefs should NOT appear on both sides of an equation 

For example, in reaction MAR04499:

	1 MAM02039@m + 1 MAM02485@m + 1 MAM02741@m <?> 1 MAM02040@m + 1 MAM02484@m

the following xrefs are given:

     MAM02484	kegg:C03688;lipidmaps:PROTEIN;mnx:MNXM91491;vmhmetabolite:HC02223
     MAM02485	kegg:C03688;lipidmaps:PROTEIN;mnx:MNXM91491;vmhmetabolite:HC02222

i.e. MAM02484 and MAM02485 is the same metabolite!

   Marco

Two other equations are affected by the same problem:  MAR09464 and MAR9487

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
@mpagni12 thanks! how do you suggest to fix this?

**Comment by mpagni12** [comment]
Rewrite the equation using explicitly the ACP-x and ACP-y metabolites from ChEBI. See
 
   https://www.rhea-db.org/rhea?query=ACP

for an already long list of reactions with similar pattern. Maybe your three equations are already in this list?

**Comment by Hao-Chalmers** [comment]
it seems the annotation to `MAM02484` was wrong, should be revised.

**Comment by Hao-Chalmers** [comment]
1. [MAR04499](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04499): according to the KEGG ([R01623](https://www.kegg.jp/entry/R01623)) and Rhea ([20540](https://www.rhea-db.org/rhea/20540)) annotation, `MAM02484` should be annotated as [CHEBI:64479](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=64479), while `MAM02485` as [
CHEBI:29999](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=29999).

2. [MAR09464](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09464): this is actually a hydrolysis reaction that has dextrin polymer on both sides, while the product has one less monomer (glucose) than reactant. 

3. [MAR09487](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09487): similar to `MAR09464`, `MAR09487` also has polymers on both sides.

@mpagni12 what do you suggest to deal with polymerization reacton?

**Comment by mihai-sysbio** [comment]
Has already	been solved as part of the merged PR?

**Comment by Hao-Chalmers** [comment]
no

**Comment by mihai-sysbio** [comment]
Since MAR09464 and MAR9487 are polymerization reactions, there doesn't seem to be an obvious solution to these.

If desired, please open up an issue generically targeting polymerization reactions, giving the examples of MAR09464 and MAR9487 and linking to this thread. With this, I am considering the issue of `having the same metabolite on both sides of the equation` resolved.
