### ISSUE TITLE
links to 'identifiers.org' not working for KEGG metabolites

### ISSUE THREAD

**Issue by ANiknejad** [SysBioChalmers/Human-GEM#309]
Hello,

see this example

https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03165c

the link to 
KEGG | C02076
https://identifiers.org/kegg.metabolite:C02076

reports an error
"INVALID resolution request for 'kegg.metabolite:C02076', due to 'Resolution request 'kegg.metabolite:C02076' is NOT ABOUT A NAMESPACE; UNKNOWN namespace 'kegg.metabolite' when verifying local ID 'C02076''

the correct link should be 
https://www.genome.jp/dbget-bin/www_bget?C02076

**Comment by Hao-Chalmers** [comment]
bug report to Met Atals @mihai-sysbio

**Comment by mihai-sysbio** [comment]
Thanks for reported this @ANiknejad and for forwarding to Met Atlas @Hao-Chalmers . The issue was reported and [a fix has been proposed in this PR](https://github.com/MetabolicAtlas/data-generation/pull/22/files). After review, it will be merged and eventually deployed.
