### ISSUE TITLE
In essential metabolic tasks: NEFA blood pool in[x] should be changed for NEFA blood pool in[s]

### ISSUE THREAD

**Issue by CadavidJoseL** [SysBioChalmers/Human-GEM#311]
Essential task 46 (Uptake and beta oxidation of all NEFAs) fails in version 1.9. NEFA blood pool in[x] should be changed for NEFA blood pool in[s]; this solves the issue.

**Comment by JonathanRob** [comment]
@CadavidJoseL Thanks for finding this, it should be changed to the [s] compartment as you suggest.

However, this task should not fail, even with the [x] compartment being used. Did you remember to add the boundary metabolites before running `checkTasks`?:

```
model_boundary = addBoundaryMets(model);
```

If the boundary metabolites are not present, then the task check results will not be valid.

**Comment by Hao-Chalmers** [comment]
@CadavidJoseL Thanks, will look into this

**Comment by CadavidJoseL** [comment]
You're right, I did forget to add those boundary mets; that also fixes the issue. Thanks!

**Comment by JonathanRob** [comment]
No problem, but I believe you are still correct in that the `NEFA blood pool in` compartment should be changed from [x] to [s] in the task file.

**Comment by JonathanRob** [comment]
If it's ok with you, @CadavidJoseL, I'd like to keep this issue open until we correct the compartment of the `NEFA blood pool in` in the task file. Otherwise we may forget to make the fix.

**Comment by JonathanRob** [comment]
This issue was resolved in #331.
