### ISSUE TITLE
Why all compartment ids are not consistent?

### ISSUE THREAD

**Issue by smoretti** [SysBioChalmers/Human-GEM#314]
Hi

I wonder why "c_i" is the only compartment of the model that is not a single letter?
**i** exists in BiGG (http://bigg.ucsd.edu/compartments/i) and could be used like this instead of c_i

Also in BiGG the extracellular compartment is *e*, not s that is eyespot.
Would you mind to change them?

**Comment by mihai-sysbio** [comment]
Thanks for getting in touch @smoretti . Could I ask where did you encounter `c_i`? I'm only asking because I couldn't find it in the `yml` file. Here is the `compartments` section:
```
- compartments: !!omap
    - s: "Extracellular"
    - p: "Peroxisome"
    - m: "Mitochondria"
    - c: "Cytosol"
    - l: "Lysosome"
    - r: "Endoplasmic reticulum"
    - g: "Golgi apparatus"
    - n: "Nucleus"
    - i: "Inner mitochondria"
    ```

**Comment by smoretti** [comment]
I found it in the SBML file

**Comment by Hao-Chalmers** [comment]
> Also in BiGG the extracellular compartment is e, not s that is eyespot.
> Would you mind to change them?

this might be a good idea

**Comment by Hao-Chalmers** [comment]
> I wonder why "c_i" is the only compartment of the model that is not a single letter?

This probably was due to an issue of the SBML exporting function, but should be fixed in the next release.

**Comment by mihai-sysbio** [comment]
The `i` to `c_i` conversion is reported as a [bug in RAVEN](https://github.com/SysBioChalmers/RAVEN/issues/366).

**Comment by Hao-Chalmers** [comment]
the `c_i` issue has been fixed in the latest release [v1.10](https://github.com/SysBioChalmers/Human-GEM/releases/tag/v1.10.0)

**Comment by Hao-Chalmers** [comment]
> Also in BiGG the extracellular compartment is `e`, not `s` that is eyespot. Would you mind to change them?

In addition to the BIGG models, [yeastGEM](https://github.com/SysBioChalmers/yeast-GEM/blob/main/model/boundaryMets.txt) also use `e` as abbreviation of extracellular compartment. Therefore it makes sense to apply it to Human-GEM.

The modification to model file would be simple and straightforward. But I'm afraid this would affect some functions in HumanGEM and RAVEN. @JonathanRob what do you?

**Comment by JonathanRob** [comment]
I'm also open to this suggested change in abbreviation. But yes, this should be done carefully because it will require additional changes and will break backwards compatibility in some cases.

Since we're suggesting changes to the extracellular compartment abbreviation, we should also consider changing other compartment(s). For example, in Human-GEM, `peroxisome` is abbreviated as `p`, whereas I believe COBRA models typically use `x` to abbreviate the peroxisome. So it would make sense to me to change all of the abbreviations so that they are consistent with whichever scheme is used most often (i.e., in COBRA-like models).

**Comment by Hao-Chalmers** [comment]
I wonder if there is any existing standards defined for cellular compartment abbreviations somewhere, like SBML or COBRA?

**Comment by mihai-sysbio** [comment]
> I wonder if there is any existing standards defined for cellular compartment abbreviations somewhere, like SBML or COBRA?

@edkerk you seem to be more familiar with the standards - do you know of any compartment abbreviations?

**Comment by edkerk** [comment]
To my knowledge there is no universal standard, although the closest to this would be the compartment abbreviation convention that is used in [BiGG models](http://bigg.ucsd.edu/compartments):

<html>
<body>


BiGG ID | Name
-- | --
c | cytosol
e | extracellular space
p | periplasm
m | mitochondria
x | peroxisome/glyoxysome
r | endoplasmic reticulum
v | vacuole
n | nucleus
g | golgi apparatus
u | thylakoid
l | lysosome
h | chloroplast
f | flagellum
s | eyespot
im | intermembrane space of mitochondria
cx | carboxyzome
um | thylakoid membrane
cm | cytosolic membrane
i | inner mitochondrial compartment
mm | mitochondrial intermembrane
w | wildtype staph aureus
y | cytochrome complex


</body>
</html>

**Comment by smoretti** [comment]
KBase/SEED had a compartment list very close to this one in the past. It does not look to be available online any more.
Some pieces of the former list are there: https://github.com/ModelSEED/ModelSEEDDatabase/blob/master/Templates/*/Compartments.tsv in the different Templates sub-directories.

In MetaNetX/MNXref we built a "SEED" compartment list over the years. Here is for the single letter abbreviations:
a	carboxysome
b	plasma membrane
c	cytosol|cytoplasm
d	plastid
e	extracellular space|extra-organism|extraorganism|extracellular
f	endoplasmic reticulum membrane
g	golgi apparatus|golgi
i	mitochondrial outer membrane
j	mitochondrial intermembrane space
k	mitochondrial inner membrane
l	lysosome
m	mitochondria|mitochondrion
n	nucleus
p	periplasm|periplasmic space
r	endoplasmic reticulum
s	plastid outer membrane|plastidial outer membrane
t	plastid intermembrane space|plastidial intermembrane space
u	plastid inner membrane|plastidial inner membrane
v	vacuole
w	cell wall
x	peroxisome/glyoxysome
y	thylakoid
z	thylakoid lumen

**Comment by Hao-Chalmers** [comment]
@edkerk @smoretti thanks for the info!

Despite of the differences between the two lists used by BiGG and SEED, both abbreviation changes for "Extracellular", from `s` -> `e` (proposed by @smoretti), and "Perxisome", from `p` - > `x` (proposed by @JonathanRob), make sense and would promote the convenience and compatibility of Human-GEM.

I would suggest to take steps in this implementation, maybe begin with the modification to Perxisome compartment abbreviation.

**Comment by Hao-Chalmers** [comment]
The abbreviation `x` is already assigned to the boundary compartment in Human-GEM. The change from `p` to `x` may affect some existing implementations (e.g. [addBoundaryMets](https://github.com/SysBioChalmers/Human-GEM/blob/main/code/addBoundaryMets.m)).

**Comment by mihai-sysbio** [comment]
How about using `b` for the `boundary` compartment? Theoretically it would clash with the abbreviation list in MetaNetX shown above by @smoretti, but only if the model would be imported into MetaNetX after running `addBoundaryMets`. So, to my understanding, this would be a problem in practice.
