### ISSUE TITLE
https://metabolicatlas.org/search  does not support composite(complex) metabolite Name or aliases ?

### ISSUE THREAD

**Issue by ANiknejad** [SysBioChalmers/Human-GEM#319]
hello!

for example:
MAM02911c sn-glycero-3-phospho-1-inositol

I can get 'MAM02911c' from 
https://metabolicatlas.org/explore
or from
https://metabolicatlas.org/search

but not 'sn-glycero-3-phospho-1-inositol', neither from
https://metabolicatlas.org/explore
or from
https://metabolicatlas.org/search

BUT WITH simple name like 'itaconate' both search engine work fine

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio bug report to Met Atlas

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio bug report to Met Atlas

Absolutely, @Hao-Chalmers.

**Comment by Hao-Chalmers** [comment]
it's ok. Duplication is useful sometimes

**Comment by mihai-sysbio** [comment]
Thanks @ANiknejad for bringing this up.

When it comes to issues experienced on the website https://metabolicatlas.org that have to do with the interaction on the website, such as the one described above, feel free to create issues directly in the corresponding repository.
I have taken the liberty to duplicate this issue over at https://github.com/MetabolicAtlas/MetabolicAtlas/issues/686, and will consequently close this one here.
