### ISSUE TITLE
Recon ids as reaction names

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/Human-GEM#333]
### Description of the issue:
Some reactions (145) use the old Recon ids as reaction names.

#### Expected feature/value/output:
If the reaction names cannot be filled in from an appropriate source, they should be left empty.

#### Current feature/value/output:
Recon ids as reaction names.

#### Reproducing these results:

**I hereby confirm that I have:**
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
Removing recon ids from reaction names (#334) is fine with me.

This issue is related to #181, which discussed about adding descriptive reaction names. What do you think? @mihai-sysbio

**Comment by mihai-sysbio** [comment]
Having the Recon ids as reaction names is easy to fix, and the improvement will be directly visible in Metabolic Atlas, so I suggest to keep the issues separate. I'll share my thoughts on #181 there.

**Comment by mihai-sysbio** [comment]
This issue appears to be resolved by #334 so I propose closing it, while leaving #181 open, since that's where the new relation names would one in.

**Comment by Hao-Chalmers** [comment]
sure, please go ahead
