### ISSUE TITLE
I suspect that the GPR for MAR04840 is wrong and should be removed

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/Human-GEM#342]
### Description of the issue:
MAR04840 {'H2O[c] + H2S2O3[c] => 2 H+[c] + H2S[c] + sulfate[c]'} currently has the GPR ENSG00000198610 (AKR1C4). Comment here https://www.genome.jp/entry/R00864 says it is a spontaneous reaction. And, when I look at the gene (https://www.proteinatlas.org/ENSG00000198610-AKR1C4) and EC number (https://www.brenda-enzymes.org/enzyme.php?ecno=1.1.1.50), these describe a totally different reaction, involving NAD+/NADP+? 

#### Expected feature/value/output:
I suspect that the EC number and GPR should be cleared, and that the reaction should be marked as spontaneous?

#### Reproducing these results:

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already

**Comment by JonathanRob** [comment]
Thanks for spotting this, @johan-gson. I agree, it looks like this reaction should be spontaneous - the associated gene seems out of place. It would be interesting to identify the source of this erroneous annotation, but in the mean time feel free to remove it.

**Comment by johan-gson** [comment]
I discovered this when comparing the outputs of tINIT and ftINIT - this reaction was not gapfilled by the original tINIT, but with ftINIT. I think in general this could be a way to find some other errors.

**Comment by JonathanRob** [comment]
Issue was resolved in #362
