### ISSUE TITLE
Remove duplicates - identical except that one is unidirectional, the other reversible

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/Human-GEM#345]
### Description of the issue:
The following reactions is of the type
remove: a[x] + b[x] => c[x]
keep:     a[x] + b[x] <=> c[x]

It is difficult to say which is right, but at least the 'remove' reactions are currently meaningless and only makes the model larger. They also create loops, which is sometimes annoying, for example in tINIT.

Otherwise identical, although sometimes reversed perhaps.
The reactions (46 in total):

    To remove:  	to keep:
    {'MAR08971'}    {'MAR04306'}
    {'MAR00121'}    {'MAR00607'}
    {'MAR04911'}    {'MAR04411'}
    {'MAR06324'}    {'MAR00079'}
    {'MAR00101'}    {'MAR02199'}
    {'MAR00445'}    {'MAR02339'}
    {'MAR07441'}    {'MAR01728'}
    {'MAR07742'}    {'MAR01827'}
    {'MAR04455'}    {'MAR11237'}
    {'MAR04463'}    {'MAR11251'}
    {'MAR04478'}    {'MAR11252'}
    {'MAR04502'}    {'MAR11253'}
    {'MAR04517'}    {'MAR11254'}
    {'MAR04576'}    {'MAR11247'}
    {'MAR04609'}    {'MAR11249'}
    {'MAR04622'}    {'MAR11248'}
    {'MAR04626'}    {'MAR11255'}
    {'MAR04653'}    {'MAR11256'}
    {'MAR04659'}    {'MAR11257'}
    {'MAR04669'}    {'MAR11258'}
    {'MAR04713'}    {'MAR11260'}
    {'MAR04724'}    {'MAR11261'}
    {'MAR04747'}    {'MAR11262'}
    {'MAR04751'}    {'MAR11263'}
    {'MAR04753'}    {'MAR11264'}
    {'MAR04761'}    {'MAR11265'}
    {'MAR04794'}    {'MAR11238'}
    {'MAR04795'}    {'MAR11266'}
    {'MAR04798'}    {'MAR11267'}
    {'MAR04800'}    {'MAR11239'}
    {'MAR04801'}    {'MAR11268'}
    {'MAR06494'}    {'MAR11240'}
    {'MAR06497'}    {'MAR11241'}
    {'MAR06504'}    {'MAR11242'}
    {'MAR06541'}    {'MAR11243'}
    {'MAR06582'}    {'MAR11244'}
    {'MAR06590'}    {'MAR11246'}
    {'MAR06594'}    {'MAR11271'}
    {'MAR06706'}    {'MAR11245'}
    {'MAR06853'}    {'MAR11280'}
    {'MAR06856'}    {'MAR11278'}
    {'MAR06857'}    {'MAR11279'}
    {'MAR06858'}    {'MAR11259'}
    {'MAR07191'}    {'MAR09057'}

#### Reproducing these results:
```Matlab

```

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already

**Comment by johan-gson** [comment]
And, all pairs (remove, keep) have identical GPRs

**Comment by JonathanRob** [comment]
Again, nice find, and it makes things simpler since the GPRs are the same.

As for which of the reactions to keep from each pair, I wonder if we should keep the older (lower numbered) reaction and make it reversible, or just keep the reversible reaction regardless of it's relative "age"?

**Comment by mihai-sysbio** [comment]
Hmm it might be easier to keep the reversible reaction, so that deprecating the reactions implies less work in terms of carrying over reaction annotation.

**Comment by JonathanRob** [comment]
Resolved in #403 and #405.
