### ISSUE TITLE
remove duplicates

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/Human-GEM#346]
### Description of the issue:
These reactions are duplicates, they have the same GPR: 
MAR04474: {'6-phospho-D-gluconate[c] + NADP+[c] => CO2[c] + NADPH[c] + ribulose-5-phosphate[c]'          }
MAR08973: {'3 6-phospho-D-gluconate[c] + 3 NADP+[c] => 3 CO2[c] + 3 NADPH[c] + 3 ribulose-5-phosphate[c]'} (remove this one)

~These reactions could be joined into a reversible rxn to avoid loops, they have the same GPRs:
'MAR08482': {'3-oxotetradecanoyl-[ACP][c] + H+[c] + NADPH[c] => HMA[c] + NADP+[c]'}
'MAR02358': {'HMA[c] + NADP+[c] => 3-oxotetradecanoyl-[ACP][c] + H+[c] + NADPH[c]'}~  moved into #348

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
NIcely spotted @johan-gson! How did you find these duplicates? Do you think the detection can be scripted?

**Comment by johan-gson** [comment]
Yeah, I found this doing some script, while working on speeding up tINIT. So, this can be scripted.

**Comment by mihai-sysbio** [comment]
@johan-gson I hope it's okay that I've edited the issue: the second pair of reactions didn't have the exact same GPRs, so I moved it into #348. This way we can resolve at least the straightforward part of this issue sooner.

**Comment by johan-gson** [comment]
Very okay, no worries :)

**Comment by JonathanRob** [comment]
Resolved with #365
