### ISSUE TITLE
verify reaction GPRs

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/Human-GEM#363]
### Description of the issue:
As originally reported in #344, the following reactions should have their GPRs checked.

| remove | keep | GPR | GPR |
| - | - | - | - |
MAR08992 | MAR04477 | RPE | RPE or RPEL1
MAR02490 | MAR06621 | empty | (RRM1 and RRM2 and RRM2B and TXN2) or (RRM1 and RRM2 and RRM2B and TXN)
MAR04562 | MAR02608 | CPT1A or CPT1B or CPT1C | CPT1A or CPT1B or CPT1C
MAR00464 | MAR07178 | empty | FABP1
MAR11310 | MAR00108 | empty | CPT1A or CPT1B or CPT1C
MAR10410 | MAR02404 | empty | SLC22A10

#### Expected feature/value/output:
Either cleaned-up GPRs or reactions merged.

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by Devlin-Moyer** [comment]
all of these duplicates were addressed in #561/#573 by removing MAR08992, MAR02490, MAR04562, MAR00464, MAR11310, and MAR10410
