### ISSUE TITLE
Can't search by metabolite id in metabolic atlas 

### ISSUE THREAD

**Issue by PkiwiBird** [SysBioChalmers/Human-GEM#378]
When searching for metabolite id MAM02040c in the search bar od metabolic atlas with "Human-GEM" selected at the left gives no results, but it works fine when using reaction ids. When clicking "Search all integrated GEMs" it shows the result for the metabolite though.
Also, the compartment 's' in the metabolic atlas seems to be different from the external compartment in models, which is 'e' 

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by JonathanRob** [comment]
Thanks for identifying this problem, @PkiwiBird! Any issues related to Metabolic Atlas can be reported in the [Metabolic Atlas GitHub repo](https://github.com/MetabolicAtlas/MetabolicAtlas), so could you please create this same issue in that repository instead?

**Comment by JonathanRob** [comment]
Issue was moved and addressed elsewhere (https://github.com/MetabolicAtlas/MetabolicAtlas/issues/936) so I'll close it here.
