### ISSUE TITLE
MAR02517 should not be associated with the CTSA gene

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#381]
### Description of the issue:
As identified by a user, [`MAR02517`](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02517) is currently associated to only the CTSA gene (encoding Cathepsin A, a serine protease). This reaction involves fatty acid elongation and should not be associated with CTSA - it is not supported in literature/databases, and the only [reference currently associated with the reaction](https://doi.org/10.1006/mgme.1999.2883) is irrelevant.

Furthermore, it appears that the EC number associated with the reaction ([3.1.2.2](https://www.genome.jp/dbget-bin/www_bget?ec:3.1.2.2)) is also incorrect.

### Proposed solution
- ~~[ ] Remove CTSA from the MAR02517 gene rule.~~
- ~~[ ] Update the MAR02517 gene rule such that it is associated with the correct gene(s).~~
- ~~[ ] Correct the MAR02517 EC number.~~
- [x] Remove the MAR02517 reaction.

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
> Update the MAR02517 gene rule such that it is associated with the correct gene(s).

@JonathanRob what are the correct genes?

**Comment by JonathanRob** [comment]
It seems like the correct genes should be the [ELOVL genes](https://biocyc.org/gene?orgid=META&id=HS10142), but the process takes place in (the membrane of) the endoplasmic reticulum. The [MAR02517](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02517) reaction (the subject of this issue) is located in the lysosome, which is an odd place for a fatty acid elongation reaction to occur.

Human-GEM has two reactions that are equivalent to MAR02517 but located in different compartments: [MAR02519](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02519) in the endoplasmic reticulum, and [MAR02190](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02190) in the cytoplasm. These reactions are associated with some or all of the ELOVL genes, and although the cytoplasm location is questionable, it is at least not an isolated/dead-end reaction.

The lysosomal MAR02517 reaction is isolated, where its substrates malonyl-CoA[l] and palmitoyl-CoA[l], and product 3-oxooctadecanoyl-CoA[l] do not participate in any other reactions.

Given this, I would instead recommend that we just remove the MAR02517 reaction.

**Comment by haowang-bioinfo** [comment]
@JonathanRob based on your investigation, MAR02517 seem to be formulated in wrong compartment, GPR, EC number, and reference. Agree to remove it.

**Comment by haowang-bioinfo** [comment]
fixed in #432
