### ISSUE TITLE
Missing reaction names in Human-GEM 

### ISSUE THREAD

**Issue by Selimvrl** [SysBioChalmers/Human-GEM#385]
### Description of the issue:
Only 4724 reaction out of 13069 has reaction names given in Human-GEM model. Although I can see the reaction codes from rxns list under the model, rxnNames list does not consists the majority of their names.

#### Expected feature/value/output:
All reactions to have their reaction names stated in rxnNames list.

Note: I tried to download the latest version manually as well for the model, but the reaction names are still missing. 

**I hereby confirm that I have:**
- [x] Tested my code on my own computer for running the model
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already

![image](https://user-images.githubusercontent.com/93686856/164252696-2a158682-06c9-454f-a718-98ece1109143.png)

**Comment by mihai-sysbio** [comment]
Thank you for the question @Selimvrl.

There have been long-standing issues regarding the reaction names, and only incremental have been made so far in https://github.com/SysBioChalmers/Human-GEM/issues/333 and https://github.com/SysBioChalmers/Human-GEM/issues/181.

If your question is open-ended, then we would love your input and suggestions in #181, in which case this issue could be closed. If you question, however, is more related to the reaction annotation, then it would be great if you could share more about your use-case.

**Comment by haowang-bioinfo** [comment]
duplicate to #181
