### ISSUE TITLE
Error addBoundaryMets execution

### ISSUE THREAD

**Issue by FloraMika** [SysBioChalmers/Human-GEM#391]
Dear Sir or Madam,

I have simply downloaded the Human-GEM folder and I get the following issue where addBoundaryMets is not working

### Description of the issue:

addpath(genpath('/home/flomik/Desktop/Code-PHD/Git/Human-GEM/'))
addpath(genpath('/home/flomik/Desktop/Code-PHD/Git/RAVEN'))

ihuman = addBoundaryMets(ihuman);

Error using dispEM (line 49)
metsToAdd.compartments must have the same number of elements as metsToAdd.mets

Error in addMets (line 132)
    dispEM(EM);

Error in addBoundaryMets (line 109)
new_model = addMets(model,metsToAdd);

What should I do ?

I am using matlab R021a

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already

**Comment by JonathanRob** [comment]
Hi @FloraMika, this bug was unfortunately introduced with a recent change in RAVEN. There are currently pending pull requests in both the Human-GEM and RAVEN repositories to fix the bug from both sides.

In the mean time, I recommend trying to downgrade RAVEN to [2.6.2](https://github.com/SysBioChalmers/RAVEN/releases/tag/v2.6.2), or using the most recent [fix branch](https://github.com/SysBioChalmers/RAVEN/tree/fix/addMets_comps) on RAVEN.

Sorry for the inconvenience!

**Comment by FloraMika** [comment]
Dear Jonathan,

Thank you very much for this information and your fast answer. Hope you can get it fixed soon :).

Best regards,

Flora

----- Original Message -----

**Comment by FloraMika** [comment]
Dear Jonathan,

Now it is working to add the boundaries but gurobi is not recognised (unrecognised function or variable gurobi) while running checkTasks for example. Does it means I need to install cobra solver ?

Best regards,

Flora

----- Original Message -----

**Comment by JonathanRob** [comment]
You will need to have at least one solver installed; gurobi is one option, though cobra and glpk are also OK. You can see the RAVEN [installation instructions](https://github.com/SysBioChalmers/RAVEN/wiki/Installation#installation) for help, specifically the [solvers](https://github.com/SysBioChalmers/RAVEN/wiki/Installation#solvers) section.

**Comment by FloraMika** [comment]
Dear Jonathan,

Thank you very much for your help.

Now it works with the glpk solver (still gurobi solver does not work I dont understand why --> it was working with non human model with the last raven version)

But all the essential tasks are failing. How is it possible ? What is the problem here ? 

Please find enclosed my code. Thank you again for your time and understanding.

addpath(genpath('/home/flomik/Desktop/Code-PHD/Git/Human-GEM/'))
addpath(genpath('/home/flomik/Desktop/Code-PHD/Git/RAVEN-fix-addMets_comps'))

solver = 'glpk'
setRavenSolver(solver)

load('Human-GEM.mat');

ihuman = addBoundaryMets(ihuman);

essentialTasks = parseTaskList('/home/flomik/Desktop/Code-PHD/Git/Human-GEM/data/metabolicTasks/metabolicTasks_Essential.txt')

checkTasks(ihuman, [], true, false, false, essentialTasks);


Best regards,

Flora

----- Original Message -----

**Comment by JonathanRob** [comment]
Very strange that the tasks are failing for you, @FloraMika. When I repeated your same commands (using latest release of Human-GEM and current `devel` version of RAVEN), all tasks were passing.

Could you try using the current version of the [RAVEN `devel` branch](https://github.com/SysBioChalmers/RAVEN/tree/devel) and double check that you're using the latest version of the Human-GEM `main` branch, run your script again, and provide the output of your commands?

**Comment by FloraMika** [comment]
Dear Jonathan,

I tried with the RAVEN devel branch and again I have a problem with the addMets function. The only version working for me with this function is this one RAVEN-fix-addMets_comps but all the essential tasks are failing.

I really do not understand what I am doing wrong.

Best regards,

Flora

----- Original Message -----

**Comment by FloraMika** [comment]
Dear Jonathan,

It is finally working with the version 4.2.0. It works really well now ! So interesting to start working with it.

Do you know when we will be able to use the latest version ?

I was also wondering if you have time .... What would you use to speed up the process ? I have to make a GEM for 197 patients. I am quite new in matlab and really enthousiastic to learn :)
I was wondering if you had some advice (is there any good tool for parallel computing like in Python ? I am trying the parfor loop ...)

Thank you again for this great tool.

Best regards,

Flora

----- Original Message -----

**Comment by mihai-sysbio** [comment]
Since there not seem to be any issues with `addMets`, perhaps this issue should be converted into a discussion.

**Comment by JonathanRob** [comment]
@FloraMika if you're talking about speeding up the process of running tINIT, then I recommend you take a look at "fast" tINIT (ftINIT). The pre-print is [here](https://www.biorxiv.org/content/10.1101/2022.04.25.489379v1.full), and the [ftINIT function](https://github.com/SysBioChalmers/RAVEN/blob/devel/INIT/ftINIT.m) has been implemented on the `devel` branch of RAVEN.

@mihai-sysbio also makes a good point. I will go ahead and close this issue as resolved, but feel free to open a Discussion @FloraMika if you have further items to discuss, or an Issue if you find any problems/bugs.
