### ISSUE TITLE
Update with T2T-CHM13 genome

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/Human-GEM#402]
Hi, I am wondering if it is now possible to update the human GEM based on the new release of the human reference genome [T2T-CHM13](https://www.science.org/doi/10.1126/science.abj6987).

**Comment by JonathanRob** [comment]
Hi @Yu-sysbio, in general we retrieve our gene IDs and their associated symbols/other IDs from Ensembl. Is there something specific (gene/genes) that you're hoping to update?

**Comment by Yu-sysbio** [comment]
I am not interested in any specific genes but just found in the T2T-CHM13 paper that 99 newly introduced genes were predicted to be protein coding, which (if involved in metabolism) I think could be added to the human GEM. But I am not sure whether Ensembl has included the T2T-CHM13 genome.

**Comment by JonathanRob** [comment]
Ok interesting. Unless any of the newly added genes encode a protein that catalyzes a metabolic reaction, the update would not make a difference. Though if one of the new genes is associated with a reaction, then that reaction could be added to the model.
