### ISSUE TITLE
MAR08430 should be marked spontaneous

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/Human-GEM#410]
### Description of the issue:
MAR08430: creatine-phosphate[m] => creatine-phosphate[c]
According to wikipedia (https://en.wikipedia.org/wiki/Creatine_phosphate_shuttle, not a great source, but probably ok) this transport goes via diffusion, which means it is spontaneous. I think it is good to mark all spontaneous reactions since we don't need to look for missing GPRs then!

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
It makes sense to treat passive diffusion as spontaneous process, according [various](https://www.thoughtco.com/diffusion-and-passive-transport-373399) [sources](https://physics.stackexchange.com/questions/282942/why-is-diffusion-a-spontaneous-process).

**Comment by haowang-bioinfo** [comment]
close for now, feel free to reopen
