### ISSUE TITLE
GPR curation for MAR04926

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#417]
### Description of the issue:
There are three genes associated with mitochondrial pyruvate transport reaction ([MAR04926](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04926)):
1. [ENSG00000060762](https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000060762) ([MPC1](https://www.uniprot.org/uniprotkb/Q9Y5U8/entry))
2. [ENSG00000143158](https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000143158) ([MPC2](https://www.uniprot.org/uniprotkb/[O95563](https://metabolicatlas.org/identifier/UniProt/O95563)/entry))
3. [ENSG00000238205](https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000238205) ([MPC1L](https://www.uniprot.org/uniprotkb/P0DKB6/entry))

According to this experimental [study](https://pubmed.ncbi.nlm.nih.gov/22628558/), mitochondrial pyruvate carrier is a complex, formed by two essential subunits: `MPC1` and `MPC2`, in the inner mitochondrial membrane. While there is no literature evidence associated with `MPCL1`, which shows 64.2% sequence similarity to `MPC1`.

#### Current GPR rule:
* `ENSG00000060762 or ENSG00000143158 or ENSG00000238205`

#### Expected GPR rule:
* `(ENSG00000060762 and ENSG00000143158) or (ENSG00000238205 and ENSG00000143158)`

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
To me, ~65% sequence similarity is not enough to justify equivalent function, especially in the light of there being a meaningful difference in sequence length. The predicted structured in Alphafold do not seem to support the similarity. Thus, my suggestion would be, in absence of further evidence, to remove the association with `MPC1L`.

**Comment by haowang-bioinfo** [comment]
> The predicted structured in Alphafold do not seem to support the similarity.

Excellent - can you manage to present the evidence of the predicted structure comparison between `MPC1` and `MPC1L`.

**Comment by mihai-sysbio** [comment]
> present the evidence of the predicted structure comparison

It was a visual inspection of the structure panel in the UniProt pages linked in the main issue description.

**Comment by JonathanRob** [comment]
[This study](https://pubmed.ncbi.nlm.nih.gov/27317664/) supports potential MPC1-like activity of MPC1L, though it's expression seems to be highly specific to the testes (this can also be seen in the corresponding [HPA entry](https://www.proteinatlas.org/ENSG00000238205-MPC1L/tissue)). So I would recommend against removal of MPC1L from the GPR rule.

**Comment by haowang-bioinfo** [comment]
> MPC1L shares high sequence, structural, and topological homology with MPC1. In addition, we provide several lines of evidence to show that MPC1L is functionally equivalent to MPC1: 1) when co-expressed with MPC2, it rescues pyruvate import in a MPC-deleted yeast strain; 2) in mammalian cells, it can associate with MPC2 to form a functional carrier as assessed by bioluminescence resonance energy transfer; 3) in MPC1 depleted mouse embryonic fibroblasts, MPC1L rescues the loss of pyruvate-driven respiration and stabilizes MPC2 expression; and 4) MPC1- and MPC1L-mediated pyruvate imports show similar efficiency. However, we show that MPC1L has a highly specific expression pattern and is localized almost exclusively in testis and more specifically in postmeiotic spermatids and sperm cells.

thanks @JonathanRob, indeed this paper presented solid evidence of MPC1L is functionally equivalent to MPC1 and its testis-specific expression pattern.

**Comment by mihai-sysbio** [comment]
Very nice find @JonathanRob.

This would be a good time to also update the PMIDs associated to this reaction.

**Comment by mihai-sysbio** [comment]
Given the merged PR, I believe this issue may now be closed (please re-open if otherwise).
