### ISSUE TITLE
MAR09498 (catalyzed by MGMT) should be irreversible

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#425]
### Description of the issue:
A user has indicated that transfer of methyl to MGMT's cysteine residue (represented by reaction [MAR09498](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09498)) leaves the protein unusable for any further reaction, and should therefore be an irreversible reaction.

The following sources were provided:
- Murawska et al. ACS Chem. Biol. 2022, 17, 1, 24–31 ([doi](https://doi.org/10.1021/acschembio.1c00771))
- "Comment" field in KEGG entry [EC 2.1.1.63](https://www.kegg.jp/entry/2.1.1.63)

#### Expected feature/value/output:
MAR09498 should be irreversible

#### Current feature/value/output:
MAR09498 is reversible

**Comment by feiranl** [comment]
also here in MetaCyc: [2.1.1.63](https://metacyc.org/META/substring-search?type=NIL&object=2.1.1.63+)

**Comment by haowang-bioinfo** [comment]
this is fixed in #429
