### ISSUE TITLE
Removal of MEIKIN from fatty acid activation reactions

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#426]
### Description of the issue:
* [MEIKIN](https://www.uniprot.org/uniprotkb/A0A087WXM9/entry) ([ENSG00000239642](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000239642)) is a [key regulator of kinetochore function](https://pubmed.ncbi.nlm.nih.gov/25533956/) during meiosis I. Specifically, it regulate kinases in [cohesin protection](https://pubmed.ncbi.nlm.nih.gov/33888556/). However, it was mis-annotated as one of isoenzymes that catalyze [fatty acid activation reactions](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000239642) across compartments of cytosol, mitochondria, peroxisome, and ER.

#### Current feature/value/output:
* The meiosis regulator MEIKIN (ENSG00000239642) is now involved into a total of 132 fatty acid activation reactions

#### Expected feature/value/output:
* Remove MEIKIN (ENSG00000239642) gene from Human-GEM 

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
With the discovery of this (ENSG00000239642) gene, it can thus be speculated that there might be others that are actually not involve into metabolic process but were incorporated HumanGEM, probably due to sequence similarity.

A systematic investigation might be necessary at some point. The [GPT](https://openai.com/blog/chatgpt/) language model appears to be useful tools undertaking this task.

**Comment by haowang-bioinfo** [comment]
As a follow-up of above comment, the Uniprot annotation of Human-GEM genes had been screened by GPT-3 model for preliminary evaluation, the obtained non-metabolic candidates were then subjected to manual check. The results are now reported as issues #443, #444, #446, #447, and more for open discussion, before subsequent implementations in pull requests.

**Comment by mihai-sysbio** [comment]
> As a follow-up, above comment triggered `GPT3 guided curation`. First the Uniprot annotation of Human-GEM genes had been screened by GPT-3 model for preliminary evaluation, the obtained non-metabolic candidates were then subjected to manual check.

Nice description! Is this process reproducible? I'm thinking that evidence evolves, so it might be worth it to do this process again in the future. Also, are there any simulation checks ran after these deletions?

**Comment by mihai-sysbio** [comment]
And since now there are quite a few genes that will be removed from the model, could a plaintext file be set up listing these, and the reason for their removal? I'm thinking it will be easier in the future, if debates come up for their addition back into the model.

**Comment by haowang-bioinfo** [comment]
> I'm thinking that evidence evolves, so it might be worth it to do this process again in the future. 

agree

> Also, are there any simulation checks ran after these deletions?

good idea! growth simulations were made before and after the removal in #450. It would be good to have a systematic check using specific script/function, which probably can be incorporated as GH action for each PR later on

> And since now there are quite a few genes that will be removed from the model, could a plaintext file be set up listing these, and the reason for their removal? I'm thinking it will be easier in the future, if debates come up for their addition back into the model.

each of the genes has been tabulated in corresponding issues with provided reasons serving as transparent records for tracking and debating

**Comment by mihai-sysbio** [comment]
The above sounds great! ⬆️ 👍🏻

**Comment by JonathanRob** [comment]
This sounds good to me as well, though I would caution focusing on "non-metabolic" as the primary term for identifying genes that should be removed, since there are many enzymes that require "non-metabolic" structural or regulatory subunits to be expressed or function properly. Though since this process involves manual checking of the results, then I suppose it's not a major concern.

**Comment by haowang-bioinfo** [comment]
here I close this issue, where `GPT3 assisted curation` was initialized. But this work will be continued and even is becoming a routine.
