### ISSUE TITLE
reaction MAR03099 is missing a PMID prefix

### ISSUE THREAD

**Issue by avlant** [SysBioChalmers/Human-GEM#427]
### Description of the issue:
In the human1 excel file the reaction 'MAR03099' is missing a PMID prefix for the last reference in the "REFERENCE" field

#### Expected feature/value/output:
'PMID:8012501;PMID:8188243;PMID:13295248'

#### Current feature/value/output:
'PMID:8012501;PMID:8188243;13295248'

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
@avlant thanks for reporting this :-)

**Comment by mihai-sysbio** [comment]
Through the merging of #428 this issue is resolved.
