### ISSUE TITLE
Inconsistency of PMID in the REFERENCE field for several reactions

### ISSUE THREAD

**Issue by avlant** [SysBioChalmers/Human-GEM#430]
### Description of the issue:
For most reactions (5689) the pubmed ids are given as "PMID:xxxxxxx;PMID:xxxxxxx".
However for 55 reactions the pubmed id is instead given as "PMIDxxxxxxx;PMIDxxxxxx", i.e. without a ":" (colon) separator.

This applies to the following reactions:
MAR10066;MAR10092;MAR10093;MAR10094;MAR10095;MAR10096;MAR10097;MAR10098;MAR10099;MAR10105;MAR10106;MAR10107;MAR10108;MAR10111;MAR10112;MAR10113;MAR10114;MAR10116;MAR10077;MAR10078;MAR10079;MAR10080;MAR10081;MAR10082;MAR10083;MAR10084;MAR10085;MAR10086;MAR10087;MAR10088;MAR10089;MAR10090;MAR10091;MAR10100;MAR10101;MAR10102;MAR10103;MAR10104;MAR10109;MAR10110;MAR10115;MAR10117;MAR10118;MAR10119;MAR10120;MAR10125;MAR10126;MAR10127;MAR10132;MAR10073;MAR10074;MAR10075;MAR10076;MAR10071;MAR10072

Additionally, for 3 reactions the pubmed id is given as :0", i.e. "PMID:0", which is not a valid pubmed id. 
There are 7326 reactions without pubmed id, so the convention appears to be to leave the filed blank if no PMID is available.

This applies to the following reactions:
MAR03259;MAR03382;MAR03824

**Comment by haowang-bioinfo** [comment]
@

**Comment by mihai-sysbio** [comment]
Thanks @avlant for the clear reporting of this pmid issue. The fix has now been merged to `develop` so this issue will be closed.
