### ISSUE TITLE
Complex I subunit curation

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#446]
### Description of the issue:
* Currently, there are 44 subunits for Complex I reaction ([MAR06921](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06921)) in the GEM. However, according to this [paper](https://www.nature.com/articles/nature19754), there are only 26 are essential. I propose that we should have two versions for complex I, one having all subunits, the other having the essential ones. Then in the ecGEM simulation, if we can assign different kcat values for those two versions, then maybe we can simulate how the specific tissues choose whether to recruit the accessory subunits as shown by the expression levels [here](https://www.ebi.ac.uk/complexportal/complex/CPX-577).

**Comment by haowang-bioinfo** [comment]
Here are the 17 accessory subunit of Complex I, and they are believed not to be involved in catalysis, according to above [paper](https://www.nature.com/articles/nature19754).

| gene            | Subsystems                | RxnID   |
|-----------------|---------------------------|----------|
| ENSG00000065518 | Oxidative phosphorylation | MAR06921 |
| ENSG00000090266 | Oxidative phosphorylation | MAR06921 |
| ENSG00000099795 | Oxidative phosphorylation | MAR06921 |
| ENSG00000109390 | Oxidative phosphorylation | MAR06921 |
| ENSG00000125356 | Oxidative phosphorylation | MAR06921 |
| ENSG00000130414 | Oxidative phosphorylation | MAR06921 |
| ENSG00000131495 | Oxidative phosphorylation | MAR06921 |
| ENSG00000136521 | Oxidative phosphorylation | MAR06921 |
| ENSG00000147123 | Oxidative phosphorylation | MAR06921 |
| ENSG00000151366 | Oxidative phosphorylation | MAR06921 |
| ENSG00000160194 | Oxidative phosphorylation | MAR06921 |
| ENSG00000165264 | Oxidative phosphorylation | MAR06921 |
| ENSG00000166136 | Oxidative phosphorylation | MAR06921 |
| ENSG00000168653 | Oxidative phosphorylation | MAR06921 |
| ENSG00000170906 | Oxidative phosphorylation | MAR06921 |
| ENSG00000183648 | Oxidative phosphorylation | MAR06921 |
| ENSG00000186010 | Oxidative phosphorylation | MAR06921 |

**Comment by mihai-sysbio** [comment]
`MAR06921` has a confidence score of `2`, referencing `PMID:8443209`. Perhaps it's worth having a look there as well.

**Comment by haowang-bioinfo** [comment]
> Here are the 17 accessory subunit of Complex I, and they are believed not to be involved in catalysis, according to above [paper](https://www.nature.com/articles/nature19754).

The claim that these accessory subunits are `believed not to be involved in catalysis` is based on Uniprot annotation (e.g. [ENSG00000165264](https://www.uniprot.org/uniprotkb/O95139/entry)). 

However, many of these subunits are shown to be `strictly required for assembly of a functional complex I` and their corresponding knockout mutant cells cannot grow on galactose, according above mentioned [paper](https://www.nature.com/articles/nature19754). While the genes (NDUFA12, NDUFS4, NDUFS6) whose KO cells are still capable of growth are reported with [pathogenic mutations](https://www.nature.com/articles/nature19754/tables/1) in patients with mitochondrial disease.

**Comment by haowang-bioinfo** [comment]
According to [Complex portal](https://www.ebi.ac.uk/complexportal/complex/CPX-577) annotation, human Complex I comprises of 45 subunits, among which [NDUFA7](https://www.uniprot.org/uniprotkb/O95182/entry) (ENSG00000267855) is missing from ([MAR06921](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06921)) that has 44 subunits.
