### ISSUE TITLE
remove non-metabolic genes from Alanine, aspartate and glutamate metabolism

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#464]
### Description of the issue:
* three non-metabolic genes are discovered in the GPR rules of `Alanine, aspartate and glutamate metabolism`:

| gene            | Reasons                                                                                  | Subsystems                    | RxnIDs                              |
|-----------------|------------------------------------------------------------------------------------------|-------------------------------|-------------------------------------|
| [ENSG00000137261](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000137261) | [believed to be not involved in catalysis](https://www.uniprot.org/uniprotkb/Q5T4B2/entry) | Alanine, aspartate and glutamate metabolism | MAR04285 |
| [ENSG00000146166](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000146166) | [ Does not seem to have enzymatic activity (By similarity).](https://www.uniprot.org/uniprotkb/Q5TDP6/entry) | Alanine, aspartate and glutamate metabolism | MAR03890 |
| [ENSG00000241258](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000241258) | [DNA-directed RNA polymerase III - completely irrelevant](https://www.uniprot.org/uniprotkb/O75575/entry) | Alanine, aspartate and glutamate metabolism | MAR03813 |

#### Current feature/value/output:
* The association of these genes is lack of evidence according to the provided reasons

#### Expected feature/value/output:
* Remove above genes from Human-GEM 

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
very good, go ahead please
