### ISSUE TITLE
Mitochondrial respiratory chain Complex IV curation

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#469]
### Description of the issue:

Currently, the subunits for complex IV reaction ([MAR06914](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06914)) has 19 subunits in the GEM. However, according to Complex portal [CPX-6123](https://www.ebi.ac.uk/complexportal/complex/CPX-6123), there should be 14 subunits.

To match Complex IV (MAR06914) GPRs with CPX-6123 annotation, the subunits [COX4I2](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000131055), [COX6A2](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000156885), [COX6B2](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000160471), [COX7A1](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000161281), [COX7B2](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000170516), and [COX8C](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000187581) should be removed even though Uniprot annotation has not been updated yet, while [NDUFA4](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000189043) should be added.

**Comment by feiranl** [comment]
Even though Uniprot still annotated them as the subunit for complex IV. It is ok to make the change, but it is better to document that we know the Uniprot has not been updated yet.

**Comment by haowang-bioinfo** [comment]
> Even though Uniprot still annotated them as the subunit for complex IV. It is ok to make the change, but it is better to document that we know the Uniprot has not been updated yet.

The issue message has been updated by stating that "even though Uniprot annotation has not been updated yet".

**Comment by haowang-bioinfo** [comment]
fixed in #489
