### ISSUE TITLE
remove non-metabolic gene from Phenylalanine, tyrosine and tryptophan biosynthesis

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#471]
### Description of the issue:
* non-metabolic gene is discovered in the GPR rules of `Phenylalanine, tyrosine and tryptophan biosynthesis`:

| gene            | Reasons                                                                                  | Subsystems                    | RxnIDs                              |
|-----------------|------------------------------------------------------------------------------------------|-------------------------------|-------------------------------------|
| [ENSG00000059588](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000059588) | [remove, substrates should be tRNA](https://www.uniprot.org/uniprotkb/Q13395/entry) | Phenylalanine, tyrosine and tryptophan biosynthesis | MAR06710;MAR06737 |
| [ENSG00000145331](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000145331) | [remove, substrates should be tRNA](https://www.uniprot.org/uniprotkb/Q8TBZ6/entry) | Phenylalanine, tyrosine and tryptophan biosynthesis | MAR06710;MAR06737 |
| [ENSG00000146834](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000146834) | [remove, no enough supporting evidence](https://www.uniprot.org/uniprotkb/Q7L2J0/entry) | Phenylalanine, tyrosine and tryptophan biosynthesis | MAR06710;MAR06737 |
| [ENSG00000162851](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000162851) | [remove, substrate is rRNA](https://www.uniprot.org/uniprotkb/Q9H5Q4/entry) | Phenylalanine, tyrosine and tryptophan biosynthesis | MAR06710;MAR06737 |
| [ENSG00000250305](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000250305) | [remove, substrate is tRNAs](https://www.uniprot.org/uniprotkb/Q9P272/entry) | Phenylalanine, tyrosine and tryptophan biosynthesis | MAR06710;MAR06737 |

#### Current feature/value/output:
* The association of these genes is lack of evidence according to the provided reasons

#### Expected feature/value/output:
* Remove above genes from Human-GEM 

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
The high number of isoenzymes in GPR rules of these two reactions ([MAR06710](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06710) and [MAR06737](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06737)) appears to be suspicious.

**Comment by feiranl** [comment]
Maybe there are still some of them are related to RNA modification rather than the amino acid synthesis. I can double check all of them.

**Comment by JonathanRob** [comment]
Since the reactions are methylations, a lot of the isozymes are probably different types of methyltransferases. So it is a bit similar to the issue of the generic phosphorylation reaction having all the kinases associated with it. Maybe only a subset of these actually catalyze the reactions involving these specific substrates, and the others could be removed, but I'm not sure.

**Comment by haowang-bioinfo** [comment]
> Since the reactions are methylations, a lot of the isozymes are probably different types of methyltransferases. So it is a bit similar to the issue of the generic phosphorylation reaction having all the kinases associated with it. Maybe only a subset of these actually catalyze the reactions involving these specific substrates

it does appear so - many are methyltransferases catalyzing other substrates than beta-carboline or salsolinol

> Maybe there are still some of them are related to RNA modification rather than the amino acid synthesis. I can double check all of them.

sounds good, will also test with GPT model

**Comment by feiranl** [comment]
After GPT check and manual check, all genes are actually not associated with these two reactions.
|GeneID|GPT substrate answer|Manual check|Comment|
|-----------------|------------------------------------------------------------------------------------------|-------------------------------|-------------------------------------|
|[ENSG00000170439](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000170439)|The substrates of this enzyme are hydrogen sulfide and other thiol compounds including dithiothreitol, 7alpha-thiospironolactone, L-penicillamine, and captopril.|thiol related|change substrate|
|[ENSG00000101247](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000101247)|The substrates of this enzyme are Arg-111 of NDUFS7 and possibly methyltransferase.|May also have methyltransferase activity |not sure|
|[ENSG00000010165](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000010165)|The substrates of this enzyme are EEF1A1 and EEF1A2.|therefore involved in the regulation of mRNA translation|remove|
|[ENSG00000029639](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000029639)|The substrates of this enzyme are S-adenosyl-L-methionine and mitochondrial 12S rRNA.|dimethylates mitochondrial 12S rRNA|remove|
|[ENSG00000059588](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000059588)|The substrates of this enzyme are S-adenosyl-L-methionine and HIV-1 TAR RNA.|should be rna|remove|
|[ENSG00000066651](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000066651)|An enzyme responsible for methylating a guanosine nucleotide at position 10 (m2G10) on tRNAs.  The substrate of the enzyme is a guanosine nucleotide at position 10 (m2G10) on tRNAs.|tRNA methyltransferase|remove|
|[ENSG00000067365](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000067365)|The substrate of this enzyme is the amino acid lysine (KIN) at position 135.|Protein N-lysine methyltransferase|remove|
|[ENSG00000068438](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000068438)|The substrates of this enzyme are tRNAs and nucleotides.|should be rna|remove|
|[ENSG00000071462](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000071462)|Enzyme methylates the N(7) position of a guanine in 18S rRNA; enzyme adapter protein TRM112 helps; enzyme potentiates transactivation by glucocorticoid, mineralocorticoid, androgen, and progesterone receptors; enzyme required for maintenance of dimethylation on histone H3 'Lys-79' (H3K79me2).  The substrates of this enzyme are guanine in 18S rRNA, TRM112, glucocorticoid, mineralocorticoid, androgen, progesterone receptors, and histone H3 'Lys-79' (H3K79me2).|RNA methyltransferase |remove|
|[ENSG00000087995](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000087995)|The enzyme S-adenosyl-L-methionine-dependent methyltransferase methylates N(3)-methylcytidine of residue 32 of tRNA(Thr)(UGU) and tRNA(Arg)(CCU).  The substrates of this enzyme are S-adenosyl-L-methionine, tRNA(Thr)(UGU), tRNA(Arg)(CCU), N6-threonylcarbamoylation, and N(3)-methylcytidine.|tRNA anticodon loop |remove|
|[ENSG00000100462](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000100462)|Arginine methyltransferase  The substrates of this enzyme are arginine residues.|should be protein according to Uniprot|remove|
|[ENSG00000100483](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000100483)|The substrate of this enzyme is Lys-315 of VCP/p97.|protein lysine methyltransferase|remove|
|[ENSG00000101574](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000101574)|The substrates of this enzyme are RNAs and DNA.|methylate both RNAs and DNA |remove|
|[ENSG00000103037](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000103037)|The substrates of this enzyme are Lys-310 of the RELA subunit of NF-kappa-B complex, Lys-8 of H2AZ, and PAK4.|protein lysine methyltransferase|remove|
|[ENSG00000105202](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000105202)|Substrates of this enzyme are RNAs, proteins, U6 snRNAs, and histone H2A.|methylate both RNAs and proteins|remove|
|[ENSG00000108592](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000108592)|The substrates of this enzyme are 34S pre-rRNA, 18S rRNA, 40S ribosomal subunit, and HIV-1 RNA.|act on RNA|remove|
|[ENSG00000110871](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000110871)|The substrates of this enzyme are 2-polyprenyl-6-methoxy-1,4-benzoquinol (DDMQH2) and 2-polyprenyl-3-methyl-6-methoxy-1,4-benzoquinol (DMQH2).|should consider change rxn to Rhea 28286|change|
|[ENSG00000111218](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000111218)|The enzyme is an S-adenosyl-L-methionine-dependent and membrane-associated arginine methyltransferase that can catalyze the formation of omega-N monomethylarginine (MMA) and asymmetrical dimethylarginine (aDMA) in proteins such as NIFK, myelin basic protein, histone H4, H2A and H2A/H2B dimer.  The substrates of this enzyme are S-adenosyl-L-methionine, omega-N monomethylarginine (MMA), asymmetrical dimethylarginine (aDMA), NIFK, myelin basic protein, histone H4, H2A and H2A/H2B dimer, and EWS protein.|protein arginine methyltransferase|remove|
|[ENSG00000111641](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000111641)|The substrates of this enzyme are S-adenosyl-L-methionine and cytosine 4447 in 28S rRNA.|involved in ribosomal assembly|remove|
|[ENSG00000114735](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000114735)|The substrate of this enzyme is N5-glutamine and the GGQ motif of the mitochondrial translation release factor MTRF1L.|peptide involved|remove|
|[ENSG00000117481](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000117481)|The substrates of this enzyme are 5-methylcytosine rRNA and 16S rRNA.|RNA involved|remove|
|[ENSG00000122435](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000122435)|The substrates of this enzyme are cytidine(4) in tRNA(Pro) and tRNA(Gly)(GCC), and adenosine(4) in tRNA(His).|trna involved|remove|
|[ENSG00000122687](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000122687)|The substrate of this enzyme is S-adenosyl-L-methionine and the product is 2'-O-methyluridine at position 1369 in the 16S mitochondrial large subunit ribosomal RNA (mtLSU rRNA).|RNA involved|remove|
|[ENSG00000123427](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000123427)|The substrates of this enzyme are Lys-165 of EEF1A1 and EEF1A2, aminoacyl-tRNA, and GTP.|protein involved|remove|
|[ENSG00000123600](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000123600)|The substrates of this enzyme are N(3)-methylcytidine, tRNA(Ser)(UCN), tRNA(Thr) and potentially mRNAs.|trna involved|remove|
|[ENSG00000123600](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000123600)|The substrates of this enzyme are mitochondrial tRNA (Ser)(UCN), tRNA(Thr), and possibly mRNAs.|tRNA methyltransferase |remove|
|[ENSG00000126457](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000126457)|The substrates of this enzyme are arginyl residues present in proteins such as ESR1, histone H2, H3 and H4, ILF3, HNRNPA1, HNRNPD, NFATC2IP, SUPT5H, TAF15, EWS, HABP4, SERBP1, RBM15, FOXO1, CHTOP and MAP3K5/ASK1.|should be protein according to Uniprot|remove|
|[ENSG00000126749](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000126749)|Enzyme methylates pseudouridine at position 1248 (Psi1248) in 18S rRNA  The substrate of this enzyme is pseudouridine at position 1248 (Psi1248) in 18S rRNA.|Ribosomal RNA|remove|
|[ENSG00000127804](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000127804)|The substrates of this enzyme are mRNAs, U6 snRNAs, 7SK snRNA, 7SL RNA, and the MALAT1 long non-coding RNA.|RNA N6-adenosine-methyltransferase|remove|
|[ENSG00000130305](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000130305)|The substrates of this enzyme are S-adenosyl-L-methionine and cytosine 3782.|rRNA methyltransferase|remove|
|[ENSG00000132275](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000132275)|The substrates of this enzyme are unknown.|Ribosomal related|remove|
|[ENSG00000132600](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000132600)|The substrates of this enzyme are arginine residues in the small nuclear ribonucleoproteins Sm D1 (SNRPD1) and Sm D3 (SNRPD3), histone H4 'Arg-3', histone H2A, and myelin basic protein (MBP).|Protein related|remove|
|[ENSG00000137574](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000137574)|The substrates of this enzyme are 7-monomethylguanosine (m7G) caps of snRNAs and snoRNAs.|snRNAs and snoRNAs related|remove|
|[ENSG00000137760](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000137760)|This enzyme catalyzes the methylation of 5-carboxymethyl uridine to 5-methylcarboxymethyl uridine at the wobble position of the anticodon loop in tRNA.  The substrates of this enzyme are 5-carboxymethyl uridine and 5-methylcarboxymethyl uridine.|DNA repair protein|remove|
|[ENSG00000138382](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000138382)|This enzyme catalyzes the methylation of the 6th position of adenine in position 1832 of 18S rRNA.  The substrate of this enzyme is adenine in position 1832 of 18S rRNA.|rRNA related|remove|
|[ENSG00000139160](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000139160)|The substrates of this enzyme are protein-lysine and flavoprotein ETFB.|Protein-lysine methyltransferase |remove|
|[ENSG00000139780](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000139780)|The substrates of this enzyme are proteins and lysine.|Protein-lysine methyltransferase|remove|
|[ENSG00000142453](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000142453)|The substrates of this enzyme are arginyl residues, histone H3 at 'Arg-17', EP300/P300, PABPC1, ELAVL1, ELAV4, ACACA/acetyl-CoA carboxylase and PARP1.|protein involved|remove|
|[ENSG00000143499](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000143499)|Protein-lysine N-methyltransferase that methylates both histones and non-histone proteins  The substrates of this enzyme are histone H3, p53/TP53, RB1, and other non-histone proteins.|Protein-lysine N-methyltransferase|remove|
|[ENSG00000144401](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000144401)|The substrates of this enzyme are Lys-561 in HSPA1, Lys-564 in HSPA2, Lys-585 in HSPA5, Lys-563 in HSPA6, and Lys-561 in HSPA8.|Protein-lysine methyltransferase|remove|
|[ENSG00000145194](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000145194)|The substrates of this enzyme are big endothelin-1, neurotensin, angiotensin I, substance P, proenkephalin-derived peptides, and prodynorphin-derived peptides.|not related to SAM|remove|
|[ENSG00000145331](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000145331)|This enzyme catalyzes the formation of N(1)-methylguanine at position 9 (m1G9) in tRNAs  The substrates of this enzyme are S-adenosyl-L-methionine, guanine, and tRNAs.|tRNAs  related|remove|
|[ENSG00000145388](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000145388)|The substrates of this enzyme are N6-methyladenosine (m6A) and mRNAs.|mRNAs related|remove|
|[ENSG00000146834](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000146834)|The substrates of this enzyme are S-adenosyl-L-methionine, 7SK snRNA, positive transcription elongation factor b (P-TEFb), little elongation complex (LEC), and LARP7.|snRNA related|remove|
|[ENSG00000150456](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000150456)|The substrate of this enzyme is EEF1A at 'Lys-79'.|Protein N-lysine methyltransferase|remove|
|[ENSG00000156239](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000156239)|The substrates of this enzyme are proteins, Lys-12 of histone H4, Glu residue of proteins with a Gly-Gln-Xaa-Xaa-Xaa-Arg motif, ETF1 on 'Gln-185', and monomethylarsonous acid (3+).|histone related|remove|
|[ENSG00000160310](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000160310)|The substrates of this enzyme are arginyl residues in proteins such as STAT3, FBL, and histone H4.|protein related|remove|
|[ENSG00000162623](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000162623)|S-adenosyl-L-methionine and guanosine|tRNA related|remove|
|[ENSG00000162851](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000162851)|This enzyme methylates two specific adjacent adenosines in the loop of a conserved hairpin near the 3'-end of 12S mitochondrial rRNA.  The substrates of this enzyme are two specific adjacent adenosines in the loop of a conserved hairpin near the 3'-end of 12S mitochondrial rRNA.|rRNA methyltransferase|remove|
|[ENSG00000164169](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000164169)|The substrates of this enzyme are arginine, omega-N monomethylarginine (MMA), and symmetrical dimethylarginine (sDMA).|protein related|remove|
|[ENSG00000165055](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000165055)|The substrates of this enzyme are S-adenosyl-L-methionine, N(3)-methylcytidine, residue 32 of tRNA(Thr)(UGU), and tRNA(Arg)(CCU).|tRNA related|remove|
|[ENSG00000165275](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000165275)|This enzyme catalyzes the formation of N(1)-methylguanine at position 9 (m1G9) in tRNAs.  The substrates of this enzyme are S-adenosyl-L-methionine and tRNAs.|tRNA methyltransferase |remove|
|[ENSG00000165644](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000165644)|The substrates of this enzyme are molecules that contain an O-methyl group.|Putative O-methyltransferase|remove|
|[ENSG00000165792](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000165792)|The substrates of this enzyme are S-adenosyl-L-methionine and mitochondrial small ribosomal subunit (mt-SSU).|RNA methyltransferase|remove|
|[ENSG00000168806](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000168806)|Methyltransferase in wybutosine biosynthesis pathway.  The substrates of this enzyme are S-adenosyl-L-methionine, leucine residues, and alpha-leucine ester residues.|tRNA related|remove|
|[ENSG00000169519](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000169519)|The substrates of this enzyme are N4-methylcytidine (m4C) and mitochondrial 12S rRNA.|rRNA related|remove|
|[ENSG00000171806](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000171806)|Protein-L-histidine N-tele-methyltransferase monomethylates RPL3 to regulate translation elongation.  The substrates of this enzyme are Protein-L-histidine and RPL3.|protein methyltransferase|remove|
|[ENSG00000171861](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000171861)|The substrates of this enzyme are S-adenosyl-L-methionine and Gm1370 in the 16S mitochondrial large subunit ribosomal RNA (mtLSU rRNA).|RNA related|remove|
|[ENSG00000174173](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000174173)|Substrates of this enzyme are mitochondrial tRNA, MT-ND5 mRNA, and adenosine residues.|tRNA related|remove|
|[ENSG00000178694](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000178694)|This enzyme mediates methylation of cytosine to 5-methylcytosine (m5C) at position 34 of mt-tRNA(Met).  The substrates of this enzyme are cytosine and mt-tRNA(Met). |RNA methyltransferase |remove|
|[ENSG00000179299](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000179299)|The substrate of this enzyme is S-adenosyl-L-methionine.|RNA related|remove|
|[ENSG00000180917](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000180917)|This enzyme methylates mRNA and small nuclear RNA (snRNA)  Substrates|RNA related|remove|
|[ENSG00000181038](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000181038)|The substrate of this enzyme is histone H3 at Arg-17.|Histone methyltransferase|remove|
|[ENSG00000181090](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000181090)|The substrates of this enzyme are histone H3 (H3K9me1 and H3K9me2, H3K27me), p53/TP53 (Lys-373), and mitochondrial function-related genes.|Histone methyltransferase|remove|
|[ENSG00000183955](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000183955)|The substrates of this enzyme are histone H4, p53/TP53, and nucleosomes.|Protein-lysine N-methyltransferase|remove|
|[ENSG00000185238](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000185238)|The substrates of this enzyme are proteins with arginine residues.|Protein-arginine N-methyltransferase|remove|
|[ENSG00000185432](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000185432)|The substrates of this enzyme are likely involved in the assembly and release stages of hepatitis C virus (HCV).|not related|remove|
|[ENSG00000186666](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000186666)|O-methyltransferase that specifically monomethylates the 5'-monophosphate of cytoplasmic histidyl tRNA (tRNA(His)) and pre-miRNAs.  The substrates of this enzyme are the 5'-monophosphate of cytoplasmic histidyl tRNA (tRNA(His)) and pre-miRNAs.|RNA 5'-monophosphate methyltransferase|remove|
|[ENSG00000188573](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000188573)|The substrates of this enzyme are S-adenosyl-L-methionine, pre-ribosomal RNA, and proteins containing glutamine residues.|both RNAs and proteins|remove|
|[ENSG00000198890](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000198890)|The substrates of this enzyme are arginyl residues, histone H3 'Arg-2', H2A and H4 'Arg-3', HMGA1, POLB, CRTC2, GPS2, and SIRT7.|Protein related|remove|
|[ENSG00000203791](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000203791)|The substrate of this enzyme is EEF1A at 'Lys-318'.|Protein-lysine methyltransferase|remove|
|[ENSG00000204371](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000204371)|The substrates of this enzyme are|Histone methyltransferase |remove|
|[ENSG00000205629](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000205629)|The substrate of this enzyme is the carboxyl group of the C-terminal leucine residue of protein phosphatase 2A catalytic subunits.|Protein related|remove|
|[ENSG00000206562](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000206562)|S-adenosyl-L-methionine-dependent methyltransferase that methylates residue 32 of the tRNA anticodon loop  The substrates of this enzyme are S-adenosyl-L-methionine and residue 32 of the tRNA anticodon loop.|tRNA related|remove|
|[ENSG00000214756](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000214756)|Protein-lysine methyltransferase that trimethylates citrate synthase.  The substrate of this enzyme is protein-lysine and citrate synthase.|Protein-lysine methyltransferase|remove|
|[ENSG00000241058](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000241058)|S-adenosyl-L-methionine-dependent methyltransferase that specifically methylates the C5 position of cytosine 72 in tRNA(Thr)(TGT) and tRNA(Cys)(GCA).  The substrates of this enzyme are tRNA(Thr)(TGT), tRNA(Cys)(GCA), and tRNA(Thr)(AGT).|RNA methyltransferase 6|remove|
|[ENSG00000250305](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000250305)|The substrates of this enzyme are specific arginine and glutamic acid tRNAs with wobble uridines.|tRNA methyltransferase |remove|
|[ENSG00000278619](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000278619)|The substrates of this enzyme are S-adenosyl-L-methionine and Gm1145 in the 16S mitochondrial large subunit ribosomal RNA (mtLSU rRNA).|rRNA methyltransferase 1|remove|

**Comment by haowang-bioinfo** [comment]
@feiranl nice results! Good correlation between manual curation and GPT curation could be observed.

**Comment by haowang-bioinfo** [comment]
> After GPT check and manual check, all genes are actually not associated with these two reactions.

Both manual and GPT curations showed that all genes of `MAR06710` and `MAR06737` (they have identical GPRs) encode methytransferases for substrates of DNAs, RNAs, or proteins. None of them are found with substrates beta-carboline or salsolinol.

There could two follow-up implementation options:
1) remove all these genes, as well as two reactions;
2) remove these genes, but retain the two reactions as blank GPR rules, assuming that proper enzyme encoding genes can be found later

**Comment by haowang-bioinfo** [comment]
The two reactions ([MAR06710](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06710) and [MAR06737](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06737)) have identical GPRs and each has 72 genes, most of which just get involve in these two reactions.

```
ENSG00000132275: MAR06710, MAR06737
ENSG00000165275: MAR06710, MAR06737
ENSG00000143499: MAR06710, MAR06737
ENSG00000278619: MAR06710, MAR06737
ENSG00000132600: MAR06710, MAR06737
ENSG00000241058: MAR06710, MAR06737
ENSG00000160310: MAR06710, MAR06737
ENSG00000205629: MAR06710, MAR06737
ENSG00000188573: MAR06710, MAR06737
ENSG00000071462: MAR06710, MAR06737
ENSG00000165644: MAR06710, MAR06737
ENSG00000138382: MAR06710, MAR06737
ENSG00000180917: MAR06710, MAR06737
ENSG00000206562: MAR06710, MAR06737
ENSG00000101247: MAR06710, MAR06737
ENSG00000130305: MAR06710, MAR06737
ENSG00000181038: MAR06710, MAR06737
ENSG00000170439: MAR06710, MAR06737
ENSG00000165792: MAR06710, MAR06737
ENSG00000185238: MAR06710, MAR06737
ENSG00000111218: MAR06710, MAR06737
ENSG00000185432: MAR06710, MAR06737
ENSG00000101574: MAR06710, MAR06737
ENSG00000144401: MAR06710, MAR06737
ENSG00000114735: MAR06710, MAR06737
ENSG00000164169: MAR06710, MAR06737
ENSG00000111641: MAR06710, MAR06737
ENSG00000117481: MAR06710, MAR06737
ENSG00000126457: MAR06710, MAR06737
ENSG00000122435: MAR06710, MAR06737
ENSG00000126749: MAR06710, MAR06737
ENSG00000029639: MAR06710, MAR06737
ENSG00000145194: MAR06710, MAR06737
ENSG00000122687: MAR06710, MAR06737
ENSG00000214756: MAR06710, MAR06737
ENSG00000139160: MAR06710, MAR06737
ENSG00000108592: MAR06710, MAR06737
ENSG00000105202: MAR06710, MAR06737
ENSG00000087995: MAR06710, MAR06737
ENSG00000145388: MAR06710, MAR06737
ENSG00000127804: MAR06710, MAR06737
ENSG00000123427: MAR06710, MAR06737
ENSG00000162623: MAR06710, MAR06737
ENSG00000198890: MAR06710, MAR06737
ENSG00000168806: MAR06710, MAR06737
ENSG00000067365: MAR06710, MAR06737
ENSG00000174173: MAR06710, MAR06737
ENSG00000123600: MAR06710, MAR06737
ENSG00000150456: MAR06710, MAR06737
ENSG00000178694: MAR06710, MAR06737
ENSG00000156239: MAR06710, MAR06737
ENSG00000171806: MAR06710, MAR06737
ENSG00000203791: MAR06710, MAR06737
ENSG00000171861: MAR06710, MAR06737
ENSG00000186666: MAR06710, MAR06737
ENSG00000068438: MAR06710, MAR06737
ENSG00000137760: MAR06710, MAR06737
ENSG00000139780: MAR06710, MAR06737
ENSG00000165055: MAR06710, MAR06737
ENSG00000100462: MAR06710, MAR06737
ENSG00000010165: MAR06710, MAR06737
ENSG00000103037: MAR06710, MAR06737
ENSG00000100483: MAR06710, MAR06737
ENSG00000179299: MAR06710, MAR06737
ENSG00000169519: MAR06710, MAR06737
ENSG00000137574: MAR06710, MAR06737, MAR00024
ENSG00000142453: MAR06710, MAR06737, MAR00024
ENSG00000066651: MAR06710, MAR06737, MAR09519
ENSG00000110871: MAR06710, MAR06737, MAR06908
ENSG00000204371: MAR08027, MAR08026, MAR06737, MAR04241, MAR06977, MAR06975, MAR06976, MAR08025, MAR06710
ENSG00000181090: MAR08027, MAR08026, MAR06737, MAR04241, MAR06977, MAR06975, MAR06976, MAR08025, MAR06710
ENSG00000183955: MAR08027, MAR08026, MAR06737, MAR04241, MAR06977, MAR06975, MAR06976, MAR08025, MAR06710
```

**Comment by feiranl** [comment]
I believe we should get rid of these two reactions and their gene-protein-reaction associations. I was uncertain before because I was worried that if we got rid of too many reactions, it might become confusing if we want to add them back in the future. However, I now realize that even if we do decide to bring them back, we can still use the same reaction IDs, so it wouldn't be as complicated as I initially thought. So now I vote for remove.

**Comment by mihai-sysbio** [comment]
When in doubt, I would lean towards the answer supported by validation.

**Comment by feiranl** [comment]
Then I will remove those two rxns.

**Comment by mihai-sysbio** [comment]
After removing these reactions, one should also remove metabolites that would not be used in the model anymore, such as [MAM02045c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02045c) and [MAM00156c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00156c).
