### ISSUE TITLE
remove non-metabolic genes from Glycerophospholipid metabolism

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#477]
### Description of the issue:
* Non-metabolic genes are discovered in the GPR rules of following reactions in `Glycerophospholipid metabolism` subsystem:

| gene            | Reasons                                                                                  | Subsystems                    | RxnIDs                              |
|-----------------|------------------------------------------------------------------------------------------|-------------------------------|:-------------------------------------|
| [ENSG00000105198](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000105198) | [not phospholipase, strong inducer of T-cell apoptosis](https://www.uniprot.org/uniprotkb/Q9UHV8/entry) | Glycerophospholipid metabolism | MAR00633;MAR00645 |
| [ENSG00000105205](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000105205) | [has no lysophospholipase activity, but regulates immune responses](https://www.uniprot.org/uniprotkb/Q05315/entry) | Glycerophospholipid metabolism | MAR00633;MAR00645 |
| [ENSG00000105223](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000105223) | [Exonucleolytic cleavage in the 5'- to 3'-direction to yield nucleoside 3'-phosphates](https://www.uniprot.org/uniprotkb/Q8IV08/entry) | Glycerophospholipid metabolism;Ether lipid metabolism | MAR00629;MAR00642;MAR00660;MAR08523;MAR08525;MAR07605 |
| [ENSG00000138308](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000138308) | [does not seem to have catalytic activity](https://www.uniprot.org/uniprotkb/Q9BX93/entry) | Glycerophospholipid metabolism;Ether lipid metabolism;Glycerolipid metabolism | MAR00463;MAR05254;MAR00630;MAR00643;MAR07603;MAR07615 |
| [ENSG00000166428](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000166428) | [exhibits no phospholipase activity](https://www.uniprot.org/uniprotkb/Q96BZ4/entry) | Glycerophospholipid metabolism;Ether lipid metabolism | MAR00629;MAR00642;MAR00660;MAR08523;MAR08525;MAR07605 |
| [ENSG00000187980](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000187980) | [annotated as inactive](https://www.uniprot.org/uniprotkb/Q5R387/entry) | Glycerophospholipid metabolism;Ether lipid metabolism;Glycerolipid metabolism | MAR00463;MAR05254;MAR00630;MAR00643;MAR07603;MAR07615 |

#### Current feature/value/output:
* The association of these genes is lack of evidence according to the provided reasons

#### Expected feature/value/output:
* Remove above genes from Human-GEM 

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by feiranl** [comment]
LGTM! Please go ahead!
