### ISSUE TITLE
remove non-metabolic genes from Cholesterol biosynthesis pathway

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#478]
### Description of the issue:
* Non-metabolic genes are discovered in the GPR rules of `Cholesterol biosynthesis pathway` as below:

| gene            | Reasons                                                                                  | Subsystems                    | RxnIDs                              |
|-----------------|------------------------------------------------------------------------------------------|-------------------------------|:-------------------------------------|
| [ENSG00000183305](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000183305) | [anitgen involve in tumor progression and embryonal development](https://www.uniprot.org/uniprotkb/P43356/entry) | Cholesterol biosynthesis 1 (Bloch pathway) | MAR01495 |
| [ENSG00000268606](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000268606) | [anitgen involve in tumor progression and embryonal development](https://www.uniprot.org/uniprotkb/P43356/entry) | Cholesterol biosynthesis 1 (Bloch pathway) | MAR01495 |

#### Current feature/value/output:
* The association of these genes is lack of evidence according to the provided reasons

#### Expected feature/value/output:
* Remove above genes from Human-GEM 

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by feiranl** [comment]
LGTM!
