### ISSUE TITLE
remove non-metabolic isolated genes 

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#481]
### Description of the issue:
* Non-metabolic genes are discovered in the Subsystems of `Isolated` as below:

| gene            | Reasons                                                                                  | Subsystems                    | RxnIDs                              |
|-----------------|------------------------------------------------------------------------------------------|-------------------------------|:-------------------------------------|
|[ENSG00000082014](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000082014)|[Involved in transcriptional activation and repression of select genes by chromatin remodeling](https://www.uniprot.org/uniprotkb/Q6STE5/entry)|Isolated|MAR00024|
|[ENSG00000115641](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000115641)|[May function as a molecular transmitter linking various signaling pathways to transcriptional regulation](https://www.uniprot.org/uniprotkb/Q14192/entry)|Isolated|MAR00024|
|[ENSG00000120158](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000120158)|[Does not have cyclase activity](https://www.uniprot.org/uniprotkb/Q9Y2P8/entry)|Isolated|MAR09546|
|[ENSG00000121486](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000121486)|[Not methyltransferase. May play a role in motor coordination and exploratory behavior.](https://www.uniprot.org/uniprotkb/Q7Z2T5/entry)|Isolated|MAR09519|
|[ENSG00000124006](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000124006)|[Core component of the 3M complex, a complex required to regulate microtubule dynamics and genome integrity. ](https://www.uniprot.org/uniprotkb/O75147/entry)|Isolated|MAR09493|
|[ENSG00000125686](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000125686)|[Not lipid associated. Component of the Mediator complex, a coactivator involved in the regulated transcription of nearly all RNA polymerase II-dependent genes.](https://www.uniprot.org/uniprotkb/Q15648/entry)|Isolated|MAR00024|
|[ENSG00000127511](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000127511)|[Not lipid associated. Acts as a transcriptional repressor.](https://www.uniprot.org/uniprotkb/O75182/entry)|Isolated|MAR00024|
|[ENSG00000130589](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000130589)|[Helicase that acts as a transcriptional coactivator.](https://www.uniprot.org/uniprotkb/Q9BYK8/entry)|Isolated|MAR00024|
|[ENSG00000134317](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000134317)|[Transcription factor involved in epithelial development](https://www.uniprot.org/uniprotkb/Q9NZI5/entry)|Isolated|MAR00024|
|[ENSG00000135473](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000135473)|[not annotated for this rxn in KEGG](https://www.uniprot.org/uniprotkb/Q9NZI5/entry)|Isolated|MAR09490|
|[ENSG00000136715](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000136715)|[Acts as a transcriptional repressor.](https://www.uniprot.org/uniprotkb/Q9H0E3/entry)|Isolated|MAR09464|
|[ENSG00000148677](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000148677)|[May play an important role in endothelial cell activation.](https://www.uniprot.org/uniprotkb/Q15327/entry)|Isolated|MAR00024|
|[ENSG00000162571](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000162571)|[Inactive polyglycylase.](https://www.uniprot.org/uniprotkb/Q6ZVT0/entry)|Isolated|MAR09505|
|[ENSG00000167371](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000167371)|[not sugar related, may be involved in synaptic transmission in the central nervous system.](https://www.uniprot.org/uniprotkb/Q7Z6L0/entry)|Isolated|MAR09464|
|[~~ENSG00000169375~~](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000169375)|[Acts as a transcriptional repressor.](https://www.uniprot.org/uniprotkb/Q96ST3/entry)|Isolated|MAR00024|
|[~~ENSG00000177565~~](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000177565)|[recruitment of the ubiquitin/19S proteasome complex.](https://www.uniprot.org/uniprotkb/Q9BZK7/entry)|Isolated|MAR00024|
|[ENSG00000185250](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000185250)|[Probable inactive PPIase with no peptidyl-prolyl cis-trans isomerase activity.](https://www.uniprot.org/uniprotkb/Q8IXY8/entry)|Isolated|MAR09492|
|[ENSG00000185615](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000185615)|[remove from rxn MAR00030, is not a transport gene.](https://www.uniprot.org/uniprotkb/Q13087/entry)|Isolated;Transport reactions|MAR00030;MAR09806|
|[ENSG00000177200](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000177200)|[Acts as a transcriptional coactivator for PPARA and possibly other nuclear receptors.](https://www.uniprot.org/uniprotkb/Q3L8U1/entry)|Isolated|MAR00024|

#### Current feature/value/output:
* The association of these genes is lack of evidence according to the provided reasons

#### Expected feature/value/output:
* Remove above genes from Human-GEM 

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
The gene [ENSG00000185615](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000185615) is currently associated with two reactions MAR00030 and MAR09806. It [catalyzes the rearrangement of -S-S- bonds in the pancreas and may act as a chaperone that inhibits aggregation of misfolded proteins](https://www.uniprot.org/uniprotkb/Q13087/entry), this seems match well with [MAR09806](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09806).

**Comment by feiranl** [comment]
Yes. It is kind of match this rxn. I was thinking even this rxn should be removed, as the protein disulfide bond formation should be protein post-translational modification process rather a metabolic rxn, but we can keep this rxn for now and the gene association.

**Comment by haowang-bioinfo** [comment]
> I was thinking even this rxn should be removed, as the protein disulfide bond formation should be protein post-translational modification process rather a metabolic rxn,

yes indeed, it belongs to PTM process and presented as a dead-end reaction in [Human-GEM](https://metabolicatlas.org/explore/Human-GEM/map-viewer/cytosol_4?dim=2d&panel=0&sel=MAR09806&search=MAR09806&coords=-9954,-5417,1,0,0,500&dataTypes=None&dataSources=None&dataSets=None)

**Comment by feiranl** [comment]
Since `ENSG00000177565` and `ENSG00000169375` are complex subunits, it ould be safe to keep them for now.
