### ISSUE TITLE
ARG1 and ARG2 GPRs are incorrect

### ISSUE THREAD

**Issue by juliette-cooke** [SysBioChalmers/Human-GEM#495]
I am studying gene knockouts in Human 1, specifically a knockout of the gene ARG1, also known as ENSG00000118520, which codes for ARGN. There is a second gene, ARG2, which codes for a mitochondrial version of the same enzyme (ARGNm).

#### Current behavior:
Currently in Human 1, knocking out either of the ARG genes has no effect because they are both assigned to the GPR of both ARGN and ARGNm reactions in an "OR". This means that if I knock out ARG1, the ARGN reaction is not affected because ARG2 is still active.

| Gene name  | ENSG | Gene card |Current single knockout effect|
| ------------- | ------------- | ----| --|
| ARG1  | ENSG00000118520  |[ARG1](https://www.genecards.org/cgi-bin/carddisp.pl?gene=ARG1)| None|
| ARG2  | ENSG00000081181  |[ARG2](https://www.genecards.org/cgi-bin/carddisp.pl?gene=ARG2)| None|

#### Expected behavior:
Previous models (Recon 2 for example, see below) and the gene cards show that ARG1 codes for ARGN, and ARG2 codes for ARGNm. Therefore, ENSG00000118520 should be the sole gene in the GPR of MAR03816, and ENSG00000081181 should be the sole gene in the GPR of MAR08426.
| Gene name  | ENSG | Gene card |Expected single knockout effect|
| ------------- | ------------- | ----| --|
| ARG1  | ENSG00000118520  |[ARG1](https://www.genecards.org/cgi-bin/carddisp.pl?gene=ARG1)| MAR03816 (ARGN)|
| ARG2  | ENSG00000081181  |[ARG2](https://www.genecards.org/cgi-bin/carddisp.pl?gene=ARG2)| MAR08426 (ARGNm)|

#### Recon 2
| Gene name  | Gene ID |  Single knockout effect|
| ------------- | ------------- | --|
| ARG1  | 383.1  | ARGN|
| ARG2  | 384.1  |ARGNm|

**Comment by haowang-bioinfo** [comment]
@juliette-cooke thanks for reporting this!

We are very welcome community contributions that will be incorporated right away after verification.

**Comment by haowang-bioinfo** [comment]
It is confirmed that arginase-encoding genes [ENSG00000118520](https://www.uniprot.org/uniprotkb/P05089/entry#subcellular_location) and [ENSG00000081181](https://www.uniprot.org/uniprotkb/P78540/entry#subcellular_location) are localised at cytosol and mitochondrion, respectively. The corresponding changes had been made in #496, as proposed.

@juliette-cooke please review the [changes](https://github.com/SysBioChalmers/Human-GEM/pull/496/files), and thanks again.

**Comment by haowang-bioinfo** [comment]
> Previous models (Recon 2 for example) and the gene cards show that ARG1 codes for ARGN, and ARG2 codes for ARGNm.

By checking [Recon3D](https://www.vmh.life/#reaction/ARGN), it is found that both ARG genes (ENSG00000118520 and ENSG00000081181) are assigned to the GPR of [ARGN](http://bigg.ucsd.edu/models/Recon3D/reactions/ARGN) reaction in an "OR" relation.

**Comment by haowang-bioinfo** [comment]
@all-contributors please add @juliette-cooke for the bug report.
