### ISSUE TITLE
TYMP and PNP GPRs

### ISSUE THREAD

**Issue by juliette-cooke** [SysBioChalmers/Human-GEM#498]
I am working on a knockout of the TYMP gene in Human 1, which codes for the TMDPP enzyme. However, the knockout has no effect on any reactions due to its GPR.

#### Current behavior:
1) Knocking out the TYMP gene in Human 1 has no effect on the TMDPP (MAR04485) reaction because it shares the GPR with the [PNP](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000198805;r=14:20461992-20477094) gene. 

2) The TYMP gene is also part of the GPRs of 3 other reactions shared with PNP: MAR04709 MAR04695 MAR04603. This may need extra checking but based on Recon3D (see below) and the UniProt pages for [TYMP](https://www.uniprot.org/uniprotkb/P19971/entry) and [PNP](https://www.uniprot.org/uniprotkb/P00491/entry), TYMP should not be in the GPRs of these 3 reactions.

| Gene name | ENSG            | Gene card                                                       | Current single knockout effect  |
| --------- | --------------- |------------------------------ | ------------------ |
| TYMP      | ENSG00000025708 | [TYMP](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000025708;r=22:50525752-50530032) | None                           |   
| PNP      | ENSG00000198805 | [PNP](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000198805;r=14:20461992-20477094) | MAR08791 MAR08486 MAR04663 MAR04662 MAR04651 MAR04574 |     

Metabolic Atlas viewer: 
[TYMP](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000025708)
[PNP](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000198805)

#### Expected feature/value/output:
The TYMP gene should only code for [MAR04485](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04485), and all the other reactions linked to PNP and TYMP should only be PNP. This is the case in Recon3D for example (see below).

| Gene name | ENSG            | Gene card                                                       | Expected single knockout effect  |
| --------- | --------------- |------------------------------ | ------------------ |
| TYMP      | ENSG00000025708 | [TYMP](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000025708;r=22:50525752-50530032) | MAR04485                           |     
| PNP      | ENSG00000198805 | [PNP](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000198805;r=14:20461992-20477094) | MAR08791 MAR08486 MAR04709 MAR04695 MAR04663 MAR04662 MAR04651 MAR04603 MAR04574 |   

#### Recon3D
[TYMP](http://bigg.ucsd.edu/models/Recon3D/genes/1890_AT1)
[PNP](http://bigg.ucsd.edu/models/Recon3D/genes/4860_AT1)

**Comment by haowang-bioinfo** [comment]
@juliette-cooke thanks, will check this out

**Comment by haowang-bioinfo** [comment]
After taking away MAR04485 (#499), [9 reactions](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000198805) are now catalyzed by [PNP](https://www.uniprot.org/uniprotkb/P00491/entry), which actually is know to interact only with substrates inosine ([MAR04574](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04574)), hypoxanthine ([MAR04709](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04709)), guanosine ([MAR04651](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04651)), guanine ([MAR04603](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04603)), adenosine ([MAR08486](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08486)), and adenine ([MAR04695](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04695)).

This leaves a question about the validity of the other reactions [MAR04662](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04662), [MAR04663](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04663), [MAR08791](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08791).

**Comment by haowang-bioinfo** [comment]
> This leaves a question about the validity of the other reactions [MAR04662](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04662) ([nicotinate D-ribonucleoside](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02584c)), [MAR04663](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04663) ([xanthosine](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03149c)), [MAR08791](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08791) ([nicotinamide ribonucleoside](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02582c)). Should these reactions be removed or kept?

The reaction MAR04663 is supported by this [reference](https://pubmed.ncbi.nlm.nih.gov/12180982/), but no experimental evidence found with MAR04662 and MAR8791.
