### ISSUE TITLE
Refine GPR for Nicotinate and nicotinamide metabolism

### ISSUE THREAD

**Issue by manas-kohli** [SysBioChalmers/Human-GEM#503]
According to a recent nature paper: https://doi.org/10.1038/s42255-021-00374-y NADK and NADK2 have non-overlapping roles in producing NADP+. Accordingly, I propose that the GPR for MAR04268 be updated to just NADK2 and for MAR04269 to just NADK.

**Comment by haowang-bioinfo** [comment]
@manas-kohli thanks for reporting this, will check this out

**Comment by haowang-bioinfo** [comment]
As described in the above [paper](https://doi.org/10.1038/s42255-021-00374-y), "NADPH exists in separate pools in both the cytosol and mitochondria." and "Human cells express two NADKs, cytosolic NADK and mitochondrial NADK2, which generate compartment-specific sources of reducing power."

More pieces of evidence provide the same info: [NADK](https://www.uniprot.org/uniprotkb/O95544/entry#subcellular_location) and [NADK2](https://www.uniprot.org/uniprotkb/Q4G0N4/entry#subcellular_location) are specifically expressed in cytosol and mitochondrion, respectively.

Thus, subsequent changes will be:
- assign only NADK2 to [MAR04278](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04278)
- assign only NADK to [MAR04269](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04269)
- empty GPR to [MAR04279](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04279)

**Comment by haowang-bioinfo** [comment]
@manas-kohli please review the [changes](https://github.com/SysBioChalmers/Human-GEM/pull/504/files) that were proposed by you

**Comment by haowang-bioinfo** [comment]
would it be a better option to just delete the nucleus version reaction [MAR04279](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04279), which is lack of any supporting evidence?

**Comment by manas-kohli** [comment]
I think deleting the nuclear compartment reaction might be sensible and the proposed changes seem accurate

**Comment by haowang-bioinfo** [comment]
> I think deleting the nuclear compartment reaction might be sensible and the proposed changes seem accurate

Thanks for the feedback, and agree the deletion.

In addition, this reaction [MAR04279](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04279) exists as a dead-end both in [nucleus compartment](https://metabolicatlas.org/explore/Human-GEM/map-viewer/nucleus?dim=2d&panel=0&sel=MAR04279&search=MAR04279&coords=-6236.97,-12776.17,0.2,0,0,500&dataTypes=None&dataSources=None&dataSets=None) and the [subsystem](https://metabolicatlas.org/explore/Human-GEM/map-viewer/nicotinate_and_nicotinamide_metabolism?dim=2d&panel=0&sel=MAR04279&search=MAR04279&coords=-4536.5,-793.2,1,0,0,500&dataTypes=None&dataSources=None&dataSets=None) of `Nicotinate and nicotinamide metabolism`. Its deletion should have no much impact to the rest of the network.

**Comment by haowang-bioinfo** [comment]
fixed in #506

**Comment by haowang-bioinfo** [comment]
@all-contributors please add @manas-kohli for the bug report.

**Comment by haowang-bioinfo** [comment]
@all-contributors please add @manas-kohli for the bug report.

**Comment by haowang-bioinfo** [comment]
> Uuh tricky, it looks like this contribution has to be added in manually.

please go ahead

**Comment by mihai-sysbio** [comment]
> please go ahead

done, see https://github.com/SysBioChalmers/Human-GEM/pull/550

**Comment by haowang-bioinfo** [comment]
> done, see https://github.com/SysBioChalmers/Human-GEM/pull/550

thanks
