### ISSUE TITLE
GPR refinement of Pyrroline-5-carboxylate reductase

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#505]
According to the [paper](https://www.nature.com/articles/s42255-021-00374-y) mentioned in #503: "proline synthesis involves the formation of 1-pyrroline-5-carboxylate (P5C) from glutamate, and P5C can be further reduced to proline by NAD(P) H-dependent P5C reductase enzymes, through either [PYCR1](https://www.uniprot.org/uniprotkb/P32322/entry) or [PYCR2](https://www.uniprot.org/uniprotkb/Q96C36/entry) in mitochondria or the [PYCRL](https://www.uniprot.org/uniprotkb/Q53H96/entry) (aka PYCR3) in the cytosol." 

Above statement is correct, except that [PYCR2](https://www.uniprot.org/uniprotkb/Q96C36/entry#subcellular_location) is also localized in cytosol. This corresponds to 4 reactions catalyzed by pyrroline-5-carboxylate reductase:
[MAR03833](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03833): cytosol, NADPH cofactor
[MAR03835](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03835): cytosol, NADH cofactor
[MAR03837](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03837): mitochondrion, NADPH cofactor
[MAR08609](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08609): mitochondrion, NADH cofactor
Now these reactions have the same GPR: `PYCR1 or PYCR2 or PYCRL or LEFTY1` (LEFTY1 had already been removed in [v1.14.0](https://github.com/SysBioChalmers/Human-GEM/releases) via #465).

**Expected changes:**
Refine GPRs of these 4 reaction according to their subcellular localisation:
MAR03833: `PYCR2 or PYCRL`
MAR03835: `PYCR2 or PYCRL`
MAR03837: `PYCR1 or PYCR2`
MAR08609: `PYCR1 or PYCR2`

**Comment by feiranl** [comment]
LGTM! Please go ahead and make the commit.

**Comment by haowang-bioinfo** [comment]
> LGTM! Please go ahead and make the commit.

thanks for double check this.

Currently the same GPR, `PYCR1 or PYCR2 or PYCRL or LEFTY1`, were associated with following reactions:
[MAR04778](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04778): cytosol, NADH cofactor
[MAR04779](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04779): mitochondrion, NADH cofactor
[MAR04780](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04780):cytosol, NADPH cofactor
[MAR04781](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04781): mitochondrion, NADPH cofactor
There is no evidence supporting these GPRs, should be they turned into blank?
