### ISSUE TITLE
Refine GPR annotation for Glycolysis pathway

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#507]
### Description of the issue:
|Enzyme|rxn|GPT result|GPT reason|Action|
|-----------------|------------------------------------------------------------------------------------------|---------------------------------------------------------------------|-------------------------------|-------------------------------------|
|[ENSG00000198099](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000198099)|MAR03905: ethanol[c] + NAD+[c] = acetaldehyde[c] + H+[c] + NADH[c]|No|The substrates are all-trans-retinol, 9-cis-retinol, long chain omega-hydroxy fatty acids, 20-HETE, 20-oxoarachidonate, and (5Z,8Z,11Z,14Z)-eicosatetraenedioate. |[Rhea:21284;42052;39803;39799;60660](https://www.uniprot.org/uniprotkb/P08319/entry)|
|[ENSG00000184254](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000184254)|MAR04283: acetaldehyde[c] + H2O[c] + NADP+[c] = acetate[c] + 2 H+[c] + NADPH[c]|No|Catalyzing the formation of retinoic acid from all-trans retinal|[Rhea:42080](https://www.uniprot.org/uniprotkb/P47895/entry)|
|[ENSG00000147576](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000147576)|MAR03905: ethanol[c] + NAD+[c] = acetaldehyde[c] + H+[c] + NADH[c]|No|The substrates are gamma-hydroxybutyrate (GHB), succinic semialdehyde (SSA), 2-ketoglutarate (2-KG), D-2-hydroxyglutarate (D-2-HG), D,L-3-hydroxyisobutyrate and L-3-hydroxybutyrate (L-3-OHB).|[Rhea:23048](https://www.uniprot.org/uniprotkb/Q8IWW8/entry)|
|[ENSG00000143149](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000143149)|MAR08357: acetaldehyde[m] + H2O[m] + NAD+[m] = acetate[m] + 2 H+[m] + NADH[m]|Yes|Yes, the substrates and products of this enzyme cover acetaldehyde, acetate, H+, H2O, NAD+, NADH. This enzyme catalyzes the irreversible oxidation of a broad range of aldehydes to the corresponding acids in an NAD-dependent reaction, which includes acetaldehyde being converted into acetate, and NAD+ being reduced to NADH.|[Rhea:17985;19105](https://www.uniprot.org/uniprotkb/P49189/entry)|
|[ENSG00000132746](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000132746)|MAR04283: acetaldehyde[c] + H2O[c] + NADP+[c] = acetate[c] + 2 H+[c] + NADPH[c]|No|No, the substrates and products of this enzyme do not cover the given metabolites. This enzyme specifically oxidizes medium and long chain aldehydes into non-toxic fatty acids, so the only metabolites it covers are aldehydes.|[remove the gene](https://www.uniprot.org/uniprotkb/P48448/entry)|
|[ENSG00000180011](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000180011)|MAR03905: ethanol[c] + NAD+[c] = acetaldehyde[c] + H+[c] + NADH[c]|No|No, the substrates and products of this enzyme do not cover the metabolites given (acetaldehyde, ethanol, H+, NAD+, NADH). This enzyme functions as a 15-oxo-prostaglandin 13-reductase and acts on 15-keto-PGE1, 15-keto-PGE2, 15-keto-PGE1-alpha and 15-keto-PGE2-alpha with highest efficiency towards 15-keto-PGE2-alpha, but not on acetaldehyde, ethanol, H+, NAD+, NADH.|[Rhea:11912](https://www.uniprot.org/uniprotkb/Q8N4Q0/entry)|
|[ENSG00000180011](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000180011)|MAR04360: H2O[c] + methylglyoxal[c] + NADP+[c] = 2 H+[c] + NADPH[c] + pyruvate[c]|No|No, the substrates and products of this enzyme do not cover metabolites given: H+, H2O, methylglyoxal, NADP+, NADPH, pyruvate. The enzyme functions as 15-oxo-prostaglandin 13-reductase, with substrates and products being 15-keto-PGE1, 15-keto-PGE2, 15-keto-PGE1-alpha, 15-keto-PGE2-alpha, and NADPH.|[Rhea:11912](https://www.uniprot.org/uniprotkb/Q8N4Q0/entry)|
|[ENSG00000131482](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000131482)|MAR08652: carbamoyl-phosphate[r] + glucose[r] = CO2[r] + glucose-6-phosphate[r] + NH3[r]|No|No, the substrates and products of this enzyme do not cover all of the metabolites given. The enzyme hydrolyzes glucose-6-phosphate to glucose, meaning the substrates and products of the enzyme are glucose-6-phosphate and glucose, not carbamoyl-phosphate, CO2, glucose, glucose-6-phosphate, and NH3.|[Rhea:16689](https://www.uniprot.org/uniprotkb/P35575/entry)|
|[ENSG00000130649](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000130649)|MAR08757: ethanol[c] + H+[c] + NADPH[c] + O2[c] = acetaldehyde[c] + 2 H2O[c] + NADP+[c]|No|No, the substrates and products of this enzyme do not cover the metabolites given: acetaldehyde, ethanol, H+, H2O, NADP+, NADPH, O2. This enzyme only catalyzes the hydroxylation of carbon-hydrogen bonds in fatty acids, and its substrates and products are fatty acids and oxygen, respectively.|[Rhea:50076;39787;50088;39751;50096;26205](https://www.uniprot.org/uniprotkb/P05181/entry)|
|[ENSG00000143891](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000143891)|MAR07745: beta-D-glucose[c] <= glucose[c]|No|No, the substrates and products of this enzyme do not cover metabolites beta-D-glucose and glucose, as the enzyme only catalyzes the interconversion of beta-D-galactose and alpha-D-galactose.|[Rhea:28675;10264](https://www.uniprot.org/uniprotkb/Q96C23/entry)|
|[ENSG00000141349](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000141349)|MAR08652: carbamoyl-phosphate[r] + glucose[r] = CO2[r] + glucose-6-phosphate[r] + NH3[r]|No|No, the substrates and products of this enzyme do not cover the given metabolites. The enzyme hydrolyzes glucose-6-phosphate to glucose, so the substrates and products are glucose-6-phosphate and glucose, not carbamoyl-phosphate, CO2, glucose, glucose-6-phosphate, and NH3.|[Rhea:16689](https://www.uniprot.org/uniprotkb/Q9BUM1/entry)|
|[ENSG00000006534](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000006534)|MAR04283: acetaldehyde[c] + H2O[c] + NADP+[c] = acetate[c] + 2 H+[c] + NADPH[c]|No|No, the substrates and products of this enzyme do not cover the metabolites given. This enzyme oxidizes medium and long chain saturated and unsaturated aldehydes, benzaldehyde, and can use both NADP(+) and NAD(+) as electron acceptor. It has low activity towards acetaldehyde and 3,4-dihydroxyphenylacetaldehyde, and may not metabolize short chain aldehydes. The metabolites given are acetaldehyde, acetate, H+, H2O, NADP+, NADPH, which are not covered by this enzyme.|[Rhea: 33739;44100;59904; 21660;11840;59908;59912;59916;59920](https://www.uniprot.org/uniprotkb/P43353/entry)|
|[ENSG00000197894](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000197894)|MAR03905: ethanol[c] + NAD+[c] = acetaldehyde[c] + H+[c] + NADH[c]|No|No, the substrates and products of this enzyme do not cover acetaldehyde, ethanol, H+, NAD+, NADH. This enzyme catalyzes the oxidation of long-chain primary alcohols and S-(hydroxymethyl) glutathione, as well as the oxidation of long-chain omega-hydroxy fatty acids, such as 20-HETE, producing both an intermediate aldehyde and a dicarboxylic acid. It does not catalyze the oxidation of ethanol and does not involve acetaldehyde, H+, NAD+, or NADH.|[Rhea:19981;19985;39803;39799](https://www.uniprot.org/uniprotkb/P11766/entry)|
|[ENSG00000072210](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000072210)|MAR08357: acetaldehyde[m] + H2O[m] + NAD+[m] = acetate[m] + 2 H+[m] + NADH[m]|No|No, the substrates and products of this enzyme do not cover acetaldehyde, acetate, H+, H2O, NAD+, NADH. This enzyme catalyzes the oxidation of medium and long chain aliphatic aldehydes to fatty acids, not acetaldehyde, acetate, H+, H2O, NAD+, NADH.|[Rhea:36135;33739;39015;44016;44020;44168;44104;44172;44100;44108;24216](https://www.uniprot.org/uniprotkb/P51648/entry)|
|[ENSG00000149925](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000149925)|MAR04355: DHAP[c] + erythrose-4-phosphate[c] = sedoheptulose-1,7-bisphosphate[c]|No|No, the substrates and products of this enzyme do not cover DHAP, erythrose-4-phosphate, and sedoheptulose-1,7-bisphosphate. This enzyme catalyzes the reversible conversion of beta-D-fructose 1,6-bisphosphate (FBP) into two triose phosphates, which does not include DHAP, erythrose-4-phosphate, and sedoheptulose-1,7-bisphosphate as metabolites.|[remove the gene](https://www.uniprot.org/uniprotkb/P04075/entry)|
|[ENSG00000154305](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000154305)|MAR04368: 1,3-bisphospho-D-glycerate[c] + ADP[c] <= 3-phospho-D-glycerate[c] + ATP[c]|No|No, the substrates and products of this enzyme do not cover the metabolites 1,3-bisphospho-D-glycerate, 3-phospho-D-glycerate, ADP, and ATP. This enzyme is responsible for transporting large cargos like collagen VII, lipoproteins, and COPII coat components, but does not directly interact with the above metabolites.|[involve in ER transportation, remove the gene from HumanGEM](https://www.uniprot.org/uniprotkb/Q5JRA6/entry)|
|[ENSG00000166800](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000166800)|MAR04281: H+[x] + NADH[x] + pyruvate[x] <= L-lactate[x] + NAD+[x]|Yes|Yes, the substrates and products of this enzyme cover the given metabolites: H+, L-lactate, NAD+, NADH, pyruvate. This is because the enzyme catalyzes the interconversion of L-lactate and pyruvate with NAD+ as a coenzyme. Therefore, these metabolites are all part of the reaction catalyzed by the enzyme.|[remove the gene, not x annotation](https://www.uniprot.org/uniprotkb/Q6ZMR3/entry)|
|[ENSG00000121691](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000121691)|MAR08360: ethanol[x] + H2O2[x] = acetaldehyde[x] + 2 H2O[x]|No|No, the substrates and products of this enzyme do not cover metabolites given: acetaldehyde, ethanol, H2O, H2O2. This enzyme catalyzes the degradation of hydrogen peroxide (H2O2) to water and oxygen, and does not involve acetaldehyde, ethanol, H2O.|[Rhea:20309](https://www.uniprot.org/uniprotkb/P04040/entry)|
|[ENSG00000196616](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000196616)|MAR03905: ethanol[c] + NAD+[c] = acetaldehyde[c] + H+[c] + NADH[c]|No|No, the substrates and products of this enzyme do not cover the metabolites acetaldehyde, ethanol, H+, NAD+, NADH. This enzyme catalyzes the NAD-dependent oxidation of all-trans-retinol and its derivatives as well as the NADH-dependent reduction of all-trans-retinal and its derivatives.|[Rhea:21284;55936; 60632](https://www.uniprot.org/uniprotkb/P00325/entry)|

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
@feiranl maybe clarify a bit the `action` column.

are those Rhea ids the reactions to be added?

**Comment by feiranl** [comment]
We will firstly fix the remove gene part. reaction addition part will be fixed later

**Comment by haowang-bioinfo** [comment]
fixed in #517 and #535
