### ISSUE TITLE
feat: remove pseudogenes, read through genes, and ones with only predicted functions

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#510]
### Description of the issue:

It is proposed to remove following genes, because they are either pseudogenes, or genes from read through transcripts (from two adjacent genes in the same strand with same orientation), or the ones with only predicted functions.

|      gene id   |      check results                              |
|----------------|-------------------------------------------------|
| [ENSG00000011052](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000011052)|read through                                     |
| [ENSG00000099984](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000099984)|pseudogene                                       |
| [ENSG00000100101](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000100101)|novel transcript                                 |
| [ENSG00000114786](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000114786)|read through                                     |
| [ENSG00000125954](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000125954)|read through                                     |
| [ENSG00000133475](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000133475)|pseudogene                                       |
| ~~[ENSG00000137700](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000137700)~~|~~with only predicted function~~                |
| [ENSG00000168970](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000168970)| read through                                     |
| [ENSG00000172782](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000172782)| with only predicted function  |
| [ENSG00000189366](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000189366)| pseudogene, only predicted function  |
| [ENSG00000250741](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000250741)| read through, no annotation |
| [ENSG00000255730](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000255730)| with only predicted function |
| [ENSG00000259030](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000259030)| read through |
| [ENSG00000259075](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000259075)| read through, only predicted function |
| [ENSG00000259916](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000259916)| only predicted function |
| [ENSG00000272916](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000272916)| novel transcript, only predicted function |
| [ENSG00000275183](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000275183)| only predicted function |
| [ENSG00000276380](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000276380)| pseudogene |
| [ENSG00000282301](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000282301)| read through |
| [ENSG00000284844](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000284844)| only predicted function |
| [ENSG00000285043](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000285043)| novel protein, without function annotation |
| [ENSG00000285269](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000285269)| read through, only predicted function |

**Comment by feiranl** [comment]
Looks good! May I know how these genes were identified here? I double checked some read through, which is clear. As for the novel protein or predicted function, I am not sure how to double check them

**Comment by haowang-bioinfo** [comment]
> May I know how these genes were identified here?

very good question! 

Now the number of genes is 2292 in `genes.tsv`. When loading all these Ensembl ids to [uniprot.org/id-mapping](https://www.uniprot.org/id-mapping) for mapping to UniProtKB. Then these genes pop out as unmapped.

> As for the novel protein or predicted function, I am not sure how to double check them

Obviously they haven't been annotated by Uniprot. But they can be checked on Ensembl and NCBI

**Comment by haowang-bioinfo** [comment]
as the only gene for `MAR01621` and `MAR06386`, the deletion of [ENSG00000137700](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000137700) is suspended.

**Comment by haowang-bioinfo** [comment]
> as the only gene for MAR01621 and MAR06386, the deletion of [ENSG00000137700](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000137700) is suspended.

as a follow-up, replace [ENSG00000137700](https://www.uniprot.org/uniprotkb/U3KPU7/entry) with [ENSG00000281500](https://www.uniprot.org/uniprotkb/O43826/entry), because both refer to the same gene SLC37A4 while the later was reviewed with proper annotation.

**Comment by haowang-bioinfo** [comment]
now there are still 5 genes that are left unmapped to Uniprot, here are manually checked and associated as below:
|      Ensembl id   |  Uniprot id |    check results                      |
|----------------|------------|---------------------------------------|
| ENSG00000139304| A0A087WZU1 | protein-tyrosine-phosphatase |
| ENSG00000161133| Q3LFD5     | ubiquitin specific peptidase 41       |
| ENSG00000175164| A0A087X009  | predicted function |
| ENSG00000181222| A0A6Q8PGB0  | DNA-dependent RNA polymerase  |
| ENSG00000249948| Q9H227     | beta-glucosidase, with both normal and pseudogene isoforms |

**Comment by haowang-bioinfo** [comment]
fixed in #537
