### ISSUE TITLE
Error using FBA with models created from ftINIT

### ISSUE THREAD

**Issue by ShwetaNagre** [SysBioChalmers/Human-GEM#514]
Hello,
I have created GEM models using both ftINIT and tINIT algorithms. I am trying to perform FBA for these GEMs using 'ATP_hydrolysis' as an objective function. I've added this reaction to the model with the required bounds. The program runs and brings the optimal solution, but the objective function's flux value shows to be 0 (zero). Ideally, it should be 1000. This happens when used for the models created from the ftINIT algorithm.

Below is the code used.

```
%Loading the model

load("model1.mat")

%Adding the reaction

     model1 = addReaction(model1, 'ATP_Hydrolysis', 'reactionFormula', 'ATP[c] + H2O[c] => ADP[c] + H+[c] + Pi[c]', 'reversible', false, 'subSystem', 'Transport reactions', 'checkDuplicate', true, 'lowerBound',0, 'upperBound',1000)

%Setting the reaction as objective    

    model1 = setParam(model1, 'obj', 'ATP_Hydrolysis', 1);
 
% Perform FBA
    solution = solveLP(model1);

% Display the flux distribution
    disp(solution.x)
```

Any help is appreciated.
Thank you.

**Comment by haowang-bioinfo** [comment]
@johan-gson can you please take a look this

**Comment by johan-gson** [comment]
Hi and thanks for using our methods! I see a problem with your code above, but I'm not sure if that is the real problem. But at least that needs to be fixed. So, a first step is to change the line
modelP1 = setParam(modelP1, 'obj', 'ATP_Hydrolysis', 1);
to 
modelP1 = setParam(model1, 'obj', 'ATP_Hydrolysis', 1);

You are using model1 in the first half of the code and modelP1 in the other half

Could you start by checking that?

**Comment by ShwetaNagre** [comment]
I am really sorry @johan-gson .
It was a typing error from my side while pasting here. I've corrected the code in the previous comment. Please check. The error remains the same.
I don't understand after running why the flux for the objective shows to be 0.

![image](https://user-images.githubusercontent.com/110716128/227780985-5b7477d3-e555-45d2-bc09-7ebe9800a06a.png)


Thank you for helping.

**Comment by johan-gson** [comment]
Could you post the ftINIT model here by any chance? I could have a quick look.

**Comment by ShwetaNagre** [comment]
These are the fields for the single model created using ftINIT.
id: here is the sample name.

```

 struct with fields:

                     id: 'CA002YF'
            description: 'Generic genome-scale metabolic model of Homo sapiens'
                   rxns: {8495×1 cell}
                   mets: {5631×1 cell}
                      S: [5631×8495 double]
                     lb: [8495×1 double]
                     ub: [8495×1 double]
                    rev: [8495×1 double]
                      c: [8495×1 double]
                      b: [5631×1 double]
                  comps: {9×1 cell}
              compNames: {9×1 cell}
               rxnNames: {8495×1 cell}
                grRules: {8495×1 cell}
             rxnGeneMat: [8495×2495 double]
             subSystems: {8495×1 cell}
                eccodes: {8495×1 cell}
               rxnNotes: {8495×1 cell}
                  genes: {2495×1 cell}
               metNames: {5631×1 cell}
               metComps: [5631×1 double]
                 inchis: {5631×1 cell}
            metFormulas: {5631×1 cell}
          rxnReferences: {8495×1 cell}
                rxnFrom: {8495×1 cell}
                metFrom: {5631×1 cell}
    rxnConfidenceScores: [8495×1 double]
             metCharges: [5631×1 int64]
                version: '1.13.0'
             annotation: [1×1 struct]

```

For FBA I've been using the COBRAtoolbox and gurobi solver.

Thank you.

**Comment by johan-gson** [comment]
Could you post a .mat file with the model?


Den sön 26 mars 2023 17:17ShwetaNagre ***@***.***> skrev:

**Comment by ShwetaNagre** [comment]
Sorry the .mat file is not supported here.

Please check the drive link for the file.
https://drive.google.com/file/d/1LpHaimYNwyGGh4qUs-MXq_KhriIb8nJK/view?usp=share_link

**Comment by ShwetaNagre** [comment]
Hi, @johan-gson @haowang-bioinfo 

Please have a look at this code I am using for FBA according to the Human-GEM Guide.
This code works completely fine with the tINIT model while these errors and FBA issue is seen with the ftINIT model only.

```

load("model1.mat")

%Adding a reaction to the model
    model1 = addReaction(model1, 'ATP_Hydrolysis','reactionFormula', 'ATP[c] + H2O[c] => ADP[c] + H+[c] + Pi[c]','reversible',false,'subSystem','Transport reactions','checkDuplicate',true,'lowerBound',0,'upperBound',1000)


    constructEquations(model1, 'ATP_Hydrolysis')

%Change the objective to maximize flux through the ATP hydrolysis reaction:

    model1 = setParam(model1, 'obj', 'ATP_Hydrolysis', 1);


% Perform FBA
    solution = solveLP(model1);


% Display the flux distribution
    disp(solution.x)

```

So, the ``` addReaction ``` command (The parameters are given according to the Matlab documentation) works perfect and add a reaction to the model in model1.rxns field.

![image](https://user-images.githubusercontent.com/110716128/228161709-e07ae4cf-86b8-45bd-b3a9-efee19fc9e86.png)


The problem occurs for the ``` constructEquations  ``` which throws an error even though the reaction is been added.

ERROR:

```

>>     constructEquations(model1, 'ATP_Hydrolysis')
Array indices must be positive integers or logical values.

Error in constructEquations (line 88)
        comps = model.comps(model.metComps(Mindexes));

```

Later, I just tried setting the parameter to change the objective to maximize flux through the added ATP hydrolysis reaction. And performing the FBA.
The FBA showed the results as an Optimal solution obtained but the flux through the Objective function is 0(zero).

![image](https://user-images.githubusercontent.com/110716128/228162384-237a012b-4bc3-4164-ab76-c522adf7eab1.png)


The  ``` addReaction ``` command seems to be perfect but I've no idea why the ``` constructEquations  ```  is throwing an error.

This code works completely fine with the tINIT model while these errors and FBA issue is seen with the ftINIT model only.
The model is the same as I have shared before.

Please have a look.
Any help you can give would be greatly appreciated.

Thank You.

**Comment by anoop1988** [comment]
Hi,
Could you please check the issue @johan-gson @haowang-bioinfo . We have used both tINIT and ftINIT on the same data.
tINIT -> addReaction() -> FBA (solveLP) : Works perfectly fine [constructEquations() correctly printing the added reaction]
**ftINIT -> addReaction() -> FBA (solveLP): Not working.** Here addReaction() not throwing any error. But the added reaction is not getting printed using constructEquations(). Rather is throwing error. And FBA is showing 0 fluxes when running solveLP() with the added reaction as objective function. 

It will be highly appreciated if you can look into this issue as early as possible,
Thanks a million.

**Comment by haowang-bioinfo** [comment]
how was model1 generated? using what dataset?

**Comment by ShwetaNagre** [comment]
Hi,
The model1 was the contextualized model for our transcriptomic data. We used TPM normalized read counts and human generic model version 1.13.0 (downloaded from the github repo). 

The code is the following:

```

addpath(genpath('/path/Human-GEM/'))
addpath(genpath('/path/RAVEN-2.7.11'))
load('Human-GEM.mat');

prepDataHumanGEM = prepHumanModelForftINIT(ihuman, false, 'metabolicTasks_Essential.txt', 'reactions.tsv')
save('prepDataHumanGEM.mat', 'prepDataHumanGEM')

TPM_data = readtable('TPM.txt');
[~, n] = size(TPM_data);
numSamp = n-1;

data_struct.genes = TPM_data{:, 1};
data_struct.tissues = TPM_data.Properties.VariableNames(2:n);
data_struct.levels = TPM_data{:, 2:n};
data_struct.threshold = 1;

load('prepDataHumanGEM.mat');
All_GEM_Models = cell(numSamp, 1);
for i = 1:numSamp
    disp(['Model: ' num2str(i) ' of ' num2str(2)])
    All_GEM_Models{i} = ftINIT(prepDataHumanGEM, data_struct.tissues{i}, [], [], data_struct, {}, getHumanGEMINITSteps('1+0'), false, true);
    Name=data_struct.tissues{i};
    All_GEM_Models{i}.id = Name;
end
save('All_Gem_Models.mat', 'All_GEM_Models', '-v7.3')

```

Model1 is one of the models from All_Gem_Models.mat.

**Comment by JonathanRob** [comment]
@haowang-bioinfo the first task in the essential metabolic task list is to rephosphorylation of ADP to ATP, and the biomass task requires ATP production, so the model should definitely be able to hydrolyze ATP.

That being said, I still haven't identified an obvious cause of this issue, so I'm continuing to look into it.

**Comment by ShwetaNagre** [comment]
> so the model should definitely be able to hydrolyze ATP.
Exactly.

> so I'm continuing to look into it.
Yes, please. Looking forward to your response regarding this.
Thank you. @JonathanRob 


> There is an existing reaction [MAR00080](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00080) in HumanGEM, anyway this additional "ATP_Hydrolysis" is not needed. If set MAR00080 as object equation of model1, you should be able to get solutions.

@haowang-bioinfo Thank you. I will explore more into this and whether can it be used for our purpose.

**Comment by johan-gson** [comment]
@JonathanRob and others, I looked into this. The problem is that you are using AddReaction from COBRA, for some reason the metcomps becomes zero for the new metabolites. If you replace those lines with 

rxnsToAdd.rxns = {'ATP_Hydrolysis'};
rxnsToAdd.equations = {'ATP[c] + H2O[c] => ADP[c] + H+[c] + Pi[c]'};
model1=addRxns(model1,rxnsToAdd,3)

it works, and the result is a flux of 1000.

I'm not sure if it should work with the AddReaction in COBRA, I've never used it. I hope this solves your problems, @ShwetaNagre and @anoop1988

**Comment by ShwetaNagre** [comment]
Thank you @johan-gson. Now, it is working when we add the 'ATP_Hydrolysis' reaction. Also the ```constructEquations``` give the equation as result. And the flux for the objective function is also 1000 in .x field.

The issue is, the ```solution``` shows me .f field representing the flux for my obj function as -1000, even though it is correctly showing 1000 when I check .x field.

![image](https://user-images.githubusercontent.com/110716128/228264769-a1c65453-3527-469a-b145-24268a2f6e5f.png)

![image](https://user-images.githubusercontent.com/110716128/228264940-2bb0ed05-5ee5-47af-a663-1e3cc35e6cdd.png)


I am using RAVEN toolbox of SysBioChalmers/RAVEN: v2.8.0.

I can see that in the older version SysBioChalmers/RAVEN: v2.7.12 your team has fixed the bug for "solveLP report the correct sign of the objective function. .f with objective value was previously inverted (maximization gives negative value)."  https://zenodo.org/record/7653560#.ZCLyjdJBzlg

So, why is it still showing the -1000 as flux in .f field?

**Comment by mihai-sysbio** [comment]
@ShwetaNagre could you please report this issue directly on [RAVEN](https://github.com/SysBioChalmers/RAVEN)?

**Comment by ShwetaNagre** [comment]
> I'm not sure about why this is, could someone else perhaps help with this? it has always been negative as far as I can remember. I could imagine that the problem is converted to a minimization problem where the sign is flipped, but I don't really know.


Okay. No problem. Thank you for the help. @johan-gson 



> @ShwetaNagre could you please report this issue directly on [RAVEN](https://github.com/SysBioChalmers/RAVEN)?

Yes sure. I'll do that.

**Comment by johan-gson** [comment]
No problem, good that we could sort this out. Good luck with your project!

**Comment by johan-gson** [comment]
I think this can be closed now
