### ISSUE TITLE
refine GPR for lactate dehydrogenase

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#516]
### Description of the issue:
|Enzyme|localization|
|-----------------|------------------------------------------------------------------------------------------|
|[ENSG00000134333](https://www.uniprot.org/uniprotkb/P00338/entry#subcellular_location)|cytosol|
|[ENSG00000166800](https://www.uniprot.org/uniprotkb/Q6ZMR3/entry#subcellular_location)|cytosol|
|[ENSG00000111716](https://www.uniprot.org/uniprotkb/P07195/entry#subcellular_location)|cytosol,mitochondria|
|[ENSG00000171989](https://www.uniprot.org/uniprotkb/Q9BYZ2/entry#subcellular_location)|cytosol,mitochondira,nucleus|
|[ENSG00000166796](https://www.uniprot.org/uniprotkb/P07864/entry#subcellular_location)|cytosol|
|[ENSG00000151116](https://www.uniprot.org/uniprotkb/Q8IX04/entry#subcellular_location)|extracellular|

We may need to modify the GPR for rxn:

remove [ENSG00000134333](https://www.uniprot.org/uniprotkb/P00338/entry#subcellular_location) from Peroxisome [MAR04281](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04281) and mitochondria [MAR04280](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04280)
remove [ENSG00000166800](https://www.uniprot.org/uniprotkb/Q6ZMR3/entry#subcellular_location) from Peroxisome [MAR04281](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04281) and mitochondria [MAR04280](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04280)
remove [ENSG00000111716](https://www.uniprot.org/uniprotkb/P07195/entry#subcellular_location) from  Peroxisome [MAR04281](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04281)
remove [ENSG00000166796](https://www.uniprot.org/uniprotkb/P07864/entry#subcellular_location) from Peroxisome [MAR04281](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04281) and mitochondria [MAR04280](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04280)
~~remove [ENSG00000151116](https://www.uniprot.org/uniprotkb/Q8IX04/entry#subcellular_location) from  Peroxisome [MAR04281](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04281) and mitochondria [MAR04280](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04280)~~
After removal, the rxn MAR04281 contain no gene association, not sure which gene to keep.

**Comment by haowang-bioinfo** [comment]
> After removal, the rxn MAR04281 contain no gene association, not sure which gene to keep.

what do you think about MAR04281, delete it or keep with blank GPR?

**Comment by feiranl** [comment]
The ENSG00000151116 are  responsible for the cytosol reaction, so we don't have to delete it from the model. Now as for the MAR04281, [ENSG00000171989](https://www.uniprot.org/uniprotkb/Q9BYZ2/entry#subcellular_location) was kept, since it is the most versatile one.

**Comment by haowang-bioinfo** [comment]
> for the MAR04281, [ENSG00000171989](https://www.uniprot.org/uniprotkb/Q9BYZ2/entry#subcellular_location) was kept, since it is the most versatile one.

okay

> The ENSG00000151116 are responsible for the cytosol reaction

Despite of annotated with lactate/malate dehyrogenase domain, the function of [ENSG00000151116](https://www.uniprot.org/uniprotkb/Q8IX04/entry#subcellular_location) vaguely determined.

**Comment by haowang-bioinfo** [comment]
> Oh, do you think we should delete it?

good question, basically I think every change should be made based on some evidence, such as literature, experimental results, and manual reasoning.
