### ISSUE TITLE
Duplicate IDs for same mets

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#519]
### Description of the issue:

|mets|metsNoComp|metBiGGID|metKEGGID|metHMDBID|metChEBIID|metPubChemID|metHepatoNET1ID|metRecon3DID|metMetaNetXID|metHMR2ID|metRetired|
|-----------------|-----------------------------------------|------------------------------|-------------------------------|-------------|-----------------|-----------------------------------------|------------------------------|-------------------------------|-------------|-----------------|-----------------------------------------|
|MAM00270c|MAM00270|wharachd|C14748|empty|CHEBI:34306|5283157|empty|wharachd|MNXM22451|m00270c|m00270c|
|MAM00270r|MAM00270|wharachd|C14748|empty|CHEBI:34306|5283157|empty|wharachd|MNXM22451|m00270r|m00270r|
|MAM00591c|MAM00591|empty|C14748|empty|CHEBI:34306|empty|HC02179|empty|MNXM6760|m00591c|m00591c|
|MAM00591e|MAM00591|empty|C14748|empty|CHEBI:34306|empty|HC02179|empty|MNXM6760|m00591s|m00591s|
|MAM00270e|MAM00270|wharachd|C14748|empty|CHEBI:34306|5283157|empty|wharachd|MNXM22451|empty|m00270s|

**Comment by haowang-bioinfo** [comment]
this shows there are two sets ids CHEBI:34306 (KEGG:C14748) in [c] and [e], which set should be removed?

**Comment by feiranl** [comment]
We will keep the metabolite [MAM00270](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00270e) , since it is related to 12 rxns (7 related to [MAM00591](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00591c))
Duplicate rxns caused by this merge will also be removed(the right column).


|rxn with MAM00270|rxn with MAM00591|
|-----------------|-----------------------------------------|
|[MAR00934](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00934)|[MAR00941](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00941)|
|[MAR02396](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02396)|[MAR06142](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06142)|
|[MAR02398](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02398)|[MAR06143](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06143)|
|[MAR02402](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02402)|[MAR06220](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06220)|
|[MAR02404](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02404)|[MAR06252](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06252)|
|[MAR02400](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02400)|[MAR06144](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06144)|
|[MAR10348](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10348)|[MAR10025](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10025)|

**Comment by haowang-bioinfo** [comment]
> Duplicate rxns caused by this merge will also be removed(the right column).

then how to deal with the GPRs after removal?

**Comment by feiranl** [comment]
These two metabolites are mapped to the same metabolite according to the [MetaNetX](https://www.metanetx.org/chem_info/MNXM3342)

|mets|metsNoComp|metBiGGID|metKEGGID|metHMDBID|metChEBIID|metPubChemID|metLipidMapsID|metEHMNID|metHepatoNET1ID|metRecon3DID|metMetaNetXID|metHMR2ID|metRetired|
|-----------------|-----------------------------------------|------------------------------|-------------------------------|-------------|-----------------|-----------------------------------------|------------------------------|-------------------------------|-------------|-----------------|-----------------------------------------|-----------------|-----------------------------------------|
|MAM00077x|MAM00077|CE2416||||||CE2416|||MNXM165274|m00077p|m00077p|
|MAM02766x|MAM02766|prist||HMDB0000795|CHEBI:51340|123929|LMPR0104010022|CE0932||prist|MNXM3342;MNXM7698|m02766p|m02766p|

I think we should remove the metabolite [MAM00077x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00077x), as it only relate to 2 rxns, while the other one is associated with 13 rxns from all compartments.

****Associated rxns for MAM00077x
[MAR03488](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03488)
Action: remove, for the wrong annotation of EC number with this rxn. [EC1.14.11.18](https://metabolicatlas.org/search?term=1.14.11.18) should be related to `AKG`, while this rxn is more like [1.2.1.3](https://metabolicatlas.org/search?term=1.2.1.3). 

[MAR03489](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03489) is a duplicate of [MAR03387](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03387) with the duplicate met `MAM02766x` , so it is okay to remove.

**Comment by feiranl** [comment]
> > Duplicate rxns caused by this merge will also be removed(the right column).
> 
> then how to deal with the GPRs after removal?

I am not sure about this. Do you have any suggestions?

**Comment by haowang-bioinfo** [comment]
> Do you have any suggestions?

According to the update table above, all GPRs for the left column can be retained except [MAR00934](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00934), whose new GPR might be changed with merging GPR of [MAR00941](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00941)? So that there will be no information loss.

**Comment by haowang-bioinfo** [comment]
> I think we should remove the metabolite [MAM00077x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00077x), as it only relate to 2 rxns, while the other one is associated with 13 rxns from all compartments.

agree

> [MAR03489](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03489) is a duplicate of [MAR03387](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03387) with the duplicate met MAM02766x. CAUTION! GPR conflict.

a tentative solution is merging genes from both if no more evidence, e.g. use the version from [MAR03489](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03489) whose GPR includes all genes from GPR of MAR03387

**Comment by haowang-bioinfo** [comment]
fixed in #534
