### ISSUE TITLE
Parallel/Redundant Versions Of Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#524]
There are a number of cases where the "same" overall reaction is represented at multiple different levels of resolution in different reactions/series of reactions:

- [x] The aconitase reaction (citrate <-> isocitrate) can be carried out in
  - one step:MAR04456
  - two steps: MAR04458 (citrate <-> cis-aconitate + H<sub>2</sub>O) and MAR04589 (cis-aconitate + H<sub>2</sub>O <-> isocitrate)
- [x] The cytosolic isocitrate dehydrogenase (IDH) reaction (isocitrate + NADP<sup>+</sup> -> AKG + CO<sub>2</sub> + NADPH) can be carried out in
  - one step: MAR00710
  - two steps: MAR04585 (isocitrate + NADP<sup>+</sup> <-> oxalosuccinate + NADPH) and MAR04111 (oxalosuccinate -> AKG + CO<sub>2</sub>)
- [x] The peroxisomal IDH reaction can be carried out in
  - one step: MAR00712
  - two steps: MAR04587 (isocitrate + NADP<sup>+</sup> <-> oxalosuccinate + NADPH) and MAR04113 (oxalosuccinate -> AKG + CO<sub>2</sub>)
- [x] The NADP(H)-dependent mitochondrial IDH reaction can be carried out in
  - one step: MAR03958
  - two steps: MAR04586 (isocitrate + NADP<sup>+</sup> <-> oxalosuccinate + NADPH) and MAR04112 (oxalosuccinate -> AKG + CO<sub>2</sub>)
- [x] The pyruvate dehydrogenase (PDH) reaction (pyruvate + NAD<sup>+</sup> -> acetyl-CoA + CO<sub>2</sub> + NADH) can be carried out in
  - one step: MAR04137
  - three steps: MAR06410 (pyruvate + lipoamide + H<sup>+</sup> -> S-acetyldihydrolipoamide + CO<sub>2</sub>), MAR06412 (S-acetyldihydrolipoamide + CoA -> acetyl-CoA + dihydrolipoamide), and MAR06409 (lipoamide + NADH + H<sup>+</sup> <-> dihydrolipoamide + NAD<sup>+</sup>)
- [x] The 2-oxoglutarate dehydrogenase (OGDH) reaction (AKG + CoA + NAD<sup>+</sup> -> succinyl-CoA + CO<sub>2</sub> + NADH) can be carried out in
  - one step: MAR05297
  - three steps: MAR06411 (AKG + lipoamide + H<sup>+</sup> -> S-succinyldihydrolipoamide + CO<sub>2</sub>), MAR06414 (S-succinyldihydrolipoamide + CoA -> succinyl-CoA + dihydrolipoamide) and MAR06409 (lipoamide + NADH + H<sup>+</sup> <-> dihydrolipoamide + NAD<sup>+</sup>)
  - four steps: MAR04209 (AKG + thiamin-PP + H<sup>+</sup> -> 3-carboxy-1-hydroxypropyl-ThPP + CO<sub>2</sub>), MAR06413 (3-carboxy-1-hydroxypropyl-ThPP + lipoamide -> S-succinyldihydrolipoamide + thiamin-PP), MAR06414 (S-succinyldihydrolipoamide + CoA -> succinyl-CoA + dihydrolipoamide) and MAR06409 (lipoamide + NADH + H<sup>+</sup> <-> dihydrolipoamide + NAD<sup>+</sup>)
- [x] The glycine cleavage system (GCS) reaction (glycine + THF + NAD<sup>+</sup> -> 5,10-methylene-THF + CO<sub>2</sub> + NH<sub>3</sub> + NADH + H<sup>+</sup>) can be carried out in
  - one step: MAR03923
  - three steps: MAR08433 (glycine + lipoamide + H<sup>+</sup> -> S-aminomethyldihydrolipoamide + CO<sub>2</sub>), MAR08434 (S-aminomethyldihydrolipoamide + THF -> 5,10-methylene-THF + NH<sub>3</sub> + dihydrolipoamide + H<sup>+</sup>), and MAR06409 (lipoamide + NADH + H<sup>+</sup> <-> dihydrolipoamide + NAD<sup>+</sup>)
  - three steps: MAR08435 (glycine + lipoylprotein + H<sup>+</sup> -> S-aminomethyldihydrolipoylprotein + CO<sub>2</sub>), MAR08436 (S-aminomethyldihydrolipoylprotein + THF -> 5,10-methylene-THF + NH<sub>3</sub> + dihydrolipoylprotein + H<sup>+</sup>), and MAR08437 (lipoylprotein + NADH + H<sup>+</sup> <-> dihydrolipoylprotein + NAD<sup>+</sup>)

The existence of these parallel/duplicate/redundant representations of the "same" overall reaction often causes problems for me (I'm working on a new method for incorporating expression data into a generic GEM to create context-specific GEMs), so I usually block or remove the "lower-resolution" versions of these reactions. I don't know enough about the rationale/criteria/thought process behind the curation of Human1 to know if the "lower resolution" reactions

>MAR04456, MAR00710, MAR00712, MAR03958, MAR04137, MAR05297, MAR06411, MAR06414, MAR03923

 should be removed, if the "higher resolution" reactions
> MAR04458, MAR04459, MAR04585, MAR04111, MAR04587, MAR04113, MAR04586, MAR04112, MAR06410, MAR06412, MAR06409, MAR06411, MAR06414, MAR04209, MAR06413, MAR08433, MAR08434, MAR08435, MAR08436, MAR08437

 should be removed, or if it's fine to keep all of them.

- [x] However, I will say that it seems like MAR08435, MAR08436, and MAR08437 should be removed, because:
    - The only difference between (MAR08433, MAR08434, MAR06409) and (MAR08435, MAR08436, MAR08437) is that the first series uses lipoamide (MAM02393m) and dihydrolipoamide (MAM02393m) while the second uses lipoylprotein (MAM02400m) and dihydrolipoylprotein (MAM01703m)
    - MAR08435 and MAR08437 are the only two reactions that the "lipoylprotein" and "dihydrolipoylprotein" metabolites appear in
    - The "high resolution" versions of other comparable dehydrogenase reactions (e.g. MAR06410 and MAR06412 for PDH; MAR04209, MAR06413, and MAR06414 for OGDH) use (dihydro)lipoamide and not (dihydro)lipoylprotein

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer thanks for reporting this, we will investigate this and reach you back later

**Comment by haowang-bioinfo** [comment]
reformatted cases of reaction sets with different resolution as check box for downstream processing

**Comment by haowang-bioinfo** [comment]
thank you very much @Devlin-Moyer! You are absolutely correct about the co-existence of low and high resolution reactions for pyruvate dehydrogenase, 2-oxoglutarate dehydrogenase, as well as glycine cleavage system. And this should be fixed.

**Comment by haowang-bioinfo** [comment]
If keeping the high resolution reactions for these complexes, i.e. splitting one to several sub-reactions, maybe their GPRs should also be reduced to specific component. @Devlin-Moyer what do you think?

**Comment by Devlin-Moyer** [comment]
yea I think that would make sense, but I don't already know exactly which genes should catalyze each step. Also I'm not sure where we'd put structural components, like PDHX (ENSG00000110435; also known as "E3 binding protein"), which doesn't directly participate in catalysis of the PDH reaction, but still plays an important role in enabling high fluxes by keeping DLD near PDHB (ENSG00000168291). Ofc this would probably be pretty easy for the glycine cleavage system, since we know those genes are all enzymes that directly catalyze a specific step of the process and none are structural because they're all free-floating

**Comment by haowang-bioinfo** [comment]
> The 2-oxoglutarate dehydrogenase (OGDH) reaction (AKG + CoA + NAD+ -> succinyl-CoA + CO2 + NADH) can be carried out in
one step: MAR05297
three steps: MAR06411 (AKG + lipoamide + H+ -> S-succinyldihydrolipoamide + CO2), MAR06414 (S-succinyldihydrolipoamide + CoA -> succinyl-CoA + dihydrolipoamide) and MAR06409 (lipoamide + NADH + H+ <-> dihydrolipoamide + NAD+)
four steps: MAR04209 (AKG + thiamin-PP + H+ -> 3-carboxy-1-hydroxypropyl-ThPP + CO2), MAR06413 (3-carboxy-1-hydroxypropyl-ThPP + lipoamide -> S-succinyldihydrolipoamide + thiamin-PP), MAR06414 (S-succinyldihydrolipoamide + CoA -> succinyl-CoA + dihydrolipoamide) and MAR06409 (lipoamide + NADH + H+ <-> dihydrolipoamide + NAD+)

Regarding the two versions of high resolution reaction-sets for 2-oxoglutarate dehydrogenase complex: (MAR06411 + MAR06414 + MAR06409) and (MAR04209 + MAR06413 + MAR06414 + MAR06409). The only difference is that MAR06411 from the former is splitted into MAR04209 and MAR06413 from the latter, by introducing two metabolites: 3-carboxy-1-hydroxypropyl-ThPP and thiamin-PP. While 3-carboxy-1-hydroxypropyl-ThPP only occurs between these two reactions, thiamin-PP actually functions as cofactor in this step, according to [this paper](https://portlandpress.com/biochemj/article/459/2/369/46695/Studies-on-the-regulation-of-the-human-E1-subunit).

**Comment by haowang-bioinfo** [comment]
Likewise the case of MAR06409 (#529), some other sub-reactions should be modified/shrinked to more specific component in GPRs:
MAR06412: DLAT (ENSG00000150768)
MAR08433: GLDC (ENSG00000178445)
MAR08434: AMT (ENSG00000145020)

**Comment by Devlin-Moyer** [comment]
This might just be an annoying semantic point, but it feels relevant to point out that lipoamide is also a cofactor here; they're both bound to a subunit of the enzyme complex and aren't produced or consumed in the overall reaction. Is the point you're making that thiamin-PP goes in as thiamin-PP and comes out as thiamin-PP (i.e. exactly the same metabolite), while lipoamide goes in as lipoamide and then comes out as dihydrolipoamide, which needs DLD to turn it back into lipoamide while also reducing NAD<sup>+</sup>?

While normal FBA would just have the thiamin-PP cycle between MAR04209 and MAR06413 without any meaningful impact on the rest of the network, I happened to come across [this paper](https://doi.org/10.1371/journal.pcbi.1003126) earlier this week, which introduces limed-FBA, in which case the thiamin-PP would actually do something. The idea with limed-FBA is to stop cycles from happening where no metabolites come in or out, and they accomplish this by adding a "dilution" reaction for each metabolite whose flux is constrained to be a small fraction of the sum of the absolute values of all the other fluxes involving that metabolite. So the argument for keeping MAR04209 and MAR06413 is that someone might want to use Human1 with something like limed-FBA to account for the fact that real cells cannot perfectly recycle their thiamin-PP indefinitely and occasionally need to replace it with new thiamine.

Also, now feels like a good time to mention MAR08746: pyruvate[c] + thiamin-PP[c] + H<sup>+</sup>[c] -> 2-(alpha-hydroxyethyl)thiamine-diphosphate[c], with a GPR of (PDHA1 and PDHB) or (PDHA2 and PDHB). It was probably supposed to be a "higher resolution" version of the PDH reaction, like MAR04209 is for OGDH, but no other reactions involve 2-(alpha-hydroxyethyl)thiamine-diphosphate (MAM00561c), and it's in the wrong compartment (cytosol not mitochondria). Note how the top left of figure 1 from [this paper](https://doi.org/10.1074/jbc.R114.563148) and figure 2 from [this paper](https://doi.org/10.1016/B978-008045382-8.00137-4) show exactly the same structure as [the page for MAM00561c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00561c). So anyway if you remove MAR04209 because of the way it involves thiamine, you should probably also remove MAR08746 and MAM00561c, and if you keep MAR04209, you might also want to fix MAR08746 by moving it to the mitochondrial compartment (which would also involve changing MAM00561c into MAM00561m) and adding another reaction to convert _mitochondrial_ 2-(alpha-hydroxyethyl)thiamine-diphosphate and lipoamide into S-acetyldihydrolipoamide and thiamin-PP, i.e. MAM00561m + MAM02393m -> MAM02869m + MAM02984m

**Comment by Devlin-Moyer** [comment]
> MAR06412: DLAT (ENSG00000150768)
> MAR08433: GLDC (ENSG00000178445) and GCSH (ENSG00000140905)
> MAR08434: AMT (ENSG00000145020)

The suggested GPRs for MAR06412 and MAR08433 look fine to me, but I would also add GCSH (ENSG00000140905) to the GPR of MAR08434, because diagrams of the GCS (e.g. figure 1 of [this paper](https://www.jstage.jst.go.jp/article/pjab/84/7/84_7_246/_pdf/-char/ja)) always show the lipoamide bound to GCSH in every step

**Comment by haowang-bioinfo** [comment]
> I would also add GCSH (ENSG00000140905) to the GPR of MAR08434, because diagrams of the GCS (e.g. figure 1 of [this paper](https://www.jstage.jst.go.jp/article/pjab/84/7/84_7_246/_pdf/-char/ja)) always show the lipoamide bound to GCSH in every step

nice citation - GPRs updated in 20961d5742109dace2d0a489e2801984e040bec5, please re-review #538

**Comment by haowang-bioinfo** [comment]
>  if you remove MAR04209 because of the way it involves thiamine, you should probably also remove MAR08746 and MAM00561c, and if you keep MAR04209, you might also want to fix MAR08746 by moving it to the mitochondrial compartment (which would also involve changing MAM00561c into MAM00561m) and adding another reaction to convert mitochondrial 2-(alpha-hydroxyethyl)thiamine-diphosphate and lipoamide into S-acetyldihydrolipoamide and thiamin-PP, i.e. MAM00561m + MAM02393m -> MAM02869m + MAM02984m

Again, any modification to HumanGEM should be evidence-based. To keep the super high resolution version by involving thiamine-PP to krebs cycle reactions, can you please provide more references that supporting this claim.

**Comment by Devlin-Moyer** [comment]
[This paper](https://pubs.acs.org/doi/full/10.1021/bi700083z) detected2-hydroxyethyl-ThPP as an intermediate in the human PDH complex (see third paragraph of Results section and figure 1A). As did [this paper](https://pubs.acs.org/doi/full/10.1021/bi061582l); see the second paragraph in the "Kinetic Analysis of the E1 Decarboxylation Reaction under Single-Turnover Conditions by Quench Flow−1H NMR Spectroscopy" subsection.

[This paper](https://www.jbc.org/article/S0021-9258(20)37322-1/fulltext) observed 3-carboxy-1-hydroxypropyl-ThPP as an intermediate in the human OGDH complex; compare the structure in Scheme 1 labeled "C2-(alpha-hydroxy)-gamma-carboxypropylidene-ThPP" to [this](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00765m) structure of 3-carboxy-1-hydroxypropyl-ThPP.

I'm not entirely sure what evidence would support the notion that including these thiamin-PP intermediates is _necessary_; the reason I mentioned [limed-FBA](https://doi.org/10.1371/journal.pcbi.1003126) earlier was to point out that including them could be _useful_, and specifically that removing them could make Human-GEM less useful.

**Comment by haowang-bioinfo** [comment]
Very nice!

> [This paper](https://pubs.acs.org/doi/full/10.1021/bi700083z) detected 2-hydroxyethyl-ThPP as an intermediate in the human PDH complex (see third paragraph of Results section and figure 1A). As did [this paper](https://pubs.acs.org/doi/full/10.1021/bi061582l); see the second paragraph in the "Kinetic Analysis of the E1 Decarboxylation Reaction under Single-Turnover Conditions by Quench Flow−1H NMR Spectroscopy" subsection.

these studies explicitly demonstrate that the pyruvate decarboxylation process catalyzed by PDH E1 component is thiamin-dependent.
![images_medium_bi700083zn00001](https://user-images.githubusercontent.com/21077367/233774024-62c3b23e-58e0-4886-8cfd-1d3807bed610.gif)

> [This paper](https://www.jbc.org/article/S0021-9258(20)37322-1/fulltext) observed 3-carboxy-1-hydroxypropyl-ThPP as an intermediate in the human OGDH complex; compare the structure in Scheme 1 labeled "C2-(alpha-hydroxy)-gamma-carboxypropylidene-ThPP" to [this](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00765m) structure of 3-carboxy-1-hydroxypropyl-ThPP.

Overall, it seems the intermediate enamines involved in both PDH and OGDH processes are not structurally finalized, in contrast to 2-hydroxyethyl-ThPP (MAM00561c) and 3-carboxy-1-hydroxypropyl-ThPP (MAM00765m) in HumanGEM.

> I'm not entirely sure what evidence would support the notion that including these thiamin-PP intermediates is necessary; the reason I mentioned [limed-FBA](https://doi.org/10.1371/journal.pcbi.1003126) earlier was to point out that including them could be useful, and specifically that removing them could make Human-GEM less useful.

Based on these studies, inclusion of thiamin-PP intermediates may help in:
1. understanding potential interaction to ROS generation, as reported in this JBC [paper](https://www.jbc.org/article/S0021-9258(20)37322-1/fulltext)
2. more accurate simulation of thiamine metabolism together with this existing [subsystem](https://metabolicatlas.org/explore/Human-GEM/gem-browser/subsystem/thiamine_metabolism)

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer just wonder if you have a chance to look into the situation of isocitrate dehydrogenase (ICDH) reactions, after PDH and OGDH?

**Comment by Devlin-Moyer** [comment]
If you're asking if I think we need to alter the GPRs for any of the IDH reactions to represent which specific subunits catalyze each step, we do not need to make any such changes; IDH1 and IDH2 both function as homodimers that are individually capable of catalyzing both steps in the conversion of citrate to isocitrate or vice versa ([source](https://www.science.org/doi/10.1126/sciadv.aaw4543)), and you need all three subunits of IDH3 to be expressed (IDHA, IDHB, and IDHG) for full enzymatic activity ([source](https://link.springer.com/content/pdf/10.1038/srep41882.pdf)), and the GPRs I proposed in #523 and you implemented in #525 already represent this accurately.

**Comment by haowang-bioinfo** [comment]
fixed in #541
