### ISSUE TITLE
Remove Other Glycine Cleavage System Enzymes From GPR of MAR06409

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#529]
MAR06409 (lipoamide + NADH + H<sup>+</sup> <-> dihydrolipoamide + NAD<sup>+</sup>) should have its GPR changed to just "DLD" (ENSG00000091140)
At the moment, it is "DLD and GCSH and AMT and GLDC", i.e. the other components of the glycine cleavage system (GCS), but DLD also catalyzes exactly the same reaction as a subunit of the pyruvate dehydrogenase (PDH) and 2-oxoglutarate dehydrogenase (OGDH) complexes

See figures 2 and 5 of [this paper](https://doi.org/10.1016/B978-008045382-8.00137-4); I know that paper never specifically states that DLD is a member of both the GCS and the PDH complex, but I think it makes it clear that this is generally true in a variety of organisms across all domains of life -- let me know if you want me to dig up a paper that specifically mentions DLD in humans

**Comment by haowang-bioinfo** [comment]
> let me know if you want me to dig up a paper that specifically mentions DLD in human

yes, maybe dit a little bit up in human-related papers

**Comment by haowang-bioinfo** [comment]
the provided evidence pieces collectively do not appear to confirm that "DLD" should be the only gene catalyse MAR06409.

**Comment by Devlin-Moyer** [comment]
From the first paper's section on GCS: "Unlike the PDC and KDC, the GCS is not a tightly bound multienzyme
complex, but a system of four independent proteins (P, H, T, and L) that loosely associate." and I know that's technically not talking about the human GCS specifically, so also consider "[t]he functions of GLDC, AMT and GCSH are specific to the GCS, whereas DLD encodes a housekeeping enzyme" from [this paper](https://doi.org/10.1093/hmg/ddr585), which is specifically talking about the role of the GCS in human disease.

This is maybe veering into the concerns I raised in #524, but consider the following reactions:

The "low-resolution" version of the GCS reaction:
MAR03923: glycine + THF + NAD<sup>+</sup> -> 5,10-methylene-THF + CO<sub>2</sub> + NH<sub>3</sub> + NADH + H<sup>+</sup> (GPR: DLD and GCSH and AMT and GLDC)

One of the two "high-resolution" versions of the GCS reaction:
MAR08433: glycine + lipoamide + H<sup>+</sup> -> S-aminomethyldihydrolipoamide + CO<sub>2</sub> (GPR: DLD and GCSH and AMT and GLDC)
MAR08434: S-aminomethyldihydrolipoamide + THF -> 5,10-methylene-THF + NH<sub>3</sub> + dihydrolipoamide + H<sup>+</sup> (GPR: DLD and GCSH and AMT and GLDC)

The "low-resolution" version of the PDH reaction:
MAR04137: pyruvate + NAD<sup>+</sup> -> acetyl-CoA + CO<sub>2</sub> + NADH (GPR: DLD and PDHX and (PDHA1 or PDHA2) and DLAT and PDHB)

The "high-resolution" version of the PDH reaction:
MAR06410: pyruvate + lipoamide + H<sup>+</sup> -> S-acetyldihydrolipoamide + CO<sub>2</sub> (GPR: (PDHA1 and PDHB) or (PDHA2 and PDHB))
MAR06412: S-acetyldihydrolipoamide + CoA -> acetyl-CoA + dihydrolipoamide (GPR: (DLD and PDHA1 and DLAT and PDHB) or (DLD and DLAT and PDHA2 and PDHB))

Notice how in both cases, the "high-resolution" reactions produce dihydrolipoamide, which must be oxidized back to lipoamide while reducing NAD<sup>+</sup> to NADH in order for the "high-resolution" series to achieve the same overall reaction as the "low-resolution" reaction, and, as you just said, DLD is the enzyme responsible for this step in both cases. So if Human1 is going to have a separate reaction for the oxidation/reduction of (dihydro)lipoamide by NAD(H), the GPR for that reaction should  only include DLD and not any of the other genes that DLD can complex with while catalyzing this reaction. Alternatively, the GPR should look something like "(DLD and GCSH and AMT and GLDC) or (DLD and DLAT and PDHB) or (genes involved in KGDHc))." Either way, I think that the fact that DLD catalyzes the reaction portrayed in MAR06409 as a member of multiple distinct complexes means that the GPR for that reaction should not "and" DLD together with the other components of only one of those complexes.

**Comment by haowang-bioinfo** [comment]
very good discussion - will sleep on it

**Comment by feiranl** [comment]
So if I understand correctly, you are saying that if Human1 use two continuous reactions to describe the "low resolution" process, we need also separate the GPRs, right? Actually, the "high-resolution" process can be devided into three rxns (two low resolution rxns and the `MAR06409` ) as shown in the multi-step processes in [KEGG](https://www.kegg.jp/entry/R01221+R03425+R04125+R03815). Here, you claim that DLD can perform the function of [MAR06409](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06409). I suppose we need to find some direct evidence to support this: like DLD can function solely without forming any of those complexes, otherwise, I vote for the alternative change to the case "(DLD and GCSH and AMT and GLDC) or (DLD and DLAT and PDHB) or (genes involved in KGDHc))."

**Comment by Devlin-Moyer** [comment]
[this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3641859/) measured catalytically-active DLD in human serum and specifically confirmed that the other members of the enzymes complexes DLD is known to participate in were not there

**Comment by haowang-bioinfo** [comment]
> [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3641859/) measured catalytically-active DLD in human serum and specifically confirmed that the other members of the enzyme complexes DLD is known to participate in were not there

@Devlin-Moyer can you please explain, or speculate, why serum DLD is lack of diaphorase activity, and fail to be recognized by antibodies that recognize mitochondrial DLD?

**Comment by Devlin-Moyer** [comment]
I haven't come across any papers that specifically say this yet, but a possible explanation is that DLD has a slightly different overall shape when free vs in an enzyme complex, and it seems plausible that most mitochondrial DLD is complexed with the other PDH or OGDH complex subunits. Since antibodies generally recognize shapes of things, an antibody that binds to bound-to-a-complex DLD might not bind to free DLD. And similarly, DLD might only have diaphorase activity in the bound-to-other-complex-subunits conformation and not its free-floating conformation

**Comment by haowang-bioinfo** [comment]
[This paper](https://link.springer.com/article/10.1007/s11373-006-9136-0) describes that DLD, as a shared component of pyruvate dehydrogenase, glycine cleavage system, alpha-ketoglutarate dehydrogenase complexes, specifically transfer electrons from dihydrolipoamide to NAD+ in human and other organisms.

**Comment by haowang-bioinfo** [comment]
fixed in #537
