### ISSUE TITLE
Reversibility and GPRs of MAR04567 and MAR04568

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#547]
## Current Situation

Both reactions are reversible:
MAR04567: `sedoheptulose-1,7-bisphosphate + ADP + H<sup>+</sup> <-> sedoheptulose-7-phosphate + ATP`
MAR04568: `sedoheptulose-1,7-bisphosphate + UDP + H<sup>+</sup> <-> sedoheptulose-7-phosphate + UTP`

and both have the same GPR: `ENSG00000067057 or ENSG00000141959 or ENSG00000152556` (three isozymes of phosphofructokinase (PFK))

## Problems With The Current Situation

I find their reversibility suspicious, since that would imply that cells can produce ATP by removing a phosphate from sedoheptulose-1,7-bisphosphate (S17BP), which is not a method of ATP production I've ever heard of in humans. Also, it allows this loop of arbitrarily large fluxes with no inputs or outputs to form with MAR04379, MAR04375, MAR04355, and MAR04565:
![PPP_loop_ids](https://user-images.githubusercontent.com/33460176/235376620-25be039e-9941-4ed5-b219-65bd15a072bd.png)
Same as above but with names instead of IDs:
![PPP_loop_names](https://user-images.githubusercontent.com/33460176/235376624-abcc641c-bb58-485a-a50d-8fd19536f55b.png)

The [only reference associated with MAR04568](https://febs.onlinelibrary.wiley.com/doi/epdf/10.1016/0014-5793%2868%2980041-9) does not mention sedoheptulose-7-phosphate (S7P) at all; it's about how yeast PFK acts on fructose-6-phosphate. [One of the references associated with MAR04567](https://www.sciencedirect.com/science/article/pii/0005274473901046?via%3Dihub) shows that rabbit PFK can phosphorylate S7P to S17BP, but says nothing about the reverse reaction. [The only other reference associated with MAR04567](https://pubmed.ncbi.nlm.nih.gov/4084320/) claims that aldolase and PFK can form S17BP and that fructose-1,6-bisphosphatase (FBPase) can dephosphorylate it to S7P, but it appears to just be the abstract of a paper that is otherwise not available online, so it's not clear if they found that FBPase could form ATP or just cleave the phosphate and release it as a free inorganic phosphate (also it was talking about rats and not humans).

I found [this paper](https://doi.org/10.1007/BF02702726) that found that human F16BPase can _hydrolyze_ S17BP to S7P and generally gives me the impression that they did not also observe ADP or UDP simultaneously being phosphorylated to ATP/UTP. [This paper](https://www.sciencedirect.com/science/article/pii/0020711X80901123) says that PFK catalyzes the S7P -> S17BP reaction and specifically says that F16BPase catalyzes S17BP -> S7P + P<sub>i</sub>, although it's not exactly clear which organism they're talking about (they mention several different mammals throughout the paper).

## Proposed Changes

- [ ] Make MAR04567 and MAR04568 irreversible and switch their reactants and products:
MAR04567: sedoheptulose-7-bisphosphate + ATP -> sedoheptulose-1,7-bisphosphate + ADP + H<sup>+</sup>
MAR04568: sedoheptulose-7-bisphosphate + UTP -> sedoheptulose-1,7-bisphosphate + UDP + H<sup>+</sup>
with IDs instead of names:
MAR04567: `MAM02884c + MAM01371c -> MAM02883c + MAM01285c + MAM02039c`
MAR04568: `MAM02884c + MAM03130c -> MAM02883c + MAM03106c + MAM02039c`
Their GPRs can stay the same, since those genes are all PFK isozymes, which is apparently known to catalyze this reaction in humans, but only in the ATP/UTP-consuming direction ([source](https://doi.org/10.1007/BF02702726), [source](https://www.sciencedirect.com/science/article/pii/0020711X80901123)).

- [ ] Add a new irreversible reaction for the hydrolysis of S17BP into S7P and phosphate catalyzed by the human FBPase isozymes FBP1 and FBP2 (`ENSG00000130957 or ENSG00000165140`, the same GPR as MAR04377): `MAM02883c + MAM02040c -> MAM02884c + MAM02751c`

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer thanks again for the detail investigation and report!

**Comment by Devlin-Moyer** [comment]
Yea after another round of searching, I can't seem to find any papers that actually demonstrated direct conversion of S7P to S17BP in humans; everyone just keeps citing the same two papers that observed it in rabbit and rat liver extracts. Also, as [this review](https://portlandpress.com/biochemsoctrans/article-abstract/41/2/674/66476) points out, those papers were using liver extracts that were _enriched_ in PFK but also had plenty of other enzymes around, and they never specifically determined that PFK was catalyzing the direct phosphorylation of S7P to S17BP.

So maybe the best course of action here is to remove MAR04567 and MAR04568 entirely and replace them with a single reaction that converts S17BP to S7P + P<sub>i</sub> with FBP1 or FBP2, since that actually seems to have been directly observed to happen with human enzymes ([source](https://doi.org/10.1007/BF02702726), [source](https://www.sciencedirect.com/science/article/pii/0020711X80901123))

**Comment by haowang-bioinfo** [comment]
> Yea after another round of searching, I can't seem to find any papers that actually demonstrated direct conversion of S7P to S17BP in humans; everyone just keeps citing the same two papers that observed it in rabbit and rat liver extracts. Also, as [this review](https://portlandpress.com/biochemsoctrans/article-abstract/41/2/674/66476) points out, those papers were using liver extracts that were enriched in PFK but also had plenty of other enzymes around, and they never specifically determined that PFK was catalyzing the direct phosphorylation of S7P to S17BP.

This [study](https://www.hindawi.com/journals/omcl/2019/5913635/) reports elevated S17BP level in human Hep G2 cells as a response to oxidative stress. It also provided alternatives routes of S17BP formation in PPP pathway, including the one from S7P catalyzed by phosphofructokinase but without citation!

> So maybe the best course of action here is to remove MAR04567 and MAR04568 entirely and replace them with a single reaction that converts S17BP to S7P + Pi with FBP1 or FBP2, since that actually seems to have been directly observed to happen with human enzymes ([source](https://doi.org/10.1007/BF02702726), [source](https://www.sciencedirect.com/science/article/pii/0020711X80901123))

Not exactly sure about removing MAR04567 and MAR04568. But it makes sense to have one that converts S17BP to S7P + Pi with GPR of `FBP1 or FBP2`

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer how about this proposal for follow-up implementation:
1. remove MAR04568, because there is no evidence;
2. make MAR04567 irreversible as [RHEA:31444](https://www.rhea-db.org/rhea/31444) that is catalyzed by [PfkA](https://www.uniprot.org/uniprotkb/P0A796/entry) in E. coli - same plan as above; because it shouldn't be reversible;
3. add new reaction: `H2O + S17BP -> S7P + Pi` to cytosol

Only old references can be associated with step 2 (Biochem J. 1974 138:71-6) and 3 (Biochem J. 1978 176:257–282), would be good to find more recent ones.

**Comment by Devlin-Moyer** [comment]
Sounds good to me; I have tried to find more recent references relating to these reactions and failed; all the recent papers that mention this reaction I can find are talking about how human gut microbes use it and now how human cells use it

**Comment by haowang-bioinfo** [comment]
would you like to implement this proposal that you initialized @Devlin-Moyer

**Comment by Devlin-Moyer** [comment]
I could try but I'm not entirely certain that I'd do it right; I don't know a ton about using Git/GitHub and am not confident that I've fully grasped how all the different files here fit together

**Comment by haowang-bioinfo** [comment]
then give a try - just ask if you need help

**Comment by mihai-sysbio** [comment]
> ![PPP_loop_ids](https://user-images.githubusercontent.com/33460176/235376620-25be039e-9941-4ed5-b219-65bd15a072bd.png)

@Devlin-Moyer looking closer at the figure, I'm wondering how you obtained it. It looks Escher-like (curved lines), but also with a layout that is algorithmic-like (aligned nodes). Could you share some details about it?

**Comment by Devlin-Moyer** [comment]
Yep that's just an ordinary Escher map that I spent a potentially unreasonable amount of time fiddling with to try and get everything laid out cleanly; no layout algorithms were involved (I would love it if there were such an automated layout algorithm for making Escher maps, but I've never found one, and I get why; it seems like it'd be quite difficult to create)

**Comment by mihai-sysbio** [comment]
Thanks @Devlin-Moyer for the info. At Metabolic Atlas we have been thinking of the best of doing this for some time, and have started some tiny steps in this direction but there is a long way to go.

**Comment by haowang-bioinfo** [comment]
feel free to reopen
