### ISSUE TITLE
Refine GPRs for Alanine, Aspartate and Glutamate subsystem

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#548]
### Description of the issue:
|Enzyme|rxn|grRules|GPT result|GPT reason|Action|
|-----------------|------------------------|------------------------------------------------------------------|---------------------------------------------------------------------|-------------------------------|-------------------------------------|
[ENSG00000134864](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000134864) | MAR06972: 5-oxoproline[c] + GSH[c] <=> gamma-glutamylglutathione[c] | ENSG00000006625 or ENSG00000134864 | No | the substrates and products of this enzyme do not cover 5-oxoproline | [remove the gene](https://www.uniprot.org/uniprotkb/Q9BVM4/entry), add new rxn [Rhea:16961](https://www.uniprot.org/uniprotkb/Q9BVM4/entry)
[ENSG00000134864](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000134864) | MAR06971: (S)-2-aminobutanoate[c] + 5-oxoproline[c] <=> gamma-L-glutamyl-L-alpha-aminobutyrate[c] | ENSG00000006625 or ENSG00000134864 | No | the substrates and products of this enzyme do not cover (S)-2-aminobutanoate | [remove the gene](https://www.uniprot.org/uniprotkb/Q9BVM4/entry), add new rxn [Rhea:16961](https://www.uniprot.org/uniprotkb/Q9BVM4/entry)
[ENSG00000147471](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000147471) | MAR07642: D-alanine[c] <=> alanine[c] | ENSG00000147471 | No | the substrates and products of this enzyme do not cover alanine and D-alanine. This enzyme is only responsible for binding Pyridoxal 5'-phosphate (PLP) and is not involved in any metabolic pathways associated with alanine and D-alanine. | [remove the gene](https://www.uniprot.org/uniprotkb/O94903/entry)
[ENSG00000091483](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000091483) | MAR03831: aspartate[c] => fumarate[c] + H+[c] + NH3[c] | ENSG00000091483 | No | the substrates and products of this enzyme do not cover metabolites given: aspartate | [remove the rxn](https://www.uniprot.org/uniprotkb/P07954/entry)

**I hereby confirm that I have:**
- [X] Done this analysis in the `main` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by haowang-bioinfo** [comment]
what about MAR06972, MAR06971, and MAR07642, should they be removed?

**Comment by feiranl** [comment]
Removing the gene from MAR06972, MAR06971, grRule for those rxn are not empty, thus, the rxns are kept. As for MAR07642, I am not sure, I found for this rxn, the annotation in Recon3D was added for modeling purpose. Thus, I would suggest, we need to validate metabolic tasks can still be fulfilled before removing this rxn.

**Comment by haowang-bioinfo** [comment]
fixed in #559
