### ISSUE TITLE
GPR curation for Cysteine metabolism

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#552]
### Description of the issue:
|Enzyme|rxn|grRules|GPT result|Manual check |Action|
|-----------------|------------------------|------------------------------------------------------------------|---------------------------------------------------------------------|-------------------------------|-------------------------------------|
[ENSG00000083123](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000083123) | MAR06523: H+[c] + H2O2[c] + thiocyanate[c] <=> H2O[c] + hypothiocyanite[c] | ENSG00000083123 or ENSG00000091140 or ENSG00000117592 or ENSG00000121053 or ENSG00000130508 or ENSG00000142046 or ENSG00000167419 or ENSG00000248098 or ENSG00000255730 | Yes, the substrates and products of this enzyme cover metabolites given: H+, H2O, H2O2, hypothiocyanite, thiocyanate. The enzyme catalyzes the overall conversion of alpha-keto acids to acyl-CoA and CO2, which involves the production of H2O2 and the reaction of H2O2 and hypothiocyanite to form thiocyanate. | No | [remove the gene](https://www.uniprot.org/uniprotkb/P21953/entry)
[ENSG00000248098](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000248098) | MAR06523: H+[c] + H2O2[c] + thiocyanate[c] <=> H2O[c] + hypothiocyanite[c] | ENSG00000083123 or ENSG00000091140 or ENSG00000117592 or ENSG00000121053 or ENSG00000130508 or ENSG00000142046 or ENSG00000167419 or ENSG00000248098 or ENSG00000255730 | No, the substrates and products of this enzyme do not cover metabolites H+, H2O, H2O2, hypothiocyanite, thiocyanate. This is because the substrates and products of this enzyme are alpha-ketoacid, acyl-CoA and CO2. | No | [remove the gene](https://www.uniprot.org/uniprotkb/P12694/entry)
[ENSG00000091140](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000091140) | MAR06523: H+[c] + H2O2[c] + thiocyanate[c] <=> H2O[c] + hypothiocyanite[c] | ENSG00000083123 or ENSG00000091140 or ENSG00000117592 or ENSG00000121053 or ENSG00000130508 or ENSG00000142046 or ENSG00000167419 or ENSG00000248098 or ENSG00000255730 | No, the substrates and products of this enzyme do not cover metabolites H+, H2O, H2O2, hypothiocyanite, thiocyanate. This enzyme is involved in the metabolism of lipoamide and 2-oxoglutarate, not the given metabolites. | No | [remove the gene](https://www.uniprot.org/uniprotkb/P09622/entry)
[ENSG00000168710](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000168710) | MAR03877: H2O[c] + SAH[c] => adenosine[c] + homocysteine[c] | ENSG00000101444 or ENSG00000158467 or ENSG00000168710 | No, the substrates and products of this enzyme do not cover adenosine, H2O, homocysteine, SAH as none of these metabolites are mentioned as substrates or products of this enzyme. | No. In vitro does not exhibit any S-adenosyl-L-homocysteine hydrolase activity | [remove the gene](https://www.uniprot.org/uniprotkb/O43865/entry)

**Comment by haowang-bioinfo** [comment]
fixed in #560
