### ISSUE TITLE
ENSG00000268104 Should probably be removed from GPRs of reactions without Cl-

### ISSUE THREAD

**Issue by jreimertz** [SysBioChalmers/Human-GEM#567]
Recently I came across 22 reactions which include ENSG00000268104 (SLC6A14) in their GPRs despite not including chloride in their reactants, which is required for transport with this gene according to its [Uniprot page](https://www.uniprot.org/uniprotkb/Q9UN76/entry)

These reactions include:
- MAR05305: alanine [e] + Na+ [e] --> alanine [c] + Na+ [c]
- MAR05308: glutamine [e] + Na+ [e] --> glutamine [c] + Na+ [c]
- MAR05311: asparagine [e] + Na+ [e] --> asparagine [c] + Na+ [c]
- MAR05314: Na+ [e] + valine [e] --> Na+ [c] + valine [c]
- MAR05315: leucine [e] + Na+ [e] --> leucine [c] + Na+ [c]
- MAR05316: isoleucine [e] + Na+ [e] --> isoleucine [c] + Na+ [c]
- MAR05317: Na+ [e] + tryptophan [e] --> Na+ [c] + tryptophan [c]
- MAR05318: Na+ [e] + tyrosine [e] --> Na+ [c] + tyrosine [c]
- MAR05319: Na+ [e] + phenylalanine [e] --> Na+ [c] + phenylalanine [c]
- MAR05320: glycine [e] + Na+ [e] --> glycine [c] + Na+ [c]
- MAR05324: methionine [e] + Na+ [e] --> methionine [c] + Na+ [c]
- MAR05326: Na+ [e] + threonine [e] --> Na+ [c] + threonine [c]
- MAR05333: histidine [e] + Na+ [e] --> histidine [c] + Na+ [c]
- MAR06375: Na+ [e] + serine [e] --> Na+ [c] + serine [c]
- MAR06377: cysteine [e] + Na+ [e] --> cysteine [c] + Na+ [c]
- MAR06380: glutamine [e] + H+ [c] + Na+ [e] --> glutamine [c] + H+ [e] + Na+ [c]
- MAR06381: H+ [c] + Na+ [e] + serine [e] --> H+ [e] + Na+ [c] + serine [c]
- MAR06382: asparagine [e] + H+ [c] + Na+ [e] --> asparagine [c] + H+ [e] + Na+ [c]
- MAR06384: H+ [c] + histidine [e] + Na+ [e] --> H+ [e] + histidine [c] + Na+ [c]
- MAR08629: arginine [e] + Na+ [e] --> arginine [c] + Na+ [c]
- MAR08917: lysine [e] + Na+ [e] --> lysine [c] + Na+ [c]
- MAR11791: Na+ [e] + selenomethionine [e] --> Na+ [c] + selenomethionine [c]

All of these reactions besides MAR08629 include other genes in their GPRs

**Comment by haowang-bioinfo** [comment]
@jreimertz thanks for reporting this.

As described in the [Uniprot annotation](https://www.uniprot.org/uniprotkb/Q9UN76/entry), SLC6A14 does mediate transportation of neutral and cationic amino acids in a Na+/Cl--dependent manner. Do you suggest to remove it from above reactions' GPRs?

**Comment by jreimertz** [comment]
Yes, I think it would make sense to remove SLC6A14 from the above reactions' GPRs. 

I was able to find this [paper](https://www.jbc.org/article/S0021-9258(20)72291-X/fulltext) from 2011 which cites this [paper](https://doi.org/10.2174/156800805774912953) from 2005.

**Comment by haowang-bioinfo** [comment]
> I was able to find this [paper](https://www.jbc.org/article/S0021-9258(20)72291-X/fulltext) from 2011 which cites this [paper](https://doi.org/10.2174/156800805774912953) from 2005.

The following discovery (illustrated in Fig3 and Fig4) in this JBC [paper](https://www.jbc.org/article/S0021-9258(20)72291-X/fulltext) supports the removal of SLC6A14 from above mentioned GPRs.

"Perifusion of SLC6A14-expressing oocytes with all three amino acids induced inward currents in the presence of NaCl; such currents were not detectable in the absence of either Na+ or Cl−, indicating that both ions are obligatory for transport."

**Comment by haowang-bioinfo** [comment]
> Sure I can do that

go ahead please

**Comment by haowang-bioinfo** [comment]
fixed in #576
