### ISSUE TITLE
Possibly remove Reaction MAR04411

### ISSUE THREAD

**Issue by jreimertz** [SysBioChalmers/Human-GEM#568]
When looking through reactions I noticed MAR04411: 1.5 Na+ [e] + Pi [e] <=> 1.5 Na+ [c] + Pi [c] includes ENSG00000144136 (SLC20A1) and ENSG00000168575 (SLC20A2) in its GPR. The [Uniprot page](https://www.uniprot.org/uniprotkb/Q8WUM9/entry) for SLC20A1 displays the stoichiometry for this reaction as: 3.0 Na+ [e] + Pi [e] <=> 3.0 Na+ [c] + Pi [c]. Confirming with the papers cited by Uniprot and the [paper](https://link.springer.com/article/10.1007/s00424-003-1088-x) included in the notes for this reaction it appears that the required stoichiometry is >1 NA+ per Pi. Additionally, this paper cited 1.5 as the Hill coefficient which suggests that including 1.5 as the Na+ coefficient may have been a typo. 

This reaction is identical to MAR04910: 3.0 Na+ [e] + Pi [e] --> 3.0 Na+ [c] + Pi [c], with different coefficients for the Na+. With this in mind, I believe MAR04411 could be removed. Because MAR04411 is a reversible reaction currently and MAR04910 is not, I've included this [paper](https://link.springer.com/article/10.1007/s12031-017-0934-9) which states that SLC20A1 and SLC20A2 transport phosphate in the opposite direction of XPR1 which exports phosphate.

**Comment by haowang-bioinfo** [comment]
yes, it does appear so.

**Comment by jreimertz** [comment]
XPR1 should be added to MAR02351 since this is the only Pi export reaction in Human1.

Additionally, table 1 in this [paper](https://journals.physiology.org/doi/full/10.1152/physrev.00022.2017) displays the known stoichiometry's for each of the transporters included in the Pi import reactions. Based on this and other sources noted in this paper, I suggest dropping SLC20A1 and SLC20A2 from MAR05413 since Pi transport with SLC20 is Na+ dependent and because these are the only genes associated with this reaction. Since there doesn't appear to be any evidence of Pi transport with H+ in humans, it is likely that this reaction could be dropped entirely.

**Comment by feiranl** [comment]
I agree with @jreimertz suggestion about removing the rxn `MAR05413` . According to Uniprot, the SLC20A1 and SLC20A2 are annotated to utilize over 1 Na+ per Pi, having a rxn `Na+ [e] + Pi [e] ⇒ Na+ [c] + Pi [c]` or the original  `H+ [e] + Pi [e] ⇒ H+ [c] + Pi [c]` is not appropriate.

**Comment by jreimertz** [comment]
Sounds good to me!

I think MAR04912 is okay since the [paper](https://journals.physiology.org/doi/full/10.1152/physrev.00022.2017) states the stoichiometry for SLC20A1 and SCL20A2 are both 2:1 Na+/Pi and the [uniprot page](https://www.uniprot.org/uniprotkb/Q8N130/entry) for SLC34A3 shows the stoichiometry as 2:1 Na+/Pi as well

**Comment by haowang-bioinfo** [comment]
> Sounds good to me!

then go ahead please
