### ISSUE TITLE
Proposed changes to Sodium Transport GPRs

### ISSUE THREAD

**Issue by jreimertz** [SysBioChalmers/Human-GEM#569]
I came across another collection of transport reactions which likely should should have their GPRs updated.

- [x] 1. Remove ENSG00000111371 ([SLC38A1](https://www.uniprot.org/uniprotkb/Q9H2H9/entry)), ENSG00000134294 ([SLC38A2](https://www.uniprot.org/uniprotkb/Q96QD8/entry)), and ENSG00000139209 ([SLC38A4](https://www.uniprot.org/uniprotkb/Q969I6/entry)) from reaction [MAR06380](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06380)
    - These all encode sodium-coupled amino acid transporters and do not include the H+ that is included in MAR06380

- [x] 2. Add ENSG00000188338 ([SLC38A3](https://www.uniprot.org/uniprotkb/Q99624/entry)) to MAR06380
    - SLC38A3 does encode the correct reaction and stoichiometry and should be added
    
- [x] 3. Remove reaction [MAR05310](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05310)
    - MAR05310 currently includes [SLC38A3](https://www.uniprot.org/uniprotkb/Q99624/entry) and [SLC38A5](https://www.uniprot.org/uniprotkb/Q8WUX1/entry) in its GPR but this isn't the correct stoichiometry according to both Uniprot pages. Adding SLC38A3 to MAR06380 will fix this and remove the need for MAR05310.

- [x] 4. ~Add ENSG00000268104 ([SLC6A14](https://www.uniprot.org/uniprotkb/Q9UN76/entry)) to reaction [MAR09887](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09887)~
    - ~The stoichiometry matches for SLC6A14 but it is currently not included in the GPR for MAR09887~

- [x] 5. ~Remove ENSG00000164363 ([SLC6A18](https://www.uniprot.org/uniprotkb/Q96N87/publications)) and ENSG00000147003 ([CLTRN](https://www.uniprot.org/uniprotkb/Q9HBJ8/entry)) from reaction MAR09887~
    - ~SLC6A18 and CLTRN are the sodium dependent transporter components and do not involve Cl- which is included in MAR09887~
- [x] 4. Remove MAR09887 because it does not match the reactions catalyzed by either gene it's currently associated with, and almost represents the reaction catalyzed by SLC6A14 (`ENSG00000268104`), but MAR06896 already represents that reaction with the correct stoichiometry and is already associated with SLC6A14
- [x] 5. Make MAR06380 reversible to match Uniprot annotation for [SLC38A3](https://www.uniprot.org/uniprotkb/Q99624/entry)

**Comment by jreimertz** [comment]
The proposed changes to MAR06380 and MAR05310 can also be applied to MAR06382 and MAR05312 respectively. I'll continue to add similar reactions as I encounter them

**Comment by haowang-bioinfo** [comment]
> I'll continue to add similar reactions as I encounter them

good job - please continue!

**Comment by haowang-bioinfo** [comment]
@all-contributors please add @jreimertz for bug report.

**Comment by haowang-bioinfo** [comment]
@jreimertz sorry for the late response, here are a few comments:
- agree to remove [MAR05310](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05310) and modify GPRs of [MAR06380](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06380) as proposed. According to the Uniprot annotation, should MAR06380 be converted to reversible?
- likewise, how about remove [MAR09887](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09887) and keep [MAR06896](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06896), which has matched stoichiometry and was assigned with [SLC6A14](https://www.uniprot.org/uniprotkb/Q9UN76/entry)?

**Comment by Devlin-Moyer** [comment]
yep it does look like MAR06380 should be reversible and that the proposed changes to MAR09887 would make it identical to MAR06896, so MAR09887 should just be removed altogether
