### ISSUE TITLE
Problems with Glucose Uptake and Sodium/Potassium Pump Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#570]
- [x] Remove `MAR06895: ATP [c] + H2O [c] + 2 Na+ [e] + glucose [e] ⇒ ADP [c] + H+ [c] + 2 Na+ [c] + Pi [c] + glucose [c]`, GPR: `ENSG00000100170` because it is (almost) equivalent to the combined actions of `MAR05429` and `MAR08884` and misrepresents the function of `ENSG00000100170`:
  - According to [Uniprot](https://www.uniprot.org/uniprotkb/P13866/entry), `ENSG00000100170` does symport of 2 Na<sup>+</sup> and one glucose "dependent on the sodium gradient established by the Na<sup>+</sup>/K<sup>+</sup> pump" and does not directly hydrolyze ATP.
  - `MAR05429: 2 K+ [e] + 3 Na+ [c] + ATP [c] + H2O [c] ⇒ 2 K+ [c] + 3 Na+ [e] + ADP [c] + H+ [c] + Pi [c]` accurately represents the action of the ATP-hydrolyzing Na<sup>+</sup>/K<sup>+</sup> pump (the GPR is all of the subunits of the relevant enzyme complex).
  - `MAR08884: 2 Na+ [e] + glucose [e] ⇒ 2 Na+ [c] + glucose [c]`, GPR: `ENSG00000100170` accurately represents the reaction directly catalyzed by `ENSG00000100170`.
- [x] Remove `ENSG00000140675` from the GPR of `MAR05029` because, [according to Uniprot](https://www.uniprot.org/uniprotkb/P31639/entry), `ENSG00000140675` catalyzes _sodium-dependent_ symport of glucose, and `MAR05029` does not involve any sodium.
  - The other genes in the GPR of `MAR05029` all facilitate reversible diffusion of unaccompanied glucose according to Uniprot, so they can stay.
- [x] Remove `MAR05295: K+ [e] + Na+ [c] + ATP [c] + H2O [c] ⇒ K+ [c] + Na+ [e] + ADP [c] + H+ [c] + Pi [c]` because it is a duplicate of `MAR05429` but with the wrong stoichiometric coefficients.
  - The [reference](https://journals.physiology.org/doi/epdf/10.1152/physrev.1981.61.1.1) associated with `MAR05295` clearly states the stoichiometry is 3 Na<sup>+</sup> to 2 K<sup>+</sup> and that the reaction is electrogenic; stoichiometric coefficients of 1 for all metabolites would be electroneutral since the two metabolites being exchanged have the same charge.
- [x] Copy the [reference](https://journals.physiology.org/doi/epdf/10.1152/physrev.1981.61.1.1) currently associated with `MAR05295` to `MAR05429`.
  - `MAR05429` currently has no references associated with it and is the same reaction as `MAR05295`.
- [x] Edit `MAR01444` so that it becomes `ATP [c] + H2O [c] + K+ [e] + H+ [e] + 2 Na+ [c] ⇒ ADP [c] + Pi [c] + K+ [c] + H+ [c] + 2 Na+ [e]` with GPR `ENSG00000075673 and ENSG00000186009` so that it is no longer redundant with `MAR08892`
  - Currently, `MAR01444` is redundant with `MAR08892`; they have identical stoichiometry and the GPR of `MAR01444` is `ENSG00000105675 and ENSG00000186009` and the GPR of `MAR08892` is `(ENSG00000105675 and ENSG00000186009) or (ENSG00000075673 and ENSG00000186009)`.
  - Either `ENSG00000105675` or `ENSG00000075673` can dimerize with `ENSG00000186009` to form a catalytically-active complex capable of exchanging 2 intracellular H<sup>+</sup> with 1 extracellular K<sup>+</sup> and 1 extracellular H<sup>+</sup> ([source](https://doi.org/10.1007/978-3-030-55454-5_10)), so the GPR of `MAR08892` fully captures this situation and there is no reason for `MAR01444` to exist as a separate reaction.
  - However, according to that same source, the `ENSG00000075673`-`ENSG00000186009` dimer can also exchange 2 intracellular Na<sup>+</sup> for 1 extracellular K<sup>+</sup> and 1 extracellular H<sup>+</sup>, and, as far as I can tell, there is currently no such reaction in Human-GEM.
  - So instead of just removing `MAR01444` for being redundant with `MAR08892`, I propose that it be edited to become the sodium-dependent reaction that the `ENSG00000075673`-`ENSG00000186009` dimer can also catalyze that is not currently represented.

**Comment by feiranl** [comment]
@Devlin-Moyer Good work! It would be great if you can explain the following question.

> Remove `ENSG00000100170` from the GPR of `MAR05029` because, [according to Uniprot](https://www.uniprot.org/uniprotkb/P13866/entry), ENSG00000100170 catalyzes sodium-dependent symport of glucose, and MAR05029 does not involve any sodium.
> The other genes in the GPR of MAR05209 all facilitate reversible diffusion of unaccompanied glucose according to Uniprot, so they can stay.

`ENSG00000100170` is not in grRules for `MAR05029` in the main branch and develop branch. 



> Edit MAR01444 so that it becomes ATP [c] + H2O [c] + K+ [e] + H+ [e] + 2 Na+ [c] ⇒ ADP [c] + Pi [c] + K+ [c] + H+ [c] + 2 Na+ [e] with GPR ENSG00000075673 and ENSG00000186009 so that it is no longer redundant with MAR08992
> Currently, MAR01444 is redundant with MAR08992; they have identical stoichiometry and the GPR of MAR01444 is ENSG00000105675 and ENSG00000186009 and the GPR of MAR08992 is (ENSG00000105675 and ENSG00000186009) or (ENSG00000075673 and ENSG00000186009).
> Either ENSG00000105675 or ENSG00000075673 can dimerize with ENSG00000186009 to form a catalytically-active complex capable of exchanging 2 intracellular H+ with 1 extracellular K+ and 1 extracellular H+ ([source](https://doi.org/10.1007/978-3-030-55454-5_10)), so the GPR of MAR08992 fully captures this situation and there is no reason for MAR01444 to exist as a separate reaction.
> However, according to that same source, the ENSG00000075673-ENSG00000186009 dimer can also exchange 2 intracellular Na+ for 1 extracellular K+ and 1 extracellular H+, and, as far as I can tell, there is currently no such reaction in Human-GEM.
> So instead of just removing MAR01444 for being redundant with MAR08992, I propose that it be edited to become the sodium-dependent reaction that the ENSG00000075673-ENSG00000186009 dimer can also catalyze that is not currently represented.

I suppose you are referring to `MAR08892` rather `MAR08992`, I am ok with the proposed change.

**Comment by Devlin-Moyer** [comment]
re: `ENSG00000100170` in `MAR05029`: the symbol for that gene is SLC5A1, and the gene I intended to talk about is SLC5A2, `ENSG00000140675`, which is in the GPR of `MAR05029` and is also sodium-dependent [according to Uniprot](https://www.uniprot.org/uniprotkb/P31639/entry); I can edit the original comment accordingly

and yes sorry I did mean `MAR08892`; I will also edit the original comment to fix that

**Comment by feiranl** [comment]
Great! Please go ahead and make those changes.

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer brilliant!

if to remove MAR06895 given the combined existence of MAR05429 and MAR08884, should MAR06895 also be removed because it is equivalent to MAR05429 + MAR08877?

**Comment by Devlin-Moyer** [comment]
I hadn't noticed that before, but yes that seems correct to me; should I add another commit to #581 to do that, or should it be implemented in a separate PR?

**Comment by haowang-bioinfo** [comment]
no need to start a separate PR, just commit to #581

**Comment by haowang-bioinfo** [comment]
fixed in #581
