### ISSUE TITLE
Pairs of reactions with identical stoichiometry and one has a GPR and one doesn't

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#579]
Reaction without GPR should be removed and reaction with GPR should be made reversible if not already

- [X] MAR06884: cobamide-coenzyme [e] --> cobamide-coenzyme [c], GPR: `ENSG00000107611 and ENSG00000134812 and ENSG00000166126`
MAR06873: cobamide-coenzyme [c] --> cobamide-coenzyme [e], no GPR

- [X] MAR11815: calcitriol [e] --> calcitriol [c], GPR: `ENSG00000015520 or ENSG00000073060 or ENSG00000135218`
MAR11964: calcitriol [c] --> calcitriol [e], no GPR

- [X] MAR00108: L-carnitine [c] + oleoyl-CoA [c] <=> CoA [c] + octadecenoylcarnitine(5) [c], GPR: `ENSG00000110090 or ENSG00000169169 or ENSG00000205560`
~MAR11310: CoA [c] + octadecenoylcarnitine(5) [c] <=> L-carnitine [c] + oleoyl-CoA [c], no GPR~ already removed by #573

- [X] MAR02404: 10-HETE [e] <=> 10-HETE [c], GPR: `ENSG00000184999`
~MAR10410: 10-HETE [c] <=> 10-HETE [e], no GPR~ already removed by #573

- [X] MAR07178: PE-LD pool [c] <=> PE-LD pool [r], GPR: `ENSG00000163586`
~MAR00464: PE-LD pool [c] <=> PE-LD pool [r], no GPR~ already removed by #573

- [X] MAR06621: dUTP [m] + H2O [m] + oxidized thioredoxin [m] <=> thioredoxin [m] + UTP [m], GPR: `(ENSG00000048392 and ENSG00000100348 and ENSG00000167325 and ENSG00000171848) or (ENSG00000048392 and ENSG00000136810 and ENSG00000167325 and ENSG00000171848)`
~MAR02490: thioredoxin [m] + UTP [m] <=> dUTP [m] + H2O [m] + oxidized thioredoxin [m], no GPR~ already removed by #573 

I found these with the Python code mentioned in #562

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer sorry for the late response

for the paired reactions MAR06884/MAR06873 and MAR11815/MAR11964, not sure if merging is a good idea. Because the transporters of the import reactions are annotated for uptake only. For example, the activity of  [ENSG00000135218](https://www.uniprot.org/uniprotkb/P16671/entry) is irreversible for import, [ENSG00000134812](https://www.uniprot.org/uniprotkb/P27352/entry) and [ENSG00000015520](https://www.uniprot.org/uniprotkb/Q9UHC9/entry) are also annotated for absorption only. Therefore, merging the pairs into reversible one would be inaccurate implementation. What do you think?

**Comment by Devlin-Moyer** [comment]
Ah I didn't think to check the annotations of the genes themselves since one reaction had no genes in each pair; in that case, should MAR06873 and MAR11964 exist at all? I'm pretty sure the only things calcitriol and cobamide-coenzyme can really do in Human-GEM is wind up as biomass precursors, so do they need to be capable of moving from [c] to [e]? I suppose if you wanted to model the maximum possible production of either one independent of the rest of the biomass precursors, you'd want them to be able to reach their exchange reactions.
Should I
* Close #656 and leave MAR06884/MAR06873 and MAR11815/MAR11964 exactly as they are, or
* Edit #656 to leave MAR06884 and MAR11815 as irreversible [e] to [c] reactions, but still remove MAR06873 and MAR11964?

**Comment by haowang-bioinfo** [comment]
> should MAR06873 and MAR11964 exist at all? I'm pretty sure the only things calcitriol and cobamide-coenzyme can really do in Human-GEM is wind up as biomass precursors, so do they need to be capable of moving from [c] to [e]?

good questions and I'm not exactly sure. A feasible principle, which Human-GEM is applying now, probably is to make changes whenever evidence is provided 

> I suppose if you wanted to model the maximum possible production of either one independent of the rest of the biomass precursors, you'd want them to be able to reach their exchange reactions.

this appears to be a reasonable claim to keep MAR06873 and MAR11964 as they are

**Comment by Devlin-Moyer** [comment]
alright so in that case I'll just close #656 as well as this issue
