### ISSUE TITLE
Incorrect metabolite formulas

### ISSUE THREAD

**Issue by pinarkocabas** [SysBioChalmers/Human-GEM#58]
### Description of the issue:
* During manual curation of reaction balancing using MetaNetX database, 11 metabolites were found to have incorrect molecular formulas.

#### Current feature/value/output:
The following metabolites are curated accordingly:

Met ID | Metabolite name | Current formula | MNX formula 20181029 | MNX formula 20181211 | MNX charge 20181211 | MNX ids-20181211
-- | -- | -- | -- | -- | -- | --
m02682 | PAPS | C10H11N5O10P2 | C10H11N5O13P2S | C10H11N5O13P2S | -4 | MNXM49
m00737 | 3,5-diiodo-L-thyronine-4-O-sulfate | C15H12I2NO7S | C15H13I2NO7S | C15H12I2NO7S | -1 | MNXM150744
m01195 | 7-Hydroxymethyl-12-methylbenz[a]anthracene   sulfate | C20H16O4S | C20H15O4S | C20H15O4S | -1 | MNXM15042
m01657 | Dehydrodolichol   diphosphate | C1080H1738O70P20 | C95H153O7P2 | NA | NA | MNXM48918
m00531 | 1D-myo-inositol-bisdiphosphate-tetrakisphosphate | C6H7O24P6 | C6H7O30P8 | C6H20O30P8 | NA | MNXM34087
m02977 | tetraHCA | C27H47O4 | C27H45O6 | C27H45O6 | -1 | MNXM30748
m01599 | cob(II)alamin | C62CoH92N13O14P | C62CoH92N13O14P | C62H88CoN13O14P | 0 | MNXM814
m01598 | cob(I)alamin | C62CoH88N13O14P | C62CoH88N13O14P | C62H88CoN13O14P | -1 | MNXM91519
m00676 | 2-S-glutathionyl   acetate | C12H18N3O8S | C12H17N3O8S | C12H17N3O8S | -2 | MNXM5771
m02837 | retinyl   palmitate | C36H58O3 | C36H60O2 | C36H60O2 | 0 | MNXM918
3hpvs | 3'-S-hydroxy-pravastatin | C23H35NaO8 | C23H36O8 | C23H35NaO8 | 0 |  

**I hereby confirm that I have:**
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by JonathanRob** [comment]
This issue was addressed in the recent PR #131.
