### ISSUE TITLE
Pairs of reactions with identical stoichiometry but different GPRs

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#580]
Not sure if I should check the references to see if this reaction should be reversible or if we can assume that it is reversible and remove the irreversible one, like nearly all NAD(H)-dependent reactions seem to be:

- [x] MAR03933: formylglutathione [c] + H+ [c] + NADH [c] <=> hydroxymethylglutathione [c] + NAD+ [c], GPR: `ENSG00000197894`
~MAR20045: hydroxymethylglutathione [c] + NAD+ [c] --> formylglutathione [c] + H+ [c] + NADH [c], GPR: `ENSG00000197894`~ already removed in #573

In addition to figuring out whether or not `ENSG00000197763` should be in this GPR, these should probably be merged into a single reversible reaction:

- [x] MAR08482: H+ [m] + NADPH [m] + oxidized thioredoxin [m] --> NADP+ [m] + thioredoxin [m], GPR: `ENSG00000184470 or ENSG00000197763 or ENSG00000198431`
MAR02358: NADP+ [m] + thioredoxin [m] --> H+ [m] + NADPH [m] + oxidized thioredoxin [m], GPR: `ENSG00000184470 or ENSG00000198431`

These have one GPR that is fully contained within the other; haven't looked into any to determine whether the longer or shorter GPR seems more accurate/justified

- [x] MAR03984: 2.0 H2O2 [x] --> 2.0 H2O [x] + O2 [x], GPR: `ENSG00000121691 or ENSG00000166016`
MAR20066: 2.0 H2O2 [x] --> 2.0 H2O [x] + O2 [x], GPR: `ENSG00000121691`

- [x] MAR04521: glucose-6-phosphate [r] + H2O [r] --> glucose [r] + Pi [r], GPR: `ENSG00000131482 or ENSG00000141349 or ENSG00000152254`
MAR20020: glucose-6-phosphate [r] + H2O [r] --> glucose [r] + Pi [r], GPR: `ENSG00000131482 or ENSG00000141349`

- [x] MAR06631: NAD+ [c] + retinol [c] --> H+ [c] + NADH [c] + retinal [c], GPR: `ENSG00000025423 or ENSG00000135437 or ENSG00000147576 or ENSG00000170786 or ENSG00000172955 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198099 or ENSG00000248144`
MAR20002: NAD+ [c] + retinol [c] --> H+ [c] + NADH [c] + retinal [c], GPR: `ENSG00000198099 or ENSG00000196616`

The longer GPR does not fully contain the shorter one, and I haven't looked up any of the genes to figure out what the situation is yet:

 - [X] MAR00025: MAM01268n -> MAM01268c, GPR: `ENSG00000065833 or ENSG00000105398 or ENSG00000112972 or ENSG00000130304 or ENSG00000139278 or ENSG00000143344 or ENSG00000147872 or ENSG00000170485 or ENSG00000198431`
MAR00030: MAM01286c -> MAM01286n, GPR: `ENSG00000004799 or ENSG00000005471 or ENSG00000072310 or ENSG00000099194 or ENSG00000100979 or ENSG00000105398 or ENSG00000110090 or ENSG00000113790 or ENSG00000117054 or ENSG00000118137 or ENSG00000130304 or ENSG00000134240 or ENSG00000134824 or ENSG00000135218 or ENSG00000138823 or ENSG00000147872 or ENSG00000149485 or ENSG00000151726 or ENSG00000156096 or ENSG00000157184 or ENSG00000158874 or ENSG00000161533 or ENSG00000163586 or ENSG00000165029 or ENSG00000166819 or ENSG00000166821 or ENSG00000167114 or ENSG00000167588 or ENSG00000167772 or ENSG00000169710 or ENSG00000175445 or ENSG00000177666 or ENSG00000185000 or ENSG00000187048 or ENSG00000278540`

All of these except the last one were found by the Python code in #562

**Comment by feiranl** [comment]
Nice!  Please go ahead and make changes. I suggest to remove `MAR20045, MAR02358, MAR20066, MAR20020, MAR20002` by a separate PR. 

As for the last one, the GPR need to be doubled checked.
This is not a conventional metabolic rxn, it is difficult to decide wether the gene is associated with this rxn.
but for sure [ENSG00000065833](https://www.uniprot.org/uniprotkb/P48163/entry)  is not this function
[ENSG00000112972](https://www.uniprot.org/uniprotkb/Q01581/entry)
[ENSG00000198431](https://www.uniprot.org/uniprotkb/Q16881/entry)

**Comment by Devlin-Moyer** [comment]
It looks like the only other reaction `MAM01286n` can participate in is `MAR00024`, which irreversibly produces it, so we could also just remove `MAR00030` and leave `MAR00025` as-is (irreversible transport from [n] to [c]) since, unless someone adds some other reactions that can consume `MAM01286n`, there's no reason for there to be a [c] to [n] transport reaction. I'm leaning towards removing `MAR00030` instead of looking through all of the genes associated with `MAR00030` since, as you said, it's not really clear how to tell which genes should or shouldn't be there

**Comment by haowang-bioinfo** [comment]
all duplicate pairs reported seem to be reasonable, except the last one `MAR00025 versus MAR00030`. They apparently are not duplicate to each other.

> It looks like the only other reaction MAM01286n can participate in is MAR00024, which irreversibly produces it, so we could also just remove MAR00030 and leave MAR00025 as-is (irreversible transport from [n] to [c]) since, unless someone adds some other reactions that can consume MAM01286n, there's no reason for there to be a [c] to [n] transport reaction. 

This is speculation purely based on current model, without literature- or annotation-based evidence. Is there any paper that describes transportation direction or mechanism of MAM01268n?

> I'm leaning towards removing MAR00030 instead of looking through all of the genes associated with MAR00030 since, as you said, it's not really clear how to tell which genes should or shouldn't be there

removing MAR00030 would lead to deletion of ENSG00000072310, ENSG00000100979, ENSG00000138823. The first one ENSG00000138823 is regulatory transcription factor involving into cholesterol biosynthesis and lipid metabolism, while the last two are transporters with a bunch of substrates, of which if any is related to MAM01268n?

**Comment by Devlin-Moyer** [comment]
`MAM01286n` is named "activation-ppara", which I assume means it represents the active, ligand-bound form of [Peroxisome Proliferator Alpha](https://journals.lww.com/hep/Fulltext/9900/Hepatic_fibrosis__targeting_peroxisome.256.aspx), a transcription factor. In some sense, a [c] -> [n] transport reaction would be a reasonable representation of the fact that it's first translated on a cytosolic ribosome (like all proteins) and must subsequently be imported into the nucleus before it can do its job as a transcription factor, but, as I mentioned earlier, there aren't any "reactions" that represent its role as a transcription factor in the nucleus (only its binding to ligands), since this is a model of metabolism and not transcriptional regulation. As far as I can tell, there's no reason to believe that it can be exported from nuclei (I can find zero papers that mention nuclear transport of PPARA in either direction), and I assume that was only added in to give it a connection to the exchange reaction for `MAM01286e` so that people could model activation of PPARA by the various metabolites that can activate it.

**Comment by haowang-bioinfo** [comment]
> MAM01286n is named "activation-ppara", which I assume means it represents the active, ligand-bound form of Peroxisome Proliferator Alpha, a transcription factor. In some sense, a [c] -> [n] transport reaction would be a reasonable representation of the fact that it's first translated on a cytosolic ribosome (like nearly all proteins) and must subsequently be imported into the nucleus before it can do its job as a transcription factor

good summary

> As far as I can tell, there's no reason to believe that it can be exported from nuclei (I can find zero papers that mention nuclear transport of PPARA in either direction), and I assume that was only added in to give it a connection to the exchange reaction for MAM01286e so that people could model activation of PPARA by the various metabolites that can activate it.

this transport reaction from nuclei bring activated PPARA into cytosol, from which it is further transported into various compartments where however story ends and no follow-ups

> but, as I mentioned earlier, there aren't any "reactions" that represent its role as a transcription factor in the nucleus (only its binding to ligands), since this is a model of metabolism and not transcriptional regulation. 

make sense, what if just remove the "reactions" related this transcription factor?

**Comment by Devlin-Moyer** [comment]
removing all reactions involving "activation-ppara" or PPARA would remove:
- `MAR00024: PPARA [n] + fatty acid-ligands [n] ⇒ activation-ppara [n]`
- `MAR00025: activation-ppara [n] ⇒ activation-ppara [c]`
- `MAR00030: activation-ppara [c] ⇒ activation-ppara [n]`
- `MAR00026: activation-ppara [c] ⇒ activation-ppara [r]`
- `MAR00027: activation-ppara [c] ⇒ activation-ppara [m]`
- `MAR00028: activation-ppara [c] ⇒ activation-ppara [x]`
- `MAR00029: activation-ppara [c] ⇒ activation-ppara [e]`
- `MAR13064: activation-ppara [e] ⇔`
- `MAR05289: 467 ATP [l] + 934 H2O [l] + PPARA [l] ⇒ 467 ADP [l] + 476 H+ [l] + 467 Pi [l] + 31 alanine [l] + 19 arginine [l] + 19 asparagine [l] + 27 aspartate [l] + 19 cysteine [l] + 34 glutamate [l] + 16 glutamine [l] + 28 glycine [l] + 13 histidine [l] + 29 isoleucine [l] + 47 leucine [l] + 33 lysine [l] + 15 methionine [l] + 22 phenylalanine [l] + 20 proline [l] + 37 serine [l] + 18 threonine [l] + 14 tyrosine [l] + 27 valine [l]`

Ok yea while putting together that list I noticed that there are a bunch of random genes associated with those transport reactions that are absolutely not responsible for transporting proteins across intracellular membranes (e.g. ACOX1 and ACADM, fatty acid oxidation enzymes, and ME1, malic enzyme), so they all seem just as questionable as `MAR00030` and `MAR00025`. Also the two PPARA metabolites (`MAM02757l` and `MAM02757n`) could only be consumed and never produced, so this whole pathway was completely non-functional

**Comment by haowang-bioinfo** [comment]
thanks for the listing that helps a lot!

> Should I open a separate PR to remove all of these PPARA-related reactions, or add that on to https://github.com/SysBioChalmers/Human-GEM/pull/657?

would lean toward letting #657 go first, because not sure about [MAR05289](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05289). @JonathanRob any clue about this reaction, would it be okay to remove it?

**Comment by haowang-bioinfo** [comment]
> In addition to figuring out whether or not ENSG00000197763 should be in this GPR, these should probably be merged into a single reversible reaction:
 MAR08482: H+ [m] + NADPH [m] + oxidized thioredoxin [m] --> NADP+ [m] + thioredoxin [m], GPR: ENSG00000184470 or ENSG00000197763 or ENSG00000198431
MAR02358: NADP+ [m] + thioredoxin [m] --> H+ [m] + NADPH [m] + oxidized thioredoxin [m], GPR: ENSG00000184470 or ENSG00000198431

based on the catalytic activity of [ENSG00000184470](), [ENSG00000197763](), and [ENSG00000198431](), they all irreversibly catalyze toward oxidized NADP+. So MAR08482 should be in its original way and just remove MAR02358. 

Additionally, only ENSG00000184470 should be kept given its localization, while the other two should be for [MAR03931](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03931) which is the cytosolic version of MAR08482 and now has the same GPR with the 3 genes.

**Comment by haowang-bioinfo** [comment]
> yep it looks like all three of those enzymes can reduce but not oxidize thioredoxin, ENSG00000184470 is localized to mitochondria, and both ENSG00000197763 and ENSG00000198431 are not localized to mitochondria

thanks, the changes were just made to #657

should there also be a separate PR about that? at this point I'm maybe thinking I should just close https://github.com/SysBioChalmers/Human-GEM/pull/657 altogether, since it seems like each one of these pairs maybe has a distinct issue going on

or just merge it, the others are just pure duplicate pairs

**Comment by Devlin-Moyer** [comment]
oh yea I didn't see that you were making those changes while I was typing that comment; if you think #657 is ok to merge now, that's fine by me

**Comment by Devlin-Moyer** [comment]
Addressed by #657 and #678
