### ISSUE TITLE
FAHD1 Catalyzes MAR11430

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#585]
`MAR11430: H+ [c] + OAA [c] ⇒ CO2 [c] + pyruvate [c]` currently has no genes associated with it.
`ENSG00000180185` encodes FAHD1, which has been shown to catalyze this reaction in human cells ([source](https://www.jbc.org/article/S0021-9258(20)76756-6/fulltext)).
It may also be relevant to note that FAHD1 is not currently in Human-GEM.

**Comment by haowang-bioinfo** [comment]
yes, this is align with [Uniprot annotation](https://www.uniprot.org/uniprotkb/Q6P587/entry).

please add this gene to GPR of MAR11430, and `genes.tsv`

**Comment by haowang-bioinfo** [comment]
This [FAHD1](https://www.uniprot.org/uniprotkb/Q6P587/entry#subcellular_location) is localized in both cytsol and mitochondrion. Maybe also add a new reaction `H+ [m] + OAA [m] ⇒ CO2 [m] + pyruvate [m]`?

**Comment by haowang-bioinfo** [comment]
fixed in #592
