### ISSUE TITLE
Inaccurate Representation of CLYBL

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#586]
### The Problem:

CLYBL (`ENSG00000125246`) is currently associated with exactly two reactions in Human-GEM: `MAR05294` and `MAR11421`. Both reactions are citrate -> oxaloacetate + acetate; `MAR05294` uses the mitochondrial versions of those metabolites, and `MAR11421` uses the cytosolic versions. CLYBL is the only gene associated with both reactions.

This reaction is the ATP-independent citrate lyase reaction, which human cells do not catalyze; we instead have the ATP citrate lyase reaction ([source](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009346)), which is already represented by `MAR04149: ATP [c] + CoA [c] + citrate [c] ⇒ ADP [c] + OAA [c] + Pi [c] + acetyl-CoA [c]` GPR: `ENSG00000131473` (ACLY).

CLYBL resembles the beta subunnit of en enzyme complex that catalyzes the ATP-independent citrate lyase reaction in many bacteria (hence the name Citrate LYase Beta-Like), but in humans, it is a citramalyl-CoA lyase (see [Uniprot](https://www.uniprot.org/uniprotkb/Q8N0X4/entry) and [this paper](https://www.sciencedirect.com/science/article/pii/S0092867417311820)). This reaction is represented in Human-GEM by `MAR08666: (3S)-citramalyl-CoA [m] ⇒ acetyl-CoA [m] + pyruvate [m]`, which currently has no genes associated with it. There is no cytosolic version of this reaction, but that is not a problem because CLYBL is a strictly mitochondrial gene according to all the sources I cited above.

### Proposed Changes:

- [x] Add `ENSG00000125246` to the currently empty GPR of `MAR08666`
- [x] Add 29056341 as a reference for `MAR08666`
- [x] Remove `MAR05294` and `MAR11421`

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer yes, you are right! CLYBL (ENSG00000125246) should be added to MAR08666. 

Could you please check if it can also be added to any other reactions？

**Comment by Devlin-Moyer** [comment]
Uniprot cites [two](https://www.cell.com/cell/fulltext/S0092-8674(17)31182-0?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867417311820%3Fshowall%3Dtrue) [papers](https://academic.oup.com/hmg/article/23/9/2313/632255?login=false) that found that CLYBL is also capable of catalyzing
- glyolxalate + acetyl-CoA + H2O -> malate + CoA
- glyoxalate + propionyl-CoA + H2O -> 3-methylmalate + CoA
- malyl-CoA + H2O -> malate + CoA
But none of those are currently reactions in Human-GEM. The first of those papers found that CLYBL was thousands of times faster at catalyzing MAR08666 than any of these three reactions, but it seems pretty clear that these reactions do occur. The first reaction could be added relatively easily, since all of those metabolites already exist in Human-GEM, but the others involve metabolites that are not currently in Human-GEM, so they'd be dead-end/isolated reactions unless we figured out what other reactions they participate in that are also missing and add those as well; I have no idea how involved that would wind up being.

**Comment by haowang-bioinfo** [comment]
> So if we wanted, we could also add a new reaction MAM02007m + MAM01261m + MAM02040m -> MAM02439m MAM01597m GPR: ENSG00000125246

yes, please add this that had been [experimentally validated](https://pubmed.ncbi.nlm.nih.gov/24334609/)

**Comment by Devlin-Moyer** [comment]
fixed in #606
