### ISSUE TITLE
Inaccurate GPR of MAR04372

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#587]
### The Problem:
`MAR04372: 2,3-bisphospho-D-glycerate [c] + H2O [c] ⇒ 3-phospho-D-glycerate [c] + Pi [c]` is currently associated with BPGM (`ENSG00000172331`), which catalyzes the isomerization of 1,3-bisphosphoglycerate and 2,3-bisphosphoglycerate (i.e. `MAR04371`, which already has BPGM in its GPR), not the dephosphorylation of 2,3-bisphosphoglycerate (see [Uniprot](https://www.uniprot.org/uniprotkb/P07738/entry)). The correct GPR for `MAR04372` is [ACYP1](https://www.uniprot.org/uniprotkb/P07311/entry) or [ACYP2](https://www.uniprot.org/uniprotkb/P14621/entry) (`ENSG00000119640 or ENSG00000170634`), i.e. the same as the current GPR for `MAR04370: 1,3-bisphospho-D-glycerate [c] + H2O [c] ⇒ 3-phospho-D-glycerate [c] + H+ [c] + Pi [c]` (see their Uniprot pages).

### Proposed Changes:
- [ ] Change the GPR of `MAR04372` from `ENSG00000172331` to `ENSG00000119640 or ENSG00000170634`

**Comment by haowang-bioinfo** [comment]
yes, it does appear that [ACYP1](https://www.uniprot.org/uniprotkb/P07311/entry) and [ACYP2](https://www.uniprot.org/uniprotkb/P14621/entry) produce carboxylate and phosphate, while [BPGM](https://www.uniprot.org/uniprotkb/P07738/entry) is irrelevant to dephosphorylation. 

just wonder if there is any evidence associating ACYP1 or ACYP2 to substrates of bisphospho-D-glycerate?

**Comment by Devlin-Moyer** [comment]
The only paper I can find that specifically associates them with bisphosphoglycerate is [this one](https://link.springer.com/article/10.1007/PL00000585), but that doesn't directly present any experimental observations and cites an even older source that appears to be a book/textbook I cannot find any digital copies of. Also I'm not even sure what organism(s) it's talking about in that context. Many people seem to cite this paper when they say that ACYP1 and ACYP2 participate in glycolysis in humans and/or mice.

**Comment by haowang-bioinfo** [comment]
fixed in #596
