### ISSUE TITLE
Duplicate Carbonic Anhydrase Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#589]
## Background Information:

These are all the reactions that represent the carbonic anhydrase reaction currently in Human-GEM:

ID | reaction | Description
---|---|---
MAR03955 | CO2 [c] + H2O [c] ⇒ H+ [c] + HCO3- [c] | one-step cytosolic version
MAR05406 | CO2 [c] + H2O [c] ⇔ carbonate [c] | first step of two-step cytosolic version
MAR08749 | H+ [c] + HCO3- [c] ⇔ carbonate [c] | second step of two-step cytosolic version
MAR03956 | CO2 [m] + H2O [m] ⇒ H+ [m] + HCO3- [m] | one-step mitochondrial version
MAR08751 | CO2 [m] + H2O [m] ⇔ carbonate [m] | first step of two-step mitochondrial version
MAR08750 | H+ [m] + HCO3- [m] ⇔ carbonate [m] | second step of two-step mitochondrial version
MAR05407 | CO2 [e] + H2O [e] ⇔ carbonate [e] | first step of two-step extracellular version
MAR05409 | carbonate [e] ⇒ H+ [e] + HCO3- [e] | second step of two-step extracellular version

## Problems:
- The one- and two-step versions of this reaction in the cytosol and mitochondria enable arbitrarily large loop fluxes
- All of these reactions should be reversible; even if the enzymes didn't catalyze both directions (which they do), this reaction occurs spontaneously at an appreciable rate in both directions

## Proposed Changes:
I personally would remove the two-step versions and keep the one-step versions, because they just seem unnecessary complicated; the only other reaction that carbonate (`MAM01421e/c/m`) participates in is its exchange reaction, `MAR13066`), so it's not really adding anything of value to the model. But I recognize that you might want to keep the two-step versions and drop the one-step versions, so I have outlined both options:

### Keep the one-step versions:
- [x] Remove `MAR05406` and `MAR08749` for being redundant with `MAR03955`
- [x] Remove `MAR08751` and `MAR08750` for being redundant with `MAR03956`
- [x] Make `MAR03955` and `MAR03956` reversible
- [x] Remove either `MAR05407` or `MAR05409` (one of the two extracellular reactions)
- [x] Edit either `MAR05407` or `MAR05409` (whichever wasn't removed) to be `MAM01596e + MAM02040e <-> MAM02039e + MAM02046e` so that all compartments accomplish this reaction in a single step
- [x] Remove `MAR13066` (carbonate exchange reaction)
- [x] Remove `MAM01421e`, `MAM01421c`, and `MAM01421m` (carbonate)

~###Keep the two-step versions:~
~- [ ] Remove `MAR03955` for being redundant with `MAR05406`+`MAR08749`~
~- [ ] Remove `MAR03956` for being redundant with `MAR08751`+`MAR08750`~
~- [ ] Make `MAR05409` reversible~

**Comment by haowang-bioinfo** [comment]
A direct impression is this is too large, please consider to break it down to manageable size

**Comment by Devlin-Moyer** [comment]
How would you split it? Compartment-specific GPRs in one issue and resolving the one-step vs two-step duplicates in another?

**Comment by haowang-bioinfo** [comment]
> How would you split it? Compartment-specific GPRs in one issue and resolving the one-step vs two-step duplicates in another?

actually I don't know, which way do you prefer?

if you hope to keep it in one piece, please rebuttal

**Comment by Devlin-Moyer** [comment]
I'll split it into three separate issues once I get to work (in ~1 hour)

**Comment by haowang-bioinfo** [comment]
thanks - take your time :-)

**Comment by Devlin-Moyer** [comment]
So while I understand that reason for wanting to retain as many metabolites as possible in general, in the specific instance of retaining the "carbonate" metabolite, I don't think that's reasonable. In any system with both CO<sub>2</sub> and water, there is a constant equilibrium between these reactions, which all happen spontaneously and rapidly equilibrate at the temperatures and pressures living cells typically find themselves in:
CO<sub>2</sub> + H<sub>2</sub>O <-> H<sub>2</sub>CO<sub>3</sub>
H<sub>2</sub>CO<sub>3</sub> <-> H<sup>+</sup> + HCO<sub>3</sub><sup>-</sup>
HCO<sub>3</sub><sup>-</sup> <-> H<sup>+</sup> + CO<sub>3</sub><sup>-2</sup>
It is extremely difficult to _separately_ measure the abundances of H<sub>2</sub>CO<sub>3</sub>, HCO<sub>3</sub><sup>-</sup>, and CO<sub>3</sub><sup>-2</sup>, and those measurements require entirely different experimental setups than those typically used in metabolomics experiments ([source](https://link.springer.com/article/10.1007/s10953-013-0094-7)). As far as I know, metabolomics datasets will either not report abundances for any of these compounds, or do something like [this paper](https://www.mdpi.com/2218-1989/3/2/243) where they estimate an approximate lower bound on the total amount of dissolved CO<sub>2</sub>, i.e. the sum of the abundances of H<sub>2</sub>CO<sub>3</sub>, HCO<sub>3</sub><sup>-</sup>, and CO<sub>3</sub><sup>-2</sup>
So as I said before, I don't think including the "carbonate" metabolites (which I put in quotes because those metabolite objects represent H<sub>2</sub>CO<sub>3</sub>, which is carbonic acid -- carbonate refers to CO<sub>3</sub><sup>-2</sup>) adds anything to the models

**Comment by feiranl** [comment]
It would be better for us to agree on general rule about how to deal with this kind of cases of lumped rxns. If that is agreed to keep as many mets as possible, then even the specific case is a little bit different, I would suggest follow the rule. 
However, I totally agree with your comments in this specific case of carbonate. So if @haowang-bioinfo  also votes removing carbonate, I am also ok with that :)

**Comment by haowang-bioinfo** [comment]
agree to remove carbonate - one-step versions are always preferred if possible (Occam's razor principle)

**Comment by JonathanRob** [comment]
I wouldn't necessarily say that a one-step reaction should always be preferred over a multi-step formulation. In some cases, it can be useful to explicitly show individual reaction steps, especially if those steps are catalyzed by different enzymes and/or the intermediate metabolite(s) are used in other reactions. 

However, in this case I agree with all of you that keeping carbonate as an intermediate in these reactions is not so useful, and if anything just causes problems with loops and a larger-than-necessary model.

Keep up the good work @Devlin-Moyer, @haowang-bioinfo, and @feiranl!

**Comment by haowang-bioinfo** [comment]
@JonathanRob good points

So the reasons for keeping multi-step formulation are:
- those steps are catalyzed by different enzymes
- the intermediate metabolite(s) are used in other reactions

**Comment by feiranl** [comment]
> @JonathanRob good points
> 
> So the reasons for keeping multi-step formulation are:
> 
> * those steps are catalyzed by different enzymes/subunits
> * the intermediate metabolite(s) are used in other reactions

@haowang-bioinfo  
and I would suggest also keep if those intermediate metabolites are detected as metabolites in[ human metabolome data](https://hmdb.ca/metabolites).

**Comment by haowang-bioinfo** [comment]
> I would suggest also keep if those intermediate metabolites are detected as metabolites in[ human metabolome data](https://hmdb.ca/metabolites).

good point

**Comment by haowang-bioinfo** [comment]
just wonder if reaction `MAR05407: CO2 [e] + H2O [e] <=> H+ [e] + HCO3- [e]` is needed, how about just remove it?

**Comment by haowang-bioinfo** [comment]
fixed in #601
