### ISSUE TITLE
GPR for MAR08664

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#590]
`MAR08664: (3S)-citramalyl-CoA [m] ⇔ H2O [m] + itaconyl-CoA [m]` currently has no genes associated with it.
According to [Uniprot](https://www.uniprot.org/uniprotkb/Q13825/entry) and [this paper](https://www.cell.com/cell/fulltext/S0092-8674(17)31182-0?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867417311820%3Fshowall%3Dtrue) (4th paragraph of discussion), AUH (`ENSG00000148090`, already in Human-GEM) catalyzes it.

**Comment by feiranl** [comment]
Good point! Please go ahead make the change and add the paper as the reference of this rxn.

**Comment by haowang-bioinfo** [comment]
based on above paper, should this reaction be in the irreversible direction of hydrolysis?

**Comment by Devlin-Moyer** [comment]
Yep I hadn't noticed that before; I can make that happen (and also switch the products and reactants around so it isn't constrained to only have negative fluxes)

**Comment by haowang-bioinfo** [comment]
> Yep I hadn't noticed that before; I can make that happen (and also switch the products and reactants around so it isn't constrained to only have negative fluxes)

thanks

**Comment by haowang-bioinfo** [comment]
fixed in #591
