### ISSUE TITLE
Problems With Acetyl-CoA Carboxylase Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#593]
## Background Info:
These are all of the reactions that currently represent the acetyl-CoA carboxylase reaction in Human-GEM:

ID | reaction | GPR | notes
---|---|---|---
`MAR04156` | ATP [c] + HCO3- [c] + acetyl-CoA [c] ⇒ ADP [c] + H+ [c] + Pi [c] + malonyl-CoA [c] | ACACA or ACACB | one-step cytosolic version
`MAR07672` | ATP [c] + HCO3- [c] + apoC-lys_btn [c] ⇒ ADP [c] + H+ [c] + Pi [c] + carboxybiotin-carboxyl-carrier [c] | ACACA or ACACB | first step of two-step cytosolic version
`MAR07673` | acetyl-CoA [c] + carboxybiotin-carboxyl-carrier [c] ⇒ apoC-lys_btn [c] + malonyl-CoA [c] | ACACA or ACACB | second step of two-step cytosolic version
`MAR04295` | ATP [m] + HCO3- [m] + acetyl-CoA [m] ⇒ ADP [m] + H+ [m] + Pi [m] + malonyl-CoA [m] | ACACB | one-step mitochondrial version

A pathway for recycling apoC-lys_btn (MAM01357c/m) is present in both the cytosol and the mitochondria (first ID is the cytosolic version, second is the miochondrial version):
`MAR07669`/`MAR00073`: [apocarboxlase] + lysine ⇒ H+ + H2O + apoC-lys GPR: none
`MAR07670`/`MAR00092`: apoC-lys + biotinyl-5-AMP ⇒ AMP + H+ + apoC-lys_btn GPR: HLCS
`MAR07671`/`MAR00074`: H2O + apoC-lys_btn ⇒ [apocarboxlase] + biocytin GPR: none

There is also an exchange reaction (`MAR09202`) and a cytosol <-> extracellular transport reaction (`MAR07660`) but not a cytosol <-> mitochondria transport reaction for apoC-lys (`MAM01356`)

## Problems:
- ACACB (`ENSG00000076555`) is mitochondrial ([Uniprot](https://www.uniprot.org/uniprotkb/O00763/entry)), but ACACB shows up in the GPR of the non-mitochondrial versions of the reaction
- `MAR04156` duplicates the combined activity of `MAR07672`+`MAR07673`
- Inconsistent level of detail between compartments (one step in mitochondria, one and two steps in cytosol)
- Some of these reactions are in the "Biotin metabolism" subsystem, and others are in "Fatty acid biosynthesis (even-chain)", and it seems like they should probably all be in "Fatty acid biosynthesis (even-chain)"
- The names of `MAM00185c` and `MAM00185m` are misspelled: they should both be "[apocarboxylase]" and not "[apocarboxlase]"
- No net production of `MAM00185m` is possible -- if there were a cytosol <-> mitochondria transport reaction, it would be connected to the apoC-lys exchange reaction

## Proposed Changes:
- [x] Change the names of `MAM00185c` and `MAM00185m` to "[apocarboxylase]"
- [x] Remove ACACB (`ENSG00000076555`) from GPRs of `MAR07672` and `MAR07673`
- [x] Change the subsystems of `MAR07672` and `MAR07673` to "Fatty acid biosynthesis (even-chain)"
- [x] Remove `MAR04156` for being redundant with `MAR07672`+`MAR07673`
- [x] Create new metabolite `MAM01422m` (mitochondrial carboxybiotin-carboxyl-carrier)
- [x] Change `MAR04295` to `MAM01261m + MAM01422m -> MAM01357m + MAM02444m` (mitochondrial version of `MAR07673`)
- [x] Create new reaction `MAM01371m + MAM02046m + MAM01357m -> MAM01285m + MAM02039m + MAM02751m` (mitochondrial version of `MAR07672`
- [x] Add new reaction `MAM00185c <-> MAM00185m` (cytosol to mitochondria transport of [apocarboxylase])

**Comment by haowang-bioinfo** [comment]
this issue is clear, comprehensive, and scientifically beautiful - a classic one!

a minor issue: if there is any evidence supporting the transport reaction of [apocarboxylase] between cytosol to mitochondria?

**Comment by Devlin-Moyer** [comment]
I'd say yes, in the sense that one of the two actual proteins (ACACA and ACACB) that the [apocaboxylase] "metabolite" represents is a mitochondrial protein (according to Uniprot), so it is presumably translated in the cytosol and then transported into the mitochondria before folding, like most other mitochondrial proteins.
Another option would be to create a new metabolite so there can be two separate "metabolites", one for ACACA and one for ACACB, so that only the ACACB "metabolite" could be transported into the mitochondria. At that point, rather than trying to connect them to exchange reactions, it might make sense create two new "translation" reactions that produce them from charged tRNAs (like MAR05171), but that'd be noticeably more work.

**Comment by Devlin-Moyer** [comment]
It makes sense to not include a transport reaction for [apocarboxylase] and say that the mitochondrial version is ACACB and the cytosolic one is ACACA; I suggested the addition of a "translation" reaction for it because I'd previously come across some of the 25 reactions in [the "Protein assembly" subsystem](https://metabolicatlas.org/explore/Human-GEM/gem-browser/subsystem/protein_assembly), and at least some of those produce apoenzymes that are then attached to cofactors, e.g. `MAR05171` produces `MAM01358c` (apocytochrome-C), which can be transported into the mitochondria (`MAR05227`) and combined with heme (`MAM02049m`) to produce `MAM01631m` (cytochrome-C, the holoenzyme), so while it is clearly uncommon for enzymes to be represented by "metabolites" and the translation of those enzymes to be represented by "reactions", there is precedent in Human-GEM

**Comment by Devlin-Moyer** [comment]
Also this may be overly pedantic, but it _would_ make sense to have a transport reaction from the cytosolic compartment to the mitochondrial compartment for a "metabolite" that represented a protein that is known to be localized to the mitochondria: all mitochondrial proteins that are not encoded in the mitochondrial genome (which is 99% of all mitochondrial proteins, including ACACB, which is [on chromosome 12](https://useast.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000076555;r=12:109116587-109268226)) are translated on cytosolic ribosomes and then imported into mitochondria as fully-synthesized (but usually not yet folded) proteins ([source](https://www.nature.com/articles/nrm2959)).

**Comment by Devlin-Moyer** [comment]
Oh I just noticed your (@haowang-bioinfo) suggestion of removing the [apocarboxylase] metabolites entirely; we could do that, but that would wind up being a bit more involved than it seems like it should be:
Removing all reactions that involve either [apocarboxylase] metabolite would remove MAR07669, MAR00073, MAR07671 and MAR00074, which would make flux through MAR00092 impossible by removing the only source of mitochondrial apoC-lys. MAR07670 would be fine, because cytosolic apoC-lys would still be available via MAR9202+MAR07660, but then it would _only_ be capable of sustaining flux if uptake of apoC-lys was allowed (i.e. lower bound of MAR09202 <0). 

I personally usually make sure the only metabolites that can be produced via exchange reactions are ones known to be present in the culture media of the cells I'm modeling, so I would have blocked uptake of apoC-lys and probably not expected that to block flux through the acetyl-CoA carboxylase reaction.

so anyway, we _can_ drop the [apocarboxylase] metabolites altogether, but if we do, I think we should keep MAR04156 and remove MAR07672 and MAR07673 (i.e. the opposite of what I initially proposed and you approved) as well all of the other reactions that involve apoC-lys (MAM01356) and/or apoC-lys_btn (MAM01357), i.e. MAR07669, MAR00073, MAR07671, MAR00074, MAR00092, MAR07670, MAR07660, and MAR9202.

**Comment by JonathanRob** [comment]
Thanks for the suggested changes @Devlin-Moyer. I think this could be fixed using a few of your suggested alternatives, however I'm leaning toward the suggestion in the original list - to implement a cytosol to mitochondria transport of [apocarboxylase]. It seems reasonable and is one of the more simple solutions.

Just to make sure I understand, the metabolites apoC-lys_btn and carboxybiotin-carboxyl-carrier are both intermediates in the 2-step reaction, and therefore do not need to be produced/consumed anywhere else for the reaction to carry flux, correct? Further, the net outcome of the three-reaction apoC-lys_btn recycling pathway you show is a consumption of lysine and biotinyl-5-AMP to produce biocytin, so again apoC-lys_btn and [apocarboxylase] are intermediates that have no net consumption/production. So then I'm curious why there is a need to ensure that net production of these intermediates is possible in the model?

**Comment by haowang-bioinfo** [comment]
> the metabolites apoC-lys_btn and carboxybiotin-carboxyl-carrier are both intermediates in the 2-step reaction, and therefore do not need to be produced/consumed anywhere else for the reaction to carry flux, correct? 

only apoC-lys_btn need to be produced elsewhere to enable the 2-step reactions MAR07672+MAR07673

> the net outcome of the three-reaction apoC-lys_btn recycling pathway you show is a consumption of lysine and biotinyl-5-AMP to produce biocytin, so again apoC-lys_btn and [apocarboxylase] are intermediates that have no net consumption/production. So then I'm curious why there is a need to ensure that net production of these intermediates is possible in the model?

are you suggesting the one-step versions?

**Comment by JonathanRob** [comment]
> only apoC-lys_btn need to be produced elsewhere to enable the 2-step reactions MAR07672+MAR07673

Does it? The two reactions are:

MAR07672: ATP [c] + HCO3- [c] + apoC-lys_btn [c] ⇒ ADP [c] + H+ [c] + Pi [c] + carboxybiotin-carboxyl-carrier [c]
MAR07673: acetyl-CoA [c] + carboxybiotin-carboxyl-carrier [c] ⇒ apoC-lys_btn [c] + malonyl-CoA [c]

The net stoichiometry becomes:

ATP [c] + HCO3- [c] + acetyl-CoA [c] => ADP [c] + H+ [c] + Pi [c] + malonyl-CoA [c]

because every mol of apoC-lys_btn [c] produced by MAR07673 is consumed by MAR07672, and vice versa for carboxybiotin-carboxyl-carrier [c]; i.e., these metabolites are intermediates (no net consumption or production) of the reaction pair.


> are you suggesting the simplified one-step versions?

No, I'm in favor of the two-step, I just don't quite understand the need to ensure that intermediate metabolites can be produced/consumed by other reactions.

**Comment by haowang-bioinfo** [comment]
> The net stoichiometry becomes:
ATP [c] + HCO3- [c] + acetyl-CoA [c] => ADP [c] + H+ [c] + Pi [c] + malonyl-CoA [c]
because every mol of apoC-lys_btn [c] produced by MAR07673 is consumed by MAR07672, and vice versa for carboxybiotin-carboxyl-carrier [c]; i.e., these metabolites are intermediates (no net consumption or production) of the reaction pair.

yes, the net stoichiometry of MAR07672+MAR07673 cross out metabolites apoC-lys_btn and carboxybiotin-carboxyl-carrier which become in zero contribution.

in parallel, apoC-lys_btn is the product of MAR07669+MAR07670 in cytosol, or MAR00073+MAR00092 in mitochondrion, catalyzed by Holocarboxylase synthetase (HLCS).

**Comment by Devlin-Moyer** [comment]
I don't know that it's _necessary_ to ensure that net production of all intermediates is possible, but it is clearly the case that real cells are capable of net production of all metabolites or they wouldn't have any to recycle in the first place. Also I personally have recently been experimenting with using [limed-FBA](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003126), which requires net production of all metabolites in a model as a way to mitigate (and sometimes eliminate) the problem of unbounded loop fluxes. (For a more thorough explanation of the reasons why it's helpful to constrain models in this way, see the [MD-FBA](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-4-r43) paper, which seems to have been the predecessor to/inspiration for limed-FBA). So it would be convenient for my project in particular if Human-GEM could sustain net production of as many metabolites as possible, and there seem to be some decently compelling arguments that it would generally enable Human-GEM to be used to make more realistic predictions. But I get if you don't want to go to that effort, because this is far from the only case where some intermediates can only be recycled and never synthesized _de novo_ (I’ve also noticed that ferro/ferricytochrome C and lipoamide have no biosynthesis pathways in Human-GEM), so it would be a lot of work.

**Comment by JonathanRob** [comment]
I think it's fine to add reactions to ensure the ability to net produce metabolites, since as you say @Devlin-Moyer, real cells must be able to do so.

My comment was more so just to make sure I understood the reasoning, and that I wasn't missing anything. But I certainly support adding functionality to the model in cases like this where it is more representative of reality (as long as it isn't excessively large or complex).

**Comment by haowang-bioinfo** [comment]
fixed in #624
