### ISSUE TITLE
Curation of reactions: balancing elements

### ISSUE THREAD

**Issue by pinarkocabas** [SysBioChalmers/Human-GEM#60]
### Description of the issue: 
Four HMR reactions were detected to have incorrect reactants based on gene-reaction relation, databases and therefore they were corrected with reaction data in MetaNetX, Brenda. These reactions are  HMR_8615, HMR_6397, HMR_1296, HMR_1689. 
#### Expected feature/value/output:
HMR_8615 with MNXR131193: ATP[m] + cob(II)alamin[m] + H+[m] <=> adenosylcob(III)alamin[m] + triphosphate[m]
HMR_6397 with MNXR100066:  1 (R)-dihydrolipoamide + 1 NAD(+) <=> 1 H(+) + 1 NADH + 1 (R)-lipoamide
HMR_1296 with MNXR103981:  1 CoA-18-COOH-16E-dinor-LTE5 + 1 H2O2 = 1 O2 + 1 CoA-omega-COOH-dinor-LTE4 
HMR_1689 with MNXR109129:  1 5beta-cholestane-3alpha,7alpha,26-triol + 1 NAD(+) = 1 H(+) + 1 NADH + 1 3alpha,7alpha-dihydroxy-5beta-cholestan-26-al 

**I hereby confirm that I have:**
- [x] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by JonathanRob** [comment]
This issue was addressed in the recent PR #131.
