### ISSUE TITLE
Electron Transport Flavoprotein

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#608]
**Note**: significantly edited after discovering that the Metabolic Atlas website showed an older version of `MAR06911` with a different GPR

## Background

`MAR000562` and `MAR00563` are redox reactions between Electron Transport Flavoprotein and FAD. The GPR of `MAR00562` is `ETFA or ETFB`, and the GPR of `MAR00563` is `ETFDH`.

Before #489, the GPR of `MAR06911` (redox between FAD and ubiquinone) was `ETFA or ETFB or ETFDH or SDHC`. That PR changed the GPR of `MAR06911` to `SDHA and SDHB and SDHC and SDHD`, with the justification (given in #486) that `MAR06911` represented the reaction catalyzed by Complex II/Succinate Dehydrogenase, and ETFA, ETFB, and ETFDH are not subunits of Complex II/SDH.

ETFA and ETFB encode the two subunits of the Electron Transport Flavoprotein heterodimer, which binds to a number of other mitochondrial FAD-dependent enzymes, transfers electrons from their FAD cofactors to its FAD cofactor, then binds to ETFDH in the mitochondrial membrane and passes those electrons onto ETFDH's FAD cofactor, which ETFDH uses to reduce ubiquinone to ubiquinol. ([source](https://doi.org/10.1016/j.gene.2021.145407), [source](https://www.pnas.org/doi/epdf/10.1073/pnas.0604567103)). Here's a diagram (from [this paper](https://febs.onlinelibrary.wiley.com/doi/full/10.1111/febs.16164)) that illustrates the situation (specifically the bottom center; Q/QH<sb>2</sub> is ubiquinone/ubiquinol):
![image](https://github.com/SysBioChalmers/Human-GEM/assets/33460176/7eb42c73-2e2f-4a64-b9cf-f91d2cf7eb1a)

## Problems

The Electron Transport Flavoprotein "metabolites", `MAM03573m` and `MAM03574m`, only appear in `MAR00562` and `MAR00563`, so they don't really represent the role of ETF in binding to other FAD-dependent enzymes and transfering electrons between their FAD cofactors. The enzymes that ETF interacts with (shown in the above diagram) collectively catalyze >100 reactions in Human-GEM, most of which involve FAD (i.e. `MAM01802m` and `MAM01803m`) and not `MAM03573m` and `MAM03574m`. I think changing all of those reactions to involve `MAM03573m` and `MAM03574m` instead of FAD would be worse than just returning ETFA, ETFB and ETFDH to the GPR of `MAR06911` and removing `MAR00562`, `MAR00563`, `MAM03573m` and `MAM03574m`.

I also think the Complex II/SDH subunits should be removed from the GPR of `MAR06911`, since, as discussed in #607, `MAR04652` and `MAR08743` also represent the reaction catalyzed by Complex II/SDH. The proposed changes in #607 would leave `MAR04652` as a single one-step reaction that represents the Complex II/SDH reaction, so leaving the Complex II/SDH subunits in `MAR06911` would make it a partial duplicate of `MAR04652`.

Also, as the above diagram shows, several other FAD-dependent enzymes (namely PRODH, PRODH2, GPD2, DHODH and CHDH) are capable of directly transfering electrons from their FAD/FMN cofactors to ubiquinone without the aid of ETFA/B and ETFDH, so I think they should be added to the GPR of `MAR06911`.

As a side note, the only enzyme that appears on that diagram that isn't already in Human-GEM is SQOR, which, according to [Uniprot](https://www.uniprot.org/uniprotkb/Q9Y6N5/entry), catalyzes reactions that are also not currently in Human-GEM (as far as I can tell), but I figure that discussing whether or not SQOR and any of its associated reactions should be added to Human-GEM can be a separate issue.

## Proposed Changes:
- [x] Remove `MAR00562` and `MAR00563` for being redundant with `MAR06911`
- [x] Remove `MAM03573m` and `MAM03574m`
- [x] Change the GPR of `MAR06911` to `ETFA or ETFB or ETFDH or PRODH or PRODH2 or GPD2 or DHODH or CHDH`, i.e. `ENSG00000140374 or ENSG00000105379 or ENSG00000171503 or ENSG00000100033 or ENSG00000250799 or ENSG00000115159 or ENSG00000102967 or ENSG00000016391`

**Comment by JonathanRob** [comment]
I agree completely - including a separate reaction for ETF redox is overkill, and can instead be captured by adding it to the GPR of the relevant reactions.

And I suppose it does make sense to add the relevant FADH-ubiquinone redox enzymes to the GPR of MAR06911.

**Comment by haowang-bioinfo** [comment]
fixed in #612
