### ISSUE TITLE
Suspected duplicated metabolites from Bigg

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#610]
#### Current behavior:
Suspected duplicated metabolites from Bigg:

|reference ID|met ID|Duplicate rxn pairs| Action for mets|Action for rxns| Comments|
|-----------------|-----------------|------------------------|---------------------------|----------------------|----------------------|
3hibutcoa|[MAM00785m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00785m) [MAM03226m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03226m)|([MAR00042](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00042) [MAR03755](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03755))|remove MAM03226m |remove MAR00042| ||
dmhptcoa|[MAM00563m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00563m) [MAM03553m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03553m)|No|~~replace MAM03553m to MAM00563m~~|No| ||
xolest2_hs|[MAM01451l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01451l) [MAM10004l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM10004l) [MAM01451r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01451r) [MAM10004r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM10004r)|([MAR10037](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10037) [MAR03537](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03537))([MAR10038](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10038) [MAR03622](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03622))|~~remove MAM10004l and MAM10004r~~|~~remove MAR03537 and MAR03622~~| ||
phyt|[MAM02746c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02746c) [MAM03884c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03884c) [MAM02746e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02746e) [MAM03884e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03884e) [MAM02746x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02746x) [MAM03884x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03884x)|([MAR00440](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00440) [MAR01617](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR01617))( [MAR03480](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03480)   [MAR00740](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00740))  ([MAR09037](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09037) [MAR00659](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00659) )([MAR03482](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03482)  [MAR05323](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05323))|remove MAM03884c and MAM03884e; replace MAM03884x to MAM02746x|remove MAR01617, MAR00740, MAR00659 and MAR05323| || 
dmnoncoa|[MAM00933c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00933c) [MAM03554c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03554c)|([MAR03517](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03517) [MAR01709](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR01709))|remove MAM03554c|remove MAR01709| ||
tag1p__D|[MAM01746c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01746c) [MAM03960c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03960c)| | change BiGG ID annotation for MAM01746c to [tag6p__D](http://bigg.ucsd.edu/universal/metabolites/tag6p__D) | |Not duplicates||
pristcoa|[MAM03887x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03887x) [MAM00078x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00078x)| | change BiGG ID annotation for MAM00078x to [CE5125](http://bigg.ucsd.edu/universal/metabolites/CE5125)| |Not duplicates||
galgluside_hs|[MAM02328c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02328c) [MAM03586c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03586c) [MAM02328g](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02328g) [MAM03586g](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03586g) [MAM02328l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02328l) [MAM03586l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03586l) [MAM02328e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02328e) [MAM03586e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03586e) [MAM02328r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02328r)| |change BiGG ID annotation for MAM02328 to [digalside_hs](http://bigg.ucsd.edu/universal/metabolites/digalside_hs) | |Not duplicates||
gm1_hs|[MAM02008c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02008c) [MAM03635c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03635c) [MAM02008g](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02008g) [MAM03635g](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03635g) [MAM02008l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02008l) [MAM03635l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03635l) [MAM02008e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02008e) [MAM03635e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03635e) [MAM03635n](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03635n)| | change BiGG ID annotation for MAM02008 to [HC02161](http://bigg.ucsd.edu/universal/metabolites/HC02161)| |Not duplicates||
  

- [x] remove mets `MAM03226m`, `MAM03884c`, `MAM03884e`, `MAM03554c`
- [x]  remove rxns `MAR00042`,`MAR01617`, `MAR00740`, `MAR00659`, `MAR05323`, `MAR01709`
- [x]  change BiGG ID annotations for `MAM01746c`, `MAM00078x`, `MAM02328c`, `MAM02328g`, `MAM02328l`, `MAM02328e`, `MAM02328r`, `MAM02008c`, `MAM02008g`, `MAM02008l`, `MAM02008e`
- [x]  replace mets 

|old ID|new ID| 
|-----------------|-----------------|
|~~MAM03553m~~| ~~MAM00563m~~|
|MAM03884x| MAM02746x|

**Comment by feiranl** [comment]
As for `dmhptcoa` they are not 100% same, one is the general form, the other one is isomer, and they should have different BiGG IDs. The  BiGG ID for [MAM03553m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03553m) should changed to [CE4798](http://bigg.ucsd.edu/universal/metabolites/CE4798). And I suggest we keep it for now, what do you think? @haowang-bioinfo   

As for the `xolest2_hs`, I am not sure where these coefficients come from, and how should we deal with the coefficient difference @JonathanRob

**Comment by haowang-bioinfo** [comment]
@JHL-452b good to know this, nice work!

> As for dmhptcoa they are not 100% same, one is the general form, the other one is isomer, and they should have different BiGG IDs. The BiGG ID for [MAM03553m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03553m) should changed to [CE4798](http://bigg.ucsd.edu/universal/metabolites/CE4798). And I suggest we keep it for now, what do you think? @haowang-bioinfo

they do appear to be the same compound, maybe in different chirality. agree to your proposal - only change BiGG id for now

**Comment by haowang-bioinfo** [comment]
if to remove MAR01709, how about move its GPR to that of MAR03517?

**Comment by JHL-452b** [comment]
> a few questions:
> 
> * if to remove MAR01709, how about move its GPR to that of MAR03517?
> * why should [digalside_hs](http://bigg.ucsd.edu/universal/metabolites/digalside_hs) be assigned to MAM02328?
> * why should [HC02161](http://bigg.ucsd.edu/universal/metabolites/HC02161) be assigned to MAM02008?

Thanks for your reply!
* the GPR of MAR01709 was annotated as ENSG00000116171 and it was already moved to MAR03517 in [PR](https://github.com/SysBioChalmers/Human-GEM/pull/646). As for other annotations have also been moved, such as EC, the direction of reaction, etc.
* The assignment of MAM02328 and MAM02008 were determined by mapping relationships with other databases. Such as 
[MAM02328 ](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02328c) links to MNXM269 in Human-GEM, and [MNXM269](https://www.metanetx.org/chem_info/MNXM269) links to digalside_hs in MetaNetX;
[MAM02008](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02008c) links to MNXM164818 in Human-GEM, and [MNXM164818](https://metabolicatlas.org/identifier/MetaNetX/MNXM164818) links to HC02161 in MetaNetX.

**Comment by haowang-bioinfo** [comment]
fixed in #646
