### ISSUE TITLE
Suspected duplicated metabolites from EHMN

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#616]
#### Current behavior:
Suspected duplicated metabolites from EHMN:

reference ID|met ID|affected rxns| Action for mets|Action for rxns|Comments|
|-----------------|-----------------|------------------------|---------------------------|----------------------|----------------------|
CE5122|[MAM02747c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02747c) [MAM03362c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03362c) [MAM02747x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02747x) [MAM03362x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03362x) |~~No~~|~~replace MAM03362c to MAM02747c; replace MAM03362x to MAM02747x~~|~~No~~|chiral metabolites, keep it for now
CE4824|[MAM00134r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00134r) [MAM03353r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03353r)|~~No~~|~~replace MAM03353r to MAM00134r~~|~~No~~|chiral metabolites, keep it for now
CE4837|[MAM00131c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00131c) [MAM03354c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03354c) [MAM00131r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00131r) [MAM03354r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03354r)|([MAR02401](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02401) [MAR03441](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03441))|remove MAM03354c; replace MAM03354r to MAM00131r|remove MAR03441|Yes, and also combine all cross reference annotations for mets and rxns
CE7090|[MAM00028c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00028c) [MAM00029c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00029c)|([MAR02586](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02586) [MAR02588](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02588))|replace MAM00029c to MAM00028c|remove MAR02588|yes
CE2516|[MAM01696c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01696c) [MAM03332c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03332c) [MAM01696e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01696e) [MAM03332e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03332e)|([MAR00407](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00407) [MAR10164](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10164)) ([MAR00576](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00576) [MAR10433](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10433))|remove MAM03332c and MAM03332e|remove MAR10164 and MAR10433|yes
CE5123|[MAM00655x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00655x) [MAM03363x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03363x)|([MAR03484](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03484) [MAR03384](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03384)) ([MAR03486](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03486) [MAR03385](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03385))|~~remove MAM03363x~~|~~remove MAR03384 and MAR03385~~|chiral metabolites, keep it for now
CE5169|[MAM00748m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00748m) [MAM03368m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03368m) [MAM00748x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00748x) [MAM03368x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03368x)|No|replace MAM03368m to  MAM00748m; replace MAM03368x to MAM00748x|No|Yes
CE5168|[MAM00036m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00036m) [MAM03367m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03367m) [MAM00036x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00036x) [MAM03367x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03367x)|([MAR01644](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR01644) [MAR03754](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03754)) ([MAR01642](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR01642) [MAR03756](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03756)) |~~replace MAM03367m to MAM00036m; replace MAM03367x to MAM00036x~~|~~remove MAR03754 and MAR03756~~|Not the same according to SMILES check, keep it for now
CE5160|[MAM00893m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00893m) [MAM00893x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00893x) [MAM03364c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03364c) [MAM03364r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03364r)|~~No~~ |~~replace MAM03364c to MAM00893c; replace MAM03364r to MAM00893r~~|~~No~~ |Not the same according to SMILES check, keep it for now|
CE4820|[MAM00853x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00853x) [MAM00902c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00902c) [MAM00853r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00853r)|No | replace MAM00902c to MAM00853c|No |Yes |
CE2084|[MAM01123c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01123c) [MAM01126c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01126c) [MAM01123m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01123m) [MAM01123x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01123x) [MAM01126m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01126m) [MAM01126x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01126x)| | change EHMN ID annotation for MAM01123c, MAM01123m and MAM01123x to  CE7097| |No duplicates

- [ ] remove mets  `MAM03354c`, `MAM03332c`, `MAM03332e`
- [ ]  remove rxns `MAR03441`, `MAR02588`, `MAR10164`, `MAR10433 `
- [ ] change EHMN ID annotations for `MAM01123c`, `MAM01123m`, `MAM01123x`
- [ ]  replace mets 

|old ID|new ID| 
|-----------------|-----------------|
|MAM03354r| MAM00131r|
|MAM00029c| MAM00028c|
|MAM03368m| MAM00748m|
|MAM03368x| MAM00748x|
|MAM00902c |MAM00853c |

**Comment by feiranl** [comment]
Please go ahead and make the corresponding changes.

**Comment by haowang-bioinfo** [comment]
fixed in #649
