### ISSUE TITLE
Suspected duplicated metabolites from PubChem

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#622]
#### Current behavior:
Suspected duplicated metabolites from PubChem:

reference ID|met ID|affected rxns| Action for mets|Action for rxns|Comments|
|-----------------|-----------------|------------------------|---------------------------|----------------------|----------------------|
|53477830|[MAM02640c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02640c) [MAM03790c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03790c) [MAM02640m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02640m) [MAM03790m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03790m)|~~No~~|~~replace MAM03790c to MAM02640c; replace MAM03790m to MAM02640m~~|~~No~~| chiral metabolites, keep it for now|
|53477846|[MAM00131c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00131c) [MAM03354c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03354c) [MAM00131r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00131r) [MAM03354r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03354r)|([MAR02401](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02401) [MAR03441](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03441))|~~remove MAM03354c; replace MAM03354r to MAM00131r~~|~~remove MAR03441~~| same as [EHMN: CE4837](https://github.com/SysBioChalmers/Human-GEM/issues/617)|
|26840|[MAM02746c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02746c) [MAM03884c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03884c) [MAM02746e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02746e) [MAM03884e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03884e) [MAM02746x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02746x) [MAM03884x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03884x)|([MAR00440](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00440) [MAR01617](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR01617)) ([MAR03480](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03480) [MAR00740](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00740)) ([MAR09037](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09037) [MAR00659](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00659)) ([MAR03482](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03482) [MAR05323](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05323))|~~remove MAM03884c and MAM03884e; replace MAM03884x to MAM02746x~~|~~remove MAR01617, MAR00740, MAR00659 and MAR05323~~| same as [Bigg: phyt](https://github.com/SysBioChalmers/Human-GEM/issues/610)|
|22833562|[MAM00678c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00678c) [MAM03543c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03543c)|~~No~~|~~replace MAM03543c to MAM00678c~~|~~No~~| suspect chiral metabolites, keep it for now|
|22833583|[MAM02443c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02443c) [MAM03494c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03494c)|[MAR02599](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02599) [MAR05434](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05434)|~~replace MAM03494c to MAM02443c~~|~~remove MAR05434~~| chiral metabolites, keep it for now|
|168381|[MAM01729c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01729c) [MAM03540c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03540c) [MAM03540e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03540e)|([MAR02602](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02602) [MAR04506](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04506))|replace MAM03540c to MAM01729c; replace MAM03540e to MAM01729e|remove MAR04506| |
|563|[MAM00684c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00684c) [MAM03325c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03325c)|~~No~~|~~replace MAM03325c to MAM00684c~~|~~No~~| same as [HMDB: HMDB0001527](https://github.com/SysBioChalmers/Human-GEM/issues/617)|
|5312983|[MAM00307c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00307c) [MAM00324c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00324c) [MAM00307r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00307r) [MAM00324r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00324r)|~~No~~|~~replace MAM00324c to MAM00307c; replace MAM00324r to MAM00307r~~|~~No~~| suspect chiral metabolites, keep it for now|
|16061126|[MAM00028c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00028c) [MAM00029c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00029c)|~~No~~|~~replace MAM00029c to MAM00028c~~|~~No~~| same as [EHMN: CE7090](https://github.com/SysBioChalmers/Human-GEM/issues/616)|
|5280581|[MAM01696c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01696c) [MAM03332c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03332c) [MAM01696e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01696e) [MAM03332e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03332e)|([MAR00407](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00407) [MAR10164](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10164)) ([MAR00576](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00576) [MAR10433](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10433))|~~remove MAM03332c and MAM03332e~~|~~remove MAR10164 and MAR10433~~| same as [EHMN: CE2516](https://github.com/SysBioChalmers/Human-GEM/issues/616)|
|5280771|[MAM03203m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03203m) [MAM03967m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03967m)|([MAR05075](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05075) [MAR06418](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06418)) ([MAR05123](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05123) [MAR06437](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06437))|~~remove MAM03967m~~|~~remove MAR06418 and MAR06437~~| suspect chiral metabolites, keep it for now|
|5281877|[MAM00353c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00353c) [MAM02836c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02836c) [MAM00353e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00353e) [MAM02836e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02836e) [MAM00353r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00353r) [MAM02836r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02836r)|([MAR08718](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08718) [MAR08714](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08714)) ([MAR09210](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09210) [MAR09405](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09405)) ([MAR08717](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08717) [MAR08713](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08713)) ([MAR08719](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08719) [MAR08715](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08715))|~~remove MAM02836c, MAM02836e and MAM02836r~~|~~remove MAR08714, MAR09405, MAR08713 and MAR08715~~| same as [HMDB: HMDB0003141](https://github.com/SysBioChalmers/Human-GEM/issues/617)|
|5283078|[MAM02789c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02789c) [MAM01221c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01221c)|~~No~~|~~replace MAM01221c to MAM02789c~~|~~No~~| suspect chiral metabolites, keep it for now|
|10133|[MAM01435c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01435c) [MAM03318c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03318c) [MAM01435e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01435e) [MAM03318e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03318e) [MAM01435r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01435r) [MAM03318r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03318r)|~~No~~|~~replace MAM03318c to MAM01435c; replace MAM03318e to MAM01435e; replace MAM03318r to MAM01435r~~|~~No~~| same as [HMDB: HMDB0000518](https://github.com/SysBioChalmers/Human-GEM/issues/617)|
|536537|[MAM01057c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01057c) [MAM03346c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03346c)|([MAR06685](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06685) [MAR03031](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03031))|~~remove MAM03346c~~|~~remove MAR03031~~| suspect chiral metabolites, keep it for now|
|440690|[MAM00748m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00748m) [MAM03368m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03368m) [MAM00748x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00748x) [MAM03368x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03368x)|~~No~~|~~replace MAM03368m to MAM00748m; replace MAM03368x to MAM00748x~~|~~No~~| same as [EHMN: CE5169](https://github.com/SysBioChalmers/Human-GEM/issues/616)|
|6438629|[MAM00993c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00993c) [MAM01006c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01006c) [MAM00993r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00993r)|([MAR06702](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06702) [MAR08700](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08700))|~~replace MAM00993c to MAM01006c; replace MAM00993r to MAM01006r~~|~~remove MAR06700~~| same as [HMDB: HMDB0006254](https://github.com/SysBioChalmers/Human-GEM/issues/617)|
|21252281|[MAM01576m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01576m) [MAM01576x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01576x) [MAM03978m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03978m) [MAM03978x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03978x) [MAM04041m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM04041m)|~~No~~|~~replace MAM03978m to MAM01576m; replace MAM03978x to MAM01576x; replace MAM04041m to MAM01576m~~|~~No~~| suspect chiral metabolites, keep it for now|
|638015|[MAM01230c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01230c) [MAM02832c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02832c)| |change PubChem ID annotation for MAM01230c to [6436082](https://pubchem.ncbi.nlm.nih.gov/compound/6436082)| |No duplicates|
|6610221|[MAM01201m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01201m) [MAM01206m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01206m)| | | |No duplicates|
|11953816|[MAM02411c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02411c) [MAM02676c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02676c) [MAM02411m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02411m) [MAM02676m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02676m) [MAM02411r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02411r) [MAM02676r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02676r) [MAM02411e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02411e) [MAM02676e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02676e) [MAM02411x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02411x)| |change PubChem ID annotation for MAM02676 to [129849228](https://pubchem.ncbi.nlm.nih.gov/compound/129849228)| |No duplicates|
|193321|[MAM01090c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01090c) [MAM01090m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01090m) [MAM01092c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01092c) [MAM01092m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01092m)| | | | No duplicates|
|5280355|[MAM02647x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02647x) [MAM03789x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03789x)| |change PubChem ID annotation for MAM02647x to [5497111](https://pubchem.ncbi.nlm.nih.gov/compound/5497111)| |No duplicates|
|53480665|[MAM03021m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03021m) [MAM02698m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02698m) [MAM03021x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03021x) [MAM02698x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02698x)| |change PubChem ID annotation for MAM03021 to [5280770](https://pubchem.ncbi.nlm.nih.gov/compound/5280770)| | No duplicates|
|735|[MAM03026c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03026c) [MAM03590c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03590c)| | | | No duplicates |
|890|[MAM00531c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00531c) [MAM00531n](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00531n) [MAM02492c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02492c) [MAM02492n](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02492n)| |change PubChem ID annotation for MAM00531 to [96024277](https://pubchem.ncbi.nlm.nih.gov/substance/96024277)| |No duplicates|
|169691|[MAM02118c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02118c) [MAM02118l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02118l) [MAM02118m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02118m) [MAM02118e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02118e) [MAM02119c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02119c) [MAM02119l](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02119l) [MAM02119m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02119m) [MAM02119e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02119e)| | | |No duplicates|
|15667|[MAM02678c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02678c) [MAM02678m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02678m) [MAM02678x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02678x) [MAM02678r](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02678r) [MAM02679e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02679e)| |change PubChem ID annotation for MAM02678 to [644109](https://pubchem.ncbi.nlm.nih.gov/compound/644109); change PubChem ID annotation for MAM02679e to [439322](https://pubchem.ncbi.nlm.nih.gov/compound/439322)| |No duplicates|

- [ ]  remove rxns `MAR04506`
- [ ] change PubChem ID annotations for `MAM01230c`, `MAM02676c`, `MAM02676m`, `MAM02676r`, `MAM02676e`, `MAM02647x`, `MAM03021m`, `MAM03021x`, `MAM00531c`, `MAM00531n`, `MAM02678c`, `MAM02678m`, `MAM02678x`, `MAM02678r`, `MAM02679e`
- [ ]  replace mets 

|old ID|new ID| 
|-----------------|-----------------|
|MAM03540c| MAM01729c|
|MAM03540e| MAM01729e|

**Comment by haowang-bioinfo** [comment]
good job @JHL-452b

**Comment by feiranl** [comment]
Good to go!

**Comment by haowang-bioinfo** [comment]
fixed in #662
