### ISSUE TITLE
Suspected duplicated reactions

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/Human-GEM#630]
Reaction|Equation|GPR
-- | ------------------- | --
MAR04521 | glucose-6-phosphate[er] + H2O[er] -> glucose[er] + Pi[er] | ENSG00000131482 or ENSG00000141349 or ENSG00000152254
MAR20020 | glucose-6-phosphate[er] + H2O[er] -> glucose[er] + Pi[er] | ENSG00000131482 or ENSG00000141349
MAR06981 | 4-trimethylammoniobutanal[c] + H2O[c] + NAD+[c] -> gamma-butyrobetaine[c] + 2 H+[c] + NADH[c] | ENSG00000143149
MAR20014 | 4-trimethylammoniobutanal[c] + H2O[c] + NAD+[c] -> gamma-butyrobetaine[c] + 2 H+[c] + NADH[c] | ENSG00000143149
MAR04689 | 4-aminobutanal[c] + H2O[c] + NAD+[c] -> 4-aminobutyrate[c] + 2 H+[c] + NADH[c] | ENSG00000143149
MAR20015 | 4-aminobutanal[c] + H2O[c] + NAD+[c] -> 4-aminobutyrate[c] + 2 H+[c] + NADH[c] | ENSG00000143149
MAR06631 | NAD+[c] + retinol[c] -> H+[c] + NADH[c] + retinal[c] | ENSG00000025423 or ENSG00000135437 or ENSG00000147576 or ENSG00000170786 or ENSG00000172955 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198099 or ENSG00000248144
MAR20002 | NAD+[c] + retinol[c] -> H+[c] + NADH[c] + retinal[c] | ENSG00000198099 or ENSG00000196616
MAR06646 | H2O[c] + NAD+[c] + retinal[c] -> 2 H+[c] + NADH[c] + retinoate[c] | ENSG00000128918 or ENSG00000165092
MAR20012 | H2O[c] + NAD+[c] + retinal[c] -> 2 H+[c] + NADH[c] + retinoate[c] | ENSG00000184254
MAR03984 | 2 H2O2[p] -> 2 H2O[p] + O2[p] | ENSG00000121691 or ENSG00000166016
MAR20066 | 2 H2O2[p] -> 2 H2O[p] + O2[p] | ENSG00000121691
MAR00067 | H2O[c] + NAD+[c] + 2(S)-pristanal[c] -> 2 H+[c] + NADH[c] + pristanic acid[c] | ENSG00000072210
MAR20052 | H2O[c] + NAD+[c] + 2(S)-pristanal[c] -> 2 H+[c] + NADH[c] + pristanic acid[c] | ENSG00000072210

**Comment by Devlin-Moyer** [comment]
These pairs of reactions were already pointed out in #578:
- `MAR06981` and `MAR20014`
- `MAR04689` and `MAR20015`
- `MAR00067` and `MAR20052`

and these were already pointed out in #580:
- `MAR04521` and `MAR20020`
- `MAR06631` and `MAR20002`
- `MAR03984` and `MAR20066`

**Comment by haowang-bioinfo** [comment]
the pair `MAR06646` and `MAR20012` is awaiting fixation

**Comment by haowang-bioinfo** [comment]
fixed in #578, #580, and #582
