### ISSUE TITLE
Proposed removal of MAR00032

### ISSUE THREAD

**Issue by jreimertz** [SysBioChalmers/Human-GEM#631]
Reaction MAR00032 can likely be removed since the only source of MAM02392c (lipid droplet), which is the only reactant, is MAR00031, which is exactly the reverse of MAR00032. The only other reaction that MAM02392c participates in is one of the blocked biomass reactions (MAR00021). This results in a loop with MAR00032 and MAR00031, whose only purpose is to support biomass production through MAR00031

**Comment by JonathanRob** [comment]
Thanks for the suggestion @jreimertz.

The lipid droplet reactions were inherited from HMR2, which I think in turn inherited it from the iAdipocytes1809 GEM, so it is a bit old. The original purpose of these reactions was to help simulate lipid droplet production/breakdown, specifically in the liver.

MAR00032 is an example of a reaction that no longer contributes to GEM simulation, but instead serves as information about the metabolic network, which can be valuable especially for maintaining gene-reaction-metabolite associations. However, given that many of the gene associations to MAR00032 seem pretty questionable, I would lean toward removing the reaction as you suggest.

**Comment by haowang-bioinfo** [comment]
fixed in #658
