### ISSUE TITLE
Proposed Removal of MAR03767

### ISSUE THREAD

**Issue by jreimertz** [SysBioChalmers/Human-GEM#633]
[MAR03767](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03767) can likely be removed since it is a duplicate of [MAR06421](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06421) and [MAR06422](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06422)

**Comment by haowang-bioinfo** [comment]
it appears that MAR03767 and MAR06421+MAR06422 differ in the utilization of NAD+/NADH cofactor pair, which should be included or not, any reference about this?

**Comment by haowang-bioinfo** [comment]
fixed in #660
