### ISSUE TITLE
Duplicate Bile Acid Synthesis Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#637]
## Background:

There are currently pathways for converting 25(R)THCA-CoA to cholyl-CoA/cholate in both the [m] and [x] comparments, but these reactions only occur in peroxisomes (sources: ([1](https://doi.org/10.1194/jlr.R900009-JLR200), [2](https://doi.org/10.1016/j.plipres.2008.05.001), [3](https://doi.org/10.1016/S0022-2275(20)32022-8))), so all of the [m] reactions (and their associated metabolites, since they do not participate in any other reactions) should be removed. Some of these reactions were already mentioned in #634, so I've updated the proposed changes in #634 to skip these reactions, since I have now determined that they do not occur in mitochondria

Diagram with metabolite/reaction IDs:
![with IDs](https://github.com/SysBioChalmers/Human-GEM/assets/33460176/3b90a33d-35bc-409b-8996-a45e247ca0c1)

with metabolite names:
![with names](https://github.com/SysBioChalmers/Human-GEM/assets/33460176/6c2fadc5-34cd-41f0-959b-da71a2f3cac3)

`MAR01458` sort of duplicates `MAR01642`+`MAR01646`, except there's also conversion of O<sub>2</sub> to water, and I have no idea where that's coming from; also the only gene associated with it, HSD17B4, is only known to be NAD-dependent and not NADP-dependent ([Uniprot](https://www.uniprot.org/uniprotkb/P51659/entry)), so I'm pretty sure it should be removed.

According to the [reference](https://doi.org/10.1016/S0022-2275(20)32022-8) associated with `MAR01656`, "all newly formed primary bile acid-CoA esters within the peroxisomes are instantly conjugated in situ with glycine or taurine before secretion", so `MAR01656` should also be removed, because `MAR01659` already represents ATP-dependent import of choloyl-CoA into peroxisomes.

While there are enzymes that produce choloyl-CoA in the cytosol, `MAR07758`, `MAR01662`, and `MAR01666` are also suspicious because:
* The only gene associated with `MAR07758`, [DBI](https://www.uniprot.org/uniprotkb/P07108/entry#subcellular_location) (`ENSG00000155368`), is not known to be localized to mitochondria, and `MAR07758` has no references associated with it
* The references ([1](https://doi.org/10.1006/bbrc.2000.3285), [2](https://doi.org/10.1080/00365510050184903), [3](https://doi.org/10.1074/jbc.M103025200), [4](https://doi.org/10.1074/jbc.M106458200)) associated with `MAR01662` all provide evidence of this reaction occuring in peroxisomes, not mitochondria
* The [reference](https://doi.org/10.1146/annurev.biochem.72.121801.161712) associated with `MAR01666` says that "a transport system similar to the carnitine/carnitine palmitoyl transferase machinery used to import fatty acids into the mitochondria may exist to shuttle bile acid intermediates between intracellular compartments; however, no covalently modified derivatives of bile acid intermediates that could represent a transport form have been reported", and neither associated gene ([SLC27A2](https://www.uniprot.org/uniprotkb/O14975/entry#subcellular_location) and [SLC27A5](https://www.uniprot.org/uniprotkb/Q9Y2P5/entry#subcellular_location)) is known to localize to either mitochondrial membrane or transport cholate

## Proposed Changes:
- [ ] Remove MAR01630, MAR01635, MAR01637, MAR01644, MAR01651, MAR01653, MAR03754, and MAR03760 for being redundant with peroxisomal versions
- [ ] Remove MAM00616m, MAM00618m, MAM00749m, MAM00036m, MAM00748m, MAM03367m, MAM01445m, and MAM01514m (MAM03368m was already removed in #649)
- [ ] Remove MAR01656 for being redundant with MAR01659
- [ ] Remove MAR07758, MAR01662, and MAR01666 for being redundant with peroxisomal versions
- [ ] Remove MAR01458 for being redundant with MAR01642+MAR01646

**Comment by Devlin-Moyer** [comment]
I think it's pretty evident from these diagrams that MAR03764, MAR03756, MAM03368x, and MAM003367x should also be removed for being redundant with MAR01646, MAR01642, MAM00748x, and MAM00036x, but I didn't include those proposed changes here, since it seems like #616 is going to handle that

**Comment by haowang-bioinfo** [comment]
nice plot!

it seems that enough evidence has been provided for removing the mitochondria version

> Some of these reactions were already mentioned in https://github.com/SysBioChalmers/Human-GEM/issues/634, so I've updated the proposed changes in https://github.com/SysBioChalmers/Human-GEM/issues/634 to skip these reactions, since I have now determined that they do not occur in mitochondria

very good that you noticed overlap issue to this one (please always check overlap/conflict issues before making new ones).

> I think it's pretty evident from these diagrams that MAR03764, MAR03756, MAM03368x, and MAM003367x should also be removed for being redundant with MAR01646, MAR01642, MAM00748x, and MAM00036x, respectively, but I didn't include those proposed changes here, since it seems like https://github.com/SysBioChalmers/Human-GEM/issues/616 is going to handle that

A likely sequence of implementation might be: 1) #616; 2) #637; 3) #634. what do you think?

**Comment by Devlin-Moyer** [comment]
> A likely sequence of implementation might be: 1) https://github.com/SysBioChalmers/Human-GEM/issues/616; 2) https://github.com/SysBioChalmers/Human-GEM/issues/637; 3) https://github.com/SysBioChalmers/Human-GEM/issues/634. what do you think?

Sounds reasonable to me

**Comment by haowang-bioinfo** [comment]
by looking into the pair of `MAR01635 versus MAR01632`, they both are supported by the annotation of associated gene [AMACR](https://www.uniprot.org/uniprotkb/Q9UHK6/entry) (ENSG00000242110) in catalytic activity and subcellular localization. Should it really be removed? any more evidence for the deletion?

**Comment by Devlin-Moyer** [comment]
Yes, because while AMACR is localized to both compartments, the substrate of MAR01653 is not produced in mitochondria, since it is strictly an intermediate in bile acid production, which only occurs in peroxisomes, because only peroxisomal fatty acid oxidation machinery can handle bile acids (sources: [1](https://doi.org/10.1194/jlr.R900009-JLR200), [2](https://doi.org/10.1016/j.plipres.2008.05.001), [3](https://doi.org/10.1016/S0022-2275(20)32022-8))

**Comment by haowang-bioinfo** [comment]
Ok let's move forward according to the provided evidence.

Even if new conflicting evidence appeared later, the changes can be easily reverted given the clear history in #637
