### ISSUE TITLE
Suggestion to make malic enzyme reactions reversible

### ISSUE THREAD

**Issue by jreimertz** [SysBioChalmers/Human-GEM#638]
The Uniprot page for [ME3](https://www.uniprot.org/uniprotkb/Q16798/entry) (which is included in the GPRs of reactions [MAR04087](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04087) and [MAR04091](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04091)) and the papers that are cited by Uniprot state that reactions encoded by ME3 are reversible. As a result, it would seem that both of these reactions should be reversible.

**Comment by feiranl** [comment]
According to the description: `Can also reverse the decarboxylation reaction, but only with significantly lower efficiency.` I would suggest we keep this rxn still irreversible. Otherwise, CO2 can be fixed with only one cost of NADH, it may triggers the unrealistic flux simulation.

**Comment by edkerk** [comment]
It's ΔG'° is quite neutral though (-0.3199463 kcal/mol, [MetaCyc](https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=1.1.1.39-RXN)). Would be good to evaluate what the effect of this change would be on flux distributions, it might not go in reverse in most conditions anyway?

**Comment by haowang-bioinfo** [comment]
close for now, feel free to reopen
