### ISSUE TITLE
FAD/Oxygen-Peroxide Duplicate Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#639]
## Problems

Similarly to #607, I found a number of pairs of reactions that are largely identical except one reduces FAD to FADH<sub>2</sub> and the other reduces O<sub>2</sub> to H<sub>2</sub>O<sub>2</sub>:

Reactant | FAD-dependent ID | O<sub>2</sub>-dependent ID
---|---|---
25(S)THCA-CoA | MAR01638 | MAR01639
linoleoyl-CoA | MAR02804 | MAR03301
cis,cis-palmito-7,10-dienoyl-CoA | MAR02808 | MAR03306
cis,cis-myristo-5,8-dienoyl-CoA | MAR02810 | MAR03311
4-cis-decenoyl-CoA | MAR02818 | MAR04966
palmitoleoyl-CoA | MAR03276 | MAR03364
(7Z)-tetradecenoyl-CoA | MAR03289 | MAR03369
(5Z)-dodecenoyl-CoA | MAR03295 | none

There's also this strange case:
`MAR00059: 3alpha,7alpha-dihydroxy-5beta-cholest-24-enoyl-CoA [x] + FADH2 [x] + 0.5 O2 [x] ⇒ (24R,25R)3alpha,7alpha,24-trihydroxy-5beta-cholestanoyl-CoA [x] + FAD [x], GPR: ACOX2`

## Background/Rationale

ACOX2 irreversibly _oxidizes_ its substrates (see [Uniprot](https://www.uniprot.org/uniprotkb/Q99424/entry) and [this paper](https://doi.org/10.1016/j.jhep.2016.11.005)), so `MAR00059` definitely doesn't represent a reaction catalyzed by ACOX2 (see #634 for details and examples of reactions that ACOX2 should be associated with). However, `MAR00059` is very similar to `MAR01706`:

`MAR00059: 3alpha,7alpha-dihydroxy-5beta-cholest-24-enoyl-CoA [x] + FADH2 [x] + 0.5 O2 [x] ⇒ (24R,25R)3alpha,7alpha,24-trihydroxy-5beta-cholestanoyl-CoA [x] + FAD [x], GPR: ACOX2`
`MAR01706: 3alpha,7alpha-dihydroxy-5beta-cholest-24-enoyl-CoA [x] + H2O [x] ⇒ (24R,25R)3alpha,7alpha,24-trihydroxy-5beta-cholestanoyl-CoA [x], GPR: ACAA1 and EHHADH and HSD17B4`

According to [this paper](https://doi.org/10.1194/jlr.R900009-JLR200) about bile acid biosynthesis, `MAR01706` already accurately represents this step in the pathway and the catalytic activities of [EHHADH](https://www.uniprot.org/uniprotkb/Q08426/entry) and [HSD17B4](https://www.uniprot.org/uniprotkb/P51659/entry) (also see their Uniprot pages), so `MAR00059` should just be removed for being a less-accurate version of `MAR01706`. Relatedly, [ACAA1](https://www.uniprot.org/uniprotkb/P09110/entry) is a 3-ketoacyl thiolase, and `MAR01706` doesn't involve any thiolysis, so it should be removed from the GPR of `MAR01706`.

Most similar reactions (i.e. the ~100 other reactions associated with ACOX1, ACOX2, or ACOX3 that involve peroxisomal metabolites) reduce O<sub>2</sub> to H<sub>2</sub>O<sub>2</sub> and not FAD to FADH<sub>2</sub>, so it would be easier/simpler to remove the FAD-dependent versions and keep the O<sub>2</sub>-dependent versions. However, that would be inconsistent with the changes and rationale in #607, where we kept the FAD-dependent versions of the reactions to explicitly account for its role in the transfer of electrons from various substrates to ubiquinone. Also, FAD cofactors are not covalently attached to most human enzymes ([source](https://doi.org/10.1016/j.abb.2013.02.015)), FAD cannot be biosynthesized in human peroxisomes ([source](https://doi.org/10.1042/BJ20111420)), and SLC25A17 (`ENSG00000100372`) exchanges cytosolic FAD for peroxisomal FMN in humans (same source as before). Keeping the FAD-dependent members of each of these pairs, replacing O<sub>2</sub> and H<sub>2</sub>O<sub>2</sub> with FAD and FADH<sub>2</sub> in all similar reactions, and adding a separate reaction for reduction of O<sub>2</sub> to H<sub>2</sub>O<sub>2</sub> by FADH<sub>2</sub> would be a lot of work, but it would be more realistic (and consistent with #607).

## Proposed Changes

- [x] Remove `MAR00059` for being a less accurate version of `MAR01706`
- [x] Change the GPR of `MAR01706` to `ENSG00000113790 or ENSG00000133835` and add `PMID:19357427` to its references
- [x] Remove `MAR01639` for being redundant with `MAR01638`
- [x] Remove `MAR03301` for being redundant with `MAR02804`
- [x] Remove `MAR03306` for being redundant with `MAR02808`
- [x] Remove `MAR03311` for being redundant with `MAR02810`
- [x] Remove `MAR04966` for being redundant with `MAR02818`
- [x] Remove `MAR03364` for being redundant with `MAR03276`
- [x] Remove `MAR03369` for being redundant with `MAR03289`
- [x] Replace `MAM02630x` (O<sub>2</sub>) with `MAM01802x` (FAD) and `MAM02041x` (H<sub>2</sub>O<sub>2</sub>) with `MAM01803x` (FADH<sub>2</sub>) in `MAR00442, MAR00759, MAR00777, MAR00800, MAR00833, MAR00872, MAR00952, MAR00968, MAR00974, MAR00975, MAR00977, MAR00978, MAR00982, MAR01001, MAR01005, MAR01018, MAR01162, MAR01205, MAR01254, MAR01271, MAR01291, MAR01296, MAR01303, MAR01600, MAR01704, MAR02408, MAR02510, MAR03053, MAR03054, MAR03055, MAR03056, MAR03057, MAR03062, MAR03066, MAR03070, MAR03074, MAR03078, MAR03082, MAR03086, MAR03090, MAR03094, MAR03098, MAR03102, MAR03326, MAR03330, MAR03334, MAR03338, MAR03342, MAR03346, MAR03350, MAR03356, MAR03360, MAR03459, MAR03466, MAR03470, MAR03498, MAR03506, MAR03512, MAR03849, MAR03984, MAR04001, MAR04650, MAR04789, MAR04981, MAR05025, MAR05026, MAR05028, MAR05097, MAR05100, MAR05108, MAR05119, MAR05175, MAR05178, MAR05180, MAR05182, MAR05184, MAR05189, MAR05196, MAR05300, MAR05327, MAR05331, MAR05350, MAR05366, MAR05372, MAR05374, MAR05377, MAR05382, MAR05421, MAR05428, MAR05431, MAR06284, MAR06285, MAR06322, MAR06344, MAR06345, MAR06933, MAR06936, MAR06943, MAR06946, MAR06949, MAR06952, MAR06959, MAR06962, MAR06964, MAR07641, MAR07647, MAR07704, MAR07706, MAR08017, MAR08021, MAR08415, MAR08689, MAR08690, MAR08755, MAR11529, MAR11534, MAR11539, MAR12372, MAR12808, and MAR20066` (every reaction that consumes O<sub>2</sub> and produces H<sub>2</sub>O<sub>2</sub> in the peroxisome except the ones that already have FAD-dependent versions)
- [x] Create new reaction to represent reduction of O<sub>2</sub> by FADH<sub>2</sub>: `MAM02630x + MAM01803x -> MAM02041x + MAM01802x`, GPR: `ENSG00000161533 or ENSG00000168306 or ENSG00000087008 or ENSG00000110887 or ENSG00000203797 or ENSG00000007171 or ENSG00000148832 or ENSG00000179761 or ENSG00000158125` (every enzyme mentioned [here](https://link.springer.com/chapter/10.1007/978-981-13-2233-4_19/tables/1) except ACOXL, which the paper says is not known to be catalytically active, UOX, which is a pseudogene in humans, and HAO1 and HAO2, which use FMN and not FAD according to [this paper](https://febs.onlinelibrary.wiley.com/doi/full/10.1111/febs.16164))

**Comment by haowang-bioinfo** [comment]
nice and thorough investigation, and a large chunk of the network would be affected by the proposed changes

**Comment by feiranl** [comment]
Please manually test all metabolic tasks can be filled before making the changes.

**Comment by Devlin-Moyer** [comment]
I don't know what that means; which metabolic tasks are we talking about?

**Comment by feiranl** [comment]
The task list can be found [here](https://github.com/SysBioChalmers/Human-GEM/tree/main/data/metabolicTasks), and @haowang-bioinfo maybe you can guide how to test those tasks. I only find the RAVEN function  `checkTasks`, not sure wether this is correct.

taskStruct = parseTaskList('../data/metabolicTasks_Essential.txt');
[taskReport, essentialRxnMat, ~, essentialFluxes] = checkTasks(bModel,[],true,false,true,taskStruct);

**Comment by JonathanRob** [comment]
When running checkTasks in this case, you can set the getEssential input to False, since you don’t need to get the essential reactions, just test if the tasks pass. So the second line could just be:

checkTasks(bModel,[],true,false,false,taskStruct);

This will greatly decrease run time, since the essentiality part takes a while.

**Comment by haowang-bioinfo** [comment]
> I don't know what that means; which metabolic tasks are we talking about?

feel free to start a PR which can be made directly to Human-GEM, rather than from a forked repo. Then we can check out the tasks

**Comment by Devlin-Moyer** [comment]
yea I can do that once #624 is merged; I've been holding off on opening any other PRs that add new reactions until #624 is merged since that adds new reactions, and having multiple PRs that add new reactions open at the same time seems like it'd set us up for some confusing/annoying/complicated merge conflicts and/or distinct reactions with the same IDs

**Comment by Devlin-Moyer** [comment]
Addressed by #670
