### ISSUE TITLE
More Reversible Pyrophosphate Reactions That Should Be Irreversible

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#648]
Follow-up on #527: I recently reran the same bit of Python code I used to identify all the reactions mentioned in #527 (and fixed in #557) on the latest version of Human-GEM, and it came up with a few more reactions:

ID | Reaction | Proposed Change
---|---|---
MAR02786 | ATP + CoA + linoleate <=> AMP + linoleoyl-CoA + PPi | set lower bound to 0
MAR02802 | ATP + CoA + linoleate <=> AMP + linoleoyl-CoA + PPi | set lower bound to 0
MAR03388 | ATP + CoA + phytanic acid <=> AMP + PPi + 3(S)-Phytanoyl Coenzyme A | set lower bound to 0
MAR03390 | ATP + CoA + pristanic acid <=> (2R)-pristanoyl-CoA + AMP + PPi | set lower bound to 0
MAR09508 | (5)ppPur-mRNA + GTP <=> G(5)pppR-RNA + PPi | set lower bound to 0
MAR01845 | AMP + glycolithocholate + H+ + PPi <=> ATP + glycine + lithocholate | swap products & reactants, then set lower bound to 0
MAR09523 | PPi + tRNA containing 6-isopentenyladenosine <=> dimethylallyl-PP + tRNA | swap products & reactants, then set lower bound to 0
MAR09546 | AMP + PPi + RNA-terminal-2,3-cyclic-phosphate <=> ATP + RNA-3-terminal-phosphate | swap products & reactants, then set lower bound to 0

See #527 for a more thorough explanation, but all of these reactions should be irreversible in the direction that consumes PP<sub>i</sub> due to the ubiquitous abundant expression of highly-active pyrophosphatases. I have no idea why they weren't caught the first time (none of these reactions appear to have been edited or created since #557 was merged), but these should all be made irreversible for all the same reasons mentioned in #527.

I've already opened #641 to implement the proposed changes

**Comment by feiranl** [comment]
Fixed in #641
