### ISSUE TITLE
Ammonia/Ammonium Duplicate Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#665]
## The Problem:

There are several reactions that are completely identical except one uses NH<sub>4</sub><sup>+</sup> (`MAM02579`) and the other uses NH<sub>3</sub> (`MAM02578`) + H<sup>+</sup>:

ID | Reaction | Genes
---|---|---
MAR01515 | H2O + methylamine + O2 --> formaldehyde + H2O2 + NH4+ | AOC1 or AOC3 or AOC2
MAR08529 | H2O + methylamine + O2 --> formaldehyde + H+ + H2O2 + NH3 | AOC1 or AOC3 or AOC2
MAR00039 | 1,3-diaminopropane + H2O + O2 --> 3-amino-propanal + H2O2 + NH4+ | AOC1 or AOC3 or AOC2
MAR07992 | 1,3-diaminopropane + H2O + O2 --> 3-amino-propanal + H+ + H2O2 + NH3 | AOC1 or AOC3 or AOC2
MAR00096 | 3-ureidoisobutyrate + 2 H+ + H2O --> CO2 + D-3-amino-isobutanoate + NH4+ | UPB1
MAR04819 | 3-ureidoisobutyrate + H+ + H2O --> CO2 + D-3-amino-isobutanoate + NH3 | UPB1
MAR02027 | cysteine + H2O <=> H+ + H2S + NH4+ + pyruvate | CTH
MAR04302 | cysteine + H2O --> 2 H+ + H2S + NH3 + pyruvate | CTH
MAR02006 | 2 ATP + CO2 + H2O + NH4+ --> 2 ADP + carbamoyl-phosphate + 3 H+ + Pi | CPS1
MAR03873 | 2 ATP + CO2 + H2O + NH3 --> 2 ADP + carbamoyl-phosphate + 2 H+ + Pi | CPS1

Uniprot lists all reactions associated with [AOC1](https://www.uniprot.org/uniprotkb/P19801/entry), [AOC2](https://www.uniprot.org/uniprotkb/O75106/entry), [AOC3](https://www.uniprot.org/uniprotkb/Q16853/entry), [UPB1](https://www.uniprot.org/uniprotkb/Q9UBR1/entry), [CTH](https://www.uniprot.org/uniprotkb/P32929/entry), and/or [CPS1](https://www.uniprot.org/uniprotkb/P31327/entry) with NH<sub>4</sub><sup>+</sup> rather than NH<sub>3</sub>.

## Proposed Changes:

Since `MAR02027` (NH<sub>4</sub><sup>+</sup>) is reversible but `MAR04302` (NH<sub>3</sub>) is irreversible, [Uniprot](https://www.uniprot.org/uniprotkb/P32929/entry) says that reaction should be irreversible, most similar reactions already in Human-GEM involve NH<sub>3</sub> (`MAM02578`) rather than NH<sub>4</sub><sup>+</sup> (`MAM02579`), I think it makes sense to remove all of the NH<sub>4</sub><sup>+</sup> versions and keep all of the NH<sub>3</sub> versions. `MAR05127: NH4+ [c] ⇔ H+ [c] + NH3 [c]` allows ammonium and ammonia to freely interconvert (which is reasonable; that reaction is spontaneous in aqueous solutions), so it's not really contradicting Uniprot to keep the NH<sub>3</sub> versions instead of the NH<sub>4</sub><sup>+</sup> versions, and that would make the proposed changes a little simpler:

- [x] Remove `MAR01515` for being a duplicate of `MAR08529`
- [x] Remove `MAR00039` for being a duplicate of `MAR07992`
- [x] Remove `MAR00096` for being a duplicate of `MAR04819`
- [x] Remove `MAR02027` for being a duplicate of `MAR04302`
- [x] Remove `MAR02006` for being a duplicate of `MAR03873`
- [x] Merge annotations/references/etc. from removed reactions into corresponding kept reactions

**Comment by feiranl** [comment]
Agree! please go ahead and make these changes!

**Comment by Devlin-Moyer** [comment]
Fixed in #677
