### ISSUE TITLE
Citrate Synthase Is Not Reversible In Humans

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#673]
`MAR04145: CoA [m] + H+ [m] + citrate [m] ⇔ H2O [m] + OAA [m] + acetyl-CoA [m], GPR: ENSG00000062485` ([citrate synthase](https://www.uniprot.org/uniprotkb/O75390/entry)) should be irreversible, since the human citrate synthase enzyme (and apparently [most organisms' citrate synthases](https://doi.org/10.1126/science.aao2410)) only catalyze the forward reaction (source focused on the human enzyme specifically is page 130 of [this book](https://books.google.com/books?hl=en&lr=&id=A3u1891gHfkC&oi=fnd&pg=PP1&ots=Ap4zUyLCPY&sig=hw2H0Zb-04QqkQ4StEMr3aX8DI4#v=onepage&q=citrate&f=false))

**Comment by feiranl** [comment]
Nice catch! Please go ahead and make the change

**Comment by Devlin-Moyer** [comment]
Resolved by #676
