### ISSUE TITLE
Near-Duplicate Lipoic Acid Transport Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#679]
## Background
There are currently three reactions representing sodium-dependent import of lipoic acid via SLC5A6 (`ENSG00000138074`):
`MAR01483`: ATP [c] + H2O [c] + lipoic acid [e] + Na+ [e] --> ADP [c] + H+ [c] + lipoic acid [c] + Na+ [c] + Pi [c]
`MAR06406`: ATP [c] + H2O [c] + lipoic acid [e] + 2 Na+ [e] --> ADP [c] + H+ [c] + lipoic acid [c] + 2 Na+ [c] + Pi [c]
`MAR09608`: lipoic acid [e] + 2 Na+ [e] --> lipoic acid [c] + 2 Na+ [c]

## Problems
SLC5A6 is a sodium-dependent transporter, and while the sodium concentration gradient it depends on to bring its various substrates into cells is established by ATP-dependent sodium transporters, SLC5A6 does not itself hydrolyze ATP (sources: [1](https://doi.org/10.1074/jbc.M110.167197), [2](https://doi.org/10.1074/jbc.274.21.14875)). None of the references currently associated with `MAR01483` or `MAR06406` found SLC5A6 to be ATP-dependent (many aren’t even relevant to this reaction), and most directly state that the stoichiometry is 2 Na<sup>+</sup> to 1 substrate, which is consistent with `MAR09068` but not `MAR01483`. `MAR01483` and `MAR06406` should be removed, since neither accurately represent the function of SLC5A6, and `MAR09606` does.

## Proposed changes
- [x] Remove `MAR01483` and `MAR06406`
- [x] Merge annotations for `MAR01483` and `MAR06406` in `reactions.tsv` with those for `MAR09608`
- [x] Set the references for `MAR09608` to `PMID:9516450;PMID:10329687;PMID:15561972`

**Comment by haowang-bioinfo** [comment]
the provided evidence for SLC5A6, as well as its [Uniprot annotation](https://www.uniprot.org/uniprotkb/Q9Y289/entry), support the removal of MAR01483 and MAR06406, please move on to implementation.

additionally, would suggest to associate MAR01483 with Rhea id RHEA:73379/RHEA:73380

**Comment by Devlin-Moyer** [comment]
oh yea I should probably not add that to the list of references for `MAR09608`, since it only provides evidence that SLC5A6 isn't ATP-dependent, which is justification to remove the other two reactions, rather than evidence supporting the existence of `MAR09608`; I'll update the proposed changes accordingly
