### ISSUE TITLE
Duplicate Lipoic Acid Biosynthesis Pathways

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#682]
## Background
At the moment, octanoyl-[ACP] (`MAM02643c`) can become [protein]-N6-(lipoyl)lysine (`MAM00209c`) via either `MAR06400` + `MAR06401` or `MAR06402` + `MAR06403`:

Reaction ID | Reaction | Genes
---|---|---
`MAR06400` | 5 H+ [c] + 7 NADPH [c] + octanoyl-[ACP] [c] + 2 PAPS [c] + 2 SAM [c] --> 2 5-deoxyadenosine [c] + 6 H2O [c] + lipoyl-[ACP] [c] + 2 methionine [c] + 7 NADP+ [c] + 2 PAP [c] | LIAS or LIPT2 (`ENSG00000121897 or ENSG00000175536`)
`MAR06401` | apoA1 [c] + lipoyl-[ACP] [c] --> [ACP] [c] + [protein]-N6-(lipoyl)lysine [c] | LIPT2 (`ENSG00000175536`)
| |
`MAR06402` | apoA1 [c] + octanoyl-[ACP] [c] --> [ACP] [c] + [protein]-N6-(octanoyl)lysine [c] | LIPT2 (`ENSG00000175536`)
`MAR06403` | [protein]-N6-(octanoyl)lysine [c] + 5 H+ [c] + 7 NADPH [c] + 2 PAPS [c] + 2 SAM [c] --> [protein]-N6-(lipoyl)lysine [c] + 2 5-deoxyadenosine [c] + 6 H2O [c] + 2 methionine [c] + 7 NADP+ [c] + 2 PAP [c] | LIAS (`ENSG00000121897`)

## Problems
According to [these](https://doi.org/10.1016/j.ajhg.2017.07.001) [papers](https://doi.org/10.1007/s10545-014-9705-8), the lipoic acid biosynthesis starts with LIPT2 transferring an octanoyl residue from ACP to GCSH, and LIAS only converts that octanoyl residue into a lipoyl residue after the octanoyl has been moved off of ACP. Figure S1 from the first paper cited above illustrates this:
![Screenshot from 2023-07-19 11-06-36](https://github.com/SysBioChalmers/Human-GEM/assets/33460176/1601066e-6798-4a6b-944a-c67be5eee10d)

That paper also mentions that this whole process happens in mitochondria, and both sets of Human-GEM reactions happen entirely in the cytosol, but several of the metabolites involved do not currently exist in [m], and addressing that turns out to get rather complicated, so I’ve separated all that out into #684 and #685. For now, I’m just proposing that `MAR06400` and `MAR06401` be removed for being redundant with `MAR06402` and `MAR06403` and misrepresenting the timing of the ACP to GCSH octanoyl transfer mediated by LIPT2.

## Proposed Changes:
- [x] Merge annotations of `MAR06400` into annotations for `MAR06403`
- [x] Remove `MAR06400` for being a less accurate version of `MAR06403`
- [x] Merge annotations of `MAR06401` into annotations for `MAR06402`
- [x] Remove `MAR06401` for being a less accurate version of `MAR06402`
- [x] Remove now-isolated `MAM02397c` (lipoyl-[ACP])

**Comment by haowang-bioinfo** [comment]
yes the lipoic acid synthesis should be in mitochondria, to which the relevant modifications are planned in #685

**Comment by haowang-bioinfo** [comment]
fixed in #707
