### ISSUE TITLE
Misrepresentation of Catalytic Activity of LIPT1

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#683]
## Background

The changes proposed in #685 depend on the ones proposed in this issue

LIPT1 (`ENSG00000144182`) is currently associated with four reactions:
ID | Reaction | Genes
---|---|---
`MAR06398` | ATP [c] + H+ [c] + lipoic acid [c] --> lipoyl-AMP [c] + PPi [c] | LIPT1
`MAR06399` | apoA1 [c] + lipoyl-AMP [c] --> [protein]-N6-(lipoyl)lysine [c] + AMP [c] + H+ [c] | LIPT1
`MAR01088` | CoA [c] + H+ [c] + N-acetyl-LTE4 [c] <=> acetyl-CoA [c] + leukotriene E4 [c] | LIPT1 or (many other genes)
`MAR01091` | CoA [n] + H+ [n] + N-acetyl-LTE4 [n] <=> acetyl-CoA [n] + leukotriene E4 [n] | LIPT1 or (many other genes)

## Problems
- None of the references associated with `MAR01088` or `MAR01091` mention LIPT1, and I can't find any other papers that associate LIPT1 with leukotriene metabolism, so I believe that LIPT1 should be removed from the GPRs of both reactions.
- According to [this paper](https://doi.org/10.1073/pnas.1805862115), LIPT1 is not capable of adenylating free lipoic acid or using lipoyl-AMP to lipoylate proteins; furthermore, no human enzyme is capable of carrying out the reactions represented by `MAR06398` and `MAR06399` -- humans cannot ligate free lipoic acid to proteins at all -- so both reactions should be removed entirely.
- That same paper shows that LIPT1 is instead capable of transfering lipoyl moeities from [GCSH](https://www.uniprot.org/uniprotkb/P23434/entry) (where it is synthesized from octanoyl moities bound to GCSH) to subunits of the 2-ketoacid dehydrogenase complexes (i.e. [DLAT](https://www.uniprot.org/uniprotkb/P10515/entry), [DLST](https://www.uniprot.org/uniprotkb/P36957/entry), and [DBT](https://www.uniprot.org/uniprotkb/P11182/entry)).
  - There is no existing Human-GEM reaction that represents this transfer of lipoyl moeities, but I think this can be somewhat realistically represented by creating a new reaction that turns [protein]-N6-(lipoyl)lysine (`MAM00209c`) into lipoamide (`MAM02393m`) and associating LIPT1 with that reaction. I know that converts a metabolite in [c] directly into a metabolite in [m], but since #685 would make all the changes necessary to make [protein]-N6-(lipoyl)lysine able to be produced directly in [m], for now I'm just proposing we ignore this issue and replace `MAM00209c` with a new mitochondrial version in this reaction in #685.
  - Creating that new rection would also solve the related problem that lipoamide (`MAM02393m`) represents the role of lipoic acid as a cofactor for GCSH and the 2-ketoacid dehydrogenase complexes (in `MAR04599`, `MAR06413`, `MAR06416`, `MAR06419`, `MAR06421`, `MAR08433`, and `MAR20069`), but is disconnected from the lipoic acid biosynthesis reaction `MAR06403` (`5 H+ [c] + 7 NADPH [c] + 2 PAPS [c] + 2 SAM [c] + [protein]-N6-(octanoyl)lysine [c] ⇒ 2 5-deoxyadenosine [c] + 6 H2O [c] + 7 NADP+ [c] + 2 PAP [c] + [protein]-N6-(lipoyl)lysine [c] + 2 methionine [c]`), because `MAR06403` produces "[protein]-N6-(lipoyl)lysine" (`MAM00209c`), which cannot be made into lipoamide (`MAM02393m`).
  - Treating [protein]-N6-(lipoyl)lysine as lipoylated GCSH and lipoamide as lipoylated DLAT/DLST/DBT would also be a step towards enabling Human-GEM to accurately simulate the metabolic consequences of defective LIPT1 in humans described in that same paper, namely that catalytic activity of GCSH is unaffected, but the catalytic activities of all the 2-ketoacid dehydrogenase complexes are severely impaired. Fully accomplishing that would also require:
    - Replacing lipoamide (`MAM02393m`) with [protein]-N6-(lipoyl)lysine (`MAM00209m`) in `MAR08433` (`H+ [m] + glycine [m] + lipoamide [m] ⇒ CO2 [m] + S-aminomethyldihydrolipoamide [m]`) and
    - Replacing dihydrolipoamide (`MAM01701m`) with [protein]-N6-(dihydrolipoyl)lysine (`MAM00208m`) in `MAR08434` (`S-aminomethyldihydrolipoamide [m] + THF [m] ⇒ 5,10-methylene-THF [m] + H+ [m] + NH3 [m] + dihydrolipoamide [m]`)
  - Those changes are slightly complicated by the fact that neither `MAM00209m` nor `MAM00208m` exist at the moment, as I mentioned above. So once again, I'm just proposing that `MAR08433` and `MAR0844` use the existing `MAM00209c` and `MAM00208c` metabolites, even though they're in [c] and the rest of the reaction happens in [m], and having #685 replace them with new mitochondrial versions after making all the other necessary changes to make them producible in [m].
- On the topic of lipoic acid biosynthesis happening in the mitochondria of human cells, I think `MAR11361` (`H+ [i] + lipoamide [c] ⇒ H+ [m] + lipoamide [m]`) should be either be made reversible or irreversible in the opposite direction (i.e. from [m] to [c]).
  - I also think the protons should be removed from `MAR11361`, since the lipoamide metabolites (`MAM02393`) represent lipoic acid conjugated to a lysine residue on a protein, rather than free lipoic acid (`MAM02394`), and all proteins that human cells lipoylate are strictly mitochondrial proteins (see [these](https://doi.org/10.1016/j.ajhg.2017.07.001) [papers](https://doi.org/10.1007/s10545-014-9705-8)), so this transport reaction doesn't represent a real transport reaction, and the only reason to keep this reaction at all would be to keep the mitochondrial lipoamide metabolite connected to its exchange reaction (`MAR11345`).
  - The same issues also apply to `MAR06408` (`H+ [i] + dihydrolipoamide [c] ⇒ H+ [m] + dihydrolipoamide [m]`). However, since this is the only reaction that `MAM01701c` participates in, and it definitely doesn't represent real-world biology, I think both `MAR06408` and `MAM01701c` should be removed.

## Proposed Changes
- [x] Remove LIPT1 (`ENSG00000144182`) from the GPRs of `MAR01088` and `MAR01091`
- [x] Remove `MAR06398`, `MAR06399`, and `MAM02398c` (lipoyl-AMP)
- [x] Create new reaction `MAM00209c -> MAM02393m`, GPR: `ENSG00000144182`, references: `PMID:29987032`
- [x] Replace `MAM02393m` with `MAM00209c` in `MAR08433`
- [x] Replace `MAM01701m` with `MAM00208c` in `MAR08434`
- [x] Remove `MAM02039c` and `MAM02039e` `MAR11346`
- [x] Remove `MAM02039i` and `MAM02039m` from `MAR11361`
- [x] Make `MAR11361` reversible
- [x] Remove `MAR06408` and `MAM01701c`

**Comment by haowang-bioinfo** [comment]
Overall it's hard for me to under this issue, it feels like filling the gap between #682 and #685. Can you please somehow improve the text and make it easier to understand.

In particular, you claim that MAR06408 should be removed but without evidence. If "dihydrolipoamide (MAM01701c) can't be produced by any other reactions", then which dihydrolipoamide-producing reaction is correct and should be kept?

**Comment by Devlin-Moyer** [comment]
I have tried to rephrase and rearrange the ideas in the original comment to be easier to follow; let me know if it makes more sense now.

I initially wrote all of these issues related to lipoic acid metabolism (#682, #684, and #685) as one very long and complicated issue, and then tried to figure out how to separate them out into smaller, more digestible issues, but it was difficult to do in a way that didn't seem to make an already-confusing situation even more confusing. So I might not have included all the necessary context to make sense of what's going on here in each of these individual issues, since they're all kind of jumbled together in my head.

**Comment by haowang-bioinfo** [comment]
thanks for improving the text that is better now

Given the provided citation and explanation, I don't see a reason to hold this up, please go ahead to implementation
