### ISSUE TITLE
Short- and medium-chain fatty acids don't have hydrolysis rxns

### ISSUE THREAD

**Issue by pranasag** [SysBioChalmers/Human-GEM#689]
#### Current behavior:
Hi everyone, 
after the fix #557/discussion in #527, the Human-GEM v1.16 cannot produce free C4-C11 fatty acids (the ATP-generating reaction was the only route to get free FAs from their CoA-bound forms). Acyl-CoA hydrolysis reactions for C12 and longer FAs [exist already](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00189).

#### Expected feature/value/output:
We would need cytosolic reactions for [C4-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01412c), [C6-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02122c), [C8-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02644c), [C10-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01650c), and [C11-CoA](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03116c) hydryolysis in the same spirit as for C12 [MAR00189](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00189): `H2O[c] + acyl-CoA[c] => CoA[c] + H+[c] + free fatty acid[c]`.

**Comment by haowang-bioinfo** [comment]
interesting

> We would need cytosolic reactions for [C4-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01412c), [C6-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02122c), [C8-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02644c), [C10-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01650c), and [C11-CoA](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03116c) hydryolysis in the same spirit as for C12 [MAR00189](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00189): H2O[c] + acyl-CoA[c] => CoA[c] + H+[c] + free fatty acid[c].

what are the gene(s) that are involved in these hydrolysis reactions?

**Comment by pranasag** [comment]
Good question. Currently, almost all reactions in the `Acyl-CoA hydrolysis` subsystem have the same GPR association (`ENSG00000097021 or ENSG00000119673 or ENSG00000136881 or ENSG00000177465 or ENSG00000184227 or ENSG00000205669`) - these are different isoforms of acyl-CoA thioesterase. 

I initially thought that defining new reactions with just use the same GPR string will suffice, I think other entries also need a bit of curation. From a quick look to respective UniProt entries, some of these enzymes are known to have higher specificity for [very] long-chain fatty acids, and [ACOT4](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000177465;r=14:73591873-73595766;t=ENST00000326303) is even labelled as peroxisomal isoform in [UniProt](https://www.uniprot.org/uniprotkb/Q8N9L9/entry), thus should not be associated to the cytoplasmic acyl-CoA hydrolysis reactions.

**Comment by haowang-bioinfo** [comment]
> Good question. Currently, almost all reactions in the Acyl-CoA hydrolysis subsystem have the same GPR association (ENSG00000097021 or ENSG00000119673 or ENSG00000136881 or ENSG00000177465 or ENSG00000184227 or ENSG00000205669) - these are different isoforms of acyl-CoA thioesterase.

good

> I initially thought that defining new reactions with just use the same GPR string will suffice, I think other entries also need a bit of curation. From a quick look to respective UniProt entries, some of these enzymes are known to have higher specificity for [very] long-chain fatty acids, and [ACOT4](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000177465;r=14:73591873-73595766;t=ENST00000326303) is even labelled as peroxisomal isoform in [UniProt](https://www.uniprot.org/uniprotkb/Q8N9L9/entry), thus should not be associated to the cytoplasmic acyl-CoA hydrolysis reactions.

it does appear so. Maybe begin with sorting out cytoplasmic acyl-CoA hydrolysis reactions first. Please go ahead proposing an implementation plan

**Comment by pranasag** [comment]
Hi there, 
With some input from [Christoff Odendaal](https://research.vu.nl/en/persons/christoff-odendaal) I have summarized what I found in literature in [this .csv file](https://github.com/SysBioChalmers/Human-GEM/files/12342808/ACOTs.csv). The main points are:

* Suggested new reactions for short-chain acyl-CoA hydrolysis, reaction IDs to be assigned
* For existing cytosolic reactions, GPRs were reviewed based to the localization of the ACOTs and their known specificity towards different carbon chain lengths
* Ditto for the GPRs of the peroxisomal reactions
* Suggest adding two genes that are not currently in the model [THEM4](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000159445;r=1:151870866-151909637) and [THEM5](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000196407;r=1:151847101-151853712)

As you could see in the .csv summary, many ACOTs localize to mitochondria as well. Thus a potential next step in curation would be to add analogous hydrolysis reactions for mitochondrial acyl-CoAs.

**Comment by haowang-bioinfo** [comment]
fixed by #715 and #717
