### ISSUE TITLE
Mitochondrial Nucleotide Transporters

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#694]
According to [this paper](https://doi.org/10.1074/jbc.M114.610808) (specifically Figure 4 and Table 1 from that paper), SLC25A33 (`ENSG00000171612`) and SLC25A36 (`ENSG00000114120`) can transport pyrimidine (d)NTPs, (d)NDPs, and (d)NMPs from the cytosol into the mitochondria. To be specific:

Reaction | Appropriate GPR
---|---
CTP [c] + CDP [m] <-> CTP [m] + CDP [c] | `ENSG00000114120`
CTP [c] + CMP [m] <-> CTP [m] + CMP [c] | `ENSG00000114120`
CTP [c] + dCTP [m] <-> CTP [m] + dCTP [c] | `ENSG00000114120`
CTP [c] + dCDP [m] <-> CTP [m] + dCDP [c] | `ENSG00000114120`
CTP [c] + dCMP [m] <-> CTP [m] + dCMP [c] | `ENSG00000114120`
CTP [c] + GTP [m] <-> CTP [m] + GTP [c] | `ENSG00000114120`
CTP [c] + GDP [m] <-> CTP [m] + GDP [c] | `ENSG00000114120`
CTP [c] + GMP [m] <-> CTP [m] + GMP [c] | `ENSG00000114120`
CTP [c] + dGTP [m] <-> CTP [m] + dGTP [c] | `ENSG00000114120`
CTP [c] + dGDP [m] <-> CTP [m] + dGDP [c] | `ENSG00000114120`
CTP [c] + dGMP [m] <-> CTP [m] + dGMP [c] | `ENSG00000114120`
CTP [c] + ITP [m] <-> CTP [m] + ITP [c] | `ENSG00000114120`
CTP [c] + IDP [m] <-> CTP [m] + IDP [c] | `ENSG00000114120`
CTP [c] + IMP [m] <-> CTP [m] + IMP [c] | `ENSG00000114120`
CTP [c] + UTP [m] <-> CTP [m] + UTP [c] | `ENSG00000114120 or ENSG00000171612`
CTP [c] + UDP [m] <-> CTP [m] + UDP [c] | `ENSG00000114120`
CTP [c] + UMP [m] <-> CTP [m] + UMP [c] | `ENSG00000114120`
CTP [c] + dUTP [m] <-> CTP [m] + dUTP [c] | `ENSG00000114120`
CTP [c] + dUDP [m] <-> CTP [m] + dUDP [c] | `ENSG00000114120`
CTP [c] + dUMP [m] <-> CTP [m] + dUMP [c] | `ENSG00000114120`
UTP [c] + CDP [m] <-> UTP [m] + CDP [c] | `ENSG00000171612`
UTP [c] + dCTP [m] <-> UTP [m] + dCTP [c] | `ENSG00000171612`
UTP [c] + dCDP [m] <-> UTP [m] + dCDP [c] | `ENSG00000171612`
UTP [c] + GTP [m] <-> UTP [m] + GTP [c] | `ENSG00000171612`
UTP [c] + GDP [m] <-> UTP [m] + GDP [c] | `ENSG00000171612`
UTP [c] + dGTP [m] <-> UTP [m] + dGTP [c] | `ENSG00000171612`
UTP [c] + dGDP [m] <-> UTP [m] + dGDP [c] | `ENSG00000171612`
UTP [c] + ITP [m] <-> UTP [m] + ITP [c] | `ENSG00000171612`
UTP [c] + dTTP [m] <-> UTP [m] + dTTP [c] | `ENSG00000171612`
UTP [c] + dTDP [m] <-> UTP [m] + dTDP [c] | `ENSG00000171612`
UTP [c] + UDP [m] <-> UTP [m] + UDP [c] | `ENSG00000171612`
UTP [c] + dUTP [m] <-> UTP [m] + dUTP [c] | `ENSG00000171612`
CTP [c] <-> CTP [m] | `ENSG00000114120 or ENSG00000171612`
GTP [c] <-> GTP [m] | `ENSG00000114120 or ENSG00000171612`
dTTP [c] <-> dTTP [m] | `ENSG00000171612`
UTP [c] <-> UTP [m] | `ENSG00000114120 or ENSG00000171612`

The only one of those reactions that is already represented in Human-GEM is `MAR08301: dTTP [c] ⇒ dTTP [m]`, but it is irreversible has no genes associated with it; it should be made reversible and have its GPR set to `ENSG00000171612`.

There are also `MAR07823: dCTP [c] ⇒ dCTP [m]`, `MAR07926: dGTP [c] ⇒ dGTP [m]`, and `MAR09019: CDP [c] ⇒ CDP [m]`, none of which have any associated genes. Adding all of the reactions in the table above would allow all three of these metabolites to be exchanged and actually have evidence supporting their existence, so I think `MAR07823`, `MAR07926`, and `MAR09019` should be removed. Similarly, I think `MAR04843: GDP [c] + GTP [m] ⇔ GDP [m] + GTP [c]` should also be removed in favor of the reactions in the above table; it is currently associated with [ALDH1A3](https://www.uniprot.org/uniprotkb/P47895/entry), [ALDH3A1](https://www.uniprot.org/uniprotkb/P30838/entry), and [ALDH3B2](https://www.uniprot.org/uniprotkb/P48448/entry), but none of those known to exchange GTP and GDP between the cytosol and mitochondria. The [only reference](https://doi.org/10.1152/ajpcell.2000.279.6.c1870) associated with `MAR04843` just shows that GTP, GDP, and GMP can be transported into mitochondria from their surroundings and does not identify which gene(s) is/are responsible or even whether this transport is antiport, symport, or uniport.

There are also a large number of reactions that exchange (d)NTPs and (d)NDPs catalyzed by SLC15A19 that should all be removed, but I address that in #695.

### Proposed Changes

- [x] Create new gene entries for `ENSG00000171612` (name: SLC25A33) and `ENSG00000114120` (name: SLC25A36)
- [x] Make `MAR08301` reversible and change its GPR to `ENSG00000171612`
- [x] Remove `MAR07823`
- [x] Remove `MAR07926`
- [x] Remove `MAR09019`
- [x] Remove `MAR04843`
- [x] Create new reaction `CTP [c] + CDP [m] <-> CTP [m] + CDP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + CMP [m] <-> CTP [m] + CMP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dCTP [m] <-> CTP [m] + dCTP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dCDP [m] <-> CTP [m] + dCDP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dCMP [m] <-> CTP [m] + dCMP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + GTP [m] <-> CTP [m] + GTP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + GDP [m] <-> CTP [m] + GDP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + GMP [m] <-> CTP [m] + GMP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dGTP [m] <-> CTP [m] + dGTP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dGDP [m] <-> CTP [m] + dGDP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dGMP [m] <-> CTP [m] + dGMP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + ITP [m] <-> CTP [m] + ITP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + IDP [m] <-> CTP [m] + IDP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + IMP [m] <-> CTP [m] + IMP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + UTP [m] <-> CTP [m] + UTP [c]`, GPR: `ENSG00000114120 or ENSG00000171612`
- [x] Create new reaction `CTP [c] + UDP [m] <-> CTP [m] + UDP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + UMP [m] <-> CTP [m] + UMP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dUTP [m] <-> CTP [m] + dUTP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dUDP [m] <-> CTP [m] + dUDP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `CTP [c] + dUMP [m] <-> CTP [m] + dUMP [c]`, GPR: `ENSG00000114120`
- [x] Create new reaction `UTP [c] + CDP [m] <-> UTP [m] + CDP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + dCTP [m] <-> UTP [m] + dCTP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + dCDP [m] <-> UTP [m] + dCDP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + GTP [m] <-> UTP [m] + GTP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + GDP [m] <-> UTP [m] + GDP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + dGTP [m] <-> UTP [m] + dGTP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + dGDP [m] <-> UTP [m] + dGDP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + ITP [m] <-> UTP [m] + ITP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + dTTP [m] <-> UTP [m] + dTTP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + dTDP [m] <-> UTP [m] + dTDP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + UDP [m] <-> UTP [m] + UDP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `UTP [c] + dUTP [m] <-> UTP [m] + dUTP [c]`, GPR: `ENSG00000171612`
- [x] Create new reaction `CTP [c] <-> CTP [m]`, GPR: `ENSG00000114120 or ENSG00000171612`
- [x] Create new reaction `GTP [c] <-> GTP [m]`, GPR: `ENSG00000114120 or ENSG00000171612`
- [x] Create new reaction `UTP [c] <-> UTP [m]`, GPR: `ENSG00000114120 or ENSG00000171612`

**Comment by feiranl** [comment]
@Devlin-Moyer  these rxns mentioned in the beginning are missing in the tasks/actions.
rxn|grRule
-- | --
CTP [c] <-> CTP [m] | ENSG00000114120 or ENSG00000171612
GTP [c] <-> GTP [m] | ENSG00000114120 or ENSG00000171612

**Comment by Devlin-Moyer** [comment]
oops, looks like I forgot those; I'll add them to the list of new reactions to add

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer very nice findings!

it has been nearly 10 years since the publication of [this paper](https://doi.org/10.1074/jbc.M114.610808), if there are any new isoenzymes of these transporters reported recently?

**Comment by Devlin-Moyer** [comment]
not that I can tell; the only more recent papers that mention either gene were looking for something else and happened to find that one or both was over- or under-expressed in response to some perturbation.

**Comment by haowang-bioinfo** [comment]
> not that I can tell; the only more recent papers that mention either gene were looking for something else and happened to find that one or both was over- or under-expressed in response to some perturbation.

good to know this. I assume it was found manually, if it's possible to get it done by script automatically?

**Comment by Devlin-Moyer** [comment]
yea all the papers I've found for all my issues were ones I found manually, either by directly searching on Google Scholar or looking at references on Uniprot pages for specific proteins; I have no thoughts or experience on any sort of automated paper-finding script

**Comment by haowang-bioinfo** [comment]
fixed in #709
