### ISSUE TITLE
Gene essentiality returning same output for every model

### ISSUE THREAD

**Issue by manas-kohli** [SysBioChalmers/Human-GEM#699]
Hi there! I've recently produced a few models using ftINIT on a particular cohort I'm interested in. After producing the models, I wanted to run a gene essentiality analysis on some metabolic tasks to find potential novel targets between subcategories of interest. However, when I run a gene essentiality anlysis, I end up with the same output for every model which seems odd. I confirmed that each model is unique and have a different number of reactions and metabolites. Also through FBA on the enzyme constraint versions of the models, I also see that they possess different flux vectors. However, every model has the same number of genes as the reference model. I'm not sure if I'm doing anything incorrect so any help would be appreciated. I'll paste the simple function I use for the analysis below. I am also attaching a zip of the folder containing each model (38 in total). 

```
function gene_essentiality(output_path, taskStruc, models, modelids)

for i =1:length(models)

    current_model = addBoundaryMets(models{i});
       
    [~, essentialGenes] = checkTasksGenes(current_model, [], true, false, true, taskStruc);
    
    disp(modelids{i})

    mkdir([output_path '/' modelids{i}])
    write_path_genes = [output_path '/' modelids{i} '/' 'genes_all.csv'];
    writecell(regen_model.genes, write_path_genes)
    write_path_essential_genes = [output_path '/' modelids{i} '/' 'gene_essentiality_matrix.csv'];
    writematrix(essentialGenes, write_path_essential_genes, 'Delimiter', ',')
end

end
```

[Dataset_HumanGEM_GitUpload.zip](https://github.com/SysBioChalmers/Human-GEM/files/12586650/Dataset_HumanGEM_GitUpload.zip)

**Comment by JonathanRob** [comment]
Hmm, I can't remember exactly how ftINIT decides to remove genes, but it does seem a little suspicious that all models would have the same genes as the reference model. Maybe if we can determine the reason for this, it will provide hints to why you are seeing the same set of essential genes for all models.

As a minor note, I don't see where `regen_model` is defined in your pasted function.

**Comment by haowang-bioinfo** [comment]
@manas-kohli thanks for reporting this

if understand correctly, you constructed some cell line-specific models from a group of subjects using ftINIT, and conducted essentiality check using the list of metabolic tasks (`metabolicTasks_Essential`) that are necessary for nearly all cells. Given the homogeneous of the small cohort, it's not surprising that they would report the same list of essential genes.

**Comment by JonathanRob** [comment]
@haowang-bioinfo good point, if the gene expression profiles are quite similar, then it is feasible that the resulting essentiality will be the same. 

@manas-kohli you note that the models _are_ unique with respect to reactions and metabolites; are they quite different, or do they only differ by a small handful of reactions/metabolites?

**Comment by manas-kohli** [comment]
Hi @haowang-bioinfo @JonathanRob,

I had a deeper look at some of the issues and I noted Jonathan's comment about the regen_model function. 

Before looking at the above cohort in more detail, I examined the Breast Cancer Cell Lines from CCLE. I had generated these models both using regular INIT and using ftINIT using the recommended TPM threshold of 1.0. Using regular INIT, I definitely got differing numbers of genes per model and differing results for the gene essentiality analyses. When I repeated this for the CCLE Breast Lines from ftINIT, I again got the same numbers of genes for every model and identical gene essentiality results. 

I've now tried to incorporate the regen_model function:

`function gene_essentiality(output_path, taskStruc, models, modelids, prepData)

for i =1:length(models)
    current_model = addBoundaryMets(models{i});
    %current_model = models{i};
       
    regen_model = regen_tINIT_model(current_model, addBoundaryMets(prepData.refModel), modelids{i});

    [~, essentialGenes] = checkTasksGenes(regen_model, [], true, false, true, taskStruc);
    
    disp(modelids{i})

    mkdir([output_path '/' modelids{i}])
    write_path_genes = [output_path '/' modelids{i} '/' 'genes_all.csv'];
    writecell(regen_model.genes, write_path_genes)
    write_path_essential_genes = [output_path '/' modelids{i} '/' 'gene_essentiality_matrix.csv'];
    writematrix(essentialGenes, write_path_essential_genes, 'Delimiter', ',')
end

end`

When I ran this for two models, I now get differing numbers of genes. I'll hopefully be able to get the gene essentiality results now to confirm whether I get differing gene essentiality results

**Comment by manas-kohli** [comment]
I've run this now on a few models and am getting different results for the gene essentiality. So as Jonathan pointed out it was to do with not running regen_model before calling the function. Many thanks for your help with this! I'll close this issue now
