### ISSUE TITLE
Duplicate species hexanoate/hexanoic acid

### ISSUE THREAD

**Issue by pranasag** [SysBioChalmers/Human-GEM#716]
#### Current behavior:
While dealing with #689, I found that the model has two species that correspond to the same metabolite: hexanoate [MAM03684c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03684c) and hexanoic acid [MAM02120c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02120c). I have checked a couple other short- or medium-chained fatty acids, they do not seem to have duplicates. [MAM03684c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03684c) likely comes from Recon3D, and the other from elsewhere.

#### Expected feature/value/output:
Proposed curation: "merge" species by retaining hexanoic acid [MAM02120c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02120c) for consistency with other metabolite names, e.g. octanoic acid [MAM02642c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02642c). 

Identify identical reactions between the two, and remove the one for hexanoate. GPRs are likely to be the same for duplicate reactions, but needs checking as well. In case of unique reactions, swap hexanoate [MAM03684c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03684c) for hexanoic acid [MAM02120c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02120c).

Any other tips/suggestions? Or good to go?

**Comment by haowang-bioinfo** [comment]
makes sense - go ahead please

**Comment by haowang-bioinfo** [comment]
fixed in #717
