### ISSUE TITLE
Duplicate 2-oxoadipate dehydrogenase reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#719]
### Current behavior:

`MAR04239: 2-oxoadipate + CoA + NAD+ --> CO2 + glutaryl-CoA + NADH`, GPR: `DLD and OGDH and DLST`
is the same as the net reaction of the following three reactions:
`MAR04599: 2-oxoadipate + H+ + lipoamide --> CO2 + S-glutaryldihydrolipoamide`, GPR: `OGDH or DHTKD1 or OGDHL`
`MAR06415: CoA + S-glutaryldihydrolipoamide --> dihydrolipoamide + glutaryl-CoA`, GPR: `DLST`
`MAR06409: H+ + lipoamide + NADH <=> dihydrolipoamide + NAD+`, GPR: `DLD`

### Expected feature/value/output:

Following the same rationale as #524, #529, and #660:
- [x] `MAR04239` should be removed for being a duplicate of `MAR04599` + `MAR06415`
- [x] The GPR of `MAR04599` should be changed to `(OGDH and DLST) or (DHTKD1 and DLST)`, since the lipoamide it uses is bound to DLST ([source](https://doi.org/10.1007/s10545-014-9705-8)) and OGDHL doesn't appear to catalyze this reaction ([source](https://academic.oup.com/hmg/article/29/7/1168/5803135))
  - [x] Add `PMID:28757203` to the list of references for `MAR04599`
- [x] Remove OGDHL from the GPR of `MAR04209` and `MAR06413`, since OGDHL doesn't appear to catalyze these reactions ([source](https://academic.oup.com/hmg/article/29/7/1168/5803135))

**Comment by haowang-bioinfo** [comment]
yes, it seems reasonable to remove MAR04239

regarding the change to GPR of MAR04599, can you please paste the direct evidence from that source

**Comment by Devlin-Moyer** [comment]
So that paper I cited in the original comment never super directly states that DLST is lipoylated, but [this one](https://doi.org/10.1016/j.ajhg.2017.07.001) does, right at the beginning:

> Lipoic acid (LA) is an essential cofactor of major mitochondrial enzyme complexes (Figure S1), including the glycine cleavage system (GCS) and four 2-oxoacid dehydrogenases, namely [...] 2-oxoadipate dehydrogenase (2-OADH, lysine catabolism). This cofactor is covalently bound to a conserved lysine residue of the E2 subunits of PDHc, BCKDHc, 2-OADH, and α-KGDHc as well as the H protein of GCS.

Figure S1:
![image](https://github.com/SysBioChalmers/Human-GEM/assets/33460176/aa4ef8b7-fd35-4f72-85ca-5d582b792589)

I just updated my proposed changes to include adding this paper as a reference for `MAR04599`

**Comment by haowang-bioinfo** [comment]
> 2-oxoadipate dehydrogenase (2-OADH, lysine catabolism). This cofactor is covalently bound to a conserved lysine residue of the E2 subunits of PDHc, BCKDHc, 2-OADH, and α-KGDHc as well as the H protein of GCS

maybe there are multiple aliases names, just to be sure, which of these is DLST?

**Comment by Devlin-Moyer** [comment]
DLST is the E2 subunit of both the 2-OADH (2-OxoAdipate DeHydrogenase) and α-KGDHc (α-KetoGlutarateDehydrogenase) complexes

**Comment by haowang-bioinfo** [comment]
> This cofactor is covalently bound to a conserved lysine residue of the E2 subunits of PDHc, BCKDHc, 2-OADH, and α-KGDHc as well as the H protein of GCS

according this description, DLST (E2 subunit of both the 2-OADH) should be part of the GPR of MAR04599.

Now the proposed GPR `(OGDH or DHTKD1 or OGDHL) and DLST` reflects that MAR04599 is catlyzed by a complex of E1 and E1 subunits. For the three paralogues of E1, please double if OGDHL should be included or not.

**Comment by Devlin-Moyer** [comment]
From [this paper](https://academic.oup.com/hmg/article/29/7/1168/5803135):
> The activity with OG increased only upon transfection of OGDH, while the activity with OA increased upon transfection of DHTKD1 and/or OGDH (Fig. 3A and Supplementary Material, Fig. S3B and C). [...] Transient transfection of OGDHL or MRPS36 did not increase 2-oxo acid dehydrogenase activity in HEK-293 cell lysates using either OA or OG substrates.

So perhaps OGDHL should be removed from MAR04599 as well as MAR04209 and MAR06413, since it seems to have no measurable impact on catalysis of either reaction. I noticed that [Uniprot](https://www.uniprot.org/uniprotkb/Q9ULD0/entry) only associates OGDHL with the dehydrogenation of 2-oxoglutarate "by similarity", and the above paper is the only one I can find that directly assess catalytic activity of OGDHL independently of OGDH; most of the others I can find that mention OGDHL implicitly treat it as functionally equivalent to OGDH.

**Comment by haowang-bioinfo** [comment]
thanks for the investigation - yes, OGDHL can only be associated with the dehydrogenation of 2-oxoglutarate "By Similarity", according to [Uniprot](https://www.uniprot.org/uniprotkb/Q9ULD0/entry). No evidence for the others (MAR04599, MAR04209, and MAR06413) even by similarity

**Comment by haowang-bioinfo** [comment]
it might worth revisiting the removal of OGDHL from MAR04599, MAR04209 and MAR06413; such an implementation in #725 led to its removal from Human-GEM completely and this might be an overkill

it appears that OGDHL should still be kept for MAR04209 and MAR06413, given the [Uniprot](https://www.uniprot.org/uniprotkb/Q9ULD0/entry) annotation as 2-oxoglutarate dehydrogenase-like.

**Comment by Devlin-Moyer** [comment]
As I mentioned earlier, [this paper](https://academic.oup.com/hmg/article/29/7/1168/5803135) found that
>Transient transfection of OGDHL or MRPS36 *did not increase 2-oxo acid dehydrogenase activity* in HEK-293 cell lysates using *either OA or OG substrates.*
where OA = 2-oxoadipate and OG = 2-oxoglutarate
and once again, Uniprot's only references for associating OGDHL with the OGDH reaction is "by similarity" (the two papers it cites at the very beginning only establish OGDHL's role in signalling pathways, not as an enzyme)

**Comment by haowang-bioinfo** [comment]
So the Uniprot assignment of OGDHL "by similarity" is actually overridden by the experimental validation in [this paper](https://academic.oup.com/hmg/article/29/7/1168/5803135).

**Comment by haowang-bioinfo** [comment]
> Transient transfection of OGDHL or MRPS36 did not increase 2-oxo acid dehydrogenase activity in HEK-293 cell lysates using either OA or OG substrates.

The paper is relatively new, maybe this info should be updated to Uniprot somehow. How did you trace to it specifically @Devlin-Moyer ?

**Comment by Devlin-Moyer** [comment]
pretty sure I just searched for something along the lines of "OGDHL catalytic activity" on Google Scholar; nothing fancy

**Comment by haowang-bioinfo** [comment]
pretty sure this should be turned into something processed regularly by bots

**Comment by haowang-bioinfo** [comment]
fixed by #725
