### ISSUE TITLE
MAR04665 is probably not an enzyme-catalyzed reaction

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#720]
### Current behavior:

The GPR of `MAR04665: 5,10-methenyl-THF + H2O --> 5-formyl-THF + H+` is currently `DLD and GCSH and AMT and GLDC`

### Problems:

I can find no evidence that any of those genes encodes an enzyme capable of catalyzing this reaction; Uniprot ([DLD](https://www.uniprot.org/uniprotkb/P09622/entry), [GCSH](https://www.uniprot.org/uniprotkb/P23434/entry), [AMT](https://www.uniprot.org/uniprotkb/P48728/entry), [GLDC](https://www.uniprot.org/uniprotkb/P23378/entry)) associates them with steps of the glycine cleavage system. Therefore, I think all four should be removed from the GPR of `MAR04665`.

I tried to find out if there was a different enzyme that catalyzed this reaction, and noticed that `MAR04665` matches [RHEA:34767](https://www.rhea-db.org/rhea/34767), which is associated with exactly one protein in Uniprot: [the E. coli serine hydroxymethyltransferase (SHMT)](https://www.uniprot.org/uniprotkb/P0A825/entry). The [paper](https://www.jbc.org/article/S0021-9258(18)77290-6/fulltext) that Uniprot cites to support that showed that both the E. coli and rabbit SHMTs could catalyze this reaction (they did not test the human SHMT), but [this paper](https://doi.org/10.1021/bi001362m) says that that paper was wrong and this hydrolysis reaction is actually non-enzymatic _in vivo_. I tried seeing if there were any more recent papers about this reaction that mentioned whether or not any human enzymes could catalyze it, but couldn't find anything.

### Proposed Changes:

- [x] Remove all genes from the GPR of `MAR04665`
- [ ] Add `PMID:11087421` to the list of references for `MAR04665`

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer interesting issue

Based on [the paper](https://doi.org/10.1021/bi001362m) you provided, `it is hypothesized that mildly acidic (4.0 to 4.5) subcellular organelles provide an environment for the hydrolysis of 5,10-methenyltetrahydrofolate to 5-formyltetrahydrofolate in vivo, and there is no requirement for enzyme catalysis`. However, MAR04665 is localized in [m] and in intact mitochondria, [pH remains alkaline with resting mitochondrial pH values ranging from 7.2 to 8.2 in different cell types](https://www.jbc.org/article/S0021-9258(20)53786-1/fulltext). That said, this citation doesn't support MAR04665 as a spontaneous one.

**Comment by Devlin-Moyer** [comment]
oh yea I suppose not; I still think that it's incorrect to associate this reaction with GCSH, GLDC, AMT, and/or DLD. Do you think we should associate it with SHMT, since the E. coli and rabbit homologues may catalyze this reaction? Or can we still leave it associated with no genes with the idea that it isn't spontaneous but the enzyme that catalyzes it is unknown?

**Comment by Devlin-Moyer** [comment]
I suppose another question is: do we have any evidence that this reaction actually occurs in human mitochondria? That paper suggested that it might occur in lysosomes, and the mitochondrial enzymes it's currently associated with don't seem to actually catalyze it

**Comment by haowang-bioinfo** [comment]
Good question - maybe look for more evidence supporting its lysosome localization

**Comment by haowang-bioinfo** [comment]
> oh yea I suppose not; I still think that it's incorrect to associate this reaction with GCSH, GLDC, AMT, and/or DLD. Do you think we should associate it with SHMT, since the E. coli and rabbit homologues may catalyze this reaction? Or can we still leave it associated with no genes with the idea that it isn't spontaneous but the enzyme that catalyzes it is unknown?

agree that seems no evidence support the association of MAR04665 with the four genes, which may be taken away. Between SHMT and no genes, I would lean toward ENSG00000182199 (SHMT2).

**Comment by Devlin-Moyer** [comment]
Fixed in #724
