### ISSUE TITLE
Transport of Glutathione into Mitochondria

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#722]
### Current behavior:
There are currently three reactions that transport glutathione (`MAM02026`) between [c] and [m]:
ID | Reaction | Genes
---|---|---
`MAR04940` | GSH [c] + Pi [m] --> GSH [m] + Pi [c] | SLC25A10
`MAR06391` | AKG [c] + GSH [m] <=> AKG [m] + GSH [c] | SLC25A11
`MAR08771` | ATP [c] + GSH [c] + H2O [c] --> ADP [c] + GSH [m] + H+ [c] + Pi [c] | none

### Problems:

[This paper](https://febs.onlinelibrary.wiley.com/doi/10.1016/j.febslet.2015.01.027) found that neither SLC25A10 nor SLC25A11 were capable of transporting glutathione. `MAR08771` has no genes or references associated with it; it is associated with [RHEA:29792](https://www.rhea-db.org/rhea/29792), but the only reference RHEA has for that reaction is about E. coli, and all of the proteins [Uniprot](https://www.uniprot.org/uniprotkb/?query=rhea:29791) associates with this RHEA ID are bacterial.

[This paper](https://www.nature.com/articles/s41586-021-04025-w) found that SLC25A39 (`ENSG00000013306`) and SLC25A40 (`ENSG00000075303`) are capable of transporting glutathione into mitochondria in human cells. They also found that knocking out both at the same time seems to completely block transport of glutathione into mitochondria in HEK293T and Jurkat cells, i.e. these are, in at least some human cell types, the only two mitochondrial glutathione transporters.

Unfortunately, that paper didn't do any experiments to figure out if SLC25A39 and SLC25A40 are ATP-dependent or require antiport of glutathione with some other metabolite. The only other paper I can find that characterizes either protein is [this one](https://www.nature.com/articles/s41467-022-30126-9), which only mentions SLC25A39 and also doesn't clarify ATP (in)dependence or antiport vs uniport. [Uniprot](https://www.uniprot.org/uniprotkb/Q9BZJ4/entry) associates SLC25A39 with [RHEA:74819](https://www.rhea-db.org/rhea/74819), which is just reversible uniport of glutathione between two arbitrary compartments. The only two papers RHEA cites are the two I just linked above, so I feel like it's reasonable to conclude that, given the evidence that is currently available, the best representation of mitochondrial glutathione transport in human cells is ATP-independent uniport.

### Proposed Changes:

- [x] Remove `MAR04940` and `MAR06391`
- [x] Edit `MAR08771` to be `MAM02026c --> MAM02026m`, GPR: `ENSG00000013306 or ENSG00000075303`, `RHEA:74819`

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer thanks for providing this [evidence](https://www.nature.com/articles/s41586-021-04025-w) that demonstrate DIC (SLC25A10) and OGC (SLC25A11) do not transport GSH. This suggests that SLC25A10 and SLC25A11 should be taken away from the GPRs of MAR04940 and MAR06931, respectively.

**Comment by haowang-bioinfo** [comment]
> [This paper](https://www.nature.com/articles/s41586-021-04025-w) found that SLC25A39 (ENSG00000013306) and SLC25A40 (ENSG00000075303) are capable of transporting glutathione into mitochondria in human cells. They also found that knocking out both at the same time seems to completely block transport of glutathione into mitochondria in HEK293T and Jurkat cells, i.e. these are, in at least some human cell types, the only two mitochondrial glutathione transporters.
> 
> Unfortunately, that paper didn't do any experiments to figure out if SLC25A39 and SLC25A40 are ATP-dependent or require antiport of glutathione with some other metabolite. The only other paper I can find that characterizes either protein is [this one](https://www.nature.com/articles/s41467-022-30126-9), which only mentions SLC25A39 and also doesn't clarify ATP (in)dependence or antiport vs uniport. [Uniprot](https://www.uniprot.org/uniprotkb/Q9BZJ4/entry) associates SLC25A39 with [RHEA:74819](https://www.rhea-db.org/rhea/74819), which is just reversible uniport of glutathione between two arbitrary compartments. The only two papers RHEA cites are the two I just linked above, so I feel like it's reasonable to conclude that, given the evidence that is currently available, the best representation of mitochondrial glutathione transport in human cells is ATP-independent reversible uniport.

Two questions: 
1. both papers here suggest that SLC25A39, and it paralogue SLC25A40, function as importer `MAM02026c -> MAM02026m`, why propose it as reversible? 
2. why is the GSH transport ATP independent?

**Comment by Devlin-Moyer** [comment]
I proposed reversible transport cuz Uniprot/RHEA associated SLC25A39 with the master (undefined direction) RHEA ID rather than either of the direction-specific ones. It now occurs to me that [the](https://www.nature.com/articles/s41586-021-04025-w) [papers](https://www.nature.com/articles/s41467-022-30126-9) I cited both mentioned that glutathione biosynthesis only occurs in the cytosols of human cells, so on top of the fact that they don't provide any evidence that either transporter can export glutathione, human mitochondria probably never have any reason to export glutathione anyway. I've edited my proposed changes accordingly

I said that glutathione transport into mitochondria is ATP-independent because I couldn't find anything to show that SLC25A39 or SLC25A40 were or weren't ATP-dependent (or that glutathione import into mitochondria in general by any mechanism is an ATP-dependent process in human cells), and I felt like it made more sense to go with the simpler option (ATP-independent transport) in the absence of evidence.

**Comment by Devlin-Moyer** [comment]
>further evidence supporting either direct removal of MAR04940 and MAR06391, or assignment of new genes to their GPRs?

As far as I can tell, the only evidence that ever supported the existence of `MAR04940` or `MAR06391` was disproven by [this paper](https://febs.onlinelibrary.wiley.com/doi/10.1016/j.febslet.2015.01.027), and the only other human genes anyone has ever shown to be capable of transporting glutathione into mitochondria by are SLC25A39 and SLC25A40.

**Comment by haowang-bioinfo** [comment]
thanks for answers that seem to be rational

maybe start a branch and give a try, let's see what would happen to those GH action checks

**Comment by haowang-bioinfo** [comment]
fixed by #723
