### ISSUE TITLE
DECR1 and DECR2 use NADPH, not NADH

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#736]
### Current behavior:

These are all reactions currently in Human-GEM that use NADH to reduce 2,4-dienoyl-CoAs and are associated with DECR1 and/or DECR2:

ID|Reaction
---|---
`MAR03322` | 2-trans-4-cis-decadienoyl-CoA [x] + H+ [x] + NADH [x] --> NAD+ [x] + trans-3-decenoyl-CoA [x]
`MAR03296` | 2-trans-4-cis-decadienoyl-CoA [m] + H+ [m] + NADH [m] --> NAD+ [m] + trans-3-decenoyl-CoA [m]
`MAR06433` | 11-carboxy-alpha-tocotrienol [m] + ATP [m] + CoA [m] + 2 H2O [m] + NAD+ [m] + O2 [m] --> 9-carboxy-alpha-tocotrienol [m] + acetyl-CoA [m] + AMP [m] + 2 H+ [m] + H2O2 [m] + NADH [m] + PPi [m]
`MAR06448` | 11-carboxy-gamma-tocotrienol [m] + ATP [m] + CoA [m] + 2 H2O [m] + NAD+ [m] + O2 [m] --> 9-carboxy-gamma-tocotrienol [m] + acetyl-CoA [m] + AMP [m] + 2 H+ [m] + H2O2 [m] + NADH [m] + PPi [m]

### Expected behavior:

[DECR1](https://www.uniprot.org/uniprotkb/Q16698/entry) (the mitochondrial enzyme) and [DECR2](https://www.uniprot.org/uniprotkb/Q9NUI1/entry) (the peroxisomal equivalent) both appear to be exclusively capable of using NADPH and not NADH to catalyze this reaction. `MAR04970` and `MAR04974` already represent NADPH-dependent equivalents of `MAR03296` and `MAR03322`, respectively, so `MAR03322` and `MAR03296` can just be removed. The other two have a number of other problems, which I address separately in #738 

### Proposed changes:

- [ ] Remove `MAR03322` for being a less accurate version of `MAR04974`
- [ ] Remove `MAR03296` for being a less accurate version of `MAR04970`

**Comment by haowang-bioinfo** [comment]
> [DECR1](https://www.uniprot.org/uniprotkb/Q16698/entry) (the mitochondrial enzyme) and [DECR2](https://www.uniprot.org/uniprotkb/Q9NUI1/entry) (the peroxisomal equivalent) both appear to be exclusively capable of using NADPH and not NADH to catalyze this reaction. MAR04970 and MAR04974 already represent NADPH-dependent equivalents of MAR03296 and MAR03322, respectively, so MAR03322 and MAR03296 can just be removed.

yes, it does appear that the NAD versions (MAR03322 and MAR03296) should be removed.

additionally and relevant to this, MAR04005 (the cytosol version of MAR04970[m] and MAR04974[x]) may also be revmoed?

**Comment by Devlin-Moyer** [comment]
yes it does look like `MAR04005` is isolated and there's no reason to believe it'd happen in the cytosol, so it makes sense to remove it along with `MAM00678c` and  `MAM03035c` (since `MAR04005` is the only reaction either of those metabolites participate in)

**Comment by haowang-bioinfo** [comment]
MAR04005 is removed by fa52bf007c21a8750c5b577fc0a8f55448ea849a in #788

**Comment by haowang-bioinfo** [comment]
MAM00678c and MAM03035c are now removed by 1e2fac9de6702bdf6120b6dc8ddaf8527c8211f1

**Comment by haowang-bioinfo** [comment]
fixed by #788
