### ISSUE TITLE
ACAD10

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#739]
When working on #726, I noticed that ACAD10 (`ENSG00000111271`) is currently associated with only two reactions in Human-GEM:

ID | reaction | GPR
---|---|---
MAR03212 | FAD [m] + propanoyl-CoA [m] --> acrylyl-CoA [m] + FADH2 [m] | ACAD10 or ACADM or ACADS or ACAD8 or ACAD9 or ACADSB or ACAD11
MAR03163 | butyryl-CoA [m] + FAD [m] --> crotonyl-CoA [m] + FADH2 [m] | ACAD10 or ACADM or ACADS or ACAD8 or ACAD9 or ACADSB or ACAD11

[Uniprot](https://www.uniprot.org/uniprotkb/Q6JQN1/entry) says ACAD10 can only act on (R)- and (S)-2-methyl-pentadecanoyl-CoA, citing [this paper](https://doi.org/10.1016/j.ymgme.2010.12.005). From the end of the paragraph under the section heading "Prokaryotic expression of ACAD10 and ACAD11" of that paper:

>Extracts from cells expressing a predicted mature mitochondrial ACAD10 insert were only active with R and S, 2 methyl-C15-CoA (R and S, 2-methyl-pentadecanoyl-CoA) among a broad series of other substrates including the optimum ones for all of the other ACADs. The measured activity (1.4 mU/mg at 150 μM substrate concentration) is considerably lower than that obtained with other expressed ACADs towards their optimum substrates, suggesting that the dehydrogenation reaction between ACAD10 and R or S, 2 methyl-C15-CoA is unlikely the optimal function for ACAD10 in vivo.

I can't seem to find any other papers that ever showed that ACAD10 can act on propanoyl-CoA, butyryl-CoA, or anything else. Also Human-GEM does not already seem to have a metabolite for 2-methyl-pentadecanoyl-CoA; the closest I can find is pristanoyl-CoA (`MAM00078x`), i.e. 2,6,10,14-tetramethylpentadecanoyl-CoA, but that's known to be oxidized by peroxisomal beta-oxidation ([source](https://doi.org/10.1016/S0163-7827(01)00011-X)), and ACAD10 seems to be localized to mitochondria, or at least not localized to peroxisomes ([source](https://doi.org/10.1016/j.ymgme.2010.12.005)).

I think ACAD10 should be removed from the GPRs of `MAR03212` and `MAR03163` and also removed from Human-GEM altogether.

This is slightly redundant with the proposed changes in #634, since both reactions are also associated with ACAD11, which is localized to peroxisomes, but the metabolites are all mitochondrial, and #634 proposes new GPRs that only contain genes that code for mitochondrial proteins known to catalyze this kind of reaction.

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer thanks for collecting the evidence, in which the statement "ACAD10 insert were only active with R and S, 2 methyl-C15-CoA among a broad series of other substrates including the optimum ones for all of the other ACADs" supports the removal of MAR03212 and MAR03163, as well as Human-GEM

**Comment by haowang-bioinfo** [comment]
fixed by #740
