### ISSUE TITLE
Duplicate Branched-Chain Ketoacid Dehydrogenase Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#741]
#### Current behavior:

There are currently two parallel/redundant reactions/pathways for oxidative decarboxylation of 2-oxo-3-methylvalerate (`MAM00669m`) and 3-methyl-2-oxobutyrate (`MAM00824m`):

ID | Reaction | Notes
--- | --- | ---
MAR03748 | 3-methyl-2-oxobutyrate [m] + CoA [m] + NAD+ [m] ⇒ CO2 [m] + NADH [m] + isobutyryl-CoA [m] | One-step version
MAR06416 | 3-methyl-2-oxobutyrate [m] + H+ [m] + lipoamide [m] ⇒ CO2 [m] + S-(2-methylpropanoyl)-dihydrolipoamide [m] | First step of three-step version
MAR06417 | CoA [m] + S-(2-methylpropanoyl)-dihydrolipoamide [m] ⇔ dihydrolipoamide [m] + isobutyryl-CoA [m] | Second step of three-step version
MAR06409 | H+ [m] + NADH [m] + lipoamide [m] ⇔ NAD+ [m] + dihydrolipoamide [m] | Third step of three-step version
| |
MAR03780 | 2-oxo-3-methylvalerate [m] + CoA [m] + NAD+ [m] ⇒ 2-methylbutyryl-CoA [m] + CO2 [m] + NADH [m] | One-step version
MAR06419 | 2-oxo-3-methylvalerate [m] + H+ [m] + lipoamide [m] ⇒ CO2 [m] + S-(2-methylbutanoyl)-dihydrolipoamide [m] | First step of three-step version
MAR06420 | CoA [m] + S-(2-methylbutanoyl)-dihydrolipoamide [m] ⇒ 2-methylbutyryl-CoA [m] + dihydrolipoamide [m] | Second step of three-step version
MAR06409 | H+ [m] + NADH [m] + lipoamide [m] ⇔ NAD+ [m] + dihydrolipoamide [m] | Third step of three-step version

#### Expected feature/value/output:

This situation is analogous to the situations in #524 and #633; these are reactions catalyzed by the branched-chain alpha-ketoacid dehydrogenase (BCKDH) complex, which uses lipoic acid (bound to a lysine residue on one of the subunits, hence the lipo _amide_) as a cofactor ([source](https://doi.org/10.1007/s00726-017-2412-7)). In line with the changes we made when resolving the duplicate representations of the other alpha-ketoacid dehydrogenase complexes, I think the one-step versions, i.e. `MAR03748` and `MAR03780`, should be removed.

#### Proposed changes:
- [x] Remove `MAR03748` for being a duplicate of `MAR06416` + `MAR06417` + `MAR06409`
- [x] Remove `MAR03780` for being a duplciate of `MAR06419` + `MAR06420` + `MAR06409`

**Comment by haowang-bioinfo** [comment]
Very clear, makes sense, go ahead please

**Comment by haowang-bioinfo** [comment]
fixed by #743
