### ISSUE TITLE
Genes Associated with the BCKDH Complex and Thiocyanate

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#742]
### Current behavior:

While working on #741, I noticed some suspicious things about the genes associated with the branched-chain ketoacid dehydrogenase (BCKDH) complex reactions, specifically the reactions that BCKDHA (`ENSG00000248098`), BCKDHB (`ENSG00000083123`), and TMEM91 (`ENSG00000142046`) are associated with:

ID | Reaction | Genes
--- | --- | ---
MAR03800 | 2-oxobutyrate + CoA + NAD+ --> CO2 + NADH + propanoyl-CoA | BCKDHB and DLD and DBT and BCKDHA
MAR06416 | 3-methyl-2-oxobutyrate + H+ + lipoamide --> CO2 + S-(2-methylpropanoyl)-dihydrolipoamide | BCKDHB and TMEM91 and BCKDHA
MAR06419 | 2-oxo-3-methylvalerate + H+ + lipoamide --> CO2 + S-(2-methylbutanoyl)-dihydrolipoamide | BCKDHB and TMEM91 and BCKDHA
MAR06421 | 4-methyl-2-oxopentanoate + H+ + lipoamide --> CO2 + S-(3-methylbutanoyl)-dihydrolipoamide | BCKDHB and TMEM91 and BCKDHA
MAR02532 | H+ [m] + H2O2 [m] + thiocyanate [m] <=> H2O [m] + hypothiocyanite [m] | BCKDHB or DLD or BCKDHA
MAR02534 | H+ [n] + H2O2 [n] + thiocyanate [n] <=> H2O [n] + hypothiocyanite [n] | MPO
MAR06523 | H+ [c] + H2O2 [c] + thiocyanate [c] <=> H2O [c] + hypothiocyanite [c] | PRDX6 or EPX or PXDN or TMEM91 or LPO

(These are all reactions associated with BCKDHA, BCKDHB, and/or TMEM91 except for `MAR03748` or `MAR03780`, since I just proposed to have those reactions removed in #741)

### Expected feature/value/output:

While there is evidence to associate BCKDHA and BCKDHB with `MAR03800`, `MAR06416`, `MAR06419`, and `MAR06421` (see table 1 of [this paper](https://doi.org/10.1007/s00726-017-2412-7)), I think DBT (`ENSG00000137992`) should be added to the GPRs of `MAR06416`, `MAR06419`, and `MAR06421`, since the lipoyl cofactor of the BCKDH complex is specifically bound to DBT (see previously cited paper and [Uniprot](https://www.uniprot.org/uniprotkb/P11182/entry)). Relatedly, I can find no evidence that [TMEM91](https://www.uniprot.org/uniprotkb/Q6ZNR0/entry) (`ENSG00000142046`) is known to catalyze any reactions, so I think it should be removed from all of these reactions' GPRs and from Human-GEM entirely.

While [one of the references](https://doi.org/10.1093/ajcn/68.1.72) associated with `MAR02532` mentions the subunits of the BCKDH complex, it only associates them with branched-chain amino acid metabolism and does not mention thiocyanate or hypothiocyanite. Furthermore, I don't think `MAR02532` should exist at all: while [the other reference](https://doi.org/10.1074/jbc.M004881200) associated with `MAR02532` mentions that [EPX](https://www.uniprot.org/uniprotkb/P11678/entry) (`ENSG00000121053`), [LPO](https://www.uniprot.org/uniprotkb/P22079/entry) (`ENSG00000167419`) and [MPO](https://www.uniprot.org/uniprotkb/P05164/entry) can all catalyze this reaction, none of them are localized to mitochondria (see linked Uniprot entries). Some papers (e.g. [1](https://doi.org/10.1016/j.redox.2020.101602), [2](https://doi.org/10.1089/ars.2020.8030)) mention that hypothiocyanite can interact with several mitochondrial proteins, but they never mention any mitochondrial enzymes capable of producing it. Relatedly, `MAR02534` is a nuclear version of this reaction that I also think should be removed -- it's only associated with MPO, which seems to be an exclusively lysosomal and/or extracellular protein (see Uniprot and other papers cited in this paragraph).

As far as I can tell, neither [PXDN](https://www.uniprot.org/uniprotkb/Q92626/entry) (`ENSG00000130508`) nor [PRDX6](https://www.uniprot.org/uniprotkb/P30041/entry) (`ENSG00000117592`) are capable of catalyzing `MAR06523`; Uniprot only associates them with somewhat similar reactions (bromide + H<sub>2</sub>O<sub>2</sub> -> hypobromite for PXDN and glutathione + H<sub>2</sub>O<sub>2</sub> -> glutathione disulfide + water for PRDX6), and they're already associated with plenty of other reactions that they probably do catalyze (e.g. `MAR04121`), so I think both genes should be removed from the GPR of `MAR06523`.

### Proposed changes:
- [x] Add `ENSG00000137992` to the GPRs of `MAR06416`, `MAR06419`, and `MAR06421`
- [x] Remove `MAR02532` and `MAM02158m`
- [x] Remove `MAR02534`, `MAM02158n`, and `MAM02986n`
- [x] Remove `ENSG00000130508` and `ENSG00000117592` from the GPR of `MAR06523`
- [x] Add `PMID:11013238` and `PMID:31989833` to the list of references for `MAR06523`
- [x] Remove `ENSG00000142046` from the GPRs of `MAR06416`, `MAR06419`, `MAR06421`, and `MAR06523` as well as the list of genes in Human-GEM

**Comment by JonathanRob** [comment]
Thanks again for your investigation @Devlin-Moyer (here and elsewhere). I agree with these changes, though some parts are a bit unclear due to some likely typos in IDs. For example, the second proposed change is to remove `MAR02354`, but it's not mentioned elsewhere in your text and doesn't seem directly related.

**Comment by Devlin-Moyer** [comment]
ah yea that was a typo of MAR02534, the nuclear version of the thiocyanate + peroxide -> hypothiocyanite reaction

**Comment by haowang-bioinfo** [comment]
this is an interesting issue that has two sections that appears to be irrelevant: i) the changes regarding BCKDH Complex are clear and straightforward; ii) the interconversions of `thiocyanate <-> hypothiocyanite` in different compartments are messy

Some questions:
1. should DLD be added to the GPRs of MAR06416, MAR06419, and MAR06421 as well?
2. is there any evidence supporting MAR06523 after all?

**Comment by Devlin-Moyer** [comment]
DLD should not be added to `MAR06416`, `MAR06419`, or `MAR06421`, because it is responsible for oxidizing dihydrolipoyl residues to lipoyl residues, which is not what is happening in those three reactions. See #529 for more details on DLD.

The evidence supporting the existence of `MAR06523` is that both [LPO](https://www.uniprot.org/uniprotkb/P22079/entry#subcellular_location) and [EPX](https://www.uniprot.org/uniprotkb/P11678/entry#subcellular_location) are localized to the cytosol according to Uniprot, and both are capable of catalyzing that reaction according to [this paper](https://doi.org/10.1074/jbc.M004881200).

**Comment by haowang-bioinfo** [comment]
thanks for the clarification @Devlin-Moyer

**Comment by haowang-bioinfo** [comment]
fixed by #750
