### ISSUE TITLE
Inconsistent Representation of Thiamine's Role in 2-Oxoacid Dehydrogenase Complexes

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#744]
#### Current behavior:

In #524, when resolving the duplicate representations of the pyruvate dehydrogenase (PDH) and 2-oxoglutarate dehydrogenase (OGDH) complexes, we decided to keep the sets of reactions that explicitly show the involvement of thiamine in the catalytic mechanism (see [this comment](https://github.com/SysBioChalmers/Human-GEM/issues/524#issuecomment-1518575254) in particular for the rationale). The reactions representing the catalytic activities of the 2-oxoadipate dehydrogenase (OADH) and branched-chain ketoacid dehydrogenase (BCKDH) complexes do not show the involvement of thiamine, despite the fact that all four complexes use thiamine in exactly the same way (sources for [BCKDH](https://doi.org/10.1074/jbc.M610843200) and [OADH](https://doi.org/10.1016/j.bbabio.2018.05.001)):

Complex | ID | Reaction | Genes
---|---|---|---
PDH | MAR08746 | H+ + pyruvate + thiamin-PP --> 2-(alpha-hydroxyethyl)thiamine-diphosphate + CO2 | (PDHA1 and PDHB) or (PDHA2 and PDHB)
PDH | MAR20069 | 2-(alpha-hydroxyethyl)thiamine-diphosphate + lipoamide --> S-acetyldihydrolipoamide + thiamin-PP | (PDHA1 and PDHB and DLAT) or (PDHA2 and PDHB and DLAT)
PDH | MAR06412 | CoA + S-acetyldihydrolipoamide --> acetyl-CoA + dihydrolipoamide | PDHX and DLAT
PDH | MAR06409 | H+ + lipoamide + NADH <=> dihydrolipoamide + NAD+ | DLD
| | |
OGDH | MAR04209 | AKG + H+ + thiamin-PP --> 3-carboxy-1-hydroxypropyl-ThPP + CO2 | OGDH or DHTKD1
ODGH | MAR06413 | 3-carboxy-1-hydroxypropyl-ThPP + lipoamide --> S-succinyldihydrolipoamide + thiamin-PP | OGDH or DHTKD1
OGDH | MAR06414 | CoA + S-succinyldihydrolipoamide <=> dihydrolipoamide + succinyl-CoA | DLST
OGDH | MAR06409 | H+ + lipoamide + NADH <=> dihydrolipoamide + NAD+ | DLD
| | |
OADH | MAR04599 | 2-oxoadipate + H+ + lipoamide --> CO2 + S-glutaryldihydrolipoamide | (OGDH and DLST) or (DHTKD1 and DLST)
OADH | MAR06415 | CoA + S-glutaryldihydrolipoamide --> dihydrolipoamide + glutaryl-CoA | DLST
OADH | MAR06409 | H+ + lipoamide + NADH <=> dihydrolipoamide + NAD+ | DLD
| | |
BCKDH | MAR06416 | 3-methyl-2-oxobutyrate + H+ + lipoamide --> CO2 + S-(2-methylpropanoyl)-dihydrolipoamide | BCKDHB and TMEM91 and BCKDHA
BCKDH | MAR06417 | CoA + S-(2-methylpropanoyl)-dihydrolipoamide <=> dihydrolipoamide + isobutyryl-CoA | DBT
BCKDH | MAR06409 | H+ + lipoamide + NADH <=> dihydrolipoamide + NAD+ | DLD
| | |
BCKDH | MAR06419 | 2-oxo-3-methylvalerate + H+ + lipoamide --> CO2 + S-(2-methylbutanoyl)-dihydrolipoamide | BCKDHB and TMEM91 and BCKDHA
BCKDH | MAR06420 | CoA + S-(2-methylbutanoyl)-dihydrolipoamide --> 2-methylbutyryl-CoA + dihydrolipoamide | DBT
BCKDH | MAR06409 | H+ + lipoamide + NADH <=> dihydrolipoamide + NAD+ | DLD
| | |
BCKDH | MAR06421 | 4-methyl-2-oxopentanoate + H+ + lipoamide --> CO2 + S-(3-methylbutanoyl)-dihydrolipoamide | BCKDHB and TMEM91 and BCKDHA
BCKDH | MAR06422 | CoA + S-(3-methylbutanoyl)-dihydrolipoamide --> dihydrolipoamide + isovaleryl-CoA | DBT
BCKDH | MAR06409 | H+ + lipoamide + NADH <=> dihydrolipoamide + NAD+ | DLD
| | |
BCKDH | MAR03800 | 2-oxobutyrate + CoA + NAD+ --> CO2 + NADH + propanoyl-CoA | BCKDHB and DLD and DBT and BCKDHA

(`MAR06409` appears multiple times because DLD is a subunit of all of these complexes; see #529)

#### Expected feature/value/output:

All reactions representing the activities of 2-ketoacid dehydrogenase complexes should represent the role of thiamine in the catalytic mechanism in the same way. This would entail adding several new reactions to parallel `MAR08746` and `MAR04209` for the OADH and BCKDH reactions. `MAR03800` glosses over the role of lipoic acid in the catalytic mechanism of BCKDH, so I'm also proposing changes to take care of that inconsistency.

### Proposed Changes:

- [x] Create a new metabolite to represent 2-(4-carboxy-1-hydroxybutyl)thiamine diphosphate
- [x] Create a new reaction: 2-oxoadipate (`MAM00670m`) + thiamin-PP (`MAM02984m`) + H<sup>+</sup> (`MAM02039m`) -> 2-(4-carboxy-1-hydroxybutyl)thiamine diphosphate + CO<sub>2</sub> (`MAM01596m`), GPR: OGDH or DHTKD1 (`ENSG00000105953 or ENSG00000181192`)
- [x] Replace 2-oxoadipate (`MAM00670m`) with 2-(4-carboxy-1-hydroxybutyl)thiamine diphosphate, replace CO<sub>2</sub> (`MAM01596m`) with thiamin-PP (`MAM02984m`), and remove H<sup>+</sup> in `MAR04599`
- [x] Create a new metabolite to represent 2-(2-methyl-1-hydroxypropyl)thiamine diphosphate
- [x] Create a new reaction: 3-methyl-2-oxobutyrate (`MAM00824m`) + thiamin-PP (`MAM02984m`) + H<sup>+</sup> (`MAM02039m`) -> 2-(2-methyl-1-hydroxypropyl)thiamine diphosphate + CO<sub>2</sub> (`MAM01596m`), GPR: BCKDHA and BCKDHB (`ENSG00000248098 and ENSG00000083123`)
- [x] Replace 3-methyl-2-oxobutyrate (`MAM00824m`) with 2-(2-methyl-1-hydroxypropyl)thiamine diphosphate, replace CO<sub>2</sub> (`MAM01596m`) with thiamin-PP (`MAM02984m`), and remove H<sup>+</sup> in `MAR06416`
- [x] Create a new metabolite to represent 2-(2-methyl-1-hydroxybutyl)thiamine diphosphate
- [x] Create a new reaction: 2-oxo-3-methylvalerate (`MAM00669m`) + thiamin-PP (`MAM02984m`) + H<sup>+</sup> (`MAM02039m`) -> 2-(2-methyl-1-hydroxybutyl)thiamine diphosphate + CO<sub>2</sub> (`MAM01596m`), GPR: BCKDHA and BCKDHB (`ENSG00000248098 and ENSG00000083123`)
- [x] Replace 2-oxo-3-methylvalerate (`MAM00669m`) with 2-(2-methyl-1-hydroxybutyl)thiamine diphosphate, replace CO<sub>2</sub> (`MAM01596m`) with thiamin-PP (`MAM02984m`), and remove H<sup>+</sup> in `MAR06419`
- [x] Create a new metabolite to represent 2-(3-methyl-1-hydroxybutyl)thiamine diphosphate
- [x] Create a new reaction: 4-methyl-2-oxo-pentanoate (`MAM01013m`) + thiamin-PP (`MAM02984m`) + H<sup>+</sup> (`MAM02039m`) -> 2-(3-methyl-1-hydroxybutyl)thiamine diphosphate + CO<sub>2</sub> (`MAM01596m`), GPR: BCKDHA and BCKDHB (`ENSG00000248098 and ENSG00000083123`)
- [x] Replace 4-methyl-2-oxo-pentanoate (`MAM01013m`) with 2-(3-methyl-1-hydroxybutyl)thiamine diphosphate, replace CO<sub>2</sub> (`MAM01596m`) with thiamin-PP (`MAM02984m`), and remove H<sup>+</sup> in `MAR06421`
- [x] Create a new metabolite to represent 2-(1-hydroxypropyl)thiamine diphosphate
- [x] Create a new metabolite to represent S-propanoyldihydrolipoamide
- [x] Change `MAR03800` to: 2-oxobutyrate (`MAM00671m`) + thiamin-PP (`MAM02984m`) + H<sup>+</sup> (`MAM02039m`) -> 2-(1-hydroxypropyl)thiamine diphosphate + CO<sub>2</sub> (`MAM01596m`), GPR: BCKDHA and BCKDHB (`ENSG00000248098 and ENSG00000083123`)
- [x] Create a new reaction: 2-(1-hydroxypropyl)thiamine diphosphate + lipoamide (`MAM02393m`) -> S-propanoyldihydrolipoamide + thiamin-PP (`MAM02984m`), GPR: BCKDHA and BCKDHB and DBT (`ENSG00000248098 and ENSG00000083123 and ENSG00000137992`)
- [x] Create a new reaction: S-propanoyldihydrolipoamide + CoA (`MAM01597m`) -> propanoyl-CoA (`MAM02774m`) + dihydrolipoamide (`MAM01701m`), GPR: DBT (`ENSG00000137992`)

**Comment by JonathanRob** [comment]
Very clearly presented - I agree with the suggested changes!

**Comment by Devlin-Moyer** [comment]
fixed in #753
