### ISSUE TITLE
Duplicate Beta-oxidation Reactions for Decanoyl-CoA

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#745]
### Current behavior:

There are several partially redundant sets of reactions representing the beta-oxidation of decanoyl-CoA to octanoyl-CoA:

ID | Reaction | Genes | Notes
---|---|---|---
`MAR03142` | FAD [m] + decanoyl-CoA [m] ⇒ (2E)-decenoyl-CoA [m] + FADH2 [m] | ACADM or ACAD9 | Step 1
`MAR03143` | (2E)-decenoyl-CoA [m] + H2O [m] ⇒ (S)-hydroxydecanoyl-CoA [m] | HADHA and EHHADH and ECHS1 | Step 2
`MAR03144` | (S)-hydroxydecanoyl-CoA [m] + NAD+ [m] ⇒ 3-oxodecanoyl-CoA [m] + H+ [m] + NADH [m] | HSD17B10 and HADHA and HADH | Step 3
`MAR03146` | 3-oxodecanoyl-CoA [m] + CoA [m] ⇒ acetyl-CoA [m] + octanoyl-CoA [m] | HADHA and HADHB and ACAA2 | Step 4
`MAR05019` | FAD [m] + H2O [m] + decanoyl-CoA [m] ⇒ (S)-hydroxydecanoyl-CoA [m] + FADH2 [m] | ACADM and ECHS1 | Steps 1 and 2
`MAR04967` | (2E)-decenoyl-CoA [m] + CoA [m] + H2O [m] + NAD+ [m] ⇒ H+ [m] + NADH [m] + acetyl-CoA [m] + octanoyl-CoA [m] | ECHS1 and HADH and ACAA2 | Steps 2-4
`MAR05024` | CoA [m] + FAD [m] + H2O [m] + NAD+ [m] + decanoyl-CoA [m] ⇒ FADH2 [m] + H+ [m] + NADH [m] + acetyl-CoA [m] + octanoyl-CoA [m] | ACADM and ECHS1 and HADH and ACAA2 | Steps 1-4

#### Expected feature/value/output:

`MAR03142`, `MAR03143`, `MAR03144`, and `MAR03146` accurately represent each step of beta-oxidation, so I think they should be kept and `MAR05019`, `MAR04967`, and `MAR05024` should be removed for being redundant with various subsets of those four reactions.

**Comment by haowang-bioinfo** [comment]
the proposed changes seem rational

by the way, if the GPRs should be modified together or another time?

**Comment by Devlin-Moyer** [comment]
#634 would remove EHHADH from the GPR of `MAR03143`, since EHHADH is a peroxisomal enzyme, but if you think it makes sense, it would be easy enough to make that change here and remove it from the list in #634. The only other change I would make is adding ACADL (`ENSG00000115361`) to the GPR of `MAR03142`, since [Uniprot](https://www.uniprot.org/uniprotkb/P28330/entry) cites a few papers that found it was capable of using decanoyl-CoA as a substrate.

**Comment by haowang-bioinfo** [comment]
to speed up the fixing and avoid potential errors and delays, maybe first just focus on resolving the duplication reactions, which appear to be redundant in beta-oxidation pathways of HumanGEM

**Comment by Devlin-Moyer** [comment]
yea I was kind of thinking that, once I feel like I've resolved all of this duplicates, it'd make sense to go through and systematically assess the GPRs of the remaining reactions to make sure everything checks out

**Comment by haowang-bioinfo** [comment]
fixed by #789
