### ISSUE TITLE
Overlapping duplicate reactions for beta-oxidation of octanoyl-CoA

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#747]
There are several sets of redundant partially overlapping reactions representing the beta-oxidation of octanoyl-CoA to acetyl-CoA:

ID | Reaction | Genes | Notes
--- | --- | --- | ---
`MAR03149` | FAD [m] + octanoyl-CoA [m] ⇒ (2E)-octenoyl-CoA [m] + FADH2 [m] | ACADM or ACAD9 | Round 1, Step 1
`MAR03150` | (2E)-octenoyl-CoA [m] + H2O [m] ⇒ (S)-hydroxyoctanoyl-CoA [m] | HADHA and EHHADH and ECHS1 | Round 1, Step 2
`MAR03151` | (S)-hydroxyoctanoyl-CoA [m] + NAD+ [m] ⇒ 3-oxooctanoyl-CoA [m] + H+ [m] + NADH [m] | HSD17B10 and HADHA and HADH | Round 1, Step 3
`MAR03153` | 3-oxooctanoyl-CoA [m] + CoA [m] ⇒ acetyl-CoA [m] + hexanoyl-CoA [m] | HADHA and HADHB and ACAA2 | Round 1, Step 4
`MAR03156` | FAD [m] + hexanoyl-CoA [m] ⇒ (2E)-hexenoyl-CoA [m] + FADH2 [m] | ACADSB | Round 2, Step 1
`MAR03157` | (2E)-hexenoyl-CoA [m] + H2O [m] ⇒ (S)-hydroxyhexanoyl-CoA [m] | HADHA and EHHADH and ECHS1 | Round 2, Step 2
`MAR03158` | (S)-hydroxyhexanoyl-CoA [m] + NAD+ [m] ⇒ 3-oxohexanoyl-CoA [m] + H+ [m] + NADH [m] | HSD17B10 and HADHA and HADH | Round 2, Step 3
`MAR03160` | 3-oxohexanoyl-CoA [m] + CoA [m] ⇒ acetyl-CoA [m] + butyryl-CoA [m] | HADHA and HADHB and ACAA2 | Round 2, Step 4
`MAR03163` | FAD [m] + butyryl-CoA [m] ⇒ FADH2 [m] + crotonyl-CoA [m] | ACADM or ACADS or ACADSB or ACAD8 or ACAD9 or ACAD11 | Round 3, Step 1
`MAR03164` | H2O [m] + crotonyl-CoA [m] ⇒ (S)-3-hydroxybutyryl-CoA [m] | HADHA and EHHADH and ECHS1 | Round 3, Step 2
`MAR03166` | (S)-3-hydroxybutyryl-CoA [m] + NAD+ [m] ⇒ H+ [m] + NADH [m] + acetoacetyl-CoA [m] | HSD17B10 and HADHA and HADH | Round 3, Step 3
`MAR03885` | CoA [m] + acetoacetyl-CoA [m] ⇔ 2 acetyl-CoA [m] | ACAT1 | Round 3, Step 4
`MAR06329` | CoA [m] + FAD [m] + H2O [m] + NAD+ [m] + octanoyl-CoA [m] ⇒ FADH2 [m] + H+ [m] + NADH [m] + acetyl-CoA [m] + hexanoyl-CoA [m] | ACADM and ECSH1 and HADH and ACAA2 | All steps of round 1
`MAR06283` | CoA [m] + FAD [m] + H2O [m] + NAD+ [m] + hexanoyl-CoA [m] ⇒ FADH2 [m] + H+ [m] + NADH [m] + acetyl-CoA [m] + butyryl-CoA [m] | ACADM and ECHS1 and HADH and ACAA2 | All steps of round 2
`MAR06279` | (2E)-hexenoyl-CoA [m] + CoA [m] + H2O [m] + NAD+ [m] ⇒ H+ [m] + NADH [m] + acetyl-CoA [m] + butyryl-CoA [m] | ECHS1 and HADH and ACAA2 | Steps 2-4 of round 2
`MAR05449` | CoA [m] + FAD [m] + H2O [m] + NAD+ [m] + butyryl-CoA [m] ⇒ FADH2 [m] + H+ [m] + NADH [m] + 2 acetyl-CoA [m] | ACADS and ECHS1 and HADH and ACAA2 | All steps of round 3
`MAR01009` | 3 CoA [m] + 3 FAD [m] + 3 H2O [m] + 3 NAD+ [m] + octanoyl-CoA [m] ⇒ 3 FADH2 [m] + 3 H+ [m] + 3 NADH [m] + 4 acetyl-CoA [m] | ACADM or ACADS | All steps of all rounds

### Proposed changes:

Since `MAR03149` - `MAR03885` accurately represent each individual step of the beta-oxidation of octanoyl-CoA, I think `MAR06329`, `MAR06283`, `MAR06279`, `MAR05449`, and `MAR01009` should be removed for being redundant/unnecessary.

**Comment by JonathanRob** [comment]
Agreed!

**Comment by haowang-bioinfo** [comment]
fixed by #751
