### ISSUE TITLE
Incorrect Beta-Oxidation Reaction for (4Z,7Z,10Z,13Z,16Z)-docosapentaenoyl-CoA

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#748]
`MAR00965` appears to represent a single round of beta-oxidation of (4Z,7Z,10Z,13Z,16Z)-docosapentaenoyl-CoA:

(4Z,7Z,10Z,13Z,16Z)-docosapentaenoyl-CoA [m] + CoA [m] + H2O [m] + NAD+ [m] + O2 [m] ⇒ (5Z,8Z,11Z,14Z,17Z)-eicosapentaenoyl-CoA [m] + H+ [m] + H2O2 [m] + NADH [m] + acetyl-CoA [m], GPR: ACADM or ACADS

But one round of beta-oxidation of (4Z,7Z,10Z,13Z,16Z)-docosapentaenoyl-CoA (already represented by `MAR05380` + `MAR05404` + `MAR05383` + `MAR05378`) produces 5,8,11,14-Eicosatetraenoyl Coenzyme A, not (5Z,8Z,11Z,14Z,17Z)-eicosapentaenoyl-CoA. In addition, it reduces O<sub>2</sub> to H<sub>2</sub>O<sub>2</sub>, but is associated with [ACADM](https://www.uniprot.org/uniprotkb/P11310/entry) and [ACADS](https://www.uniprot.org/uniprotkb/P16219/entry), the mitochondrial acyl-CoA dehydrogenases, which reduce FAD to FADH<sub>2</sub> (the peroxisomal acyl-CoA oxidases [ACOX1](https://www.uniprot.org/uniprotkb/Q15067/entry), [ACOX2](https://www.uniprot.org/uniprotkb/Q99424/entry), and [ACOX3](https://www.uniprot.org/uniprotkb/O15254/entry) reduce O<sub>2</sub> to H<sub>2</sub>O<sub>2</sub>), and it appears to represent all 4 steps of a single round of beta-oxidation, but is only associated with the acyl-CoA dehydrogenases that catalyze the first of those 4 steps.

Since `MAR05380` + `MAR05404` + `MAR05383` + `MAR05378` already accurately represent a single round of beta-oxidation of (4Z,7Z,10Z,13Z,16Z)-docosapentaenoyl-CoA, and (5Z,8Z,11Z,14Z,17Z)-eicosapentaenoyl-CoA can also be (accurately) produced from 	(4Z,7Z,10Z,13Z,16Z,19Z)-docosahexaenoyl-CoA in `MAR00970`, I think `MAR00965` should be removed.

`MAR00970`: (4Z,7Z,10Z,13Z,16Z,19Z)-docosahexaenoyl-CoA [m] + CoA [m] + H2O [m] + NAD+ [m] ⇒ (5Z,8Z,11Z,14Z,17Z)-eicosapentaenoyl-CoA [m] + H+ [m] + NADH [m] + acetyl-CoA [m]

**Comment by haowang-bioinfo** [comment]
thanks for careful checking of this case

it does appear that MAR00965 is duplicate to MAR00970. But both probably should be removed based on annotation of [ACADM](https://www.uniprot.org/uniprotkb/P11310/entry) and [ACADS](https://www.uniprot.org/uniprotkb/P16219/entry), or the GPR need to be modified?

**Comment by Devlin-Moyer** [comment]
[This paper](https://doi.org/10.1074/jbc.M504460200) found that ACAD9 was 1) localized to the inner mitochondrial membrane and 2) capable of oxidizing C22:6 (i.e. docosahexaenoyl-CoA). While (4Z,7Z,10Z,13Z,16Z)-docosapentaenoyl-CoA is C22:5 and not C22:6, it doesn't seem like much of a stretch to suggest that ACAD9 could catalyze `MAR00965`.

**Comment by Devlin-Moyer** [comment]
Ah I just realized that `MAR00970` represents a full round of beta-oxidation, not just the first step, but following the rationale I presented in #772 for the GPR of `MAR00923`, I think the GPR of `MAR00970` should be `(ACADL or ACAD9) and (ECI1 or ECI2) and ECH1 and DECR1 and HADHA and HADHB`

**Comment by Devlin-Moyer** [comment]
fixed in #794
