### ISSUE TITLE
Tagatose is probably not metabolized by human cells

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#754]
### Current behavior:

Human-GEM currently has this short pathway for metabolizing tagatose:

ID | Reaction | Genes
---|---|---
`MAR09417` | D-tagatose [e] ⇔ | None
`MAR08760` | D-tagatose [e] ⇒ D-tagatose [c] | None
`MAR01472` | ATP [c] + D-tagatose [c] ⇒ ADP [c] + D-Tagatose 1-Phosphate [c] + H+ [c] | KHK
`MAR01038` | D-Tagatose 1-Phosphate [c] ⇔ DHAP [c] + glyceraldehyde [c] | ALDOB
`MAR08761` | ATP [c] + D-tagatose [c] ⇒ ADP [c] + D-tagatose-6-phosphate [c] + H+ [c] | KHK
`MAR08762` | D-tagatose-6-phosphate [c] ⇔ DHAP [c] + glyceraldehyde [c] | ALDOA or ALDOB or ALDOC
`MAR04774` | CDP [c] + H+ [c] + tagatose-1,6-bisphosphate [c] ⇔ CTP [c] + D-tagatose-6-phosphate [c] | PFKP or PFKL or PFKM
`MAR04775` | D-tagatose-6-phosphate [c] + ITP [c] ⇔ H+ [c] + IDP [c] + tagatose-1,6-bisphosphate [c] | PFKP or PFKL or PFKM

I noticed this because I was looking for pairs of nearly-identical reactions that might form internal loops, and the last two do exactly that. They're also a dead-end; no other reactions involve tagatose-1,6-bisphosphate. The fact that they're both reversible also seemed suspicious, and reminded me of #547, so I tried looking to see if there was any evidence that they should or shouldn't be reversible.

I checked the references for `MAR01472`, `MAR04774` and `MAR04775` (the only reactions in the above table that had references), and none of them were about human enzymes. I found [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2653686/) that found that administering tagatose to cultured human kidney cells induced production of MCP-1 (a protein, not a metabolite), and while they suggested this was because it was phosphorylated by KHK, they did not directly demonstrate this, instead citing a paper that showed that tagatose is phosphorylated by KHK in rat hepatocytes. I also found [this paper](https://link.springer.com/article/10.1007/s00253-004-1665-8) that says (in the second paragraph under "Metabolism" subheading under the "Tagatose" main heading):

>Higher animals, including humans, have no tagatose-6-phosphate pathway, and tagatose does not break down spontaneously. [...] Tagatose is also a malabsorption sugar for humans, meaning it is a non-absorbing nutrient, and it is supposedly partially absorbed in the form of short-chain fatty acids by the normal flora of the human large intestine. 

### Expected feature/value/output:

There doesn't seem to be particularly solid evidence supporting the existence of any of these reactions in human cells. It is maybe the case that the KHK reactions happen (and thus also the transport and exchange reactions), but since tagatose monophosphate is apparently "poorly metabolized further" (in rat hepatocytes), I highly doubt the aldolase or PFK reactions are real. I'm leaning towards removing the whole pathway.

### Proposed changes:

(updated based on comments below)

- [x] Remove `MAR04774`, `MAR04775` and `MAM02955c`
- [ ] Add `PMID:33715524` as a reference for `MAR09417`, `MAR08760`, `MAR01472`, `MAR01038`, `MAR08761`, and `MAR08762`

**Comment by JHL-452b** [comment]
This is a very interesting finding. Howerver, I got some different tips. This [paper](https://www.tandfonline.com/doi/full/10.1080/10408398.2021.1895057) describing that tagatose can be absorbed by liver: 
> Carriers transporting fructose in the small intestine do not show an affinity for d-tagatose therefore, only 20% of consumed d-tagatose is absorbed in the small intestine and then metabolized in the liver by the same route as fructose but at a slower rate > (Muddada [Citation2012](https://www.tandfonline.com/doi/full/10.1080/10408398.2021.1895057#)). The rest of the undigested d-tagatose, like other low-digestible carbohydrates (dietary fiber), is fermented in the large intestine by indigenous microflora, resulting in the production of short-chain fatty acids (SCFA), specifically butyrate (reported to combat colon cancer) (Wu et al. [Citation2018](https://www.tandfonline.com/doi/full/10.1080/10408398.2021.1895057#)). Next, SCFAs are absorbed into the bloodstream from the digestive tract as a source of energy. Furthermore, d-tagatose limits the digestion and absorption of sucrose and maltose by inhibiting the activity of sucrases and maltases in the small intestine (Lu, Levin, and Donner [Citation2008](https://www.tandfonline.com/doi/full/10.1080/10408398.2021.1895057#)). Therefore, it causes a slight or > no increase in postprandial blood glucose.

So I think these reactions can continue to be preserved in the model. Maybe, we should focus on whether `MAR04774` and `MAR04775` could be reversible to solve the internal loops.

**Comment by Devlin-Moyer** [comment]
that paper says tagatose is "metabolized in the liver by the same route as fructose", and a quick look through papers that mention fructose metabolism in livers (e.g. [this one](https://doi.org/10.1093/ajcn/58.5.754S)) makes it seem like people are pretty confident that fructose is metabolized _independently_ of phosphofructokinase in livers, i.e. fructose -> fructose-1-phosphate -> DHAP + glyceraldehyde. So I still think `MAR04774`, `MAR04775` and tagatose-1,6-bisphosphate (`MAM02955c`) should be removed (since the two reactions are associated with the phosphofructokinases and they're the only two reactions tagatose-1,6-bisphosphate participates in), but the rest now seem plausible (although we should update their references with that paper you found).

**Comment by JHL-452b** [comment]
Thank you for your reply. 

I also noticed the concentrations of tagatose-1,6-bisphosphate in [HMDB](https://hmdb.ca/metabolites/HMDB0006872) is not available. So, the suggestion about removing `MAR04774`, `MAR04775`  and `MAM02955c` looks fine to me.
