### ISSUE TITLE
Localization of DECR1 and DECR2

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#755]
### Current behavior:

[DECR1](https://www.uniprot.org/uniprotkb/Q16698/entry#subcellular_location) and [DECR2](https://www.uniprot.org/uniprotkb/Q9NUI1/entry) both catalyze NADPH-dependent reduction of 2,4-dienoyl-CoAs during beta-oxidation, but DECR1 does so exclsively in mitochondria and DECR2 does so exclusively in peroxisomes. Several reactions in Human-GEM have GPRs of "DECR1 or DECR2"

ID|Reaction
---|---
`MAR01176` | 8(R)-hydroxy-hexadeca-(2E,4E,6E,10Z)-tetraenoate [m] + H+ [m] + NADPH [m] --> 8(R)-hydroxy-hexadeca-(2E,6E,10Z)-trienoate [m] + NADP+ [m]
`MAR01181` | 6(R)-hydroxy-tetradeca-(2E,4E,8Z)-trienoate [m] + H+ [m] + NADPH [m] <=> 6(R)-hydroxy-tetradeca-(2E,8Z)-dienoate [m] + NADP+ [m]
`MAR01218` | 8(S)-hydroxy-hexadeca-(2E,4E,6E,10Z)-tetraenoate [m] + H+ [m] + NADPH [m] --> 8(S)-hydroxy-hexadeca-(2E,6E,10Z)-trienoate [m] + NADP+ [m]
`MAR01222` | 6(S)-hydroxy-tetradeca-(2E,4E,8Z)-trienoate [m] + H+ [m] + NADPH [m] <=> 6(S)-hydroxy-tetradeca-(2E,8Z)-dienoate [m] + NADP+ [m]
~~`MAR03296`~~ | 2-trans-4-cis-decadienoyl-CoA [m] + H+ [m] + NADH [m] --> NAD+ [m] + trans-3-decenoyl-CoA [m]
`MAR03446` | 2-trans-cis,cis,cis,cis-4,8,11,14-eicosapentaenoyl-CoA [m] + H+ [m] + NADPH [m] --> NADP+ [m] + trans-3-cis-8,11,14-eicosatetraenoyl-CoA [m]
`MAR03457` | (2E,4Z,7Z,10Z)-hexadecatetraenoyl-CoA [m] + H+ [m] + NADPH [m] <=> (3Z,7Z,10Z)-hexadecatrienoyl-CoA [m] + NADP+ [m]
`MAR01297` | 18-COOH-(15E)-dinor-LTE4-CoA [x] + NADP+ [x] <=> 18-COOH-(16E)-dinor-LTE5-CoA [x] + H+ [x] + NADPH [x]
~~`MAR03322`~~ | 2-trans-4-cis-decadienoyl-CoA [x] + H+ [x] + NADH [x] --> NAD+ [x] + trans-3-decenoyl-CoA [x]
`MAR03461` | 2-trans-cis,cis,cis,cis-4,8,11,14-eicosapentaenoyl-CoA [x] + H+ [x] + NADPH [x] --> NADP+ [x] + trans-3-cis-8,11,14-eicosatetraenoyl-CoA [x]
`MAR03471` | (2E,4Z,7Z,10Z)-hexadecatetraenoyl-CoA [x] + H+ [x] + NADPH [x] <=> (3Z,7Z,10Z)-hexadecatrienoyl-CoA [x] + NADP+ [x]

(Some of this was originally in #634; I split it out here because #634 was unmanageably large.)

### Expected behavior:

The mitochondrial reactions should only be associated with DECR1 (`ENSG00000104325`), and the peroxisomal reactions should only be associated with DECR2 (`ENSG00000242612`). The first four should also involve acyl-CoAs and not free fatty acids, but I'm addressing that in #749. All of these should involve NADPH and not NADH, but I've addressed that in #736.

### Proposed changes:

- [x] Set the GPRs of `MAR01176`, `MAR01181`, `MAR01218`, `MAR01222`, `MAR03296`, `MAR03446`, and `MAR03457` to `ENSG00000104325`
- [x] Set the GPRs of `MAR01297`, `MAR03322`, `MAR03461`, and `MAR03471` to `ENSG00000242612`

**Comment by haowang-bioinfo** [comment]
fixed by #788
