### ISSUE TITLE
Bad GPRs for Mitochondrial delta-3-delta-2-enoyl-CoA Isomerization Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#756]
### Current behavior:

These reactions all represent delta-3- delta-2-enoyl-CoA isomerization in the mitochondria and have GPRs of "ECI1 or ECI2 or EHHADH":

ID|Reaction
---|---
`MAR03288`|cis,cis-3,6-dodecadienoyl-CoA --> trans,cis-lauro-2,6-dienoyl-CoA
`MAR03374`|trans-2-cis,cis-5,8-tetradecatrienoyl-CoA <=> (3E,5Z,8Z)-Tetradecatrienoyl Coenzyme A
`MAR03378`|Trans-2-Cis-8-Tetradecadienoyl Coenzyme A <=> Trans-3-Cis-8-Tetradecadienoyl Coenzyme A

### Expected feature/value/output:

While all three of these enzymes can catalyze this type of reaction, [EHHADH](https://www.uniprot.org/uniprotkb/Q08426/entry) (`ENSG00000113790`) is only localized to peroxisomes ([ECI1](https://www.uniprot.org/uniprotkb/P42126/entry) is localized to mitochondria, and [ECI2](https://www.uniprot.org/uniprotkb/O75521/entry) can be localized to either, depending on how it's spliced). EHHADH should be removed from all of these GPRs.

EHHADH is also associated with a lot of other mitochondrial reactions, but I'm trying to address them in small groups to avoid large complicated issues.

### Proposed changes:

- [x] Remove `ENSG00000113790` from the GPR of `MAR03288`
- ~Remove `ENSG00000113790` from the GPR of `MAR03374`~ addressed in #770
- ~Remove `ENSG00000113790` from the GPR of `MAR03378`~ addressed in #770

**Comment by haowang-bioinfo** [comment]
nice findings and thanks

**Comment by Devlin-Moyer** [comment]
fixed in #790
