### ISSUE TITLE
GPRs for Mitochondrial 2-enoyl-CoA Hydration Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#757]
### Current Behavior:

All of these reactions represent hydration of a 2-enoyl-CoA in mitochondria and have GPRs of [HADHA](https://www.uniprot.org/uniprotkb/P40939/entry) and [EHHADH](https://www.uniprot.org/uniprotkb/Q08426/entry) and [ECHS1](https://www.uniprot.org/uniprotkb/P30084/entry) (`ENSG00000084754 and ENSG00000113790 and ENSG00000127884`):

ID | Reaction | Chain Length | Appropriate GPR
--- | --- | --- | ---
MAR03219 | H2O [m] + trans,cis-2,13-docosadienoyl-CoA [m] --> 3(S)-hydroxy-13-cis-docosenoyl-CoA [m] | 22 | HADHA
MAR03108 | (2E)-docosenoyl-CoA [m] + H2O [m] --> 3-hydroxydocosanoyl-CoA [m] | 22 | HADHA
MAR03171 | (2E)-heneicosenoyl-CoA [m] + H2O [m] --> 3-hydroxyheneicosanoyl-CoA [m] | 21 | HADHA
MAR03449 | H2O [m] + trans-2-cis,cis,cis-8,11,14-eicosatetraenoyl-CoA [m] --> 3(S)-hydroxy-dihomo-gamma-linolenoyl-CoA [m] | 20 | HADHA
MAR03241 | H2O [m] + trans,cis-2,13-eicosadienoyl-CoA [m] --> 3(S)-hydroxy-13-cis-eicosenoyl-CoA [m] | 20 | HADHA
MAR03223 | H2O [m] + trans,cis-2,11-eicosadienoyl-CoA [m] --> 3(S)-hydroxy-11-cis-eicosenoyl-CoA [m] | 20 | HADHA
MAR03112 | (2E)-eicosenoyl-CoA [m] + H2O [m] --> 3-hydroxyeicosanoyl-CoA [m] | 20 | HADHA
MAR01272 | 5(S),12(R)-dihydroxy-eicosa-2,8-trans-6,14-cis-tetraenoyl-CoA [m] + H2O [m] --> 3(S),5(S),12(R)-trihydroxy-eicosa-8-trans-6,14-cis-trienoyl-CoA [m] | 20 | HADHA
MAR01255 | (18E)-20-oxo-20-CoA-LTB4 [m] + H2O [m] --> 20-CoA-20-oxo-18r-hydroxy-LTB4 [m] | 20 | HADHA
MAR01206 | 5-oxo-12(S)-hydroxy-eicosa-(2E,8E,10E,14Z)-tetraenoyl-CoA [m] + H2O [m] --> 3(S),12(S)-dihydroxy-5-oxo-eicosa-(8E,10E,14Z)-trienoyl-CoA [m] | 20 | HADHA
MAR01163 | 5-oxo-12(R)-hydroxy-eicosa-(2E,8E,10E,14Z)-tetraenoyl-CoA [m] + H2O [m] --> 3(S),12(R)-dihydroxy-5-oxo-eicosa-(8E,10E,14Z)-trienoyl-CoA [m] | 20 | HADHA
MAR03175 | (2E)-nonadecenoyl-CoA [m] + H2O [m] --> 3-hydroxynonadecanoyl-CoA [m] | 19 | HADHA
MAR03453 | (2E,6Z,9Z,12Z)-octadecatetraenoyl-CoA [m] + H2O [m] --> 3(S)-hydroxy-(6Z,9Z,12Z)-octadecatrienoyl-CoA [m] | 18 | HADHA
MAR03277 | H2O [m] + trans,cis,cis-2,9,12-octadecatrienoyl-CoA [m] --> (3S)-3-hydroxylinoleoyl-CoA [m] | 18 | HADHA
MAR03245 | H2O [m] + trans,cis-octadeca-2,11-dienoyl-CoA [m] --> (S)-3-hydroxy-11-cis-octadecenoyl-CoA [m] | 18 | HADHA
MAR03227 | H2O [m] + trans,cis-octadeca-2,9-dienoyl-CoA [m] --> (S)-3-hydroxyoleyleoyl-CoA [m] | 18 | HADHA
MAR03116 | (2E)-octadecenoyl-CoA [m] + H2O [m] --> 3-hydroxyoctadecanoyl-CoA [m] | 18 | HADHA
MAR03179 | (2E)-heptadecenoyl-CoA [m] + H2O [m] --> 3-hydroxyheptadecanoyl-CoA [m] | 17 | HADHA
MAR03281 | H2O [m] + trans,cis,cis-2,7,10-hexadecatrienoyl-CoA [m] --> (3S)-3-hydroxy-cis,cis-palmito-7,10-dienoyl-CoA [m] | 16 | HADHA
MAR03252 | H2O [m] + trans,cis-hexadeca-2,9-dienoyl-CoA [m] --> (S)-3-hydroxypalmitoleoyl-CoA [m] | 16 | HADHA
MAR03231 | H2O [m] + trans,cis-hexadeca-2,7-dienoyl-CoA [m] --> (S)-3-hydroxy-7-hexadecenoyl-CoA [m] | 16 | HADHA
MAR03122 | (2E)-hexadecenoyl-CoA [m] + H2O [m] --> (S)-3-hydroxyhexadecanoyl-CoA [m] | 16 | HADHA
MAR01219 | 3(S),8(S)-dihydroxy-(6E,10Z)-hexadecadienoate [m] <=> 8(S)-hydroxy-hexadeca-(2E,6E,10Z)-trienoate [m] + H2O [m] | 16 | HADHA
MAR01177 | 8(R)-hydroxy-hexadeca-(2E,6E,10Z)-trienoate [m] + H2O [m] --> 3(S),8(R)-dihydroxy-(6E,10Z)-hexadecadienoate [m] | 16 | HADHA
MAR03183 | (2E)-pentadecenoyl-CoA [m] + H2O [m] --> 3-hydroxypentadecanoyl-CoA [m] | 15 | HADHA
MAR03285 | H2O [m] + trans-2-cis,cis-5,8-tetradecatrienoyl-CoA [m] --> 3(S)-hydroxy-(5Z,8Z)-tetradecadienoyl-CoA [m] | 14 | HADHA
MAR03260 | H2O [m] + trans,cis-myristo-2,7-dienoyl-CoA [m] --> cis-(3S)-hydroxytetradec-7-enoyl-CoA [m] | 14 | HADHA
MAR03235 | H2O [m] + trans,cis-myristo-2,5-dienoyl-CoA [m] --> cis-(3S)-hydroxytetradec-5-enoyl-CoA [m] | 14 | HADHA
MAR03129 | (2E)-tetradecenoyl-CoA [m] + H2O [m] --> (S)-3-hydroxytetradecanoyl-CoA [m] | 14 | HADHA
MAR01224 | 6(S)-hydroxy-tetradeca-(2E,8Z)-dienoate [m] + H2O [m] --> 3(S),6(S)-dihydroxy-tetradec-(8Z)-enoate [m] | 14 | HADHA
MAR01182 | 6(R)-hydroxy-tetradeca-(2E,8Z)-dienoate [m] + H2O [m] --> 3(S),6(R)-dihydroxy-tetradec-(8Z)-enoate [m] | 14 | HADHA
MAR03187 | (2E)-tridecenoyl-CoA [m] + H2O [m] --> 3-hydroxytridecanoyl-CoA [m] | 13 | HADHA
MAR03290 | H2O [m] + trans,cis-lauro-2,6-dienoyl-CoA [m] --> (3S)-3-hydroxydodec-cis-6-enoyl-CoA [m] | 12 | HADHA or ECHS1
MAR03136 | (2E)-dodecenoyl-CoA [m] + H2O [m] --> (S)-3-hydroxydodecanoyl-CoA [m] | 12 | HADHA or ECHS1
MAR03191 | (2E)-undecenoyl-CoA [m] + H2O [m] --> 3-hydroxyundecanoyl-CoA [m] | 11 | HADHA or ECHS1
MAR03143 | (2E)-decenoyl-CoA [m] + H2O [m] --> (S)-hydroxydecanoyl-CoA [m] | 10 | HADHA or ECHS1
MAR03523 | 4(R),8-dimethyl-trans-2-nonenoyl-CoA [m] + H2O [m] --> 3(S)-hydroxy-4(R),8-dimethyl-nonanoyl-CoA [m] | 9 | HADHA or ECHS1
MAR03195 | (2E)-nonenoyl-CoA [m] + H2O [m] --> 3-hydroxynonanoyl-CoA [m] | 9 | HADHA or ECHS1
MAR03150 | (2E)-octenoyl-CoA [m] + H2O [m] --> (S)-hydroxyoctanoyl-CoA [m] | 8 | HADHA or ECHS1
MAR03528 | 2,6-dimethyl-trans-2-heptenoyl-CoA [m] + H2O [m] --> 3(S)-hydroxy-2(S),6-dimethyl-heptanoyl-CoA [m] | 7 | HADHA or ECHS1
MAR03199 | (2E)-heptenoyl-CoA [m] + H2O [m] --> 3-hydroxyheptanoyl-CoA [m] | 7 | HADHA or ECHS1
MAR03157 | (2E)-hexenoyl-CoA [m] + H2O [m] --> (S)-hydroxyhexanoyl-CoA [m] | 6 | HADHA or ECHS1
MAR03532 | 4-methyl-trans-2-pentenoyl-CoA [m] + H2O [m] --> 3(S)-hydroxy-4-methyl-pentanoyl-CoA [m] | 5 | ECHS1
MAR03203 | (2E)-pentenoyl-CoA [m] + H2O [m] --> 3-hydroxypentanoyl-CoA [m] | 5 | ECHS1
MAR03785 | H2O [m] + tiglyl-CoA [m] --> (S)-3-hydroxy-2-methylbutyryl-CoA [m] | 4 | ECHS1
MAR03164 | crotonyl-CoA [m] + H2O [m] --> (S)-3-hydroxybutyryl-CoA [m] | 4 | ECHS1
MAR04735 | acrylyl-CoA [m] + H2O [m] <=> 3-hydroxypropionyl-CoA [m] | 3 | ECHS1
MAR03753 | H2O [m] + methacrylyl-CoA [m] --> 3-hydroxyisobutyryl-CoA [m] | 3 | ECHS1

### Expected behavior:

EHHADH is localized to peroxisomes, so it should not be associated with any of these reactions. While HADHA and ECHS1 are both localized to mitochondria, ECSH1 generally acts on substrates with shorter chains than HADHA, although there is some overlap. While most papers I could find were pretty vague about exactly what the range of substrates each enzyme could act on was, the best I've managed to come up with are [these](https://jmg.bmj.com/content/52/10/691) [papers](https://doi.org/10.1016/0006-291X(92)90501-B) that say that ECSH1 can act on substrates with chain lengths of up to 12, and HADHA can act on substrates with chain lengths of at least 6. I have proposed new GPRs for each of these reactions that reflect these chain length preferences.

### Proposed changes:

- [x] Change GPR of `MAR03219` to `ENSG00000084754`
- [x] Change GPR of `MAR03108` to `ENSG00000084754`
- [x] Change GPR of `MAR03171` to `ENSG00000084754`
- [x] Change GPR of `MAR03449` to `ENSG00000084754`
- [x] Change GPR of `MAR03241` to `ENSG00000084754`
- [x] Change GPR of `MAR03223` to `ENSG00000084754`
- [x] Change GPR of `MAR03112` to `ENSG00000084754`
- [x] Change GPR of `MAR01272` to `ENSG00000084754`
- [x] Change GPR of `MAR01255` to `ENSG00000084754`
- [x] Change GPR of `MAR01206` to `ENSG00000084754`
- [x] Change GPR of `MAR01163` to `ENSG00000084754`
- [x] Change GPR of `MAR03175` to `ENSG00000084754`
- [x] Change GPR of `MAR03453` to `ENSG00000084754`
- [x] Change GPR of `MAR03277` to `ENSG00000084754`
- [x] Change GPR of `MAR03245` to `ENSG00000084754`
- [x] Change GPR of `MAR03227` to `ENSG00000084754`
- [x] Change GPR of `MAR03116` to `ENSG00000084754`
- [x] Change GPR of `MAR03179` to `ENSG00000084754`
- [x] Change GPR of `MAR03281` to `ENSG00000084754`
- [x] Change GPR of `MAR03252` to `ENSG00000084754`
- [x] Change GPR of `MAR03231` to `ENSG00000084754`
- [x] Change GPR of `MAR03122` to `ENSG00000084754`
- [x] Change GPR of `MAR01219` to `ENSG00000084754`
- [x] Change GPR of `MAR01177` to `ENSG00000084754`
- [x] Change GPR of `MAR03183` to `ENSG00000084754`
- [x] Change GPR of `MAR03285` to `ENSG00000084754`
- [x] Change GPR of `MAR03260` to `ENSG00000084754`
- [x] Change GPR of `MAR03235` to `ENSG00000084754`
- [x] Change GPR of `MAR03129` to `ENSG00000084754`
- [x] Change GPR of `MAR01224` to `ENSG00000084754`
- [x] Change GPR of `MAR01182` to `ENSG00000084754`
- [x] Change GPR of `MAR03187` to `ENSG00000084754`
- [x] Change GPR of `MAR03290` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03136` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03191` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03143` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03523` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03195` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03150` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03528` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03199` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03157` to `ENSG00000084754 or ENSG00000127884`
- [x] Change GPR of `MAR03532` to `ENSG00000127884`
- [x] Change GPR of `MAR03203` to `ENSG00000127884`
- [x] Change GPR of `MAR03785` to `ENSG00000127884`
- [x] Change GPR of `MAR03164` to `ENSG00000127884`
- [x] Change GPR of `MAR04735` to `ENSG00000127884`
- [x] Change GPR of `MAR03753` to `ENSG00000127884`

**Comment by JHL-452b** [comment]
It looks great to remove EHHADH. And I agree with your suggestion about ECSH1 and HADHA as [some](https://metacyc.org/gene?orgid=META&id=HS01481#SUMMARY) [databases](https://metacyc.org/gene?orgid=META&id=HS05132#SUMMARY) have similar description.

The **Proposed changes** tips gived above may be `ENSG0000012788` or `ENSG00000084754`, and no other genes should appear. That's a small problem need to be noticed.  (•̀ᴗ• ) ̑̑

In addition, 3-hydroxyacyl-CoA dehydrogenase from mitochondrial membranes should be a complex, HADHA can be used as an α subunit, and I suggest [HADHB](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000138029) as a β subunit. So, the GPR of the above reaction should replace `ENSG00000084754` with `ENSG00000084754 and ENSG00000138029`

**Comment by Devlin-Moyer** [comment]
oh whoops I did the classic click and drag spreadsheet thing where it increments the number for each cell; I will fix that

I didn't include HADHB in the GPRs following the rationale [here](https://github.com/SysBioChalmers/Human-GEM/issues/524#issuecomment-1517843169), where we set the GPRs of reactions catalyzed by enzyme complexes such that each reaction was only associated with the specific subunits of the larger complex that directly catalyzed that reaction and left out the genes encoding all the other subunits of the same complex

**Comment by JHL-452b** [comment]
Agree with your reply.  I think the evidence you provided is enough to support that HADHB isn't responsible for 2,3-enoyl-CoA hydratase and the 3-hydroxyacyl-CoA dehydrogenase activities. So, there is no need for the GPR of the above reaction to be replaced.

**Comment by Devlin-Moyer** [comment]
fixed by #808
