### ISSUE TITLE
GPRs for Mitochondrial 3-Hydroxyacyl-CoA Oxidation Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#758]
### Current behavior:

`MAR03269` and `MAR03380` are both associated with [HSD17B4](https://www.uniprot.org/uniprotkb/P51659/entry) and [EHHADH](https://www.uniprot.org/uniprotkb/Q08426/entry) and both represent oxidation of a 3-hydroxyacyl-CoA to a 3-oxoacyl-CoA in mitochondria:

ID|Reaction|Current GPR
---|---|---
`MAR03269`|NAD+ + 3(S)-3-Hydroxydodecen-(5Z)-Oyl Coenzyme A <=> H+ + NADH + 3-Oxolaur-Cis-5-Enoyl Coenzyme A|HSD17B10 or HADHA or EHHADH or HSD17B4 or HADHB or HADH
`MAR03380`|NAD+ + (3S)-3-Hydroxy-Cis-8-Tetradecenoyl Coenzyme A <=> H+ + NADH + 3-Oxo-Cis-8-Tetradecenoyl Coenzyme A|HSD17B10 or EHHADH or HSD17B4 or HADH

There are a number of other mitochondrial reactions associated with both of these genes, but they all have other issues that I address in #738, so I'm not mentioning them here.

### Expected behavior:

While HSD17B4 and EHHADH can both catalyze the oxidation of 3-hydroxyacyl-CoAs, they are both localized to peroxisomes and not mitochondria; the mitochondrial enzymes that can catalyze this reaction are [HADHA](https://www.uniprot.org/uniprotkb/P40939/entry) (ENSG00000084754), [HADH](https://www.uniprot.org/uniprotkb/Q16836/entry) (ENSG00000138796), and [HSD17B10](https://www.uniprot.org/uniprotkb/Q99714/entry) (ENSG00000072506).

Uniprot mentions that HADH can only act on substrates with carbon chain lengths of up to 10, so I don't think it should be associated with either of these reactions, since the reactants of `MAR03269` and `MAR03380` have chains with 12 and 14 carbons, respectively.

The [best paper](https://doi.org/10.1016/0006-291X(92)90501-B) I could find on the chain length preferences of HADHA says it can handle chain lengths between 6 and 16, and I haven't been able to find any papers that clarify what chain lengths HSD17B10 can handle, so I think both HADHA and HSD17B10 are fine to keep in the GPRs of these reactions.

### Proposed changes:
- [x] Change the GPR of `MAR03269` to `ENSG00000084754 or ENSG00000072506`
- [x] Change the GPR of `MAR03380` to `ENSG00000084754 or ENSG00000072506`

**Comment by haowang-bioinfo** [comment]
agree to assign `ENSG00000084754 or ENSG00000072506` as GPR of MAR03269 and MAR03380

for example, the comp-mismatch of HSD17B4 and EHHADH can be found and reported by the code presented in #746

**Comment by haowang-bioinfo** [comment]
fixed by #760
