### ISSUE TITLE
ACAA1 should not be in the GPR of MAR02381

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#759]
### Current behavior:

`MAR02381`: 3-oxooleoyl-CoA + CoA --> acetyl-CoA + palmitoleoyl-CoA, GPR: (HADHB and ACAA2) or (ACAA1 and HADHB)

### Expected behavior:

While [HADHB](https://www.uniprot.org/uniprotkb/P55084/entry), [ACAA1](https://www.uniprot.org/uniprotkb/P09110/entry), and [ACAA2](https://www.uniprot.org/uniprotkb/P42765/entry) can all catalyze 3-oxoacyl-CoA thiolysis reactions, ACAA1 is localized to peroxisomes, and `MAR02381` is in the mitochondrial compartment. Also, HADHB and ACAA2 can catalyze this reaction independently of each other, so the GPR of `MAR02381` should just be `HADHB or ACAA2` (`ENSG00000138029 or ENSG00000167315`).

There are many other mitochondrial reactions associated with ACAA1, but they all have several other problems that I'm addressing in separate issues (so far, just #738 and #746, but there will be more)

### Proposed changes:
- [x] Change the GPR of `MAR02381` to `ENSG00000138029 or ENSG00000167315`

**Comment by haowang-bioinfo** [comment]
fixed by #770
