### ISSUE TITLE
Duplicate Beta-Oxidation Pathways for Linolenoyl-CoA

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#765]
### Current behavior:

Linolenoyl-CoA (`MAM02390m`) can be fully oxidized to acetyl-CoA in a single step via `MAR03426` or in many steps:

ID | Reaction
---|---
MAR05359 | CoA [m] + FAD [m] + H2O [m] + linolenoyl-CoA [m] + NAD+ [m] --> acetyl-CoA [m] + FADH2 [m] + H+ [m] + NADH [m] + 7,10,13-Hexadecatrienoyl Coenzyme A [m]
MAR05194 | CoA [m] + FAD [m] + H2O [m] + NAD+ [m] + 7,10,13-Hexadecatrienoyl Coenzyme A [m] --> acetyl-CoA [m] + FADH2 [m] + H+ [m] + NADH [m] + 5,8,11-Tetradecatrienoyl Coenzyme A [m]
MAR05177 | CoA [m] + FAD [m] + H2O [m] + NAD+ [m] + 5,8,11-Tetradecatrienoyl Coenzyme A [m] --> acetyl-CoA [m] + FADH2 [m] + H+ [m] + NADH [m] + 3,6,9-Dodecatrienoyl Coenzyme A [m]
MAR05090 | 3,6,9-Dodecatrienoyl Coenzyme A [m] --> 2,6,9-Dodecatrienoyl Coenzyme A [m]
MAR05083 | CoA [m] + H2O [m] + NAD+ [m] + 2,6,9-Dodecatrienoyl Coenzyme A [m] --> acetyl-CoA [m] + H+ [m] + NADH [m] + 4,7-Decadienoyl Coenzyme A [m]
MAR04978 | FAD [m] + 4,7-Decadienoyl Coenzyme A [m] --> FADH2 [m] + 2,4,7-Decatrienoyl Coenzyme A [m]
MAR05001 | H+ [m] + NADPH [m] + 2,4,7-Decatrienoyl Coenzyme A [m] --> NADP+ [m] + 3,7-Decadienoyl Coenzyme A [m]
MAR04988 | 3,7-Decadienoyl Coenzyme A [m] --> 2,7-Decadienoyl Coenzyme A [m]
MAR04984 | CoA [m] + H2O [m] + NAD+ [m] + 2,7-Decadienoyl Coenzyme A [m] --> acetyl-CoA [m] + H+ [m] + NADH [m] + 5-Octenoyl Coenzyme A [m]
MAR06320 | CoA [m] + FAD [m] + H2O [m] + NAD+ [m] + 5-Octenoyl Coenzyme A [m] --> acetyl-CoA [m] + FADH2 [m] + H+ [m] + NADH [m] + 3-Hexenoyl Coenzyme A [m]
MAR06281 | 3-Hexenoyl Coenzyme A [m] --> (2E)-hexenoyl-CoA [m]
MAR03157 | (2E)-hexenoyl-CoA [m] + H2O [m] --> (S)-hydroxyhexanoyl-CoA [m]
MAR03158 | (S)-hydroxyhexanoyl-CoA [m] + NAD+ [m] --> 3-oxohexanoyl-CoA [m] + H+ [m] + NADH [m]
MAR03160 | 3-oxohexanoyl-CoA [m] + CoA [m] --> acetyl-CoA [m] + butyryl-CoA [m]
MAR03163 | butyryl-CoA [m] + FAD [m] --> crotonyl-CoA [m] + FADH2 [m]
MAR03164 | crotonyl-CoA [m] + H2O [m] --> (S)-3-hydroxybutyryl-CoA [m]
MAR03166 | (S)-3-hydroxybutyryl-CoA [m] + NAD+ [m] --> acetoacetyl-CoA [m] + H+ [m] + NADH [m]
MAR03885 | acetoacetyl-CoA [m] + CoA [m] <=> 2 acetyl-CoA [m]

There's also `MAR00789`, which turns linolenoyl-CoA into octanoyl-CoA in a single step, but as you can see in the above table, octanoyl-CoA isn't actually an intermediate in the beta-oxidation of linolenoyl-CoA.

Proposed changes:

- [x] Remove `MAR03426` for being a duplicate of `MAR05359` + `MAR05194` + `MAR05177` + `MAR05090` + `MAR05083` + `MAR04978` + `MAR05001` + `MAR04988` + `MAR04984` + `MAR06320` + `MAR06281` + `MAR03157` + `MAR03158` + `MAR03160` + `MAR03163` + `MAR03164` + `MAR03166` + `MAR03885`
- [x] Remove `MAR00789` for being an inaccurate representation of the beta-oxidation of linolenoyl-CoA

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer thanks for presenting this clear table!

Based on the table, it makes sense to remove MAR03426 and MAR00789, though would argue that octanoyl-CoA may still be an intermediate in the beta-oxidation of linolenoyl-CoA

**Comment by Devlin-Moyer** [comment]
as far as I know, there is no possible way to form octanoyl-CoA as an intermediate in the beta-oxidation of linolenoyl-CoA due to the position of the double bonds:

![linolenic_acid](https://github.com/SysBioChalmers/Human-GEM/assets/33460176/12f15062-787a-4927-a40c-f61002b9717f)

Linolenic acid is 9Z,12Z,15Z-octadecatrienoic acid. Before beta-oxidation of free fatty acids can begin, they are converted in to acyl-CoA esters at their carboxy group, and each round of beta-oxidation removes two carbons at a time from the main chain as acetyl-CoA, starting from the original carboxy group and proceeding down the chain until nothing is left (see e.g. [this review](https://doi.org/10.1146/annurev.nutr.21.1.193)). So one round of beta-oxidation on 9Z,12Z,15Z-octadecatrienoyl-CoA would yield 7Z,10Z,13Z-hexadecatrienoyl-CoA (two carbons shorter, numbers indicating positions of double bonds go down by 2), another would produce 5Z,8Z,11Z-tetradecatrienoyl-CoA, then 3Z,6Z,11Z-dodecatrienoyl-CoA, then 4Z,7Z-decadienoyl-CoA, then 5Z-octenoyl-CoA (you'll notice this is exactly what the above reactions depict). I know of no enzymes that normally participate in mitochondrial beta-oxidation that reduce 5-cis-enoyl-CoAs to their corresponding fully saturated acyl-CoAs (again, see the review I cited earlier). Even though the first 8 carbons in the chain have no double bonds between them, beta-oxidation starts at the carboxy group and moves inwards, so the unsaturated part of the chain isn't removed until the whole saturated stretch has already been removed.

Some fatty acids undergo omega-oxidation in the endoplasmic reticulum before they undergo beta-oxidation (again, see the review), which turns the other end of the carbon chain into a second carboxy group, potentially allowing beta-oxidation starting from the other end of the molecule and removing the unsaturated portion of the chain first. However, the original carboxy group remains intact throughout beta-oxidation of dicarboxylic acids, so after five rounds of beta-oxidation from the omega-end of linolenic acid, you'd be left with suberyl-CoA/octanedoic acid rather than octanoyl-CoA/octanoic acid, and again, as far as I know, there are no enzymes that are normally a part of mitochondrial beta-oxidation that would reduce one of those carboxy groups to a methyl group to yield octanoyl-CoA. The ultimate fate of dicarboxylic acids undergoing beta-oxidation is usually succinyl-CoA, i.e. neither carboxy group is ever removed until we definitively exit the realm of beta-oxidation and enter other pathways.

Also this whole point is moot because even if octanoyl-CoA were an intermediate in the beta-oxidation of linolenic acid, `MAR00789` would still be duplicating most of the other reactions I mentioned

**Comment by haowang-bioinfo** [comment]
> Also this whole point is moot because even if octanoyl-CoA were an intermediate in the beta-oxidation of linolenic acid, MAR00789 would still be duplicating most of the other reactions I mentioned

exactly, `it makes sense to remove lumped MAR03426 and MAR00789`, as mentioned earlier. And thanks for the detail explanations about Linolenic acid oxidation and appreciate it. However, these information and the review paper only represent the current knowledge 

> there is no possible way to form octanoyl-CoA as an intermediate in the beta-oxidation of linolenoyl-CoA due to the position of the double bonds

Without evidence, of course it cannot be presented as an intermediate of linolenic acid breakdown, since we follow the rule of evidence-based curation. But `no evidence doesn't equal impossible`, it may be that the required enoyl-CoA isomerase and/or 2,4-dienoyl-CoA reductase haven't been discovered yet

**Comment by haowang-bioinfo** [comment]
fixed by #768
