### ISSUE TITLE
Genes expressed in peroxisome but found in GPR of beta-oxidation reactions in mitochondria

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#767]
#### Current behavior:

Inspired by #746, the following peroxisome genes are found by this [code](https://github.com/SysBioChalmers/Human-GEM/pull/770/files#diff-186bf4f9b5d35a79293ff1230e7cd76d9a16b2fcb2bd2dad9e1cabe2557dac1f) through following steps:
1. find reactions that are in mitochondria compartment from `Fatty acid oxidation` subsystem
2. go through these reactions and check each gene's compartment based on the annotation in `genes.tsv`
3. report the ones that suppose to be expressed only in peroxisome compartment

| Reaction | Peroxisome gene | Equation | GPR | GPR in gene name |
| -------- | --------------- | --------------------- | ---- | ---- |
| MAR02028 | ENSG00000115425 | NADP+ + palmitoyl-CoA <=> (2E)-hexadecenoyl-CoA + H+ + NADPH | ENSG00000115425 or ENSG00000116353 | PECR or MECR |
| MAR02148 | ENSG00000115425 | NADP+ + octanoyl-CoA <=> (2E)-octenoyl-CoA + H+ + NADPH | ENSG00000115425 or ENSG00000116353 | PECR or MECR |
| MAR02149 | ENSG00000115425 | lauroyl-CoA + NADP+ <=> (2E)-dodecenoyl-CoA + H+ + NADPH | ENSG00000115425 or ENSG00000116353 | PECR or MECR |
| MAR02183 | ENSG00000115425 | myristoyl-CoA + NADP+ <=> (2E)-tetradecenoyl-CoA + H+ + NADPH | ENSG00000115425 or ENSG00000116353 | PECR or MECR |
| MAR02187 | ENSG00000115425 | decanoyl-CoA + NADP+ <=> (2E)-decenoyl-CoA + H+ + NADPH | ENSG00000115425 or ENSG00000116353 | PECR or MECR |
| MAR02207 | ENSG00000115425 | (2E)-hexenoyl-CoA + H+ + NADPH <=> hexanoyl-CoA + NADP+ | ENSG00000115425 or ENSG00000116353 | PECR or MECR |
| MAR02381 | ENSG00000060971 | 3-oxooleoyl-CoA + CoA --> acetyl-CoA + palmitoleoyl-CoA | (ENSG00000138029 and ENSG00000167315) or (ENSG00000060971 and ENSG00000138029) | (HADHB and ACAA2) or (ACAA1 and HADHB) |
| ~~MAR03269~~ | ENSG00000133835 | NAD+ + 3(S)-3-Hydroxydodecen-(5Z)-Oyl Coenzyme A <=> H+ + NADH + 3-Oxolaur-Cis-5-Enoyl Coenzyme A | ENSG00000072506 or ENSG00000084754 or ENSG00000113790 or ENSG00000133835 or ENSG00000138029 or ENSG00000138796 | HSD17B10 or HADHA or EHHADH or HSD17B4 or HADHB or HADH |
| ~~MAR03269~~ | ENSG00000113790 | NAD+ + 3(S)-3-Hydroxydodecen-(5Z)-Oyl Coenzyme A <=> H+ + NADH + 3-Oxolaur-Cis-5-Enoyl Coenzyme A | ENSG00000072506 or ENSG00000084754 or ENSG00000113790 or ENSG00000133835 or ENSG00000138029 or ENSG00000138796 | HSD17B10 or HADHA or EHHADH or HSD17B4 or HADHB or HADH |
| MAR03297 | ENSG00000113790 | H2O + Trans,Cis-Dodeca-2,5-Dienoyl Coenzyme A <=> 3(S)-3-Hydroxydodecen-(5Z)-Oyl Coenzyme A | ENSG00000084754 or ENSG00000113790 or ENSG00000127884 or ENSG00000138029 | HADHA or EHHADH or ECHS1 or HADHB |
| MAR03374 | ENSG00000113790 | trans-2-cis,cis-5,8-tetradecatrienoyl-CoA <=> (3E,5Z,8Z)-Tetradecatrienoyl Coenzyme A | ENSG00000113790 or ENSG00000167969 or ENSG00000198721 | EHHADH or ECI1 or ECI2 |
| MAR03378 | ENSG00000113790 | Trans-2-Cis-8-Tetradecadienoyl Coenzyme A <=> Trans-3-Cis-8-Tetradecadienoyl Coenzyme A | ENSG00000113790 or ENSG00000167969 or ENSG00000198721 | EHHADH or ECI1 or ECI2 |
| MAR03379 | ENSG00000113790 | H2O + Trans-2-Cis-8-Tetradecadienoyl Coenzyme A <=> (3S)-3-Hydroxy-Cis-8-Tetradecenoyl Coenzyme A | ENSG00000084754 or ENSG00000113790 or ENSG00000127884 or ENSG00000138029 | HADHA or EHHADH or ECHS1 or HADHB |
| ~~MAR03380~~ | ENSG00000113790 | NAD+ + (3S)-3-Hydroxy-Cis-8-Tetradecenoyl Coenzyme A <=> H+ + NADH + 3-Oxo-Cis-8-Tetradecenoyl Coenzyme A | ENSG00000072506 or ENSG00000113790 or ENSG00000133835 or ENSG00000138796 | HSD17B10 or EHHADH or HSD17B4 or HADH |
| ~~MAR03380~~ | ENSG00000133835 | NAD+ + (3S)-3-Hydroxy-Cis-8-Tetradecenoyl Coenzyme A <=> H+ + NADH + 3-Oxo-Cis-8-Tetradecenoyl Coenzyme A | ENSG00000072506 or ENSG00000113790 or ENSG00000133835 or ENSG00000138796 | HSD17B10 or EHHADH or HSD17B4 or HADH |

#### Expected feature/value/output:

Remove Peroxisome genes in above table from listed mitochondrial beta-oxidation reactions.

**Comment by haowang-bioinfo** [comment]
after merging #760, GPRs of MAR03269 and MAR03380 had been resolved and thus excluded from this issue

the changes proposed here to MAR02381 overlap with #759, could thus be implemented together

**Comment by Devlin-Moyer** [comment]
oh yea that would work; go ahead

**Comment by haowang-bioinfo** [comment]
> oh yea that would work; go ahead

now the proposed change in #759 has been implemented in #770

**Comment by haowang-bioinfo** [comment]
fixed by #770
