### ISSUE TITLE
Naming convention for rxns/mets identifiers in humanGEM

### ISSUE THREAD

**Issue by Hao-Chalmers** [SysBioChalmers/Human-GEM#77]
### Description of the issue:
* There have been no newly added reactions in **humanGEM** since the generation. Yet new reactions (and mets) will come now and then later. And the naming convention of forthcoming rxns/mets ids should be determined in advance.
* Here I propose a nomenclatures that is expected to be applied to new reaction/metabolite identifiers in the future.
* This issue is to bring up open discussion to the proposal. Constructive suggestions and ideas are highly welcome.

#### Expected feature/value/output:
* All existing **HMR** rxns/mets ids will remain unchanged, to avoid any further conversions.
* Given that the **humanGEM** is inherited from **HMR**, it is preferred to follow the existing style for new ids, simply by increasing the number of numerical part.
* For example, **HMR** has rxn ids from `HMR_0001` up to `HMR_9818`. I suggest to assign new reactions with ids starting form `HMR_10000`, and `HMR_10001`, `HMR_10002`, and onward...
* The existing met ids were organized as such: 'm' is followed by 5 digits and ended with comp abbreviation (e.g. `m00001c`). So far, the middle five digits range from 00001 up to 03170. Therefore, the upcoming new mets could be assigned as `m03171c`, `m03172m`, and onward...
* This would also reserve the identify of **HMR** database, despite of its renaming to **humanGEM**

**I hereby confirm that I have:**
- [X] Done this analysis in the `master` branch of the repository v0.7.0
- [X] Checked that a similar issue does not exist already

**Comment by vandutt** [comment]
Hello,
For the mets id in humanGEM, there are currently two types of assignation of compartments. Could m03171c be m03171_c, like tmacmp_c, to facilitate the parsing?
Thank you.
Du Tran

**Comment by Hao-Chalmers** [comment]
@vandutt thank you for the comments.

HumanGEM is inherited from the `HMR2` and `Recon3D`, which have different met id formats that have been retained for backward compatibility.

Note that one can directly get the metabolite compartment info through the `metComps` field provided in the model.

**Comment by Hao-Chalmers** [comment]
This convention for naming new rxn/met ids has been adopted since v0.8 and functioning well.
