### ISSUE TITLE
Duplicate Phytanic Acid/Phytanate Metabolites

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#774]
### Current behavior:

There are separate metabolites for phytanic acid (`MAM02746`) and phytanate (`MAM03884`) that participate in nearly identical reactions:

Reaction | phytanic acid ID | phytanate ID
---|---|---
Exchange | `MAR09037` | `MAR00659`
[e] <-> [c] Transport | `MAR00440` | `MAR01617`
CoA Esterification in [c] | `MAR03480` | `MAR00740`
CoA Esterification in [x] | `MAR03482` | `MAR05323`
CoA Hydrolysis in [x] | None | `MAR01675`

### Expected feature/value/output:

As in #716, I don't think that there should be separate metabolites for both the acid and its conjugate base, and I'm proposing to keep the metabolites representing the acid (`MAM02746`) and removing those representing the conjugate base (`MAM03884`). Since there is no existing peroxisomal CoA hydrolysis reaction that produces phytanic acid, instead of removing `MAR01675`, I'm proposing that it be edited to produce phytanic acid (`MAM02746`) instead of phytanate (`MAM03884`).

### Proposed changes:

- [ ] Remove `MAR00659` for being a duplicate of `MAR09037`
- [ ] Remove `MAR01617` for being a duplicate of `MAR00440`
- [ ] Remove `MAR00740` for being a duplicate of `MAR03480`
- [ ] Remove `MAR05323` for being a duplicate of `MAR03482`
- [ ] Replace `MAM03884x` with `MAM02746x` in `MAR01675`
- [ ] Remove `MAM03884e`, `MAM03884c`, and `MAM03884x` for being duplicates of `MAM02746e`, `MAM02746c`, and `MAM02746x`, respectively

**Comment by pranasag** [comment]
Hi @Devlin-Moyer, could you confirm which version of the model you are using? I see only some of the reaction identifiers you highlighted - using `v1.18`. Haven't checked thoroughly, but at least some of them have been removed already (see `/data/deprecatedIdentifiers/deprecatedReactions.tsv`).

**Comment by Devlin-Moyer** [comment]
oh yep I missed that; all of these proposed changes were implemented back in #646
