### ISSUE TITLE
Duplicate Reactions For Alpha-Oxidation of Phytanoyl-CoA

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#775]
### Current behavior:

There are currently two parallel representations of the peroxisomal alpha-oxidation of phytanoyl-CoA to pristanic acid:

ID | Reaction | Genes
---|---|---
`MAR03484` | AKG + O2 + phytanoyl-CoA --> 2-hydroxyphytanoyl-CoA + CO2 + succinate | PHYH
`MAR03486` | 2-hydroxyphytanoyl-CoA --> 2(S)-pristanal + formyl-CoA | HACL1 or KRTAP11-1
`MAR03386` | 2(S)-pristanal + H2O + NAD+ <=> 2 H+ + NADH + pristanic acid | PHYH
`MAR05186` | 2-hydroxyphytanoyl-CoA + H2O + NADP+ --> formyl-CoA + 2 H+ + NADPH + pristanic acid | ALDH3A2 and HACL1
`MAR05187` | 2-hydroxyphytanoyl-CoA + H2O + NAD+ --> formyl-CoA + 2 H+ + NADH + pristanic acid | ALDH3A2 and HACL1

### Expected behavior:

- `MAR05187` is redundant with `MAR03486` + `MAR03386`, so I think it should be removed. 
- Uniprot seems to think that [ALDH3A2](https://www.uniprot.org/uniprotkb/P51648/entry) is NAD<sup>+</sup>-dependent, not NADP<sup>+</sup>-dependent, so I think `MAR05186` is just wrong and should also be removed. 
- I can find no evidence that [KRTAP11-1](https://www.uniprot.org/uniprotkb/Q8IUC1/entry) (`ENSG00000182591`) has any enzymatic activity at all, much less for the specific reaction that `MAR03486` represents, so I think it should be removed from the GPR of `MAR03486` and from Human-GEM entirely (`MAR03486` is the only reaction it is currently associated with). 
- The GPR of `MAR03386` should be ALDH3A2, not [PHYH](https://www.uniprot.org/uniprotkb/O14832/entry) (`ENSG00000107537`); PHYH only catalyzes 2-hydroxylation of various acyl-CoA esters, i.e. the reaction represented in `MAR03484` -- ALDH3A2 is responsible for the oxidation of aldehydes to carboxylic acids (see Uniprot).

### Proposed changes:

- [x] Remove `MAR05187` for being a duplicate of `MAR03486` + `MAR03386`
- [x] Remove `MAR05186` for being a misrepresentation of the catalytic activity of ALDH3A2
- [x] Change the GPR of `MAR03386` to `ENSG00000072210`
- [x] Remove `ENSG00000182591` from the GPR of `MAR03486` and everywhere else

**Comment by haowang-bioinfo** [comment]
very interesting topic - before going into the detail, I'd like to ask why are you looking into alpha-oxidation phytanoyl-CoA, or actually also aiming to systematically formulate entire beta oxidation? @Devlin-Moyer

**Comment by Devlin-Moyer** [comment]
I'm working on a new semi-automated model curation tool that identifies reactions that form loops capable of sustaining infinite fluxes, and one such loop was phytanic acid [c] -> phytanoyl-CoA [c] -> phytanoyl-CoA [x] -> phytanic acid [x] -> phytanic acid [c]. Notably, that loop hasn't existed since #648, but I've been testing/developing the tool on version 1.15 of Human-GEM to see if I can now automatically detect any of the problems I previously identified in a more ad-hoc fashion.

**Comment by Devlin-Moyer** [comment]
But also, after you suggested that I split #634 into multiple issues in #726, I noticed that several of the mitochondrial reactions that were associated with peroxisomal genes seemed like they should be removed for being duplicates of other reactions that didn't have peroxisomal genes associated with them, so the idea behind most of the recent issues about inconsistencies in fatty acid oxidation reactions is to get rid of all the mitochondrial reactions that shouldn't exist in the first place before worrying about removing the peroxisomal genes from their GPRs

**Comment by haowang-bioinfo** [comment]
> I'm working on a new semi-automated model curation tool that identifies reactions that form loops capable of sustaining infinite fluxes, and one such loop was phytanic acid [c] -> phytanoyl-CoA [c] -> phytanoyl-CoA [x] -> phytanic acid [x] -> phytanic acid [c]. Notably, that loop hasn't existed since https://github.com/SysBioChalmers/Human-GEM/issues/648, but I've been testing/developing the tool on version 1.15 of Human-GEM to see if I can now automatically detect any of the problems I previously identified in a more ad-hoc fashion. While looking into that, I noticed all the problems in this issue, https://github.com/SysBioChalmers/Human-GEM/issues/774, https://github.com/SysBioChalmers/Human-GEM/issues/776, and https://github.com/SysBioChalmers/Human-GEM/issues/777

very good - could you please bring up this semi-automated tool as a [discussion](https://github.com/SysBioChalmers/Human-GEM/discussions) so that it could be eventually converted into GH action bot, which can avoid such cases from happening in the future while fixing the existing ones

**Comment by haowang-bioinfo** [comment]
the provided evidence seems fine and the proposed changes are rational, please move on to implementation

**Comment by Devlin-Moyer** [comment]
Fixed by #792
