### ISSUE TITLE
Duplicate Stearoyl-CoA Beta-Oxidation Reactions

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#802]
### Current behavior:

There appear to be a few duplicate reactions representing the beta-oxidation of stearoyl-CoA:

ID | Reaction | GPR
---|---|---
`MAR03115` | FAD [m] + stearoyl-CoA [m] --> (2E)-octadecenoyl-CoA [m] + FADH2 [m] | ACADVL or ACADL or ACADM or ACAD9
`MAR03116` | (2E)-octadecenoyl-CoA [m] + H2O [m] --> 3-hydroxyoctadecanoyl-CoA [m] | HADHA and EHHADH and ECHS1
`MAR03117` | 3-hydroxyoctadecanoyl-CoA [m] + NAD+ [m] --> 3-oxooctadecanoyl-CoA [m] + H+ [m] + NADH [m] | HSD17B10 and HADHA and HADH
`MAR03118` | 3-oxooctadecanoyl-CoA [m] + CoA [m] --> acetyl-CoA [m] + palmitoyl-CoA [m] | HADHA and HADHB and ACAA2
`MAR03121` | FAD [m] + palmitoyl-CoA [m] --> (2E)-hexadecenoyl-CoA [m] + FADH2 [m] | ACADVL or ACADL or ACADM or ACAD9
`MAR03122` | (2E)-hexadecenoyl-CoA [m] + H2O [m] --> (S)-3-hydroxyhexadecanoyl-CoA [m] | HADHA and EHHADH and ECHS1
`MAR03123` | (S)-3-hydroxyhexadecanoyl-CoA [m] + NAD+ [m] --> 3-oxopalmitoyl-CoA [m] + H+ [m] + NADH [m] | HSD17B10 and HADHA and HADH
`MAR03125` | 3-oxopalmitoyl-CoA [m] + CoA [m] --> acetyl-CoA [m] + myristoyl-CoA [m] | HADHA and HADHB and ACAA2
`MAR03128` | FAD [m] + myristoyl-CoA [m] --> (2E)-tetradecenoyl-CoA [m] + FADH2 [m] | ACADVL or ACOX3 or ACADL or ACADM or ACOX1 or ACAD9
`MAR03129` | (2E)-tetradecenoyl-CoA [m] + H2O [m] --> (S)-3-hydroxytetradecanoyl-CoA [m] | HADHA and EHHADH and ECHS1
`MAR03130` | (S)-3-hydroxytetradecanoyl-CoA [m] + NAD+ [m] --> 3-oxotetradecanoyl-CoA [m] + H+ [m] + NADH [m] | HSD17B10 and HADHA and HADH
`MAR03132` | 3-oxotetradecanoyl-CoA [m] + CoA [m] --> acetyl-CoA [m] + lauroyl-CoA [m] | HADHA and HADHB and ACAA2
`MAR03135` | FAD [m] + lauroyl-CoA [m] --> (2E)-dodecenoyl-CoA [m] + FADH2 [m] | ACADVL or ACADL or ACADM or ACAD9
`MAR03136` | (2E)-dodecenoyl-CoA [m] + H2O [m] --> (S)-3-hydroxydodecanoyl-CoA [m] | HADHA and EHHADH and ECHS1
`MAR03137` | (S)-3-hydroxydodecanoyl-CoA [m] + NAD+ [m] --> 3-oxododecanoyl-CoA [m] + H+ [m] + NADH [m] | HSD17B10 and HADHA and HADH
`MAR03139` | 3-oxododecanoyl-CoA [m] + CoA [m] --> acetyl-CoA [m] + decanoyl-CoA [m] | HADHA and HADHB and ACAA2
`MAR03142` | FAD [m] + decanoyl-CoA [m] ⇒ (2E)-decenoyl-CoA [m] + FADH2 [m] | ACADM or ACAD9
`MAR03143` | (2E)-decenoyl-CoA [m] + H2O [m] ⇒ (S)-hydroxydecanoyl-CoA [m] | HADHA and EHHADH and ECHS1
`MAR03144` | (S)-hydroxydecanoyl-CoA [m] + NAD+ [m] ⇒ 3-oxodecanoyl-CoA [m] + H+ [m] + NADH [m] | HSD17B10 and HADHA and HADH
`MAR03146` | 3-oxodecanoyl-CoA [m] + CoA [m] ⇒ acetyl-CoA [m] + octanoyl-CoA [m] | HADHA and HADHB and ACAA2
`MAR00776` | CoA [m] + FAD [m] + H2O [m] + NAD+ [m] + stearoyl-CoA [m] --> acetyl-CoA [m] + FADH2 [m] + H+ [m] + NADH [m] + palmitoyl-CoA [m] | ACADM or ACADS
`MAR00778` | (2E)-octadecenoyl-CoA [m] + 5 CoA [m] + 4 FAD [m] + 5 H2O [m] + 5 NAD+ [m] --> 5 acetyl-CoA [m] + 4 FADH2 [m] + 5 H+ [m] + 5 NADH [m] + octanoyl-CoA [m] | ACADM or ACADS

### Proposed changes:

- [x] Remove `MAR00776` for being a duplicate of `MAR03115` + `MAR03116` + `MAR03117` + `MAR03118`
- [x] Remove `MAR00778` for being a duplicate of  `MAR03116` + `MAR03117` + `MAR03118` + `MAR03121` + `MAR03122` + `MAR03123` + `MAR03125` + `MAR03128` + `MAR03129` + `MAR03130` + `MAR03132` +`MAR03135` + `MAR03136` + `MAR03137` + `MAR03139` + `MAR03142` + `MAR03143` + `MAR03144` + `MAR03146`

**Comment by feiranl** [comment]
ACADS is annotated with [MAR03163](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03163) , consistent with [UniProt annotation](https://www.uniprot.org/uniprotkb/P16219/entry), and also ACADM is correctly associated with the first step of beta-oxidation, so I agree it is ok to remove the `MAR00776`  and `MAR00778`.

**Comment by feiranl** [comment]
Please go ahead and make the PR. Thanks! @Devlin-Moyer

**Comment by Devlin-Moyer** [comment]
Fixed in #820
