### ISSUE TITLE
Error: MipGap too high, trying with a different run

### ISSUE THREAD

**Issue by meipingchang** [SysBioChalmers/Human-GEM#812]
Hi, I was following the tutorial at https://sysbiochalmers.github.io/Human-GEM-guide/gem_extraction/ to run ftINIT use the same data as the tutorial. By running the following command, I got the error "MipGap too high, trying with a different run". I use glpk for MILP since I don't have gorubi solver. What could be the reason for this error?

changeCobraSolver('glpk', 'MILP'); 
setRavenSolver('cobra');
model1 = ftINIT(prepData, data_struct.tissues{1}, [], [], data_struct, {}, getHumanGEMINITSteps('1+0'), false, true);

**Comment by JHL-452b** [comment]
Hello, I've tried using the `glpk` solver to run ftINIT and encountered the same issue as you did. This seems to be a common problem. However, when I switched to `gurobi` solver, ftINIT ran successfully. So, it seems this might be solver-related. 

As we discussed in [issue 810](https://github.com/SysBioChalmers/Human-GEM/issues/810), Human-GEM is large in scale, and ftINIT tasks are complex, requiring certain performance of the solver. 

Additionally, I noticed [that](https://github.com/SysBioChalmers/RAVEN/wiki/Installation#solvers) `glpk` is not feasible for MILP problems in tINIT. So you'd better use other solvers if possible.

**Comment by meipingchang** [comment]
> Hello, I've tried using the `glpk` solver to run ftINIT and encountered the same issue as you did. This seems to be a common problem. However, when I switched to `gurobi` solver, ftINIT ran successfully. So, it seems this might be solver-related.
> 
> As we discussed in [issue 810](https://github.com/SysBioChalmers/Human-GEM/issues/810), Human-GEM is large in scale, and ftINIT tasks are complex, requiring certain performance of the solver.
> 
> Additionally, I noticed [that](https://github.com/SysBioChalmers/RAVEN/wiki/Installation#solvers) `glpk` is not feasible for MILP problems in tINIT. And there was a similar [issue](https://github.com/SysBioChalmers/RAVEN/issues/518) in RAVEN, you can refer to it if necessary.

Thank you for sharing your insights.

**Comment by edkerk** [comment]
Thanks @JHL-452b, this is indeed solver related.

To avoid such confusions, I'll make ftINIT (a RAVEN function) throw an error if glpk is set as solver.

Meanwhile, `scip` should be able to function as open source alternative (although it is much slower than Gurobi).

**Comment by meipingchang** [comment]
> Thanks @JHL-452b, this is indeed solver related.
> 
> To avoid such confusions, I'll make ftINIT (a RAVEN function) throw an error if glpk is set as solver.
> 
> Meanwhile, `scip` should be able to function as open source alternative (although it is much slower than Gurobi).

@edkerk Thanks for the suggestion using 'scip' as the solver. I tried to look in the web on how to install scip with matlab to use with RAVEN/ftINIT for mac computer, but could not figure out. Can you please share with me the installation process?

**Comment by mihai-sysbio** [comment]
@meipingchang I've been struggling with the same for a long time, but it looks like there is no support this. I've installed `scip` with [brew.sh](http://brew.sh/), but the Matlab interface](https://github.com/scipopt/MatlabSCIPInterface) has no support for macOS. I've done some installation tweaks for the paths to work but in the end it doesn't seem like this can work as support for `mexmaci64`, the library format for macOS, is missing.
