### ISSUE TITLE
Unbalance reactions about FAD/Oxygen

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#813]
There appear to be a few unbalanced reactions which FAD/Oxygen have involved
#### Current behavior:
ID | Reaction | Cause of imbalance
---|---|---
`MAR08415` | 2 H+ + 2 O2- --> FAD + FADH2 | {'charge': -4, 'H': 62, 'C': 54, 'N': 18, 'O': 26, 'P': 4}
`MAR03984` | 2 FADH2 --> FAD + 2 H2O | {'charge': 2, 'H': -31, 'O': -13, 'C': -27, 'N': -9, 'P': -2}
`MAR12372` | 2 CoA + FAD + 2 H2O + 2 NAD+ + 3'-S-hydroxy-pravastatin-CoA --> 2 acetyl-CoA + 2 FADH2 + 2 H+ + 2 NADH + 3'-S-hydroxy-pravastatin-tetranor-CoA | {'charge': -2, 'C': 27, 'H': 31, 'N': 9, 'O': 13, 'P': 2}

I traced the modification history of these reactions and found that they were modified in [PR670](https://github.com/SysBioChalmers/Human-GEM/pull/670) and resulted in an imbalance. There are obvious imbalance errors in these reactions and may even lead to model inconsistencies. 

#### Proposed changes
Modify the reaction back to its original form.

ID | Reaction now | Reaction before
---|---|---
`MAR08415` | 2 H+ + 2 O2- --> FAD + FADH2 | 2 H+ + 2 O2- --> H2O2 + O2
`MAR03984` | 2 FADH2 --> FAD + 2 H2O | 2 H2O2 --> 2 H2O + O2
`MAR12372` | 2 CoA + FAD + 2 H2O + 2 NAD+ + 3'-S-hydroxy-pravastatin-CoA --> 2 acetyl-CoA + 2 FADH2 + 2 H+ + 2 NADH + 3'-S-hydroxy-pravastatin-tetranor-CoA | 2 CoA + 2 H2O + 2 NAD+ + O2 + 3'-S-hydroxy-pravastatin-CoA --> 2 acetyl-CoA + 2 H+ + 2 H2O2 + 2 NADH + 3'-S-hydroxy-pravastatin-tetranor-CoA

**Comment by feiranl** [comment]
Nice catch! @Devlin-Moyer It would be great if you can double check this. Thanks!

**Comment by Devlin-Moyer** [comment]
ah yep those reactions are all definitely unbalanced and should be reverted to their earlier forms; sorry for not noticing them back in #670
