### ISSUE TITLE
Unbalance reactions checked in the new content of Human-GEM

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#814]
#### Current behavior:

With the curation of Human-GEM, there are some unbalance rxns here that did not exist in the previous model.

ID | Reaction | Cause of imbalance | changing source |
|-|-|-|-|
|`MAR01444`|ATP + H+ + H2O + K+ + 2 Na+ --> ADP + H+ + K+ + 2 Na+ + Pi|{'charge': -1, 'H': -1}| [#581](https://github.com/SysBioChalmers/Human-GEM/pull/581)
|`MAR20005`|H2O + NAD+ + 20-oxo-(5Z,8Z,11Z,14Z)-eicosatetraenoate --> 2 H+ + NADH + (5Z,8Z,11Z,14Z)-eicosatetraenedioate|{'charge': 1}| [addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L6)|
|`MAR20006`|H2O + NAD+ + 20-oxo-(5Z,8Z,11Z,14Z)-eicosatetraenoate --> 2 H+ + NADH + (5Z,8Z,11Z,14Z)-eicosatetraenedioate|{'charge': 1}| [addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L7)|
|`MAR20007`|10-HETE + NAD+ --> H+ + NADH + 20-oxo-(5Z,8Z,11Z,14Z)-eicosatetraenoate|{'charge': 1}| [addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L8)|
|`MAR20008`|10-HETE + NAD+ --> H+ + NADH + 20-oxo-(5Z,8Z,11Z,14Z)-eicosatetraenoate|{'charge': 1}| [addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L9)|
|`MAR20021`|mead acid + O2 + FMNH2 --> FMN + H+ + H2O + 19-hydroxy-(5Z,8Z,11Z)-eicosatrienoate|{'charge': 2, 'H': 1}| [addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L22)|
|`MAR20022`|mead acid + O2 + FMNH2 --> FMN + H+ + H2O + 19-hydroxy-(5Z,8Z,11Z)-eicosatrienoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L23)|
|`MAR20023`|EPA + O2 + FMNH2 --> FMN + H+ + H2O + 19-hydroxy-(5Z,8Z,11Z,14Z,17Z)-eicosapentaenoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L24)|
|`MAR20024`|EPA + O2 + FMNH2 --> FMN + H+ + H2O + 19-hydroxy-(5Z,8Z,11Z,14Z,17Z)-eicosapentaenoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L25)|
|`MAR20025`|DHA + O2 + FMNH2 --> FMN + H+ + H2O + 21-hydroxy-(4Z,7Z,10Z,13Z,16Z,19Z)-docosahexaenoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L26)|
|`MAR20026`|DHA + O2 + FMNH2 --> FMN + H+ + H2O + 21-hydroxy-(4Z,7Z,10Z,13Z,16Z,19Z)-docosahexaenoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L27)|
|`MAR20027`|lauric acid + O2 + FMNH2 --> FMN + H+ + H2O + 11-hydroxydodecanoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L28)|
|`MAR20028`|lauric acid + O2 + FMNH2 --> FMN + H+ + H2O + 11-hydroxydodecanoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L29)|
|`MAR20029`|myristic acid + O2 + FMNH2 --> FMN + H+ + H2O + 13-hydroxytetradecanoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L30)|
|`MAR20030`|myristic acid + O2 + FMNH2 --> FMN + H+ + H2O + 13-hydroxytetradecanoate|{'charge': 2, 'H': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L31)|
|`MAR20046`|H2O + hexadecenal + NAD+ --> 2 H+ + NADH + (E)-hexadec-2-enoate|{'charge': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L47)|
|`MAR20047`|H2O + hexadecenal + NAD+ --> 2 H+ + NADH + (E)-hexadec-2-enoate|{'charge': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L48)|
|`MAR20049`|H2O + NAD+ + 22-oxodocosanoate --> 2 H+ + NADH + Docosanedioicacid|{'charge': -1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L50)|
|`MAR20050`|H2O + NAD+ + 22-oxodocosanoate --> 2 H+ + NADH + Docosanedioicacid|{'charge': -1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L51)|
|`MAR20064`|2-trans,6-trans-farnesal + H2O + NAD+ --> 2 H+ + NADH + (2E,6E)-farnesoate|{'charge': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L65)|
|`MAR20065`|2-trans,6-trans-farnesal + H2O + NAD+ --> 2 H+ + NADH + (2E,6E)-farnesoate|{'charge': 1}|[addRxnGly_20230414.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnGly_20230414.tsv#L66)|
|`MAR20098`|farnesyl-PP + 5 isopentenyl-pPP --> dehydrodolichol-diphosphate + 5 PPi|{'C': 60, 'H': 96}| [addRxnAA_20230518.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/e5f6a34b0ba85dfbaeeffd5ab94a26e1380648c8/data/modelCuration/addRxnAA_20230518.tsv#L29)
|`MAR20111`|acetyl-CoA + glyoxalate + H2O --> CoA + malate|{'charge': -1, 'H': -1}| [commits](https://github.com/SysBioChalmers/Human-GEM/commit/a822e71f6cc81e4bd5c5a2cfd48b4a822865ce29)|
|`MAR20112`|apoC-lys_btn + ATP + HCO3- --> ADP + H+ + Pi|{'charge': 1, 'C': -17, 'H': -26, 'N': -4, 'O': -5, 'S': -1, 'X': -1}| [#624](https://github.com/SysBioChalmers/Human-GEM/pull/624)|

#### Proposed changes:
|rxn_id|rxn_eq|change|check balance|
|-|-|-|-|
|MAR01444|MAM01371c + MAM02039e + MAM02040c + MAM02200e + 2 MAM02519c --> MAM01285c + MAM02039c + MAM02200c + 2 MAM02519e + MAM02751c|remove H+(MAM02039e):-1|TRUE|
|MAR20005|MAM02040n + MAM02552n + MAM20003n --> 2 MAM02039n + MAM02553n + MAM20004n|change charge of MAM20004n to -1|TRUE|
|MAR20006|MAM02040c + MAM02552c + MAM20005c --> 2 MAM02039c + MAM02553c + MAM20006c|change charge of MAM20006c to -1|TRUE|
|MAR20007|MAM00270n + MAM02552n --> MAM02039n + MAM02553n + MAM20003n|change charge of MAM20004n to -1|TRUE|
|MAR20021|MAM02457r + MAM02630r + MAM20019r --> MAM01828r + MAM02039r + MAM02040r + MAM20018r|remove H+(MAM02039r):1; change charge of MAM20018r to -1|TRUE|
|MAR20022|MAM02457i + MAM02630i + MAM20019i --> MAM01828i + MAM02039i + MAM02040i + MAM20021i|remove H+(MAM02039i):1; change charge of MAM20021i to -1|TRUE|
|MAR20023|MAM01784r + MAM02630r + MAM20019r --> MAM01828r + MAM02039r + MAM02040r + MAM20024r|remove H+(MAM02039r):1; change charge of MAM20024r to -1|TRUE|
|MAR20024|MAM01784i + MAM02630i + MAM20019i --> MAM01828i + MAM02039i + MAM02040i + MAM20025i|remove H+(MAM02039i):1; change charge of MAM20025i to -1|TRUE|
|MAR20025|MAM01689r + MAM02630r + MAM20019r --> MAM01828r + MAM02039r + MAM02040r + MAM20026r|remove H+(MAM02039r):1; change charge of MAM20026r to -1|TRUE|
|MAR20026|MAM01689i + MAM02630i + MAM20019i --> MAM01828i + MAM02039i + MAM02040i + MAM20027i|remove H+(MAM02039i):1; change charge of MAM20027i to -1|TRUE|
|MAR20027|MAM02344r + MAM02630r + MAM20019r --> MAM01828r + MAM02039r + MAM02040r + MAM20028r|remove H+(MAM02039r):1; change charge of MAM20028r to -1|TRUE|
|MAR20028|MAM02344i + MAM02630i + MAM20019i --> MAM01828i + MAM02039i + MAM02040i + MAM20029i|remove H+(MAM02039i):1; change charge of MAM20029i to -1|TRUE|
|MAR20029|MAM02494r + MAM02630r + MAM20019r --> MAM01828r + MAM02039r + MAM02040r + MAM20030r|remove H+(MAM02039r):1; change charge of MAM20030r to -1|TRUE|
|MAR20030|MAM02494i + MAM02630i + MAM20019i --> MAM01828i + MAM02039i + MAM02040i + MAM20031i|remove H+(MAM02039i):1; change charge of MAM20031i to -1|TRUE|
|MAR20046|MAM02040r + MAM02116r + MAM02552r --> 2 MAM02039r + MAM02553r + MAM20041r|change charge of MAM20041r to -1|TRUE|
|MAR20047|MAM02040c + MAM02116c + MAM02552c --> 2 MAM02039c + MAM02553c + MAM20042c|change charge of MAM20042c to -1|TRUE|
|MAR20049|MAM02040r + MAM02552r + MAM20043r --> 2 MAM02039r + MAM02553r + MAM03560r|change charge of MAM20043r to -1|TRUE|
|MAR20050|MAM02040c + MAM02552c + MAM20044c --> 2 MAM02039c + MAM02553c + MAM03560c|change charge of MAM20044c to -1|TRUE|
|MAR20064|MAM00677r + MAM02040r + MAM02552r --> 2 MAM02039r + MAM02553r + MAM20056r|change charge of MAM20056r to -1|TRUE|
|MAR20065|MAM00677c + MAM02040c + MAM02552c --> 2 MAM02039c + MAM02553c + MAM20057c|change charge of MAM20057c to -1|TRUE|
|MAR20098|MAM01806r + 5 MAM02187r --> MAM01657r + 5 MAM02759r|change formula of MAM01657r to 'C40H65O7P2'|TRUE|
|MAR20111|MAM01261m + MAM02007m + MAM02040m --> MAM01597m + MAM02439m|add H+(MAM02039m):1|TRUE|
|MAR20112|MAM01357m + MAM01371m + MAM02046m --> MAM01285m + MAM02039m + MAM02751m|add MAM01422m(1) as productant|TRUE|

All these changes ensure that the current reaction is balanced without affecting other reactions.

**Comment by JHL-452b** [comment]
@Devlin-Moyer I noticed that you have added `MAR20111` and `MAR20112`. Could you please help me to check whether the above modifications are OK?

**Comment by Devlin-Moyer** [comment]
If by "remove H+(MAM02039m):1" you mean "add one H<sup>+</sup> (`MAM02039m`) to `MAR20111` as a product", then yes, both of your proposed fixed for `MAR20111` and `MAR20112` make sense to me; sorry for missing those errors when I created them.

**Comment by JHL-452b** [comment]
> If by "remove H+(MAM02039m):1" you mean "add one H+ (`MAM02039m`) to `MAR20111` as a product"

Yeah, it's a mistake in my statement, which has been corrected.

**Comment by JHL-452b** [comment]
In Human-GEM version 1.18, the above reactions were modified to make the model consistent, but the additional unbalanced reactions in the current develop branch still make the model inconsistent. Thus, I try to find and resolve the following imbalance reactions so that the model regains consistency.

|ID | Reaction | Cause of imbalance | changing source | balance plan| check balance|
|-|-|-|-|-|-|
| `MAR03481`| MAM01371c + 2.0 MAM02040c + MAM02747c <=> MAM01285c + MAM01597c + MAM02039c + MAM02746x + MAM02751c|{'charge': -1.0, 'H': -1.0} | #815 | add additional H+(MAM02039c) as a product| True|
| `MAR20177`| MAM02393m + MAM20081m --> MAM02984m + MAM20082m|{'C': -11.0, 'H': -23.0, 'N': -1.0, 'O': -2.0, 'S': -2.0} | #753 | replace the formula of `MAM20082m` from `None` to `C11H23N1O2S2`| True|

**Comment by Devlin-Moyer** [comment]
Am I missing something or does PR #815 not mention `MAR03481`?

**Comment by Devlin-Moyer** [comment]
ah I see you meant #805; both of your proposed changes to fix the mass balance issues with those reactions look good to me

**Comment by JHL-452b** [comment]
> Am I missing something or does PR #815 not mention `MAR03481`?

Yeah, it's a wrong link and I corrected it. 

So, all these reactions has been modified and I will go head.
