### ISSUE TITLE
Update name of heneicosanoic acid in full metabolic task file

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#828]
#### Current behavior:
During discussion in #825, it was discovered that metabolite [MAM02053](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02053c) was renamed in the model from `henicosanoic acid` to `heneicosanoic acid` in #518 (discussed in #491) since the original name was misspelled; however, the metabolite name was not updated in the metabolic task file [metabolicTasks_Full.txt](https://github.com/SysBioChalmers/Human-GEM/blob/main/data/metabolicTasks/metabolicTasks_Full.txt).

#### Expected feature/value/output:
Rename `henicosanoic acid` to `heneicosanoic acid` in [metabolicTasks_Full.txt](https://github.com/SysBioChalmers/Human-GEM/blob/main/data/metabolicTasks/metabolicTasks_Full.txt).

**Comment by JHL-452b** [comment]
Looks good!  I agree to rename `henicosanoic acid` to `heneicosanoic acid`, but I did not find `henicosanoic acid` in [metabolicTasks_Essential.txt](https://github.com/SysBioChalmers/Human-GEM/blob/main/data/metabolicTasks/metabolicTasks_Essential.txt). This seems a little strange. Could you please specify the task that requires this metabolite involved?

**Comment by JonathanRob** [comment]
Ah, my bad - I meant [metabolicTasks_Full.txt](https://github.com/SysBioChalmers/Human-GEM/blob/main/data/metabolicTasks/metabolicTasks_Full.txt), not the essential task list. I will update this in the issue description.

**Comment by feiranl** [comment]
Agreed!
