### ISSUE TITLE
Error in ftINIT (line 281)

### ISSUE THREAD

**Issue by HayaAlSiyabi** [SysBioChalmers/Human-GEM#834]
### Discussed in https://github.com/SysBioChalmers/Human-GEM/discussions/832

<div type='discussions-op-text'>

<sup>Originally posted by **HayaAlSiyabi** June 27, 2024</sup>
Please help, I have followed the advice given to others with this issue in the past, but removing old version of gurobi and raven and updating them has not helped. I am using TPM_unstranded data from TCGA biolinks, I have the ensemble IDs and gene names followed by TPMs of each sample. I have tried using smaller datasets but this hasn't helped. Please let me know any advice as I have been unable to resolve this alone. Please see below the error:

model2 = ftINIT(prepData, data_struct.tissues{1}, [], [], data_struct, {}, getHumanGEMINITSteps('1+1'), false, true);

ftINIT: Running step 1

MipGap too high, trying with a different run. MipGap = 0.10429 New MipGap Limit = 0.06135

Error using dispEM

Failed to find good enough solution within the time frame. MIPGap: 0.068323

Error in ftINIT (line 281)

        dispEM(['Failed to find good enough solution within the time frame. MIPGap: ' num2str(mipGap)]);</div>

**Comment by JHL-452b** [comment]
Hello!
Sorry late for this.  I've recently used ftINIT to generate some models and didn't encounter any problems. Can you please check if all the tasks were passed when preparing the `prepData`?

**Comment by HayaAlSiyabi** [comment]
TCGA_LIHC_TPM_unstranded.csv
<https://drive.google.com/file/d/1sjFtjx96PxrWeEvFgZXjXtDt_9xcngTK/view?usp=drive_web>
Hello,

I think in the end this was the decimal points after the ensemble IDs so I
removed them, however now I have a new issue where very few reactions are
being identified, is this normal? Please see below,

Many thanks,Haya

load('Human-GEM.mat');
>> prepData = prepHumanModelForftINIT(ihuman, false,
'Human/Human-GEM-1.18.0/data/metabolicTasks/metabolicTasks_Essential.txt',
'Human/Human-GEM-1.18.0/model/reactions.tsv');
Step 1: Gene rules
Step 2: First simplification
Step 3: Check tasks (~10 min)
PASS: [ER] Aerobic rephosphorylation of ATP from glucose
PASS: [ER] Aerobic rephosphorylation of GTP
PASS: [ER] Aerobic rephosphorylation of CTP
PASS: [ER] Aerobic rephosphorylation of UTP
PASS: [BS] ATP de novo synthesis
PASS: [BS] CTP de novo synthesis
PASS: [BS] GTP de novo synthesis
PASS: [BS] UTP de novo synthesis
PASS: [BS] dATP de novo synthesis
PASS: [BS] dCTP de novo synthesis
PASS: [BS] dGTP de novo synthesis
PASS: [BS] dTTP de novo synthesis
PASS: [SU] Histidine uptake
PASS: [SU] Isoleucine uptake
PASS: [SU] Leucine uptake
PASS: [SU] Lysine uptake
PASS: [SU] Methionine uptake
PASS: [SU] Phenylalanine uptake
PASS: [SU] Threonine uptake
PASS: [SU] Tryptophan uptake
PASS: [SU] Valine uptake
PASS: [IC] Glycerate 3-phosphate  de novo synthesis
PASS: [IC] Mitochondrial acetyl-CoA de novo synthesis
PASS: [IC] Mitochondrial AKG de novo synthesis
PASS: [IC] Erythrose 4-phosphate de novo synthesis
PASS: [IC] Fructose 6-phosphate de novo synthesis
PASS: [IC] Glyceraldehyde 3-phosphate de novo synthesis
PASS: [IC] Glucose 6-phosphate de novo synthesis
PASS: [IC] Mitochondrial oxaloacetate de novo synthesis
PASS: [IC] Phosphoenolpyruvate de novo synthesis
PASS: [IC] Pyruvate de novo synthesis
PASS: [IC] Ribose 5-phosphate de novo synthesis
PASS: [IC] Mitochondrial succinyl-CoA de novo synthesis
PASS: [BS] Cholesterol de novo synthesis
PASS: [BS] Protein synthesis from AAs
PASS: [ER] Oxidative phosphorylation
PASS: [ER] Oxidative decarboxylation
PASS: [ER] Krebs cycle NADH
PASS: [ER] Ubiquinol-to-proton
PASS: [ER] Ubiquinol-to-ATP
PASS: [SU] Beta oxidation of saturated FA
PASS: [SU] Beta oxidation of long-chain FA
PASS: [SU] Beta oxidation of odd-chain FA
PASS: [SU] Beta oxidation of unsaturated fatty acid (n-9)
PASS: [SU] Beta oxidation of unsaturated fatty acid (n-6)
PASS: [SU] Uptake and beta oxidation of all NEFAs
PASS: [SU] Choline uptake
PASS: [SU] Inositol uptake
PASS: [BS] Phosphatidylcholine de novo synthesis
PASS: [BS] Phosphatidylethanolamine de novo synthesis
PASS: [BS] Phosphatidylserine de novo synthesis
PASS: [BS] Phosphatidylinositol de novo synthesis
PASS: [BS] Thiamin phosphorylation to TPP
PASS: [BS] Coenzyme A synthesis from pantothenate
PASS: [BS] FAD synthesis from riboflavin
PASS: [BS] Heme biosynthesis
PASS: [GR] Growth on Ham's media (biomass production)
Step 4: Second simplification (~1 hour)
Starting parallel pool (parpool) using the 'Processes' profile ...
Connected to the parallel pool (number of workers: 6).
Running getAllowedBounds |██████████████ 5 min, 11 sec ███████████████|100%
Step 5: Final work
>> save('prepData.mat', 'prepData')
>>
>> setRavenSolver('gurobi')
>>
>> LIHC_TCGA_1 = readtable('TCGA_LIHC_TPM_unstranded.csv');
Warning: Column headers from the file were modified to make them valid
MATLAB identifiers before creating variable names for the table. The
original column headers are saved in
the VariableDescriptions property.
Set 'VariableNamingRule' to 'preserve' to use the original column headers
as table variable names.
>> [~, n] = size(LIHC_TCGA_1);
>>
>> data_struct.genes = LIHC_TCGA_1{:, 1}; % gene names
>> data_struct.tissues = LIHC_TCGA_1.Properties.VariableNames(3:n); %
sample (tissue) names
>> data_struct.levels = LIHC_TCGA_1{:, 3:n}; % gene TPM values
>> numSamp = n-2
numSamp =
   424
>> data_struct
data_struct =
  struct with fields:
      genes: {60660×1 cell}
    tissues: {1×424 cell}
     levels: [60660×424 double]
>> model1 = ftINIT(prepData, data_struct.tissues{1}, [], [], data_struct,
{}, getHumanGEMINITSteps('1+0'), false, true);
ftINIT: Running step 1
[ER] Aerobic rephosphorylation of ATP from glucose: Added 0 reaction(s), 0
reactions added in total
[ER] Aerobic rephosphorylation of GTP: Added 0 reaction(s), 0 reactions added
in total
[ER] Aerobic rephosphorylation of CTP: Added 0 reaction(s), 0 reactions added
in total
[ER] Aerobic rephosphorylation of UTP: Added 0 reaction(s), 0 reactions added
in total
No mets ids with prefix "m_" currently exist in the model. The first new id
will be "m_0001"
task: 5
MAR03025
MAR00977
[BS] ATP de novo synthesis: Added 2 reaction(s), 2 reactions added in total
[BS] CTP de novo synthesis: Added 0 reaction(s), 2 reactions added in total
[BS] GTP de novo synthesis: Added 0 reaction(s), 2 reactions added in total
[BS] UTP de novo synthesis: Added 0 reaction(s), 2 reactions added in total
[BS] dATP de novo synthesis: Added 0 reaction(s), 2 reactions added in total
task: 10
MAR04617
[BS] dCTP de novo synthesis: Added 1 reaction(s), 3 reactions added in total
[BS] dGTP de novo synthesis: Added 0 reaction(s), 3 reactions added in total
[BS] dTTP de novo synthesis: Added 0 reaction(s), 3 reactions added in total
[SU] Histidine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Isoleucine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Leucine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Lysine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Methionine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Phenylalanine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Threonine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Tryptophan uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Valine uptake: Added 0 reaction(s), 3 reactions added in total
[IC] Glycerate 3-phosphate  de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Mitochondrial acetyl-CoA de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Mitochondrial AKG de novo synthesis: Added 0 reaction(s), 3
reactions added
in total
[IC] Erythrose 4-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Fructose 6-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Glyceraldehyde 3-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Glucose 6-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Mitochondrial oxaloacetate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Phosphoenolpyruvate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Pyruvate de novo synthesis: Added 0 reaction(s), 3 reactions added in
total
[IC] Ribose 5-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added
in total
[IC] Mitochondrial succinyl-CoA de novo synthesis: Added 0 reaction(s), 3
reactions added in total
task: 34
MAR01573
MAR01440
[BS] Cholesterol de novo synthesis: Added 2 reaction(s), 5 reactions added
in total
[BS] Protein synthesis from AAs: Added 0 reaction(s), 5 reactions added in
total
[ER] Oxidative phosphorylation: Added 0 reaction(s), 5 reactions added in
total
[ER] Oxidative decarboxylation: Added 0 reaction(s), 5 reactions added in
total
[ER] Krebs cycle NADH: Added 0 reaction(s), 5 reactions added in total
[ER] Ubiquinol-to-proton: Added 0 reaction(s), 5 reactions added in total
[ER] Ubiquinol-to-ATP: Added 0 reaction(s), 5 reactions added in total
[SU] Beta oxidation of saturated FA: Added 0 reaction(s), 5 reactions added
in total
task: 42
MAR03507
MAR03535
[SU] Beta oxidation of long-chain FA: Added 2 reaction(s), 7 reactions added
in total
[SU] Beta oxidation of odd-chain FA: Added 0 reaction(s), 7 reactions added
in total
[SU] Beta oxidation of unsaturated fatty acid (n-9) : Added 0 reaction(s),
7 reactions added in total
[SU] Beta oxidation of unsaturated fatty acid (n-6) : Added 0 reaction(s),
7 reactions added in total
task: 46
MAR02602
MAR03136
[SU] Uptake and beta oxidation of all NEFAs: Added 2 reaction(s), 9
reactions added in total
[SU] Choline uptake: Added 0 reaction(s), 9 reactions added in total
[SU] Inositol uptake: Added 0 reaction(s), 9 reactions added in total
[BS] Phosphatidylcholine de novo synthesis: Added 0 reaction(s), 9
reactions added in total
[BS] Phosphatidylethanolamine de novo synthesis: Added 0 reaction(s), 9
reactions added in total
[BS] Phosphatidylserine de novo synthesis: Added 0 reaction(s), 9
reactions added
in total
[BS] Phosphatidylinositol de novo synthesis: Added 0 reaction(s), 9
reactions added in total
[BS] Thiamin phosphorylation to TPP: Added 0 reaction(s), 9 reactions added
in total
[BS] Coenzyme A synthesis from pantothenate: Added 0 reaction(s), 9
reactions added in total
[BS] FAD synthesis from riboflavin: Added 0 reaction(s), 9 reactions added
in total
[BS] Heme biosynthesis: Added 0 reaction(s), 9 reactions added in total
task: 57
MAR06725
MAR06768
MAR06782
MAR06783
MAR07580
MAR02359
MAR02472
MAR02599
MAR02672
MAR00754
MAR06672
MAR04065
MAR00019
[GR] Growth on Ham's media (biomass production): Added 13 reaction(s), 22
reactions added in total
>> el1 =
  struct with fields:
                     id: 'Human-GEM'
            description: 'Generic genome-scale metabolic model of Homo
sapiens'
                   rxns: {7718×1 cell}
                   mets: {5380×1 cell}
                      S: [5380×7718 double]
                     lb: [7718×1 double]
                     ub: [7718×1 double]
                    rev: [7718×1 double]
                      c: [7718×1 double]
                      b: [5380×1 double]
                  comps: {9×1 cell}
              compNames: {9×1 cell}
               rxnNames: {7718×1 cell}
                grRules: {7718×1 cell}
             rxnGeneMat: [7718×2415 double]
             subSystems: {7718×1 cell}
                eccodes: {7718×1 cell}
               rxnNotes: {7718×1 cell}
                  genes: {2415×1 cell}
         geneShortNames: {2415×1 cell}
               metNames: {5380×1 cell}
               metComps: [5380×1 double]
                 inchis: {5380×1 cell}
            metFormulas: {5380×1 cell}
          rxnReferences: {7718×1 cell}
                rxnFrom: {7718×1 cell}
                metFrom: {5380×1 cell}
    rxnConfidenceScores: [7718×1 double]
             metCharges: [5380×1 double]
                version: '1.18.0'
             annotation: [1×1 struct]
model1.id = data_struct.tissues{1};
models = cell(numSamp, 1);
for i = 1:numSamp
disp(['Model: ' num2str(i) ' of ' num2str(numSamp)])
models{i} = ftINIT(prepData, data_struct.tissues{i}, [], [], data_struct,
{}, getHumanGEMINITSteps('1+0'), false, true);
end
Model: 1 of 424
ftINIT: Running step 1
[ER] Aerobic rephosphorylation of ATP from glucose: Added 0 reaction(s), 0
reactions added in total
[ER] Aerobic rephosphorylation of GTP: Added 0 reaction(s), 0 reactions added
in total
[ER] Aerobic rephosphorylation of CTP: Added 0 reaction(s), 0 reactions added
in total
[ER] Aerobic rephosphorylation of UTP: Added 0 reaction(s), 0 reactions added
in total
No mets ids with prefix "m_" currently exist in the model. The first new id
will be "m_0001"
task: 5
MAR03025
MAR00977
[BS] ATP de novo synthesis: Added 2 reaction(s), 2 reactions added in total
[BS] CTP de novo synthesis: Added 0 reaction(s), 2 reactions added in total
[BS] GTP de novo synthesis: Added 0 reaction(s), 2 reactions added in total
[BS] UTP de novo synthesis: Added 0 reaction(s), 2 reactions added in total
[BS] dATP de novo synthesis: Added 0 reaction(s), 2 reactions added in total
task: 10
MAR04617
[BS] dCTP de novo synthesis: Added 1 reaction(s), 3 reactions added in total
[BS] dGTP de novo synthesis: Added 0 reaction(s), 3 reactions added in total
[BS] dTTP de novo synthesis: Added 0 reaction(s), 3 reactions added in total
[SU] Histidine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Isoleucine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Leucine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Lysine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Methionine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Phenylalanine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Threonine uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Tryptophan uptake: Added 0 reaction(s), 3 reactions added in total
[SU] Valine uptake: Added 0 reaction(s), 3 reactions added in total
[IC] Glycerate 3-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Mitochondrial acetyl-CoA de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Mitochondrial AKG de novo synthesis: Added 0 reaction(s), 3
reactions added
in total
[IC] Erythrose 4-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Fructose 6-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Glyceraldehyde 3-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Glucose 6-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Mitochondrial oxaloacetate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Phosphoenolpyruvate de novo synthesis: Added 0 reaction(s), 3
reactions added in total
[IC] Pyruvate de novo synthesis: Added 0 reaction(s), 3 reactions added in
total
[IC] Ribose 5-phosphate de novo synthesis: Added 0 reaction(s), 3
reactions added
in total
[IC] Mitochondrial succinyl-CoA de novo synthesis: Added 0 reaction(s), 3
reactions added in total
task: 34
MAR01573
MAR01440
[BS] Cholesterol de novo synthesis: Added 2 reaction(s), 5 reactions added
in total
[BS] Protein synthesis from AAs: Added 0 reaction(s), 5 reactions added in
total
[ER] Oxidative phosphorylation: Added 0 reaction(s), 5 reactions added in
total
[ER] Oxidative decarboxylation: Added 0 reaction(s), 5 reactions added in
total
[ER] Krebs cycle NADH: Added 0 reaction(s), 5 reactions added in total
[ER] Ubiquinol-to-proton: Added 0 reaction(s), 5 reactions added in total
[ER] Ubiquinol-to-ATP: Added 0 reaction(s), 5 reactions added in total
[SU] Beta oxidation of saturated FA: Added 0 reaction(s), 5 reactions added
in total
task: 42
MAR03507
MAR03535
[SU] Beta oxidation of long-chain FA: Added 2 reaction(s), 7 reactions added
in total
[SU] Beta oxidation of odd-chain FA: Added 0 reaction(s), 7 reactions added
in total
[SU] Beta oxidation of unsaturated fatty acid (n-9) : Added 0 reaction(s),
7 reactions added in total
[SU] Beta oxidation of unsaturated fatty acid (n-6) : Added 0 reaction(s),
7 reactions added in total
task: 46
MAR02602
MAR03136
[SU] Uptake and beta oxidation of all NEFAs: Added 2 reaction(s), 9
reactions added in total
[SU] Choline uptake: Added 0 reaction(s), 9 reactions added in total
[SU] Inositol uptake: Added 0 reaction(s), 9 reactions added in total
[BS] Phosphatidylcholine de novo synthesis: Added 0 reaction(s), 9
reactions added in total
[BS] Phosphatidylethanolamine de novo synthesis: Added 0 reaction(s), 9
reactions added in total
[BS] Phosphatidylserine de novo synthesis: Added 0 reaction(s), 9
reactions added
in total
[BS] Phosphatidylinositol de novo synthesis: Added 0 reaction(s), 9
reactions added in total
[BS] Thiamin phosphorylation to TPP: Added 0 reaction(s), 9 reactions added
in total
[BS] Coenzyme A synthesis from pantothenate: Added 0 reaction(s), 9
reactions added in total
[BS] FAD synthesis from riboflavin: Added 0 reaction(s), 9 reactions added
in total
[BS] Heme biosynthesis: Added 0 reaction(s), 9 reactions added in total

**Comment by JHL-452b** [comment]
> I think in the end this was the decimal points after the ensemble IDs so I removed them, however now I have a new issue where > very few reactions are being identified, is this normal? Please see below,

It's great to see that the problem has been solved. For cell-specific models, having around 7,000 reactions is quite common. I've encountered models with a similar number of reactions in my previous work as well. Maybe you can go head with your work.

**Comment by edkerk** [comment]
I also fail to see that "very few reactions are being identified", this seems normal output to me.
