### ISSUE TITLE
GPR curation for Histidine metabolism

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#843]
#### Current behavior:

20 genes are discovered to be uncorrelated with their corresponding reactions in `Histidine metabolism`.

| Gene| UniProtID | Reaction | GPR | Correlation | Manually check |
|---------|-----------|--------|------|---------|--------|
| ENSG00000173418 | [P61599](https://www.uniprot.org/uniprotkb/P61599/entry)    | MAR04426: acetylcarnosine + CoA + H+ <=> acetyl-CoA + carnosine  | ENSG00000102030 or ENSG00000122390 or ENSG00000139977 or ENSG00000156269 or ENSG00000164134 or ENSG00000173418  | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000173418 encodes a catalytic subunit of the NatB complex, which specifically catalyzes the acetylation of N-terminal methionine residues of peptides beginning with Met-Asp, Met-Glu, Met-Asn, and Met-Gln. The reactions provided in the gene's annotation involve acetylation of specific N-terminal residues and the substrate acetyl-CoA, which is converted to CoA and an acetylated N-terminal peptide. However, the reaction provided involves acetylcarnosine converting to acetyl-CoA and carnosine, which does not align with any of the specific reactions catalyzed by the NatB complex. Therefore, the gene and the reaction are not related.| No    |
| ENSG00000139977 | [Q147X3](https://www.uniprot.org/uniprotkb/Q147X3/entry)    | MAR04426: acetylcarnosine + CoA + H+ <=> acetyl-CoA + carnosine | ENSG00000102030 or ENSG00000122390 or ENSG00000139977 or ENSG00000156269 or ENSG00000164134 or ENSG00000173418 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000139977 encodes for a catalytic subunit of the N-terminal acetyltransferase C (NatC) complex, which catalyzes the acetylation of N-terminal methionine residues in specific peptides. The described enzyme activities involve acetylation reactions using acetyl-CoA and target proteins. However, the reaction given in the prompt involves the conversion of acetylcarnosine, CoA, and H+ into acetyl-CoA and carnosine. This reaction is not related to the acetylation of N-terminal methionine residues in proteins, indicating that the gene ENSG00000139977 is not relevant to the provided reaction.| No  |
| ENSG00000156269 | [Q9BSU3](https://www.uniprot.org/uniprotkb/Q9BSU3/entry)    | MAR04426: acetylcarnosine + CoA + H+ <=> acetyl-CoA + carnosine | ENSG00000102030 or ENSG00000122390 or ENSG00000139977 or ENSG00000156269 or ENSG00000164134 or ENSG00000173418 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000156269 encodes a protein that functions as an N-terminal acetyltransferase, specifically catalyzing the transfer of an acetyl group from acetyl-CoA to the N-terminal end of various proteins. The reactions described all involve the formation of N-alpha-acetylated proteins. In contrast, the provided reaction involves the transformation of acetylcarnosine and does not fit the described function of the gene product in the context of N-terminal acetylation.| No    |
| ENSG00000132437 | [P20711](https://www.uniprot.org/uniprotkb/P20711/entry)    | MAR04428: H+ + histidine --> CO2 + histamine | ENSG00000132437 or ENSG00000140287| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000132437 encodes a protein that catalyzes the decarboxylation of L-3,4-dihydroxyphenylalanine (DOPA) to dopamine and L-5-hydroxytryptophan to serotonin. However, the provided reaction involves the conversion of histidine to histamine, which is not among the reactions catalyzed by the protein encoded by this gene. Therefore, the gene and the reaction are not related. | No  |
| ENSG00000138744 | [Q02083](https://www.uniprot.org/uniprotkb/Q02083/entry)    | MAR05336: 2.0 H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione <=> glutamate + glycine + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine  | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The function of the gene ENSG00000138744 is to degrade bioactive fatty acid amides into their corresponding acids. The gene's catalytic activities are focused on various fatty acid ethanolamides and ceramides, whereas the provided reaction involves the hydrolysis of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione to glutamate, glycine, and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine. This reaction does not involve fatty acid amides or ceramides, thus making the gene irrelevant to the reaction provided.| No  |
| ENSG00000078124 | [Q9NUN7](https://www.uniprot.org/uniprotkb/Q9NUN7/entry)    | MAR05336: 2.0 H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione <=> glutamate + glycine + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine  | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000078124 encodes an enzyme that catalyzes the hydrolysis of various ceramides into sphingoid bases and free fatty acids, specifically targeting ceramides, dihydroceramides, and phytoceramides. The catalytic activities described for this gene involve the breakdown of these lipid molecules and do not relate to the given reaction, which involves the hydrolysis of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione into glutamate, glycine, and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine. Therefore, the enzyme produced by the gene does not participate in or influence the specified reaction.  | No |
| ENSG00000172264 | [A1Z1Q3](https://www.uniprot.org/uniprotkb/A1Z1Q3/entry)    | MAR05336: 2.0 H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione <=> glutamate + glycine + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine  | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000172264 is involved in removing ADP-ribose from aspartate and glutamate residues in proteins and deacetylating O-acetyl-ADP ribose. The reactions it catalyzes involve substrates and products like ADP-D-ribose and nicotinamide, whereas the provided reaction involves the conversion of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione to glutamate, glycine, and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine. These substrates and products are different from those associated with the gene¡¯s function, indicating that the gene is not related to the provided reaction. | No |
| ENSG00000068903 | [Q8IXJ6](https://www.uniprot.org/uniprotkb/Q8IXJ6/entry)    | MAR05336: 2.0 H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione <=> glutamate + glycine + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine  | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000068903 encodes a NAD-dependent protein deacetylase that is involved in various biological processes such as cell cycle control, genomic integrity, microtubule dynamics, and autophagy by deacetylating lysines on histones, alpha-tubulin, and other proteins. However, the reaction mentioned involves the conversion of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione to glutamate, glycine, and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine, which does not involve deacetylation activity or the substrates typically associated with the gene's function. Therefore, the gene and the reaction are not related. | No |
| ENSG00000117682 | [Q86SQ9](https://www.uniprot.org/uniprotkb/Q86SQ9/entry)    | MAR05337: GSH + urocanate <=> S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione                                                                     | ENSG00000006695 or ENSG00000054267 or ENSG00000117682 or ENSG00000120942 or ENSG00000183665                                                                                                                                                                            | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000117682 encodes a protein that forms a part of the dehydrodolichyl diphosphate synthase (DDS) complex involved in the biosynthesis of dolichol phosphate, which is crucial for protein glycosylation in the ER. The encoded protein catalyzes the condensation of isopentenyl pyrophosphate with farnesyl pyrophosphate to produce dehydrodolichyl diphosphate. In contrast, the provided reaction involves the conversion of GSH and urocanate to S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione, a process unrelated to the functions described for the protein synthesized by the gene ENSG00000117682. The enzyme activity, substrate specificity, and biological pathway in which the gene's product is involved do not match the specifics of the provided reaction. | No  |
| ENSG00000183665 | [Q53H54](https://www.uniprot.org/uniprotkb/Q53H54/entry)    | MAR05337: GSH + urocanate <=> S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione                                                                     | ENSG00000006695 or ENSG00000054267 or ENSG00000117682 or ENSG00000120942 or ENSG00000183665                                                                                                                                                                            | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000183665 encodes a protein that functions as an S-adenosyl-L-methionine-dependent transferase involved in wybutosine biosynthesis specifically modifying phenylalanine tRNA. Its catalytic activity involves the transfer of an acp group to produce wybutosine, not involving glutathione (GSH) or urocanate. The provided reaction, GSH + urocanate <=> S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]glutathione, does not align with the gene's function or described catalytic activity. | No  |
| ENSG00000012660 | [Q9NYP7](https://www.uniprot.org/uniprotkb/Q9NYP7/entry)    | MAR05338: acetyl-CoA + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine --> CoA + H+ + N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine | ENSG00000012660 or ENSG00000066322 or ENSG00000118402 or ENSG00000119915 or ENSG00000164181 or ENSG00000170522 or ENSG00000197977 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000012660 catalyzes the first and rate-limiting reaction of the long-chain fatty acids elongation cycle, specifically acting on polyunsaturated acyl-CoA and malonyl-CoA to produce very-long-chain 3-oxoacyl-CoA. However, the reaction provided involves acetyl-CoA and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine to produce CoA and N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine, which is outside the scope of the fatty acid elongation processes catalyzed by ENSG00000012660. Therefore, the gene and the reaction are not related. | No |
| ENSG00000170522 | [Q9H5J4](https://www.uniprot.org/uniprotkb/Q9H5J4/entry)    | MAR05338: acetyl-CoA + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine --> CoA + H+ + N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine | ENSG00000012660 or ENSG00000066322 or ENSG00000118402 or ENSG00000119915 or ENSG00000164181 or ENSG00000170522 or ENSG00000197977 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000170522 encodes a protein that catalyzes the elongation of long and very-long-chain fatty acids. The annotated reactions involve the addition of carbons to fatty acid chains using malonyl-CoA and various acyl-CoA substrates. However, the reaction provided involves acetyl-CoA and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine converting to CoA, H+, and N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine. This reaction does not involve fatty acid elongation or the substrates/products associated with the gene's function, indicating no relevance. | No  |
| ENSG00000118402 | [Q9GZR5](https://www.uniprot.org/uniprotkb/Q9GZR5/entry)    | MAR05338: acetyl-CoA + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine --> CoA + H+ + N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine | ENSG00000012660 or ENSG00000066322 or ENSG00000118402 or ENSG00000119915 or ENSG00000164181 or ENSG00000170522 or ENSG00000197977| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000118402 encodes a condensing enzyme that catalyzes the elongation of long- and very long-chain fatty acids through reactions involving very-long-chain acyl-CoA, malonyl-CoA, and producing 3-oxoacyl-CoA, CO2, and CoA. The reactions documented involve various fatty acyl-CoA substrates and do not involve the substrate or product detailed in the provided reaction: acetyl-CoA and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine. The specified reaction produces CoA, H+, and N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine, which are unrelated to the elongation of fatty acids. Therefore, the gene does not relate to the given reaction.   | No  |
| ENSG00000078124 | [Q9NUN7](https://www.uniprot.org/uniprotkb/Q9NUN7/entry)    | MAR05339: H2O + N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine <=> acetate + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine         | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000078124 encodes an enzyme that catalyzes the hydrolysis of unsaturated long-chain ceramides, dihydroceramides, and phytoceramides into sphingoid bases and free fatty acids. The specified reaction involving H2O and N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine to produce acetate and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine does not involve ceramides or related compounds. Therefore, the gene's function is not relevant to the provided reaction. | No   |
| ENSG00000156795 | [Q96HA8](https://www.uniprot.org/uniprotkb/Q96HA8/entry)    | MAR05339: H2O + N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine <=> acetate + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine         | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. Based on the annotation of the gene ENSG00000156795, this gene mediates the side-chain deamidation of N-terminal glutamine residues to glutamate, which is important in the N-end rule pathway of protein degradation. However, the provided reaction involves the conversion of H2O and N-acetyl-S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine to acetate and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine. This reaction does not involve the deamidation of N-terminal glutamine residues, indicating that the gene's function and the reaction are unrelated.| No |
| ENSG00000138744 | [Q02083](https://www.uniprot.org/uniprotkb/Q02083/entry)    | MAR05340: H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine --> NH4+ + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate                  | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000138744 encodes an enzyme that degrades bioactive fatty acid amides to their corresponding acids and exhibits hydrolytic activity against various ceramides. The reactions it catalyzes involve breaking down N-acyl ethanolamines and N-acylsphing-4-enines, resulting in the production of fatty acids and ethanolamine or sphing-4-enine. In contrast, the reaction provided, which involves the conversion of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine to NH4+ and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate, does not involve fatty acid amides or ceramides, indicating that the gene's function does not relate to this reaction.  | No  |
| ENSG00000078124 | [Q9NUN7](https://www.uniprot.org/uniprotkb/Q9NUN7/entry)    | MAR05340: H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine --> NH4+ + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate     | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. Based on the annotation of the gene ENSG00000078124, it encodes an endoplasmic reticulum and Golgi ceramidase involved in the hydrolysis of unsaturated long-chain ceramides into sphingoid bases like sphingosine and free fatty acids at alkaline pH. The various catalytic activities listed involve ceramides and related compounds but do not include the conversion of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine to S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate and NH4+. Hence, the gene's functions and catalytic activities do not match the reaction provided, making it irrelevant. | No |
| ENSG00000133315 | [Q9BQ69](https://www.uniprot.org/uniprotkb/Q9BQ69/entry)    | MAR05340: H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine --> NH4+ + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate                  | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000133315 encodes a protein that primarily functions in removing ADP-ribose from aspartate and glutamate residues in proteins and deacetylating O-acetyl-ADP ribose. It is involved in various cellular processes, including estrogen signaling and androgen receptor activity. The gene's catalytic activities involve reactions with ADP-ribose derivatives. However, the reaction provided describes the conversion of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine to NH4+ and S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate, which does not involve ADP-ribose or related substrates. Therefore, the gene's functions and catalytic activities are not related to the given reaction. | No  |
| ENSG00000172264 | [A1Z1Q3](https://www.uniprot.org/uniprotkb/A1Z1Q3/entry)    | MAR05340: H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine --> NH4+ + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate                  | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000172264 encodes a protein that primarily removes ADP-ribose from aspartate and glutamate residues in proteins and deacetylates O-acetyl-ADP ribose. The reactions described for this gene involve the hydrolysis of ADP-D-ribosyl-protein conjugates to release ADP-D-ribose and the deacetylation of 2''-O-acetyl-ADP-D-ribose to yield ADP-D-ribose and acetate. However, the provided reaction involves the conversion of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine to S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate and NH4+, which is unrelated to the ADP-ribosylation or deacetylation activities associated with the gene ENSG00000172264.| No   |
| ENSG00000142082 | [Q9NTG7](https://www.uniprot.org/uniprotkb/Q9NTG7/entry)    | MAR05340: H2O + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine --> NH4+ + S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate                  | ENSG00000068903 or ENSG00000077463 or ENSG00000078124 or ENSG00000096717 or ENSG00000124523 or ENSG00000124596 or ENSG00000132744 or ENSG00000133315 or ENSG00000138744 or ENSG00000142082 or ENSG00000156795 or ENSG00000157045 or ENSG00000172264 or ENSG00000187531 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000142082 encodes for an NAD-dependent protein deacetylase which is known to deacetylate key lysine residues on mitochondrial target proteins. The catalytic activity associated with this gene involves the deacetylation of N(6)-acetyl-L-lysyl-[protein] using NAD(+). However, the reaction provided describes the conversion of S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-L-cysteine to S-[2-carboxy-1-(1H-imidazol-4-yl)ethyl]-3-thiolactate and does not involve deacetylation or NAD(+) as a substrate. Therefore, the gene ENSG00000142082 is not relevant to the specified reaction. | No  |

**Comment by feiranl** [comment]
LGTM!  Please go ahead and make changes. In summary, a lot of genes related to protein modification and lipid metabolism are mis-annotated to histidine metabolism.

**Comment by JHL-452b** [comment]
Fixed by #884
