### ISSUE TITLE
older Human-GEM version on MetabolicAtlas.org

### ISSUE THREAD

**Issue by DPLemonade** [SysBioChalmers/Human-GEM#845]
#### Current behavior:
Reactions MAR04137 (https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR04137) and MAR06410 (https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06410) are present in the GEM Browser but not present in the Human-GEM.xml file provided here: https://github.com/SysBioChalmers/Human-GEM/blob/main/model/Human-GEM.xml, nor the Human-GEM.xlsx file provided here: https://github.com/SysBioChalmers/Human-GEM/blob/main/model/Human-GEM.xlsx

Why were these reactions not included in the .xml or .xlsx files? Are there other reactions that are also present in the browser but not present in the files?

**Comment by edkerk** [comment]
The Human-GEM on Metabolic Atlas is [version 1.14.0](https://metabolicatlas.org/gems/repository/Human-GEM), while the latest release is [version 1.19.0](https://github.com/SysBioChalmers/Human-GEM/releases). As all the Human-GEM development is tracked here on GitHub, you should always be able to trace back why a change were made.

Regarding the [two reactions](https://github.com/search?q=repo%3ASysBioChalmers%2FHuman-GEM+MAR04137+MAR06410&type=issues) that you mention, these were redundant reactions whose deletion is described [here](https://github.com/SysBioChalmers/Human-GEM/issues/524).

> Are there other reactions that are also present in the browser but not present in the files?

Differences between release 1.14.0 and 1.19.0 are probably best visualized by comparing the [.txt model file](https://github.com/SysBioChalmers/Human-GEM/compare/v1.14.0...v1.19.0#diff-18a4af4c38b05cd0c21329f3ffa7ea1d6d85f981523829732a6b0b7613344399) (normally the .yml would be recommended, but the changes are too significant for GitHub to show them in the browser. A local diff of the two .yml files would be the best solution).

We'll work on getting the Human-GEM version on Metabolic Atlas updated. @mihai-sysbio?

**Comment by DPLemonade** [comment]
Thanks for getting back to me! I now understand the rationale of removing MAR04137 since high-resolution reactions MAR06410, MAR06412, and MAR06409 essentially do the same thing. However, it seems like MAR06410 was also removed here: https://github.com/SysBioChalmers/Human-GEM/pull/541/commits/60e7db539dc299980c0fa624cf49e3b2ee6f74df.

Could you point me to the exact reactions in the most up-to-date version that represent PDH? It seems like MAR06412 and MAR06409 combined are not enough.

**Comment by JHL-452b** [comment]
low-resolution reaction
| Reaction | eq | LB | UB   |
|----------|-------|--------|---------|
| MAR04137 | CoA[m] + NAD+[m] + pyruvate[m] --> CO2[m] + NADH[m] + acetyl-CoA[m] | 0  | 1000 |


high-resolution reactions
| Reaction | eq | LB    | UB   |
|------|--------|-------|------|
| MAR08746 | H+[m] + pyruvate[m] + thiamin-PP[m] --> 2-(alpha-hydroxyethyl)thiamine-diphosphate[m] + CO2[m]  | 0  | 1000 |
| MAR20069 | 2-(alpha-hydroxyethyl)thiamine-diphosphate[m] + lipoamide[m] --> S-acetyldihydrolipoamide[m] + thiamin-PP[m] | 0  | 1000 |
| MAR06412 | CoA[m] + S-acetyldihydrolipoamide[m] --> acetyl-CoA[m] + dihydrolipoamide[m]  | 0 | 1000 |
| MAR06409 | H+[m] + lipoamide[m] + NADH[m] <=> dihydrolipoamide[m] + NAD+[m] | -1000 | 1000 |

`MAR06410` was be replaced by  `MAR20069` (added in this #541 ) and `MAR08746`. So, the high-resolution of `MAR04137` should be `MAR08746`, `MAR20069`, `MAR06412` and `MAR06409` in latest version. I hope these are useful to you.

**Comment by feiranl** [comment]
We will close this issue since it seems solved. But we need to update the version of HMA website @mihai-sysbio @edkerk

**Comment by mihai-sysbio** [comment]
An idea for next time could be to transfer such issues to the main Metabolic Atlas repository.
