### ISSUE TITLE
GPR curation for Nucleotide metabolism

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#846]
#### Current behavior:

35 genes are discovered to be uncorrelated with their corresponding reactions in `Nucleotide metabolism`.

| Gene  | UniProtID | Reaction  | GPR| Correlation | Manually check |
|------|-----------|-------------|----------|----------|----------------|
| ENSG00000125877 | [Q9BY32](https://www.uniprot.org/uniprotkb/Q9BY32/entry)    | MAR03966: ATP + H2O --> AMP + H+ + PPi                             | ENSG00000125877| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000125877 encodes an enzyme that functions as a pyrophosphatase, hydrolyzing non-canonical purine nucleotides like ITP, dITP, dHAPTP, and XTP to their respective monophosphate derivatives. This activity involves the conversion of ribonucleoside and deoxyribonucleoside triphosphates into their monophosphate forms. However, the provided reaction describes the hydrolysis of ATP to AMP, a different reaction not directly related to the gene's annotated function. | No |
| ENSG00000168393 | [P23919](https://www.uniprot.org/uniprotkb/P23919/entry)    | MAR03968: ADP + dUDP <=> ATP + dUMP  | ENSG00000168393| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000168393 encodes an enzyme that catalyzes the phosphorylation of thymidine monophosphate (dTMP) to thymidine diphosphate (dTDP) using ATP as the phosphoryl donor. This is described by the reaction: ATP + dTMP = ADP + dTDP. However, the reaction provided is ADP + dUDP <=> ATP + dUMP, which involves different substrates and products, indicating that the gene's function does not match the provided reaction. | No |
| ENSG00000196839 | [P00813](https://www.uniprot.org/uniprotkb/P00813/entry)    | MAR04633: ATP + deoxyadenosine --> ADP + dAMP + H+ | ENSG00000196839| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000196839 encodes a protein that catalyzes the hydrolytic deamination of adenosine and 2-deoxyadenosine, converting them to inosine and 2'-deoxyinosine, respectively, with the release of NH4+. However, the provided reaction involves the conversion of ATP and deoxyadenosine to ADP, dAMP, and H+, a phosphorylation reaction, indicating that the catalyzed reaction is fundamentally different in both mechanism and substrate specificity from the gene's encoded enzyme activities.| No |
| ENSG00000168393 | [P23919](https://www.uniprot.org/uniprotkb/P23919/entry)    | MAR04640: ATP + dUMP --> ADP + dUDP                                | ENSG00000168393| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. According to the gene annotation, the gene ENSG00000168393 encodes for an enzyme that catalyzes the phosphorylation of thymidine monophosphate (dTMP) to thymidine diphosphate (dTDP), with ATP as the preferred phosphoryl donor in the presence of Mg(2+). However, the reaction provided involves the phosphorylation of deoxyuridine monophosphate (dUMP) to deoxyuridine diphosphate (dUDP). Therefore, the specific substrate and product of the reaction do not match the catalytic activity associated with the gene ENSG00000168393. | No |
| ENSG00000125458 | [Q8TCD5](https://www.uniprot.org/uniprotkb/Q8TCD5/entry)    | MAR07713: AMP + H2O --> adenosine + Pi                             | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000125458 encodes a protein that dephosphorylates deoxyribonucleotides, specifically targeting dUMP and dTMP, with intermediate activity towards dGMP, and low activity towards dCMP and dAMP. However, the reaction provided involves the hydrolysis of AMP to adenosine and Pi, which is not one of the substrates that the gene's protein product acts upon according to the given function and annotations. | No|
| ENSG00000205309 | [Q9NPB1](https://www.uniprot.org/uniprotkb/Q9NPB1/entry)    | MAR07713: AMP + H2O --> adenosine + Pi                             | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000205309 codes for an enzyme that dephosphorylates the 5' and 2'(3')-phosphates of uracil and thymine deoxyribonucleotides, which is not related to the reaction AMP + H2O --> adenosine + Pi. The enzyme specifically targets uracil and thymine deoxyribonucleotides and has only marginal activity towards dIMP and dGMP, indicating it does not act on AMP.| No  |
| ENSG00000122643 | [Q9H0P0](https://www.uniprot.org/uniprotkb/Q9H0P0/entry)    | MAR07713: AMP + H2O --> adenosine + Pi                             | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000122643 encodes a nucleotidase that specifically acts on cytidine monophosphate (CMP) and 7-methylguanosine monophosphate (m(7)GMP). The catalytic activities described for this gene involve hydrolysis reactions resulting in cytidine and phosphate or N(7)-methylguanosine and phosphate. There is no mention of activity related to AMP hydrolysis. The given reaction, AMP + H2O --> adenosine + Pi, does not match the annotated catalytic activities of the gene, which indicates specificity towards other nucleotides, not AMP.| No|
| ENSG00000125458 | [Q8TCD5](https://www.uniprot.org/uniprotkb/Q8TCD5/entry)    | MAR07716: H2O + UMP --> Pi + uridine                               | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: Based on the function of the gene ENSG00000125458, it dephosphorylates the 5' and 2'(3')-phosphates of deoxyribonucleotides, specifically preferring dUMP and dTMP. However, the reaction involves the hydrolysis of UMP to produce Pi and uridine, which is not related to the dephosphorylation activity described. Therefore, the function of the gene does not correspond to the reaction mentioned. | No  |
| ENSG00000125458 | [Q8TCD5](https://www.uniprot.org/uniprotkb/Q8TCD5/entry)    | MAR07721: CMP + H2O --> cytidine + Pi                              | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000125458 encodes an enzyme that dephosphorylates 5' and 2'(3')-phosphates of deoxyribonucleotides, with a preference for dUMP and dTMP, and varying activity towards other deoxyribonucleotides. The reaction described (CMP + H2O --> cytidine + Pi) involves the dephosphorylation of CMP, which is a ribonucleotide, not a deoxyribonucleotide. Therefore, the enzyme encoded by this gene does not catalyze the specific reaction given, making the gene irrelevant to the reaction. | No |
| ENSG00000205309 | [Q9NPB1](https://www.uniprot.org/uniprotkb/Q9NPB1/entry)    | MAR07721: CMP + H2O --> cytidine + Pi                              | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000205309 encodes a protein that specifically dephosphorylates the 5' and 2'(3')-phosphates of uracil and thymine deoxyribonucleotides, thus protecting mitochondrial DNA replication from excess dTTP. It has marginal activity towards dIMP and dGMP. The reaction provided involves the hydrolysis of CMP to cytidine and inorganic phosphate (Pi), which is not related to the described function of the gene, as the gene's product does not act on CMP.| No |
| ENSG00000122643 | [Q9H0P0](https://www.uniprot.org/uniprotkb/Q9H0P0/entry)    | MAR07725: dTMP + H2O --> Pi + thymidine                            | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000122643 encodes a nucleotidase with specific activity towards cytidine monophosphate (CMP) and 7-methylguanosine monophosphate (m(7)GMP), as well as general activity towards ribonucleoside 5'-phosphates. The provided reaction, which involves the hydrolysis of dTMP to thymidine and phosphate, does not match any of the specific or general catalytic activities listed for this gene. Therefore, the gene and the reaction are not related. | No |
| ENSG00000076685 | [P49902](https://www.uniprot.org/uniprotkb/P49902/entry)    | MAR07725: dTMP + H2O --> Pi + thymidine                            | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000076685 encodes a cytosolic 5'-nucleotidase with broad specificity that primarily catalyzes the dephosphorylation of 6-hydroxypurine nucleoside 5'-monophosphates, such as IMP and GMP, and not dTMP. The provided reaction involves the hydrolysis of dTMP to produce phosphate and thymidine, which is not among the substrates the gene product is known to act on according to the information available. | No |
| ENSG00000141698 | [Q969T7](https://www.uniprot.org/uniprotkb/Q969T7/entry)    | MAR07725: dTMP + H2O --> Pi + thymidine                            | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000141698 encodes an enzyme that specifically hydrolyzes 7-methylguanosine monophosphate (m(7)GMP) to 7-methylguanosine and inorganic phosphate, as well as has weak activity for CMP. It shows poor activity for UMP and purine nucleotides. The catalytic activities described involve reactions with m(7)GMP, CMP, and a ribonucleoside 5'-phosphate. However, the provided reaction (dTMP + H2O --> Pi + thymidine) involves the hydrolysis of dTMP to thymidine and phosphate, which is not one of the activities described for the enzyme encoded by ENSG00000141698. Therefore, the gene does not relate to the provided reaction. | No |
| ENSG00000205309 | [Q9NPB1](https://www.uniprot.org/uniprotkb/Q9NPB1/entry)    | MAR07728: GMP + H2O --> guanosine + Pi                             | ENSG00000076685 or ENSG00000116981 or ENSG00000122643 or ENSG00000125458 or ENSG00000135318 or ENSG00000141698 or ENSG00000185013 or ENSG00000205309| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000205309 encodes a protein that specifically dephosphorylates the 5' and 2'(3')-phosphates of uracil and thymine deoxyribonucleotides, and has marginal activity towards dIMP and dGMP, according to the provided annotation. However, the reaction mentioned (GMP + H2O --> guanosine + Pi) involves the dephosphorylation of GMP to guanosine and is unrelated to the specific activity of the gene's encoded protein, which does not primarily target GMP. | No |
| ENSG00000143156 | [Q9Y5B8](https://www.uniprot.org/uniprotkb/Q9Y5B8/entry) | MAR07883: ADP + UTP <=> ATP + UDP  | ENSG00000103024 or ENSG00000103202 or ENSG00000143156 or ENSG00000155085 or ENSG00000172113 or ENSG00000239672 or ENSG00000243678| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. According to the annotation, the gene ENSG00000143156 has intrinsic kinase activity and 3'-5' exonuclease activity with a preference for single-stranded DNA, as well as a role in microtubule and centrosome function. The reaction provided involves the interconversion of ADP and UTP to ATP and UDP, which implies a nucleoside diphosphate kinase activity. However, the gene explicitly does not have nucleoside diphosphate kinase activity, confirming its irrelevance to the reaction.| No|
| ENSG00000143156 | [Q9Y5B8](https://www.uniprot.org/uniprotkb/Q9Y5B8/entry)    | MAR07890: ADP + dCTP <=> ATP + dCDP                                | ENSG00000103024 or ENSG00000103202 or ENSG00000143156 or ENSG00000155085 or ENSG00000172113 or ENSG00000239672 or ENSG00000243678| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000143156 encodes a protein with intrinsic kinase activity, 3'-5' exonuclease activity, and is involved in microtubule functions, specifically in cilia axoneme and centrosome regulation. However, it does not have nucleoside diphosphate kinase activity, which would be necessary for the reaction ADP + dCTP <=> ATP + dCDP, indicating that the gene's functions do not align with the reaction specified.| No |
| ENSG00000143156 | [Q9Y5B8](https://www.uniprot.org/uniprotkb/Q9Y5B8/entry)    | MAR07895: ADP + ITP <=> ATP + IDP                                  | ENSG00000103024 or ENSG00000103202 or ENSG00000143156 or ENSG00000155085 or ENSG00000172113 or ENSG00000239672 or ENSG00000243678| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000143156 possesses intrinsic kinase activity, 3'-5' exonuclease activity, and functions in microtubule nucleation and motile cilia beating, but it does not exhibit nucleoside diphosphate kinase activity. Since the reaction described (ADP + ITP <=> ATP + IDP) involves nucleotide diphosphate kinase activity, the gene's functions do not correlate with the reaction.| No  |
| ENSG00000073417 | [O60658](https://www.uniprot.org/uniprotkb/O60658/entry)  | MAR08083: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000073417 encodes a protein that hydrolyzes cAMP to AMP, but the provided reaction involves the hydrolysis of cGMP to GMP. The specific catalytic activity of the gene product does not include the hydrolysis of cGMP; hence, the gene is not related to the reaction. | No|
| ENSG00000065989 | [P27815](https://www.uniprot.org/uniprotkb/P27815/entry)    | MAR08083: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000065989 encodes a protein that hydrolyzes 3',5'-cyclic AMP (cAMP) to AMP, but the provided reaction involves the hydrolysis of cGMP to GMP. According to the annotations, none of the isoforms hydrolyze cGMP, indicating that the gene does not participate in this specific reaction of converting cGMP to GMP. | No |
| ENSG00000205268 | Q13946    | MAR08083: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000205268 encodes a protein that hydrolyzes cAMP to AMP, which is described in its function and catalytic activity. The gene is involved in the hydrolysis of the second messenger cAMP, not cGMP. The reaction provided, "cGMP + H2O --> GMP + H+," involves the hydrolysis of cGMP, which does not align with the gene's annotated function related to cAMP. Therefore, the gene and the reaction are not related. | No  |
| ENSG00000113231 | [O95263](https://www.uniprot.org/uniprotkb/O95263/entry) | MAR08083: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000113231 encodes for a protein that hydrolyzes cAMP (3',5'-cyclic AMP) to AMP, which is not the same as the provided reaction that involves the hydrolysis of cGMP (cyclic GMP) to GMP. The specific signaling pathways and catalytic activities differ, as highlighted by the gene's function and the reaction annotation. Thus, the gene and the reaction are not related.| No |
| ENSG00000065989 | [P27815](https://www.uniprot.org/uniprotkb/P27815/entry)    | MAR08085: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000065989 encodes a protein that specifically hydrolyzes 3',5'-cyclic AMP (cAMP) into AMP. Although multiple isoforms of this gene product are mentioned, they all share the common function of hydrolyzing cAMP and not cyclic GMP (cGMP). The provided reaction involves the conversion of cGMP to GMP, which is not within the functional role of this gene product as it does not hydrolyze cGMP.| No |
| ENSG00000205268 | [Q13946](https://www.uniprot.org/uniprotkb/Q13946/entry)    | MAR08085: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000205268 encodes a protein that hydrolyzes cAMP (cyclic AMP) into AMP, as described in its function and catalytic activity. However, the reaction provided is cGMP + H2O --> GMP + H+, which involves the hydrolysis of cGMP (cyclic GMP) rather than cAMP. This indicates that the gene's product is specific to cAMP hydrolysis, and thus is not relevant to the cGMP hydrolysis reaction provided. | No |
| ENSG00000184588 | [Q07343](https://www.uniprot.org/uniprotkb/Q07343/entry)    | MAR08085: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The function and catalytic activity of gene ENSG00000184588 focus on hydrolyzing cAMP (cyclic adenosine monophosphate) to AMP (adenosine monophosphate), which does not relate to the reaction provided that involves cGMP (cyclic guanosine monophosphate) being hydrolyzed to GMP (guanosine monophosphate). Therefore, the gene associated with cAMP does not have a role in the cGMP hydrolysis reaction. | No|
| ENSG00000113231 | [O95263](https://www.uniprot.org/uniprotkb/O95263/entry)    | MAR08085: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000113231 encodes a protein that hydrolyzes cAMP into AMP, implicating its role in cAMP-specific signaling pathways, particularly in the thyroid gland. However, the reaction provided involves the hydrolysis of cGMP into GMP, a different cyclic nucleotide. Therefore, the gene's function does not match the provided reaction, leading to the conclusion that they are unrelated.| No|
| ENSG00000171408 | [Q9NP56](https://www.uniprot.org/uniprotkb/Q9NP56/entry)    | MAR08085: cGMP + H2O --> GMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000171408 encodes a protein that hydrolyzes cAMP (cyclic AMP) into AMP (adenosine monophosphate), whereas the reaction provided involves the hydrolysis of cGMP (cyclic GMP) into GMP (guanosine monophosphate). The gene product is specifically annotated to function in cAMP metabolism, not cGMP metabolism, making it unrelated to the provided reaction. | No|
| ENSG00000095464 | [P51160](https://www.uniprot.org/uniprotkb/P51160/entry)    | MAR08087: cAMP + H2O --> AMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000095464 encodes a cone-specific cGMP phosphodiesterase, which is involved in decreasing intracellular levels of cGMP during cone phototransduction. The provided reaction, however, involves the hydrolysis of cAMP to AMP, which is not related to the function of the gene. The gene's catalytic activity is specific to cGMP, not cAMP.| No |
| ENSG00000132915 | [P16499](https://www.uniprot.org/uniprotkb/P16499/entry)    | MAR08087: cAMP + H2O --> AMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000132915 encodes for a rod-specific cGMP phosphodiesterase which catalyzes the hydrolysis of 3',5'-cyclic GMP to GMP, participating in the visual signal transmission. However, the reaction provided describes the hydrolysis of cAMP to AMP, which is a different substrate and reaction not linked to the function of the gene specified.| No|
| ENSG00000160191 | [O76083](https://www.uniprot.org/uniprotkb/O76083/entry)    | MAR08087: cAMP + H2O --> AMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000160191 encodes a protein that specifically hydrolyzes cGMP, as detailed in its function and catalytic activity. The reaction provided, however, involves the hydrolysis of cAMP to AMP, which is not related to the cGMP-specific activity of the protein encoded by ENSG00000160191. Therefore, the specific function of the gene does not align with the reaction involving cAMP hydrolysis.| No |
| ENSG00000133256 | [P35913](https://www.uniprot.org/uniprotkb/P35913/entry)    | MAR08087: cAMP + H2O --> AMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000133256 encodes for a rod-specific cGMP phosphodiesterase that catalyzes the hydrolysis of 3',5'-cyclic GMP to GMP, as indicated by the provided catalytic activity details. However, the reaction provided (cAMP + H2O --> AMP + H+) involves the hydrolysis of cAMP to AMP, not cGMP. Hence, the gene is not relevant to the given reaction.| No|
| ENSG00000138735 | [O76074](https://www.uniprot.org/uniprotkb/O76074/entry)    | MAR08087: cAMP + H2O --> AMP + H+                                  | ENSG00000065989 or ENSG00000073417 or ENSG00000095464 or ENSG00000105650 or ENSG00000112541 or ENSG00000113231 or ENSG00000113448 or ENSG00000115252 or ENSG00000123360 or ENSG00000128655 or ENSG00000132915 or ENSG00000133256 or ENSG00000138735 or ENSG00000139053 or ENSG00000152270 or ENSG00000154678 or ENSG00000160191 or ENSG00000171408 or ENSG00000172572 or ENSG00000184588 or ENSG00000185527 or ENSG00000186642 or ENSG00000205268 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000138735 encodes a phosphodiesterase that specifically catalyzes the hydrolysis of cGMP to 5'-GMP. However, the provided reaction describes the conversion of cAMP to AMP, which is not catalyzed by this gene according to the given functional annotation.| No  |
| ENSG00000170502 | [Q9BW91](https://www.uniprot.org/uniprotkb/Q9BW91/entry)    | MAR08443: ADP-glucose + H2O --> AMP + glucose-1-phosphate + 2.0 H+ | ENSG00000165609 or ENSG00000170222 or ENSG00000170502| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000170502 encodes for a protein that hydrolyzes ADP-ribose (ADPR) to AMP and ribose 5'-phosphate. However, the reaction provided involves the hydrolysis of ADP-glucose to AMP and glucose-1-phosphate, which is fundamentally different from the gene's annotated function and catalytic activity. Therefore, the gene and the reaction do not share relevance. | No |
| ENSG00000170502 | [Q9BW91](https://www.uniprot.org/uniprotkb/Q9BW91/entry)    | MAR08444: ADP-mannose + H2O --> AMP + 2.0 H+ + mannose-1-phosphate | ENSG00000165609 or ENSG00000170222 or ENSG00000170502| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000170502 hydrolyzes ADP-ribose to AMP and ribose 5'-phosphate, while the reaction involves the hydrolysis of ADP-mannose to AMP and mannose-1-phosphate. The substrate specificity differs: ADP-ribose versus ADP-mannose, indicating the gene's function does not align with the given reaction.| No |
| ENSG00000162368 | [P30085](https://www.uniprot.org/uniprotkb/P30085/entry)    | MAR08450: dCDP + dGDP <=> dCMP + dGTP                              | ENSG00000162368| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The reactions catalyzed by the gene ENSG00000162368 involve the phosphorylation of nucleoside monophosphates and diphosphates primarily using ATP. However, the provided reaction (dCDP + dGDP <=> dCMP + dGTP) does not align with the gene's annotated catalytic activities, which include converting nucleoside monophosphates to diphosphates and diphosphates to triphosphates. Therefore, the gene does not catalyze the reaction dCDP + dGDP <=> dCMP + dGTP.| No |
| ENSG00000171302 | [Q8WVQ1](https://www.uniprot.org/uniprotkb/Q8WVQ1/entry)  | MAR08474: ATP + 2.0 H2O --> AMP + 2.0 H+ + 2.0 Pi  | ENSG00000054179 or ENSG00000138185 or ENSG00000168032 or ENSG00000171302 or ENSG00000187097 or ENSG00000188833 or ENSG00000197217 or ENSG00000197586 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000171302 encodes a calcium-dependent nucleotidase with a preference for UDP, GDP, UTP, and GTP, and shows very low activity towards ADP and even lower towards ATP. It does not hydrolyze AMP and GMP. The provided reaction involves the hydrolysis of ATP to AMP, which is not within the primary activity spectrum of this gene's encoded protein, thus making the gene irrelevant to the reaction. | No |

**Comment by feiranl** [comment]
LGTM! Please go ahead to make changes. In summary, we distinguished better substrates for those isoenzymes with similar functions.

**Comment by JHL-452b** [comment]
Fixed by #884
