### ISSUE TITLE
GPR curation for Glycerolipid metabolism/Glycerophospholipid metabolism/Fatty acid oxidation

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#848]
#### Current behavior:

15 genes are discovered to be uncorrelated with their corresponding reactions in `Glycerolipid metabolism`/`Glycerophospholipid metabolism`/`Fatty acid oxidation`.

| Gene | UniProtID | Reaction  | GPR | Correlation | Manually check |
|-------|--------|------|--------------|------------------|----------------|
| ENSG00000196344 | [P40394](https://www.uniprot.org/uniprotkb/P40394/entry)    | MAR00453: glyceraldehyde + H+ + NADPH <=> glycerol + NADP+| ENSG00000085662 or ENSG00000117448 or ENSG00000172955 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198074 or ENSG00000198099 or ENSG00000248144 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000196344 encodes an enzyme that primarily catalyzes the NAD-dependent oxidation of various alcohols, including retinol, omega-hydroxy fatty acids, and their derivatives, and in some cases, it catalyzes NADH-dependent reductions. The reaction provided involves the interconversion of glyceraldehyde and glycerol using NADPH/NADP+ as cofactors, which is not among the reactions or catalytic activities attributed to the enzyme associated with the gene ENSG00000196344. Therefore, the gene does not play a role in the reaction involving glyceraldehyde and glycerol.| No |
| ENSG00000196616 | [P00325](https://www.uniprot.org/uniprotkb/P00325/entry)    | MAR00458: glycerol + NADP+ --> glyceraldehyde + H+ + NADPH | ENSG00000085662 or ENSG00000117448 or ENSG00000172955 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198074 or ENSG00000198099 or ENSG00000248144 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000196616 encodes a protein that catalyzes the NAD-dependent oxidation of all-trans-retinol and its derivatives, participating in retinoid metabolism. It specifically catalyzes reactions involving all-trans-retinol, all-trans-4-hydroxyretinol, and all-trans-4-oxoretinol. However, the provided reaction involves glycerol and NADP+, producing glyceraldehyde, H+, and NADPH, which is not related to the substrates or products involved in the reactions catalyzed by the gene's product. Therefore, the gene and the reaction are not related.| No |
| ENSG00000196344 | [P40394](https://www.uniprot.org/uniprotkb/P40394/entry)    | MAR00458: glycerol + NADP+ --> glyceraldehyde + H+ + NADPH | ENSG00000085662 or ENSG00000117448 or ENSG00000172955 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198074 or ENSG00000198099 or ENSG00000248144 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000196344 encodes an enzyme that primarily catalyzes the NAD-dependent oxidation of all-trans-retinol, alcohols, and omega-hydroxy fatty acids, as well as the reduction of all-trans-retinal and various aldehydes. This enzyme¡¯s activities involve substrates like trans-retinol, hexanal, and omega-hydroxy fatty acids, using NAD+/NADH as cofactors. Conversely, the reaction provided involves the conversion of glycerol to glyceraldehyde using NADP+/NADPH, which is not a substrate or cofactor associated with the enzymatic functions described for this gene. Therefore, based on the provided annotation, the gene does not relate to the specified reaction.| No|
| ENSG00000169169 | [Q8TCG5](https://www.uniprot.org/uniprotkb/Q8TCG5/entry)    | MAR01488: L-carnitine + linolenoyl-CoA <=> CoA + Alpha-Linolenyl Carnitine| ENSG00000110090 or ENSG00000169169 or ENSG00000205560| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000169169 encodes for a palmitoyl thioesterase involved in depalmitoylation and modulation of AMPAR trafficking, binding malonyl-CoA and palmitoyl-CoA, and regulating ceramide levels and energy homeostasis. The annotated catalytic activities involve palmitoyl-CoA and not linolenoyl-CoA or Alpha-Linolenyl Carnitine, which are the substrates in the provided reaction. Therefore, the gene's function does not match the described reaction. | No |
| ENSG00000161533 | [Q15067](https://www.uniprot.org/uniprotkb/Q15067/entry)    | MAR02818: 4-cis-decenoyl-CoA + FAD --> 2-trans-4-cis-decadienoyl-CoA + FADH2 | ENSG00000087008 or ENSG00000161533 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000161533 is involved in the beta-oxidation of very-long-chain fatty acids and catalyzes the desaturation of fatty acyl-CoAs to enoyl-CoAs while producing hydrogen peroxide. However, the provided reaction involves the conversion of 4-cis-decenoyl-CoA with FAD to 2-trans-4-cis-decadienoyl-CoA and FADH2, which does not match the gene's known activities of desaturation and beta-oxidation involving O2 and H2O2, indicating no direct relevance. | ~~No~~ Yes |
| ENSG00000161533 | [Q15067](https://www.uniprot.org/uniprotkb/Q15067/entry)  | MAR03291: FADH2 + Trans,Cis-Dodeca-2,5-Dienoyl Coenzyme A <=> (5Z)-dodecenoyl-CoA + FAD | ENSG00000115361 or ENSG00000117054 or ENSG00000161533 or ENSG00000196177| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000161533 is involved in the initial and rate-limiting step of peroxisomal beta-oxidation of straight-chain saturated and unsaturated very-long-chain fatty acids, catalyzing the desaturation of fatty acyl-CoAs to 2-trans-enoyl-CoAs and producing hydrogen peroxide. The provided reaction involves FADH2 and Trans,Cis-Dodeca-2,5-Dienoyl Coenzyme A, leading to (5Z)-dodecenoyl-CoA and FAD, which is not within the scope of the gene's functions and catalytic activities described. | No |
| ENSG00000177465 | [Q8N9L9](https://www.uniprot.org/uniprotkb/Q8N9L9/entry)    | MAR03387: ATP + CoA + (2S)-pristanic acid --> (2S)-pristanoyl-CoA + AMP + PPi| ENSG00000068366 or ENSG00000103740 or ENSG00000119673 or ENSG00000123983 or ENSG00000130377 or ENSG00000140284 or ENSG00000151726 or ENSG00000164398 or ENSG00000177465 or ENSG00000197142 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000177465 encodes a protein that catalyzes the hydrolysis of various acyl-CoAs into free fatty acids and CoA. The specific reactions listed, including the hydrolysis of succinyl-CoA, glutaryl-CoA, long chain saturated acyl-CoAs, and others, involve breaking down these molecules using water (hydrolysis). However, the provided reaction (ATP + CoA + (2S)-pristanic acid --> (2S)-pristanoyl-CoA + AMP + PPi) describes the synthesis of (2S)-pristanoyl-CoA from pristanic acid, CoA, and ATP, which is a different type of biochemical reaction (a ligase reaction) that does not align with the hydrolytic function of the gene mentioned. Thus, the gene is not relevant to the provided reaction. | No, only keeps ENSG00000140284 as other genes get wrong compartment location. |
| ENSG00000169169 | [Q8TCG5](https://www.uniprot.org/uniprotkb/Q8TCG5/entry)    | MAR04457: decanoyl-CoA + L-carnitine <=> CoA + Decanoyl Carnitine| ENSG00000110090 or ENSG00000169169 or ENSG00000205560 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. Based on the function and catalytic activity annotations of the gene ENSG00000169169, it encodes a protein involved in the depalmitoylation of GRIA1 and regulation of AMPR trafficking in neurons. It modulates phosphatidylinositol-3-phosphatase activity and binds to palmitoyl-CoA and malonyl-CoA, but does not significantly exhibit carnitine palmitoyltransferase 1 catalytic activity. The described reaction involves decanoyl-CoA and L-carnitine, which is not associated with the annotated activities or substrates of the ENSG00000169169 gene product. Therefore, the gene and the reaction are not related. | No |
| ENSG00000169169 | [Q8TCG5](https://www.uniprot.org/uniprotkb/Q8TCG5/entry)    | MAR04711: L-carnitine + tiglyl-CoA <=> CoA + Tiglyl Carnitine | ENSG00000110090 or ENSG00000169169 or ENSG00000205560 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000169169 encodes for a palmitoyl thioesterase specifically expressed in the endoplasmic reticulum of neurons, which is involved in depalmitoylation processes and regulation of AMPAR trafficking, but the reaction provided involves the conversion between L-carnitine and tiglyl-CoA, which is unrelated to the gene's annotated functions and catalytic activity.| No |
| ENSG00000135929 | [Q02318](https://www.uniprot.org/uniprotkb/Q02318/entry)    | MAR04838: N-methylethanolamine-phosphate + SAM --> 2.0 H+ + phosphodimethylethanolamine + SAH | ENSG00000135929| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000135929 encodes a cytochrome P450 monooxygenase involved in the hydroxylation of cholesterol and its derivatives, as well as other sterols and vitamin D3. It catalyzes multiple reactions related to cholesterol metabolism and hydroxylation processes, none of which involve the conversion of N-methylethanolamine-phosphate to phosphodimethylethanolamine using SAM (S-adenosylmethionine) as a methyl donor. Therefore, the gene's function does not align with the reaction provided. | No |
| ENSG00000135929 | [Q02318](https://www.uniprot.org/uniprotkb/Q02318/entry)    | MAR04839: phosphodimethylethanolamine + SAM --> phosphocholine + SAH  | ENSG00000135929 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000135929 encodes a cytochrome P450 monooxygenase that primarily catalyzes hydroxylation reactions involving cholesterol and its derivatives, cholestanol, retinal 7-ketocholesterol, and vitamin D3. The listed catalytic activities focus on hydroxylating various sterol and cholesterol molecules, contributing to cholesterol homeostasis and bile acid synthesis. In contrast, the provided reaction involves the conversion of phosphodimethylethanolamine and SAM into phosphocholine and SAH, which is a methylation reaction unrelated to the functions and activities described for the cytochrome P450 monooxygenase. Thus, the gene and the reaction are not related. | No |
| ENSG00000169169 | [Q8TCG5](https://www.uniprot.org/uniprotkb/Q8TCG5/entry)    | MAR06278: L-carnitine + 3-Hydroxyisovaleryl Coenzyme A <=> CoA + 3-Hydroxy-Isovaleryl Carnitine | ENSG00000110090 or ENSG00000169169 or ENSG00000205560| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000169169 encodes a palmitoyl thioesterase that is specifically expressed in the endoplasmic reticulum of neurons and is involved in depalmitoylation processes affecting AMPAR trafficking and spine maturation. The mentioned catalytic activity involves hydrolyzing S-hexadecanoyl-L-cysteinyl-[protein] to produce hexadecanoate and L-cysteinyl-[protein]. However, the provided reaction involves L-carnitine and 3-Hydroxyisovaleryl Coenzyme A, which does not match the gene's described function and catalytic specificity. Therefore, the gene is not relevant to the reaction provided. | No |
| ENSG00000161533 | [Q15067](https://www.uniprot.org/uniprotkb/Q15067/entry)    | MAR06285: CoA + FAD + H2O + NAD+ + Adipoyl Coenzyme A --> acetyl-CoA + FADH2 + H+ + NADH + succinyl-CoA | ENSG00000060971 and ENSG00000113790 and ENSG00000133835 and ENSG00000161533| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000161533 is involved in the peroxisomal beta-oxidation of very-long-chain fatty acids, catalyzing the formation of 2-trans-enoyl-CoAs and the production of hydrogen peroxide. In contrast, the reaction described involves CoA, FAD, NAD+, adipoyl-Coenzyme A, resulting in acetyl-CoA, FADH2, H+, NADH, and succinyl-CoA, which are related to a distinct metabolic pathway. Therefore, their functions and involved substrates/products do not overlap, indicating a lack of relevance between the gene and the reaction. | ~~No~~ Yes |
| ENSG00000176454 | [Q643R3](https://www.uniprot.org/uniprotkb/Q643R3/entry)    | MAR08521: 1-alkyl-2-lysoglycerol-3-phosphocholine + acetyl-CoA --> 2-acetyl-1-alkyl-sn-glycero-3-phosphocholine + CoA | ENSG00000087253 or ENSG00000153395 or ENSG00000176454 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000176454 encodes an enzyme that catalyzes a variety of acyl-CoA-dependent lysophospholipid acyltransferase activities, including the conversion of lysophosphatidylethanolamine, lysophosphatidylcholine, and lysophosphatidylglycerol to their respective phospholipids. However, the provided reaction involves the conversion of 1-alkyl-2-lysoglycerol-3-phosphocholine to 2-acetyl-1-alkyl-sn-glycero-3-phosphocholine, which is not mentioned among the catalytic activities of the enzyme associated with the gene ENSG00000176454. Therefore, the gene is not relevant to this reaction. | ~~No~~ Yes |
| ENSG00000161533 | [Q15067](https://www.uniprot.org/uniprotkb/Q15067/entry)    | MAR11539: FAD + H2O + Suberyl Coenzyme A --> FADH2 + 3-Hydoxy-Suberyl Coenzyme A | (ENSG00000113790 and ENSG00000161533) or (ENSG00000104823 and ENSG00000161533) | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000161533 is involved in the peroxisomal beta-oxidation of very-long-chain fatty acids and catalyzes reactions resulting in the production of 2-trans-enoyl-CoAs and hydrogen peroxide (H2O2) using O2 as a substrate. The provided reaction, however, involves FAD, H2O, and Suberyl Coenzyme A transforming into FADH2 and 3-Hydroxy-Suberyl Coenzyme A, which is not mentioned as a substrate or a product in the catalytic activities of the gene ENSG00000161533, indicating they do not share involvement in the same biochemical pathway. | ~~No~~ Yes |

**Comment by feiranl** [comment]
[ENSG00000161533](https://www.ebi.ac.uk/complexportal/complex/search?query=Q15067&minConfidence=1#view_navigator) is a subunit of the complex, so it shouldn't be removed from MAR06285.  ENSG00000176454 the function is right for MAR08521. 
As for the ENSG00000161533 for MAR11539, I would not remove it, since the main substrate and product matches with Uniprot annotation.  3-hydroxyacyl-CoA in the UniProt annotation is the the alternative name for 3-Hydoxy-Suberyl Coenzyme A.

**Comment by JHL-452b** [comment]
> [ENSG00000161533](https://www.ebi.ac.uk/complexportal/complex/search?query=Q15067&minConfidence=1#view_navigator) is a subunit of the complex, so it shouldn't be removed from MAR06285. ENSG00000176454 the function is right for MAR08521.
As for the ENSG00000161533 for MAR11539, I would not remove it, since the main substrate and product matches with Uniprot annotation. 3-hydroxyacyl-CoA in the UniProt annotation is the the alternative name for 3-Hydoxy-Suberyl Coenzyme A.

Totally agree. They will not be modified any further.

**Comment by feiranl** [comment]
@edkerk Due to your expertise in lipid, maybe you can also check this? Thanks!

**Comment by edkerk** [comment]
1. But the grRule of MAR06285 states (translated to UniProt IDs): `P09110 and Q08426 and P51659 and Q15067`, which is different from the [complexes on ComplexPortal that involve `Q15067`](https://www.ebi.ac.uk/complexportal/complex/search?query=Q15067) (which is ACOX1, or ENSG00000161533).

   Therefore, I'm not convinced that ENSG00000161533 is a part of the MAR06285 complex.

2. For MAR11539 I agree to keep ENSG00000161533.
3. By removing ENSG00000135929 from MAR04838 and MAR04839, there will be no genes associated to these reactions anymore. Should these reactions then be removed? [KEGG](https://www.genome.jp/pathway/hsa00564+2.1.1.103) also does not have any human genes associated to these reactions: 
<img width="94" alt="image" src="https://github.com/user-attachments/assets/eba2f2ad-b416-4c6c-887d-89e6fe88784a">

**Comment by Devlin-Moyer** [comment]
It is definitely accurate to associate ACOX1 (`ENSG00000161533`) with `MAR02818` (sources: [1](https://link.springer.com/article/10.1023/A:1022540030918), [2](https://www.annualreviews.org/content/journals/10.1146/annurev.nutr.21.1.193)). We decided to make all of the peroxisomal acyl-CoA oxidation reactions reduce FAD to FADH<sub>2</sub> instead of O<sub>2</sub> to H<sub>2</sub>O<sub>2</sub> in #639, which might be why the AI is confused (although the explanation it provides doesn't exactly make sense).

I already identified that ACOX1 (`ENSG00000161533`) should not be associated with `MAR03291` back in #634, but the reason is that ACOX1 is strictly peroxisomal and `MAR03291` happens in the mitochondrial compartment, not that ACOX1 can't catalyze that reaction.

`MAR06285` combines all four steps of a single round of beta-oxidation into a single reaction, so it's perfectly accurate to associate ACOX1 with that reaction, since it's responsible for the first step (sources: [1](https://link.springer.com/article/10.1023/A:1022540030918), [2](https://www.annualreviews.org/content/journals/10.1146/annurev.nutr.21.1.193)). However, I see other issues with the GPR:
1. [ACOX3](https://www.uniprot.org/uniprotkb/O15254/entry) (`ENSG00000087008`) is also capable of catalyzing the first step of beta-oxidation of dicarboxylic acids in peroxisomes, so it should be ORed together with ACOX1
2. [EHHADH](https://www.uniprot.org/uniprotkb/Q08426/entry) (`ENSG00000113790`) and [HSD17B4](https://www.uniprot.org/uniprotkb/P51659/entry) (`ENSG00000133835`) are both independently capable of catalyzing the second and third steps of beta-oxidation (2-trans-enoyl hydration and 3-hydroxyacyl oxidation), so they should be ORed and not ANDed together
3. [SCP2](https://www.uniprot.org/uniprotkb/P22307/entry) (`ENSG00000116171`) is also capable of 3-ketoacyl thiolysis in peroxisomes, so it should be ORed together with ACAA1 (`ENSG00000060971`)

So overall, I would change the GPR of `MAR06285` to
`(ACOX1 or ACOX3) and (EHHADH or HSD17B4) and (ACAA1 or SCP2)`, that is `(ENSG00000161533 or ENSG00000087008) and (ENSG00000113790 or ENSG00000133835) and (ENSG00000060971 or ENSG00000116171)'

There's a similar situation with `MAR11539`: it combines the first two steps of a single round of beta-oxidation, so it's accurate to associate it with ACOX1 and EHHADH, but ACOX3 and HSD17B4 should also be in that GPR, as with `MAR06285`. However, [ECH1](https://www.uniprot.org/uniprotkb/Q13011/entry) (`ENSG00000104823`) shouldn't be here; it only catalyzes isomerization of 3,5-dienoyl-CoAs and 2,4-dienoyl-CoAs (more sources since Uniprot only annotates its function "by similarity": [1](https://doi.org/10.1006/geno.1995.1077), [2](https://www.biorxiv.org/content/10.1101/821637v1.full)), which only get produced during beta-oxidation of unsaturated fatty acids, and suberyl-CoA is fully saturated. So I would change the GPR of `MAR11539` to `(ACOX1 or ACOX3) and (EHHADH or HSD17B4)`, i.e. `(ENSG00000161533 or ENSG00000087008) and (ENSG00000113790 or ENSG00000133835)`

**Comment by Devlin-Moyer** [comment]
the AI is right about ACOT4 (`ENSG00000177465`) not belonging in the GPR of `MAR03887`, but all of the other genes except SLC27A2 (`ENSG00000140284`) should also be removed, because that reaction is in the peroxisomal compartment, and, [as far as I can tell](https://docs.google.com/spreadsheets/d/1tnUP4tQhDjZLIyAdnm2oPrflGHCt0QPS_uXUW-_6A_g/edit?gid=664978885#gid=664978885), SLC27A2 is the only human acyl-CoA synthetase conclusively known to be localized to peroxisomes

**Comment by JHL-452b** [comment]
> the AI is right about ACOT4 (`ENSG00000177465`) not belonging in the GPR of `MAR03887`, but all of the other genes except SLC27A2 (`ENSG00000140284`) should also be removed, because that reaction is in the peroxisomal compartment, and, [as far as I can tell](https://docs.google.com/spreadsheets/d/1tnUP4tQhDjZLIyAdnm2oPrflGHCt0QPS_uXUW-_6A_g/edit?gid=664978885#gid=664978885), SLC27A2 is the only human acyl-CoA synthetase conclusively known to be localized to peroxisomes

Sorry I didn't find `MAR03887` in my list, maybe you meant `MAR03387`. If it is `MAR03387`, agree to keep only `SLC27A2` as its GPR.

**Comment by Devlin-Moyer** [comment]
yep sorry that was a typo; I meant `MAR03387`

**Comment by JHL-452b** [comment]
OK, I get all your points now. In summary, 

- `ENSG00000161533` should not be removed from MAR06285;
- `ENSG00000176454` should not be removed from MAR08521;
- `ENSG00000161533` should not be removed from MAR11539;
- `ENSG00000161533` should not be removed from MAR02818;
- the GPR of MAR06285 could be `(ENSG00000161533 or ENSG00000087008) and (ENSG00000113790 or ENSG00000133835) and (ENSG00000060971 or ENSG00000116171)`;
- the GPR of MAR11539 could be `(ENSG00000161533 or ENSG00000087008) and (ENSG00000113790 or ENSG00000133835)`;
- the GPR of MAR03387 should only keep `ENSG00000140284`.

All entries that the AI ​​judged incorrectly are updated in the check column of the list.

**Comment by JHL-452b** [comment]
Fixed by #928
