### ISSUE TITLE
GPR curation for Fructose and mannose metabolism/Galactose metabolism

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#849]
#### Current behavior:

20 genes are discovered to be uncorrelated with their corresponding reactions in `Fructose and mannose metabolism`/`Galactose metabolism`.

| Gene| UniProtID | Reaction | GPR | Correlation | Manually check |
|------|-----------|-------|------------|----------|----------------|
| ENSG00000138030 | [P50053](https://www.uniprot.org/uniprotkb/P50053/entry)    | MAR01472: ATP + D-tagatose --> ADP + H+ + D-Tagatose 1-Phosphate | ENSG00000138030 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000138030 catalyzes the phosphorylation of fructose to fructose-1-phosphate. The reaction described involves the conversion of ATP and D-tagatose into ADP, H+, and D-tagatose 1-phosphate, which differs from the gene's specified function involving fructose. Therefore, the gene does not relate to the given reaction.| ~~No~~ Yes, PMID: 2469615, PMID: 19158351 |
| ENSG00000171298 | [P10253](https://www.uniprot.org/uniprotkb/P10253/entry) | MAR04303: H2O + sucrose --> fructose + glucose| ENSG00000090402 or ENSG00000171298 or ENSG00000214013 or ENSG00000257335 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000171298 is involved in the degradation of glycogen in lysosomes, specifically hydrolyzing alpha-1,4 and alpha-1,6 glycosidic linkages to release glucose. In contrast, the reaction provided involves the hydrolysis of sucrose into fructose and glucose, which is not the function of this gene. Thus, the gene and the reaction are not related.| No |
| ENSG00000198074 | [O60218](https://www.uniprot.org/uniprotkb/O60218/entry)    | MAR04316: D-glucitol + NADP+ <=> glucose + H+ + NADPH | ENSG00000085662 or ENSG00000198074 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000198074 catalyzes several NADPH-dependent reductions of various carbonyl-containing compounds to their corresponding alcohols but has no reductase activity towards glucose. The provided reaction involves D-glucitol (also known as sorbitol), which is converted to glucose, an activity not associated with the gene based on the given annotation. The reaction relevant to the gene involves retinal isomers and other specific carbonyl compounds, not glucose or sorbitol.| No |
| ENSG00000141560 | [Q9HA64](https://www.uniprot.org/uniprotkb/Q9HA64/entry)    | MAR04317: ATP + D-glucitol --> ADP + H+ + sorbitol-3-phosphate | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000141560 encodes for a ketosamine-3-kinase that is involved in the phosphorylation of ribuloselysine and psicoselysine on glycated proteins, generating ribuloselysine-3 phosphate and psicoselysine-3 phosphate, respectively. It does not phosphorylate fructoselysine. The catalytic activities of the gene product are specific to these substrates and do not include D-glucitol, which is involved in the provided reaction that converts ATP and D-glucitol to ADP, H+, and sorbitol-3-phosphate. Therefore, the gene and the reaction are not related. | No |
| ENSG00000172456 | [Q96C11](https://www.uniprot.org/uniprotkb/Q96C11/entry)    | MAR04317: ATP + D-glucitol --> ADP + H+ + sorbitol-3-phosphate| ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000172456 encodes a protein that catalyzes the ATP-dependent phosphorylation of D-ribulose at C-5 to form D-ribulose 5-phosphate, which is related to the pentose phosphate pathway. In contrast, the reaction provided involves the phosphorylation of D-glucitol to form sorbitol-3-phosphate. Therefore, the specific substrate and product of the gene's catalytic activity are different from those of the reaction provided, indicating that the gene's function does not match the given reaction.| No |
| ENSG00000167363 | [Q9H479](https://www.uniprot.org/uniprotkb/Q9H479/entry)    | MAR04317: ATP + D-glucitol --> ADP + H+ + sorbitol-3-phosphate | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000167363 encodes an enzyme that phosphorylates fructoselysine residues, psicosamines, and ribulosamines on glycated proteins, leading to the production of corresponding 3-phosphate derivatives and ADP. However, the provided reaction involves the phosphorylation of D-glucitol (sorbitol) to produce sorbitol-3-phosphate and ADP, which is not a recognized substrate or function of the enzyme encoded by ENSG00000167363. Therefore, the gene and the reaction are not related. | No |
| ENSG00000162408 | [Q5SY16](https://www.uniprot.org/uniprotkb/Q5SY16/entry)    | MAR04317: ATP + D-glucitol --> ADP + H+ + sorbitol-3-phosphate  | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000162408 encodes for a polynucleotide kinase involved in phosphorylating the 5'-hydroxyl groups of RNA and DNA substrates. It plays a role in rRNA processing and requires kinase activity for generating specific rRNA forms. The annotated reactions catalyzed by this gene involve the phosphorylation of DNA and RNA, specifically converting 5'-end dephospho nucleosides into 5'-monophospho nucleosides using ATP. However, the reaction provided (ATP + D-glucitol --> ADP + H+ + sorbitol-3-phosphate) involves the phosphorylation of D-glucitol to produce sorbitol-3-phosphate, which is unrelated to the nucleic acid phosphorylation activities of the polynucleotide kinase. Therefore, the gene and the reaction are not related. | No  |
| ENSG00000141560 | [Q9HA64](https://www.uniprot.org/uniprotkb/Q9HA64/entry)    | MAR04318: ATP + fructose --> ADP + fructose-3-phosphate + H+  | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000141560 encodes for a ketosamine-3-kinase involved in the deglycation of proteins by phosphorylating ribuloselysine and psicoselysine to produce ribuloselysine-3-phosphate and psicoselysine-3-phosphate, respectively. It does not phosphorylate fructoselysine and is not involved in the phosphorylation of fructose to fructose-3-phosphate, which is the reaction provided. Thus, the gene and the reaction are not related.| No |
| ENSG00000162408 | [Q5SY16](https://www.uniprot.org/uniprotkb/Q5SY16/entry)    | MAR04318: ATP + fructose --> ADP + fructose-3-phosphate + H+ | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000162408 encodes a polynucleotide kinase involved in phosphorylating the 5'-hydroxyl groups of RNA and DNA substrates, and is essential for rRNA processing. The catalytic activities of this enzyme include phosphorylation reactions utilizing ATP, producing 5'-monophospho-ribonucleoside and deoxyribonucleoside products. On the other hand, the reaction described involves ATP and fructose, converting them into ADP, fructose-3-phosphate, and H+. This reaction pertains to carbohydrate metabolism and not nucleic acid processing, indicating that the gene's function does not align with the provided reaction. Therefore, the gene is not relevant to the reaction provided.  | No |
| ENSG00000116199 | [O75063](https://www.uniprot.org/uniprotkb/O75063/entry)    | MAR04318: ATP + fructose --> ADP + fructose-3-phosphate + H+| ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000116199 encodes an enzyme responsible for the 2-O-phosphorylation of xylose in the glycosaminoglycan-protein linkage region of proteoglycans. Its specific catalytic activity involves the modification of the glycosaminoglycan-protein linkage region by phosphorylating xylose residues. This activity is directly related to the synthesis and maturation of glycosaminoglycan chains. In contrast, the provided reaction involves the phosphorylation of fructose to form fructose-3-phosphate using ATP. This reaction is not related to the function or activity of the enzyme encoded by the gene ENSG00000116199, as it does not involve glycosaminoglycan synthesis or the phosphorylation of xylose. Therefore, the gene and the reaction are not related. | No |
| ENSG00000141560 | [Q9HA64](https://www.uniprot.org/uniprotkb/Q9HA64/entry)     | MAR04320: ATP + mannose-1-phosphate --> ADP + D-mannose-1,6-bisphosphate + H+ | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000141560 encodes for a ketosamine-3-kinase involved in protein deglycation by phosphorylating ribuloselysine and psicoselysine on glycated proteins, producing ribuloselysine-3 phosphate and psicoselysine-3 phosphate. In contrast, the provided reaction describes the conversion of ATP and mannose-1-phosphate to ADP, D-mannose-1,6-bisphosphate, and H+, which does not involve ribuloselysine, psicoselysine, or their phosphorylation. Thus, the gene's function is not related to the reaction.| No|
| ENSG00000172456 | [Q96C11](https://www.uniprot.org/uniprotkb/Q96C11/entry)    | MAR04320: ATP + mannose-1-phosphate --> ADP + D-mannose-1,6-bisphosphate + H+ | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene, ENSG00000172456, is involved in the ATP-dependent phosphorylation of D-ribulose to form D-ribulose 5-phosphate, which is associated with metabolite repair and the pentose phosphate pathway. However, the reaction provided involves ATP and mannose-1-phosphate forming ADP and D-mannose-1,6-bisphosphate, which does not align with the gene's annotated function or catalytic activity. Therefore, the gene is not related to this reaction. | No|
| ENSG00000167363 | [Q9H479](https://www.uniprot.org/uniprotkb/Q9H479/entry)    | MAR04320: ATP + mannose-1-phosphate --> ADP + D-mannose-1,6-bisphosphate + H+ | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000167363 encodes for fructosamine-3-kinase, which is involved in the phosphorylation of fructoselysine residues on glycated proteins and is involved in protein deglycation. The catalytic activities associated with this gene include reactions involving ATP and glycated lysine residues, such as fructosyl-lysine, ribulosyl-lysine, and psicosyl-lysine. However, the reaction provided involves ATP and mannose-1-phosphate to produce ADP and D-mannose-1,6-bisphosphate, which is not related to the enzymatic activities described for fructosamine-3-kinase, thus making the gene irrelevant to the provided reaction.| No |
| ENSG00000162408 | [Q5SY16](https://www.uniprot.org/uniprotkb/Q5SY16/entry)    | MAR04320: ATP + mannose-1-phosphate --> ADP + D-mannose-1,6-bisphosphate + H+ | ENSG00000116199 or ENSG00000141560 or ENSG00000162408 or ENSG00000167363 or ENSG00000172456 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000162408 encodes a polynucleotide kinase involved in phosphorylating the 5'-hydroxyl groups of RNA and DNA substrates and is required for the processing of rRNA. The annotated catalytic activities specifically involve reactions where ATP phosphorylates dephospho-ribonucleosides and deoxyribonucleosides. In contrast, the provided reaction involves the conversion of ATP and mannose-1-phosphate to ADP, D-mannose-1,6-bisphosphate, and H+, which is unrelated to the polynucleotide kinase activity and rRNA processing functions of ENSG00000162408. | No |
| ENSG00000100413 | [Q9Y535](https://www.uniprot.org/uniprotkb/Q9Y535/entry)    | MAR04385: mannose-6-phosphate --> mannose-1-phosphate  | ENSG00000100413 or ENSG00000100417 or ENSG00000140650 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000100413 encodes a protein that functions as part of the DNA-dependent RNA polymerase III complex, which is involved in the transcription of DNA into RNA. This process is unrelated to the enzymatic reaction of converting mannose-6-phosphate to mannose-1-phosphate. | No |
| ENSG00000164068 | [Q5XPI4](https://www.uniprot.org/uniprotkb/Q5XPI4/entry)    | MAR04386: GDP + H+ + mannose-1-phosphate --> GDP-mannose + Pi | ENSG00000164068 or ENSG00000173540 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000164068 encodes a protein that functions as a catalytic subunit of the KPC complex, acting as an E3 ubiquitin-protein ligase. It is involved in processes such as the degradation of CDKN1B, regulation of NF-kappa-B signaling, and inhibition of antiviral signaling, all of which are unrelated to the reaction provided. The reaction described involves the conversion of GDP, H+, and mannose-1-phosphate to GDP-mannose and Pi, which is a different biochemical pathway involving nucleotide sugar metabolism and not linked to ubiquitination or proteasomal degradation. | No |
| ENSG00000116783 | [Q59H18](https://www.uniprot.org/uniprotkb/Q59H18/entry)    | MAR04401: GTP + H+ + L-fucose-1-phosphate --> GDP-L-fucose + PPi | ENSG00000116783 or ENSG00000254685 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000116783 is involved in the phosphorylation of proteins at serine and threonine residues, as indicated by its catalytic activity involving ATP and L-seryl-[protein] or L-threonyl-[protein]. In contrast, the provided reaction involves GTP and L-fucose-1-phosphate to produce GDP-L-fucose and PPi, which is unrelated to the phosphorylation processes catalyzed by the gene. Therefore, the functions and catalytic activities of the gene do not match the described reaction.| No |
| ENSG00000241343 | [P83881](https://www.uniprot.org/uniprotkb/P83881/entry)    | MAR04416: galactosylglycerol + H2O --> galactose + glycerol | ENSG00000102393 or ENSG00000170266 or ENSG00000241343 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000241343 encodes a component of the large ribosomal subunit, which is responsible for protein synthesis. It has no catalytic activity related to the hydrolysis reaction of galactosylglycerol into galactose and glycerol. Therefore, the gene and the reaction are not related. | No |
| ENSG00000138030 | [P50053](https://www.uniprot.org/uniprotkb/P50053/entry)    | MAR08761: ATP + D-tagatose --> ADP + D-tagatose-6-phosphate + H+| ENSG00000138030 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000138030 encodes an enzyme that catalyzes the phosphorylation of fructose to fructose-1-phosphate using ATP, as evidenced by PubMed:12941785. This enzyme's catalytic activity involves converting beta-D-fructose to beta-D-fructose 1-phosphate. However, the provided reaction involves the conversion of D-tagatose to D-tagatose-6-phosphate with ATP. The catalytic activity of the gene's enzyme does not overlap with the conversion of D-tagatose, indicating that the gene is not relevant to this specific reaction. | ~~No~~ Yes, PMID: 2469615, PMID: 19158351 |
| ENSG00000198074 | [O60218](https://www.uniprot.org/uniprotkb/O60218/entry)    | MAR08766: galactose + H+ + NADPH <=> galactitol + NADP+| ENSG00000085662 or ENSG00000198074 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000198074 catalyzes the NADPH-dependent reduction of various carbonyl-containing compounds to their corresponding alcohols, including reactions involving retinol isomers, hydroxynonenal, hexenal, and prenol. However, the gene displays no catalytic activity towards glucose, whereas the reaction provided involves the conversion of galactose to galactitol, which is not among the substrates specified in the gene's annotated catalytic activities. Hence, the gene does not relate to the provided reaction. | No |

**Comment by feiranl** [comment]
removing ENSG00000138030 would gives no gene to rxn MAR08761. Then we need to be very careful about this kind of rxn.  I double checked that the related literature. I found these [two](https://faseb.onlinelibrary.wiley.com/doi/abs/10.1096/fasebj.3.7.2469615) [papers](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2653686/#r32). So it seems that we should keep the gene for the rxn. Others seems ok to me. Please go ahead to make changes.

**Comment by JHL-452b** [comment]
It looks fine to me to keep `ENSG00000138030` in MAR08761, and those two paper would add to the references of MAR08761.

**Comment by JHL-452b** [comment]
Fixed by #886
