### ISSUE TITLE
GPR curation for Bile acid biosynthesis/Bile acid recycling

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#856]
#### Current behavior:

31 genes are discovered to be uncorrelated with their corresponding reactions in `Bile acid biosynthesis`/`Bile acid recycling`

| Gene | UniProtID | Reaction | GPR | Correlation | Manually check |
|------|-------------|-----------|-------|----------|---------|
| ENSG00000130822 | [Q6P2M8](https://www.uniprot.org/uniprotkb/Q6P2M8/entry) | MAR01659: ATP + choloyl-CoA + H2O --> ADP + choloyl-CoA + H+ + Pi | ENSG00000067829 or ENSG00000067840 or ENSG00000101986 or ENSG00000130821 or ENSG00000130822 or ENSG00000184343 or ENSG00000185825| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000130822 encodes a calcium/calmodulin-dependent protein kinase, which phosphorylates proteins at serine and threonine residues using ATP. This is evident from its catalytic activities, which involve transferring a phosphate group from ATP to L-seryl-[protein] or L-threonyl-[protein]. However, the reaction provided involves ATP, choloyl-CoA, water, ADP, choloyl-CoA, hydrogen ions, and inorganic phosphate, which does not align with the phosphorylation of protein serine or threonine residues. Thus, the gene's function and the given reaction are not related.| No|
| ENSG00000119673 | [P49753](https://www.uniprot.org/uniprotkb/P49753/entry) | MAR01716: chenodeoxycholoyl-CoA + H2O --> chenodiol + CoA + H+ | ENSG00000097021 or ENSG00000119673 or ENSG00000136881 or ENSG00000177465 or ENSG00000184227 or ENSG00000205669| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000119673 encodes an enzyme that catalyzes the hydrolysis of acyl-CoAs into free fatty acids and coenzyme A (CoASH). It primarily acts on long chain acyl CoAs (C14-C20) and is involved in enhancing hepatic fatty acid oxidation in mitochondria. However, the reaction provided involves "chenodeoxycholoyl-CoA + H2O --> chenodiol + CoA + H+", which is a different substrate and product. The mentioned gene's function and catalytic activities do not include the hydrolysis of chenodeoxycholoyl-CoA to chenodiol and CoA, making it not relevant to the reaction provided.| No, the GPR of MAR01716 should be `ENSG00000184227 or ENSG00000097021 or ENSG00000136881` |
| ENSG00000119673 | [P49753](https://www.uniprot.org/uniprotkb/P49753/entry) | MAR01718: chenodeoxycholoyl-CoA + H2O --> chenodiol + CoA + H+| ENSG00000097021 or ENSG00000119673 or ENSG00000136881 or ENSG00000177465 or ENSG00000184227 or ENSG00000205669| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000119673 encodes an enzyme that catalyzes the hydrolysis of various acyl-CoAs into free fatty acids and coenzyme A (CoASH), specifically exhibiting high activity towards long-chain acyl CoAs ranging from C10 to C20, including reactions such as the hydrolysis of hexadecanoyl-CoA, tetradecanoyl-CoA, octadecanoyl-CoA, and others. However, the provided reaction involves the hydrolysis of chenodeoxycholoyl-CoA to chenodiol and CoA, which is not listed among the catalytic activities demonstrated by the gene in question. Therefore, the gene is not related to the specific reaction provided.| No, the GPR of MAR01718 should be `ENSG00000177465 or ENSG00000101473 or ENSG00000136881`|
| ENSG00000140284 | [O14975](https://www.uniprot.org/uniprotkb/O14975/entry) | MAR01726: ATP + chenodiol + CoA --> AMP + chenodeoxycholoyl-CoA + PPi | ENSG00000083807 or ENSG00000140284| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000140284 mediates the import of long-chain fatty acids (LCFA) and catalyzes the ATP-dependent formation of fatty acyl-CoA using LCFA and very-long-chain fatty acids (VLCFA) as substrates. However, the reaction provided involves the formation of chenodeoxycholoyl-CoA from chenodiol, ATP, and CoA, which does not match any of the catalytic activities associated with this gene, therefore indicating that the gene is not relevant to this specific reaction.| No|
| ENSG00000170786 | [Q8N3Y7](https://www.uniprot.org/uniprotkb/Q8N3Y7/entry) | MAR01813: 3alpha,7alpha,12alpha,25-tetrahydroxy-5beta-cholestane-24-one + H+ + NADPH <=> 5beta-cholestane-3alpha,7alpha,12alpha,24s,25-pentol + NADP+ | ENSG00000087076 or ENSG00000099377 or ENSG00000100867 or ENSG00000109854 or ENSG00000121039 or ENSG00000138400 or ENSG00000139988 or ENSG00000145439 or ENSG00000159692 or ENSG00000160439 or ENSG00000164039 or ENSG00000167733 or ENSG00000170426 or ENSG00000170786 or ENSG00000176387 or ENSG00000183921 or ENSG00000184860 or ENSG00000186153 or ENSG00000187134 or ENSG00000197894 or ENSG00000198074 or ENSG00000198189 or ENSG00000198610 or ENSG00000204228 or ENSG00000227471 or ENSG00000240857 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000170786 encodes an oxidoreductase that specifically catalyzes the oxidation of all-trans-retinol to all-trans-retinaldehyde using NAD(+) as a cofactor, and it does not act on substrates like 11-cis-retinol or 11-cis-retinaldehyde. However, the reaction provided involves different substrates and cofactors, specifically the conversion of 3alpha,7alpha,12alpha,25-tetrahydroxy-5beta-cholestane-24-one to 5beta-cholestane-3alpha,7alpha,12alpha,24s,25-pentol using NADPH. Therefore, the gene's function does not match the reaction described.| No|
| ENSG00000160439 | [Q8NBN7](https://www.uniprot.org/uniprotkb/Q8NBN7/entry) | MAR01813: 3alpha,7alpha,12alpha,25-tetrahydroxy-5beta-cholestane-24-one + H+ + NADPH <=> 5beta-cholestane-3alpha,7alpha,12alpha,24s,25-pentol + NADP+ | ENSG00000087076 or ENSG00000099377 or ENSG00000100867 or ENSG00000109854 or ENSG00000121039 or ENSG00000138400 or ENSG00000139988 or ENSG00000145439 or ENSG00000159692 or ENSG00000160439 or ENSG00000164039 or ENSG00000167733 or ENSG00000170426 or ENSG00000170786 or ENSG00000176387 or ENSG00000183921 or ENSG00000184860 or ENSG00000186153 or ENSG00000187134 or ENSG00000197894 or ENSG00000198074 or ENSG00000198189 or ENSG00000198610 or ENSG00000204228 or ENSG00000227471 or ENSG00000240857 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000160439 encodes for a retinol dehydrogenase which specifically catalyzes the conversion of all-trans-retinol to all-trans-retinal and vice versa, with a preference for NADP. The provided reaction involves 3alpha,7alpha,12alpha,25-tetrahydroxy-5beta-cholestane-24-one and 5beta-cholestane-3alpha,7alpha,12alpha,24s,25-pentol, which are not substrates for retinol dehydrogenase. Thus, the gene does not catalyze the reaction mentioned.| No|
| ENSG00000136750 | [Q05329](https://www.uniprot.org/uniprotkb/Q05329/entry) | MAR03910: 3-sulfinoalanine + 2.0 H+ --> CO2 + hypotaurine | ENSG00000128683 or ENSG00000136750 or ENSG00000139631| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000136750 encodes an enzyme that catalyzes the production of GABA from L-glutamate, according to the provided annotation. The reaction specified, "3-sulfinoalanine + 2.0 H+ --> CO2 + hypotaurine," does not involve L-glutamate or the production of GABA, indicating a different biochemical pathway. Therefore, based on the gene function and catalytic activity, there is no relation between this gene and the specified reaction. | No |
| ENSG00000128683 | [Q99259](https://www.uniprot.org/uniprotkb/Q99259/entry) | MAR08065: H+ + L-cysteate --> CO2 + taurine| ENSG00000128683 or ENSG00000136750 or ENSG00000139631| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000128683 encodes an enzyme that catalyzes the conversion of L-glutamate to gamma-aminobutyric acid (GABA) and CO2. This reaction is different from the given reaction, which involves the conversion of L-cysteate to taurine and CO2. Therefore, the gene and the reaction are unrelated. | No|
| ENSG00000136750 | [Q05329](https://www.uniprot.org/uniprotkb/Q05329/entry) | MAR08065: H+ + L-cysteate --> CO2 + taurine| ENSG00000128683 or ENSG00000136750 or ENSG00000139631| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000136750 encodes an enzyme that catalyzes the conversion of L-glutamate to 4-aminobutanoate (GABA) and CO2. However, the reaction in question is the conversion of H+ and L-cysteate to CO2 and taurine, which is different from the reaction catalyzed by the enzyme encoded by the gene. Hence, the gene and the reaction are not related.| No|
| ENSG00000138135 | [O95992](https://www.uniprot.org/uniprotkb/O95992/entry) | MAR01786: cholesterol + H+ + NADPH + O2 --> 26-hydroxycholesterol + H2O + NADP+| ENSG00000138135| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000138135 encodes an enzyme that catalyzes the formation of 25-hydroxycholesterol from cholesterol. However, the reaction provided describes the conversion of cholesterol to 26-hydroxycholesterol. This indicates a different enzymatic activity and substrate specificity, thus making the gene irrelevant to the specified reaction.| 25-hydroxycholesterol and 26-hydroxycholesterol are too similar to be determinated. change the GPR of MAR01786 into `ENSG00000135929` |
| ENSG00000130821 | [P48029](https://www.uniprot.org/uniprotkb/P48029/entry) | MAR01659: ATP + choloyl-CoA + H2O --> ADP + choloyl-CoA + H+ + Pi| ENSG00000067829 or ENSG00000067840 or ENSG00000101986 or ENSG00000130821 or ENSG00000130822 or ENSG00000184343 or ENSG00000185825| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000130821 encodes for a creatine:sodium symporter involved in the uptake of creatine, as described in multiple studies. The catalytic activity of this gene's product involves the transport of creatine, chloride, and sodium ions. However, the provided reaction describes the hydrolysis of ATP in conjunction with choloyl-CoA, which is unrelated to the symporter's function in creatine transport. Thus, the gene and the reaction are not related.| No |
| ENSG00000138135 | [O95992](https://www.uniprot.org/uniprotkb/O95992/entry) | MAR01781: cholesterol + H+ + NADPH + O2 --> 20-hydroxycholesterol + H2O + NADP+| ENSG00000138135| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000138135 catalyzes the formation of 25-hydroxycholesterol from cholesterol, not 20-hydroxycholesterol. The reactions described in the gene annotation specifically involve the conversion of cholesterol to 25-hydroxycholesterol, whereas the reaction provided involves the production of 20-hydroxycholesterol, and thus does not relate to the activity of the gene mentioned.| 25-hydroxycholesterol and 26-hydroxycholesterol are too similar to be determinated. |
| ENSG00000203857 | [P14060](https://www.uniprot.org/uniprotkb/P14060/entry) | MAR01783: 20-hydroxycholesterol + NAD+ --> 7alpha-hydroxycholest-4-en-3-one + H+ + NADH| ENSG00000203857 or ENSG00000203859| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000203857 encodes a bifunctional enzyme responsible for the oxidation and isomerization of various 3beta-hydroxy-Delta(5)-steroid precursors to 3-oxo-Delta(4)-steroids, playing a crucial role in steroid hormone biosynthesis. It catalyzes specific reactions involving pregnenolone, progesterone, DHEA, testosterone, and other steroid intermediates with NAD(+) or NADP(+) as electron donors. However, the provided reaction involves the conversion of 20-hydroxycholesterol to 7alpha-hydroxycholest-4-en-3-one, which is not listed among the reactions catalyzed by the enzyme encoded by this gene. Therefore, the gene is not relevant to the reaction. | ~~No~~ Yes|
| ENSG00000023839 | [Q92887](https://www.uniprot.org/uniprotkb/Q92887/entry) | MAR01853: ATP + chenodiol + H2O --> ADP + chenodiol + H+ + Pi| ENSG00000023839 or ENSG00000103222| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. Based on the annotation of the gene ENSG00000023839, its function involves the ATP-dependent transport of various substrates including drugs, toxicants, and endogenous compounds across cell membranes. It specifically transports conjugated organic anions, such as sulfate, glucuronide, glutathione conjugates, and other specific substrates like bilirubin, 17beta-estradiol, leukotriene C4, and taurolithocholate sulfate. However, the reaction provided involves ATP, chenodiol, H2O, ADP, chenodiol, H+, and phosphate, which are not substrates or compounds listed within the gene's annotated functions or catalytic activities. Therefore, the gene's function does not align with the provided reaction. | ~~No~~ Yes |
| ENSG00000103222 | [P33527](https://www.uniprot.org/uniprotkb/P33527/entry) | MAR01853: ATP + chenodiol + H2O --> ADP + chenodiol + H+ + Pi | ENSG00000023839 or ENSG00000103222 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000103222 encodes a protein that mediates the export of various organic anions and drugs from the cytoplasm, including glutathione conjugates, leukotriene C4, sphingosine 1-phosphate, and several anticancer drugs through ATP-dependent mechanisms. However, the reaction provided involves ATP, chenodiol, and forms ADP, chenodiol, H+, and Pi, and there is no evidence or mention of chenodiol being a substrate or product in the catalytic activities associated with the gene. Hence, the gene does not mediate the reaction involving chenodiol. | ~~No~~ Yes|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01875: cholate + GSH + HCO3- <=> cholate + GSH + HCO3- | ENSG00000021488 or ENSG00000084453 or ENSG00000111700 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000021488 encodes a protein that mediates the exchange of cationic and neutral amino acids, specifically involving L-arginine and various other amino acids such as L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. The provided reaction involves cholate, GSH, and HCO3-, which does not correspond to the amino acid exchanges facilitated by the gene-encoded transporter. Therefore, the gene's function does not relate to the reaction involving cholate, GSH, and HCO3-. | No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01877: GSH + HCO3- + taurocholate <=> GSH + HCO3- + taurocholate| ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000021488 is involved in the electrogenic exchange of cationic and neutral amino acids, as evident from multiple catalytic activities listed including reactions involving L-arginine, L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. These processes mainly occur in the context of amino acid transport across cellular membranes. In contrast, the reaction provided involves GSH (glutathione), HCO3- (bicarbonate), and taurocholate, which are not related to the amino acid transport functions described for this gene. Therefore, the gene is not relevant to the reaction provided.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01880: cholate + glutathionyl-leukotriene C4 + HCO3- <=> cholate + glutathionyl-leukotriene C4 + HCO3-| ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000021488 encodes a protein that functions as a transporter complex involved in the electrogenic exchange of cationic and neutral amino acids. The catalytic activities listed are specific to the transport of various amino acids such as L-arginine, L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. The reaction provided, which involves cholate, glutathionyl-leukotriene C4, and bicarbonate (HCO3-), does not involve any of the substrates or products mentioned in the gene's annotated functions. Therefore, there is no connection between the gene and the specific reaction described.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01881: cholate + HCO3- + S-glutathionyl-2-4-dinitrobenzene <=> cholate + HCO3- + S-glutathionyl-2-4-dinitrobenzene| ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000021488 encodes a protein that functions as part of a transporter complex mediating the exchange of cationic and neutral amino acids, with specific catalytic activities involving L-arginine and various amino acids. The reaction described involves cholate, HCO3-, and S-glutathionyl-2-4-dinitrobenzene, which is unrelated to the amino acid exchange functions of the encoded protein. Hence, the gene and the reaction are not related.| No |
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01882: cholate + HCO3- + S-glutathionyl-ethacrynic acid <=> cholate + HCO3- + S-glutathionyl-ethacrynic acid | ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000021488 encodes a protein that functions as a transporter for cationic and neutral amino acids, facilitating their exchange across cellular membranes. Specifically, it is involved in the transport of amino acids such as L-arginine, L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. The provided reaction involves the transformation of cholate and S-glutathionyl-ethacrynic acid with bicarbonate (HCO3-), which does not involve the transport of amino acids but rather a distinct biochemical process. Therefore, the gene's function in amino acid transport does not relate to the provided reaction.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01883: glutathionyl-leukotriene C4 + glycocholate + HCO3- <=> glutathionyl-leukotriene C4 + glycocholate + HCO3- | ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000021488 encodes a protein that facilitates the electrogenic exchange of cationic and neutral amino acids, with specific catalytic activities involving amino acids such as L-arginine, L-leucine, L-histidine, L-phenylalanine, L-cysteine, and L-lysine. The provided reaction involves glutathionyl-leukotriene C4, glycocholate, and bicarbonate (HCO3-), which are not related to the amino acids or transport activities mediated by the gene product. Therefore, the gene's function and the reaction are not related.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01885: glycocholate + HCO3- + S-glutathionyl-ethacrynic acid <=> glycocholate + HCO3- + S-glutathionyl-ethacrynic acid | ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000021488 is involved in forming a transporter complex for exchanging cationic amino acids and neutral amino acids across cellular membranes, with specific catalytic activities involving amino acids such as L-arginine, L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. The reaction provided, which involves glycocholate, HCO3-, and S-glutathionyl-ethacrynic acid, does not involve amino acid transport or exchange, and therefore, is not related to the function or catalytic activities of the gene ENSG00000021488.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01886: chenodiol + glutathionyl-leukotriene C4 + HCO3- <=> chenodiol + glutathionyl-leukotriene C4 + HCO3-| ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000021488 encodes a protein that functions as a transporter involved in the exchange of cationic and neutral amino acids, specifically facilitating the translocation of L-arginine with several amino acids such as L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. This transport activity is driven by substrates like L-cystine and L-arginine. In contrast, the provided reaction involves chemiodiol and glutathionyl-leukotriene C4 along with bicarbonate ions, which are not related to the substrates or the functional mechanism of the transporter encoded by ENSG00000021488.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01887: chenodiol + HCO3- + S-glutathionyl-2-4-dinitrobenzene <=> chenodiol + HCO3- + S-glutathionyl-2-4-dinitrobenzene| ENSG00000021488 or ENSG00000084453 or ENSG00000111700 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000021488 encodes a transporter complex involved in the exchange of amino acids, specifically electrogenic exchange between cationic and neutral amino acids. The gene's activity includes the exchange of L-arginine with other amino acids such as L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine across cellular membranes. The provided reaction involves the interaction of chenodiol, bicarbonate (HCO3-), and S-glutathionyl-2-4-dinitrobenzene, which does not correspond to amino acid exchange or transportation functions described for the gene ENSG00000021488. Thus, there is no functional or catalytic link between the gene's activity and the provided reaction, making the gene irrelevant to the reaction in question. | No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01889: glutathionyl-leukotriene C4 + HCO3- + taurocholate <=> glutathionyl-leukotriene C4 + HCO3- + taurocholate  | ENSG00000021488 or ENSG00000084453 or ENSG00000111700 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000021488 is associated with the electrogenic exchange of cationic and neutral amino acids, primarily involving substrates such as L-arginine, L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. The catalytic activities listed do not involve the substrates or the specific reaction involving glutathionyl-leukotriene C4, HCO3-, and taurocholate. Therefore, the gene is not related to the reaction provided.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01890: HCO3- + S-glutathionyl-2-4-dinitrobenzene + taurocholate <=> HCO3- + S-glutathionyl-2-4-dinitrobenzene + taurocholate| ENSG00000021488 or ENSG00000084453 or ENSG00000111700 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000021488 is associated with forming a transporter complex that mediates the exchange between cationic amino acids and neutral amino acids. Its catalytic activities involve reactions such as the exchange of L-arginine with various other amino acids. However, the provided reaction involving HCO3-, S-glutathionyl-2-4-dinitrobenzene, and taurocholate is not related to the gene's function, as it does not involve the amino acid exchange activities mediated by the gene's product.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01891: HCO3- + S-glutathionyl-ethacrynic acid + taurocholate <=> HCO3- + S-glutathionyl-ethacrynic acid + taurocholate| ENSG00000021488 or ENSG00000084453 or ENSG00000111700 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000021488 encodes a protein that functions as a transporter complex mediating the exchange of cationic and neutral amino acids, with specific catalytic activities involving amino acids such as L-arginine, L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. The provided reaction involves HCO3-, S-glutathionyl-ethacrynic acid, and taurocholate, which are not related to the amino acid transport functions of the encoded protein. Therefore, the gene and the reaction are not related.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01894: HCO3- + S-glutathionyl-ethacrynic acid + taurochenodeoxycholate <=> HCO3- + S-glutathionyl-ethacrynic acid + taurochenodeoxycholate | ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. Based on the annotation of gene ENSG00000021488, the gene encodes a protein that forms a transporter complex involved in the exchange of cationic and neutral amino acids. The documented catalytic activities involve the exchange of L-arginine with other amino acids such as L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. In contrast, the provided reaction involves S-glutathionyl-ethacrynic acid and taurochenodeoxycholate, which are not amino acids and do not align with the gene's described function and catalytic activities. Therefore, the gene and the reaction are not related.| No |
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01876: glycocholate + GSH + HCO3- <=> glycocholate + GSH + HCO3-| ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000021488 encodes a protein that functions as a transporter, mediating the exchange between cationic amino acids and neutral amino acids. Its catalytic activities involve the exchange of L-arginine with various other amino acids such as L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. However, the reaction provided involves glycocholate, GSH, and HCO3-, which are not amino acids and do not participate in the exchanges mediated by the protein encoded by ENSG00000021488. Therefore, the gene is not relevant to the specified reaction.| No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01884: glycocholate + HCO3- + S-glutathionyl-2-4-dinitrobenzene <=> glycocholate + HCO3- + S-glutathionyl-2-4-dinitrobenzene | ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000021488 encodes a protein that forms a transporter complex involved in the exchange of cationic and neutral amino acids, specifically mediating reactions involving L-arginine and other amino acids such as L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. These reactions pertain to amino acid transport. The reaction provided involves glycocholate, bicarbonate (HCO3-), and S-glutathionyl-2-4-dinitrobenzene, which are not related to amino acid transport. Therefore, the gene does not have relevance to this reaction. | No|
| ENSG00000021488 | [P82251](https://www.uniprot.org/uniprotkb/P82251/entry) | MAR01888: chenodiol + HCO3- + S-glutathionyl-ethacrynic acid <=> chenodiol + HCO3- + S-glutathionyl-ethacrynic acid | ENSG00000021488 or ENSG00000084453 or ENSG00000111700| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000021488 encodes a protein that mediates the exchange of cationic and neutral amino acids, including L-arginine, L-leucine, L-histidine, L-phenylalanine, L-cysteine, L-cystine, and L-lysine. The provided reaction involves chenodiol, HCO3-, and S-glutathionyl-ethacrynic acid, which are not substrates or products of the catalytic activities associated with the gene. Therefore, there is no direct connection between the gene's function and the reaction described. | No|

**Comment by Devlin-Moyer** [comment]
the AI is right that ACOT2 (`ENSG00000119673`) shouldn't be in the GPRs of `MAR01716` and `MAR01718`, since ACOT2 is localized to mitochondria and neither reaction happens in the mitochondrial compartment ([source](doi.org/10.1016/j.tem.2017.03.001)), but misses other errors in those GPRs:
- ACOT6 (`ENSG00000205669`) is not known to be catalytically active
- ACOT4 (`ENSG00000177465`) is not localized to the cytosol, but `MAR01716` happens in the cytosolic compartment
- ACOT1 (`ENSG00000184227`) and ACOT7 (`ENSG00000097021`) are not peroxisomal proteins, but `MAR01718` happens in the peroxisomal compartment
- ACOT8 (`ENSG00000101473`) is capable of catalyzing these reactions, is localized to peroxisomes, and is the only ACOT that I could find that's specifically described as capable of acting on bile acid intermediates (like chenodeoxycholoyl-CoA)

so I think that the GPRs should be:
`MAR01716`: ACOT1 or ACOT7 or BAAT (`ENSG00000184227 or ENSG00000097021 or ENSG00000136881`)
`MAR01718`: ACOT4 or ACOT8 or BAAT (`ENSG00000177465 or ENSG00000101473 or ENSG00000136881`)

**Comment by feiranl** [comment]
It may be better to remove `ENSG00000138135` from the reaction `MAR01786`, but we should add another one with a different product. For `MAR01783`, we can keep `ENSG00000203857`; for MAR01853, we should retain `ENSG00000023839` and `ENSG00000103222`, as their patterns are similar, with only slight differences in side chains. As for the other annotations, they seem fine. This issue primarily concerns the incorrect annotation of the amino acid transporter to the bile acid transport reactions.

**Comment by feiranl** [comment]
I agree

**Comment by JHL-452b** [comment]
Fixed by #930
