### ISSUE TITLE
fix: map-guided model curations

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#87]
### Description of the issue:
* The [MetabolicAtlas](https://icsb.chalmers.se) website presents beautifully-drawn [maps](https://icsb.chalmers.se/explore/map-viewer/hmr2) of human metabolism based on **humanGEM**
* During map generation process, some inconsistent cases related to `subSystems`, `compartment` and others are noticed, and will be tabulated here for validation and further modification

#### Current feature/value/output:
* Here are a list of reactions whose `subSystems` need to be checked out based on map analysis:
ALAALACNc
ARACHFATPc
ARACHDFATPtc
CYSAMOe
C4x
C6COAt
CHOLESTle
FMNALKPle
GALFUCGALACGLCGAL14ACGLCGALGLUSIDEtg
GDA1tn
GLYC2P3Pc
GLYGLYCNc
GLYLEUHYDROc
GLYPROPRO1c
GLYSARCNc
HC02220c
HMR_0006
HMR_0007
HMR_0008
HMR_0015
HMR_0016
HMR_0017
HMR_1392
HMR_1919
HMR_2141
HMR_3964
HMR_4184
HMR_7568
LEUGLYHYc
LEULEULAPc
LGNCFATPtc
LINOFATPtc
OCDCAFATPc
OLEICFATPtc
PALFATPtc
PNTEHe
PROGLYPRO1c
PROSTGI2c
PTPATe
SAMHISTAe
TTDCAFATPc
r1146
ATPasel
HMR_2585
HMR_7569

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
From the original list, the following reactions are no longer presented in `reactions.tsv`, meaning they have thus been removed from the model: CHOLESTle.

The remaining list is:
| MA ID | original ID | Current subsystem |
| - | - | - |
| MAR06861 | ALAALACNc | Isolated |
| MAR07807 |  ARACHFATPc | Transport reactions |
| MAR09870 | ARACHDFATPtc | Transport reactions |
| MAR07817 | CYSAMOe | Transport reactions |
| MAR04678 | C4x | Transport reactions |
| MAR04722 | C6COAt | Transport reactions |
| MAR08969 | FMNALKPle | Transport reactions |
| MAR08282 | GALFUCGALACGLCGAL14ACGLCGALGLUSIDEtg | Transport reactions |
| MAR12119 | GDA1tn | Transport reactions |
| MAR09958 | GLYC2P3Pc | Transport reactions |
| MAR06898 | GLYGLYCNc | Transport reactions |
| MAR11411 | GLYLEUHYDROc | Transport reactions |
| MAR11414 | GLYPROPRO1c | Transport reactions |
| MAR06915 | GLYSARCNc | Transport reactions |
| MAR10447 | HC02220c | Transport reactions |
| MAR00006 | HMR_0006 | Transport reactions |
| MAR00007 | HMR_0007 | Transport reactions |
| MAR00008 | HMR_0008 | Transport reactions |
| MAR00015 | HMR_0015 | Transport reactions |
| MAR00016 | HMR_0016 | Transport reactions |
| MAR00017 | HMR_0017 | Transport reactions |
| MAR01392 | HMR_1392 | Transport reactions |
| MAR01919 | HMR_1919 | Transport reactions |
| MAR02141 | HMR_2141 | Transport reactions |
| MAR03964 | HMR_3964 | Transport reactions |
| MAR04184 | HMR_4184 | Transport reactions |
| MAR07568 | HMR_7568 | Transport reactions |
| MAR08979 | LEUGLYHYc | Transport reactions |
| MAR07149 | LEULEULAPc | Transport reactions |
| MAR09894 | LGNCFATPtc | Transport reactions |
| MAR07152 | LINOFATPtc | Transport reactions |
| MAR08983 | OCDCAFATPc | Transport reactions |
| MAR07156 | OLEICFATPtc | Transport reactions |
| MAR07157 | PALFATPtc | Transport reactions |
| MAR08986 | PNTEHe | Transport reactions |
| MAR07193 | PROGLYPRO1c | Transport reactions |
| MAR10395 | PROSTGI2c | Transport reactions |
| MAR08990 | PTPATe | Transport reactions |
| MAR11777 | SAMHISTAe | Transport reactions |
| MAR08996 | TTDCAFATPc | Transport reactions |
| MAR02302 | r1146 | Cholesterol metabolism |
| MAR07799 | ATPasel | Transport reactions |
| MAR02585 | HMR_2585 | Transport reactions |
| MAR07569 | HMR_7569 | Transport reactions |

What would be the suggested plan to resolve the current issue for these reactions?

**Comment by haowang-bioinfo** [comment]
@mihai-sysbio thanks for updating the table. This issue probably can be closed.

PS - was the 2D map disabled on Met Atlas?
