### ISSUE TITLE
GPR curation for Glycolysis / Gluconeogenesis and Pentose and glucuronate interconversions

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#877]
#### Current behavior:

13 genes are discovered to be uncorrelated with their corresponding reactions in `Glycolysis / Gluconeogenesis` and `Pentose and glucuronate interconversions`.

| Gene| UniProtID| Reaction| GPR| Correlation| Manually check |
|-----|----------------|------------|----------|-------|----------------|
| ENSG00000115425 | [Q9BY49](https://www.uniprot.org/uniprotkb/Q9BY49/entry) | MAR04591: NAD+ + xylitol --> H+ + L-xylulose + NADH| ENSG00000115425 or ENSG00000116353| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000115425 encodes for an enzyme involved in the chain elongation of fatty acids, catalyzing the reduction of various trans-2-enoyl-CoAs using NADPH. It shows activity with substrates of different chain lengths but does not process xylitol. The provided reaction involves the conversion of xylitol to L-xylulose using NAD+ and does not involve the substrates or products associated with the enzyme encoded by ENSG00000115425, nor does it utilize NADPH, which is specific to the enzyme's catalytic activity. Thus, the gene and the reaction are not related.| No|
| ENSG00000116353 | [Q9BV79](https://www.uniprot.org/uniprotkb/Q9BV79/entry) | MAR04591: NAD+ + xylitol --> H+ + L-xylulose + NADH| ENSG00000115425 or ENSG00000116353| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000116353 is involved in the NADPH-dependent reduction of trans-2-enoyl thioesters in mitochondrial fatty acid synthesis. It catalyzes multiple reactions involving the transformation of (2E)-enoyl-[ACP] to acyl-[ACP] using NADPH as a reducing agent. However, the provided reaction where NAD+ and xylitol convert to H+, L-xylulose, and NADH does not involve the same substrates or products and does not align with the gene's described function in fatty acid synthesis and enzyme specificity. Therefore, the gene is not relevant to the provided reaction.| No|
| ENSG00000198074 | [O60218](https://www.uniprot.org/uniprotkb/O60218/entry) | MAR04592: D-xylose + H+ + NADPH <=> NADP+ + xylitol| ENSG00000085662 or ENSG00000198074| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000198074 codes for an enzyme that catalyzes the NADPH-dependent reduction of various carbonyl-containing compounds to their corresponding alcohols. It shows enzymatic activity towards specific substrates such as all-trans-retinal, 9-cis-retinal, and 13-cis-retinal, among others. However, the reaction provided involves the conversion of D-xylose to xylitol, which is not among the reactions catalyzed by the enzyme encoded by this gene, according to the provided annotation. There is no evidence supporting the involvement of this gene in the specific reaction of D-xylose to xylitol.| No|
| ENSG00000115652 | [Q8NBZ7](https://www.uniprot.org/uniprotkb/Q8NBZ7/entry) | MAR08729: H2O + UDP-glucuronate --> glucuronate + H+ + UDP| ENSG00000115652| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000115652 encodes an enzyme that catalyzes the NAD-dependent decarboxylation of UDP-glucuronic acid to UDP-xylose, a reaction essential for the biosynthesis of glycosaminoglycans. However, the reaction provided (H2O + UDP-glucuronate --> glucuronate + H+ + UDP) is a hydrolysis reaction, not a decarboxylation reaction, and does not involve the conversion to UDP-xylose, thus indicating the gene is not related to the provided reaction.| No|
| ENSG00000198099 | [P08319](https://www.uniprot.org/uniprotkb/P08319/entry) | MAR03905: ethanol + NAD+ --> acetaldehyde + H+ + NADH| ENSG00000147576 or ENSG00000172955 or ENSG00000180011 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198099 or ENSG00000248144 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000198099 encodes for an enzyme that catalyzes several specific reactions involving all-trans-retinol, 9-cis-retinol, long-chain omega-hydroxy fatty acids, and benzoquinones. However, it does not catalyze the reaction of ethanol with NAD+ to produce acetaldehyde, H+, and NADH. Therefore, the gene and the reaction are not related.| ~~No~~ Yes|
| ENSG00000180011 | [Q8N4Q0](https://www.uniprot.org/uniprotkb/Q8N4Q0/entry) | MAR03905: ethanol + NAD+ --> acetaldehyde + H+ + NADH| ENSG00000147576 or ENSG00000172955 or ENSG00000180011 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198099 or ENSG00000248144 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000180011 encodes an enzyme that functions as a 15-oxo-prostaglandin 13-reductase, which specifically acts on various forms of 15-keto-prostaglandins and catalyzes their conversion in the presence of NADP(+). The annotated catalytic activities include the reduction of 13,14-dihydro-15-oxo-prostaglandin substrates to their respective 15-oxoprostaglandins, generating NADPH in the process. However, the provided reaction, ethanol + NAD+ --> acetaldehyde + H+ + NADH, involves the oxidation of ethanol to acetaldehyde and is not related to the reduction of 15-oxo-prostaglandins handled by the gene product. Therefore, the gene and the provided reaction are not related. | No|
| ENSG00000147576 | [Q8IWW8](https://www.uniprot.org/uniprotkb/Q8IWW8/entry) | MAR03905: ethanol + NAD+ --> acetaldehyde + H+ + NADH| ENSG00000147576 or ENSG00000172955 or ENSG00000180011 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198099 or ENSG00000248144 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000147576 encodes an enzyme that catalyzes the oxidation of gamma-hydroxybutyrate to succinic semialdehyde and the reduction of 2-ketoglutarate to D-2-hydroxyglutarate, as well as similar reactions involving other substrates. However, the given reaction describes the conversion of ethanol to acetaldehyde, which involves NAD+ and NADH. This reaction is not within the scope of the catalytic activities described for the gene ENSG00000147576, indicating they are not related.| No|
| ENSG00000196616 | [P00325](https://www.uniprot.org/uniprotkb/P00325/entry) | MAR03905: ethanol + NAD+ --> acetaldehyde + H+ + NADH| ENSG00000147576 or ENSG00000172955 or ENSG00000180011 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198099 or ENSG00000248144 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000196616 is annotated to catalyze the NAD-dependent oxidation of all-trans-retinol and its derivatives, as well as the reduction of all-trans-retinal and its derivatives. The specified enzymatic activities focus on retinoid metabolism, involving substrates such as all-trans-retinol, all-trans-4-hydroxyretinol, and all-trans-4-oxoretinol. However, the reaction provided involves the conversion of ethanol to acetaldehyde, which is a different biochemical pathway related to alcohol metabolism and not retinoid metabolism. Therefore, the gene's annotated functions do not align with the specified reaction.| ~~No~~ Yes|
| ENSG00000180011 | [Q8N4Q0](https://www.uniprot.org/uniprotkb/Q8N4Q0/entry) | MAR04360: H2O + methylglyoxal + NADP+ --> 2.0 H+ + NADPH + pyruvate| ENSG00000180011| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000180011 codes for a protein that functions as 15-oxo-prostaglandin 13-reductase, which primarily acts on substrates like 15-keto-PGE1, 15-keto-PGE2, 15-keto-PGE1-alpha, and 15-keto-PGE2-alpha. The annotated catalytic activities involve reactions that convert various dihydro-15-oxo-prostaglandins to 15-oxoprostaglandins. In contrast, the provided reaction involves the conversion of methylglyoxal and NADP+ to pyruvate, NADPH, and H+, a process not related to the functions or catalytic activities described for the gene product.| No|
| ENSG00000131482 | [P35575](https://www.uniprot.org/uniprotkb/P35575/entry) | MAR08652: carbamoyl-phosphate + glucose --> CO2 + glucose-6-phosphate + NH3 | ENSG00000131482 or ENSG00000141349 or ENSG00000152254| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000131482 encodes an enzyme that hydrolyzes glucose-6-phosphate to glucose in the endoplasmic reticulum as part of glycogenolysis and gluconeogenesis. The reaction it catalyzes involves glucose-6-phosphate and water, resulting in the production of glucose and phosphate. However, the reaction provided involves carbamoyl-phosphate and glucose resulting in CO2, glucose-6-phosphate, and NH3, which does not match the catalytic activity of the enzyme encoded by ENSG00000131482. Therefore, the gene and the reaction are not related.| No|
| ENSG00000184254 | [P47895](https://www.uniprot.org/uniprotkb/P47895/entry) | MAR04283: acetaldehyde + H2O + NADP+ --> acetate + 2.0 H+ + NADPH| ENSG00000006534 or ENSG00000108602 or ENSG00000132746 or ENSG00000184254                                                                                                | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000184254 encodes for a protein that catalyzes the NAD-dependent oxidation of specific aldehyde substrates such as all-trans-retinal and all-trans-13,14-dihydroretinal to their corresponding carboxylic acids. It has high specificity for all-trans-retinal and can also accept acetaldehyde as a substrate with lower affinity. However, the reaction provided involves the conversion of acetaldehyde to acetate using NADP+ instead of NAD+, which is different from the reactions catalyzed by the gene product. Hence, the gene is not relevant to the reaction provided.                                                                                                             | No|
| ENSG00000141349 | [Q9BUM1](https://www.uniprot.org/uniprotkb/Q9BUM1/entry) | MAR08652: carbamoyl-phosphate + glucose --> CO2 + glucose-6-phosphate + NH3 | ENSG00000131482 or ENSG00000141349 or ENSG00000152254| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000141349 is responsible for hydrolyzing glucose-6-phosphate to glucose in the endoplasmic reticulum, as part of glucose production through glycogenolysis and gluconeogenesis. However, the reaction provided involves carbamoyl-phosphate and glucose producing CO2, glucose-6-phosphate, and NH3, which does not align with the gene¡¯s annotated function or its catalytic activity.| No|
| ENSG00000197894 | [P11766](https://www.uniprot.org/uniprotkb/P11766/entry) | MAR03905: ethanol + NAD+ --> acetaldehyde + H+ + NADH| ENSG00000147576 or ENSG00000172955 or ENSG00000180011 or ENSG00000187758 or ENSG00000196344 or ENSG00000196616 or ENSG00000197894 or ENSG00000198099 or ENSG00000248144 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000197894 encodes for a protein that catalyzes the oxidation of long-chain primary alcohols, S-(hydroxymethyl) glutathione, long chain omega-hydroxy fatty acids, and is required for the clearance of cellular formaldehyde. However, it has been noted that Class-III ADH, which is encoded by this gene, is remarkably ineffective in oxidizing ethanol. The provided reaction, ethanol + NAD+ --> acetaldehyde + H+ + NADH, specifically describes the oxidation of ethanol, a reaction for which this gene's product is not efficient. Therefore, this gene is not relevant to the reaction provided.| ~~No~~ Yes|

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by JHL-452b** [comment]
This guy gives a reply with the malicious link. 😕 To avoid risks, I deleted its reply.

**Comment by feiranl** [comment]
1. - Remove ENSG00000115425 for MAR04591, and ENSG00000116353 for MAR04591 for the same reason.

2.  - Retain ENSG00000198099, ENSG00000196616, and ENSG00000197894 for MAR03905 due to the broader substrate specificity of ADH.

### Good Example for the Manuscript:
- For MAR04591, both ENSG00000115425 and ENSG00000116353 are related to fatty acid metabolism and not the xylitol process.
- For MAR04592, noting that AKR1B10 (ENSG00000198074) differs from AKR1B1 in its inability to reduce glucose and xylose as mentioned in this [reference](https://pmc.ncbi.nlm.nih.gov/articles/PMC3269042/)
- For MAR08729, ENSG00000115652 encodes an enzyme that catalyzes the NAD-dependent decarboxylation of UDP-glucuronic acid to UDP-xylose. However, the given reaction (H2O + UDP-glucuronate → glucuronate + H+ + UDP) is a hydrolysis reaction, not decarboxylation, indicating that the gene is not related to the provided reaction.

**Comment by JHL-452b** [comment]
Fixed by #924
