### ISSUE TITLE
GPR curation for Androgen metabolism and Prostaglandin biosynthesis

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#889]
#### Current behavior:

8 genes are discovered to be uncorrelated with their corresponding reactions in `Androgen metabolism` and `Prostaglandin biosynthesis`.

| Gene| UniProtID| Reaction| GPR| Correlation| Manually check |
|-------|----------------|---------|----------|-----------|----------------|
| ENSG00000163684 | [O95059](https://www.uniprot.org/uniprotkb/O95059/entry) | MAR01321: H2O + prostaglandin A2 <=> prostaglandin E2| ENSG00000163684 or ENSG00000244486| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000163684 encodes a component of ribonuclease P, which is involved in generating mature tRNA molecules by cleaving their 5'-ends. This function is related to RNA processing and has no catalytic activity associated with the conversion of prostaglandin A2 to prostaglandin E2. Therefore, the gene does not participate in the specified enzymatic reaction.| No|
| ENSG00000196139 | [P42330](https://www.uniprot.org/uniprotkb/P42330/entry) | MAR01325: NAD+ + prostaglandin F2alpha --> H+ + NADH + prostaglandin H2| ENSG00000196139| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000196139 encodes an enzyme that primarily catalyzes the reduction of ketosteroids to hydroxysteroids, regulating the metabolism of androgens, estrogens, and progesterone. It exhibits NADH and NADPH-dependent activities but the reaction provided involves NAD+ and prostaglandin F2alpha, leading to H+, NADH, and prostaglandin H2, which does not match any listed activities for this enzyme. Therefore, it is not relevant to the specified reaction.| No|
| ENSG00000163684 | [O95059](https://www.uniprot.org/uniprotkb/O95059/entry) | MAR01395: H2O + prostaglandin A1 <=> prostaglandin E1| ENSG00000163684 or ENSG00000244486| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000163684 encodes a component of ribonuclease P, which is involved in the generation of mature tRNA molecules by cleaving their 5'-ends. This function is not related to the reaction involving the conversion of prostaglandin A1 to prostaglandin E1, indicating no overlap in their biological roles.| No|
| ENSG00000197580 | [Q9BYV7](https://www.uniprot.org/uniprotkb/Q9BYV7/entry) | MAR01959: 17alpha-hydroxypregnenolone + NADPH + O2 --> acetate + dehydroepiandrosterone + H2O + NADP+ | ENSG00000148795 or ENSG00000197580| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000197580 encodes for a mitochondrial dioxygenase that is involved in the oxidative cleavage of carotenoids, such as all-trans-beta-carotene, lycopene, zeaxanthin, lutein, and beta-cryptoxanthin. The catalytic activities annotated for this gene are specific to various carotenoids and their cleavage by O2 to produce different compounds related to carotenoid metabolism. However, the reaction provided involves the conversion of 17alpha-hydroxypregnenolone to dehydroepiandrosterone (DHEA) with the participation of NADPH and O2, which is a different biochemical pathway not related to carotenoid metabolism. Thus, the gene and the reaction are not related.| No|
| ENSG00000197580 | [Q9BYV7](https://www.uniprot.org/uniprotkb/Q9BYV7/entry) | MAR01960: 17alpha-hydroxypregnenolone + NADPH + O2 <=> acetate + dehydroepiandrosterone + H2O + NADP+ | ENSG00000148795 or ENSG00000197580| Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000197580 encodes a mitochondrial dioxygenase that primarily mediates the cleavage of carotenoids such as all-trans-beta-carotene, lycopene, zeaxanthin, lutein, and beta-cryptoxanthin. The described catalytic activities involve reactions where various carotenoids are oxidatively cleaved to produce compounds like beta-ionone and 10'-apo-carotenal. These activities and the associated reactions all involve specific carotenoid substrates and do not pertain to steroid metabolism or reactions involving 17alpha-hydroxypregnenolone, NADPH, and the production of dehydroepiandrosterone. Therefore, there is no relevance between the gene ENSG00000197580 and the provided reaction. | No|
| ENSG00000149084 | [Q53GQ0](https://www.uniprot.org/uniprotkb/Q53GQ0/entry) | MAR01973: 4-androstene-3,17-dione + H+ + NADPH --> NADP+ + testosterone| ENSG00000025423 or ENSG00000086696 or ENSG00000108786 or ENSG00000130948 or ENSG00000132196 or ENSG00000149084 or ENSG00000196139 or ENSG00000198189 or ENSG00000204228 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000149084 encodes an enzyme primarily involved in the fatty acids elongation cycle and the transformation of estrone (E1) into estradiol (E2), as well as 3-ketoacyl-CoA reduction. The provided reaction involves the conversion of 4-androstene-3,17-dione to testosterone, which is not one of the catalytic activities associated with this gene according to the given annotations and evidence. Therefore, the gene and the reaction are not related.| No|
| ENSG00000086696 | [P37059](https://www.uniprot.org/uniprotkb/P37059/entry) | MAR01974: 4-androstene-3,17-dione + H+ + NADPH --> NADP+ + testosterone| ENSG00000025423 or ENSG00000086696 or ENSG00000108786 or ENSG00000130948 or ENSG00000132196 or ENSG00000149084 or ENSG00000196139 or ENSG00000198189 or ENSG00000204228 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation: The gene ENSG00000086696 encodes an enzyme that catalyzes the NAD-dependent oxidation of estradiol, testosterone, dihydrotestosterone, and 20-alpha hydroxysteroids to their less active forms. The reactions mentioned involve the conversion of these steroids using NAD(+) as a cofactor, resulting in the production of NADH. However, the provided reaction involves the conversion of 4-androstene-3,17-dione to testosterone with NADPH as a reducing agent, which is not catalyzed by the enzyme encoded by the gene ENSG00000086696.| No|
| ENSG00000204228 | [Q92506](https://www.uniprot.org/uniprotkb/Q92506/entry) | MAR01974: 4-androstene-3,17-dione + H+ + NADPH --> NADP+ + testosterone| ENSG00000025423 or ENSG00000086696 or ENSG00000108786 or ENSG00000130948 or ENSG00000132196 or ENSG00000149084 or ENSG00000196139 or ENSG00000198189 or ENSG00000204228 | Pending No, the gene is not relevant to the reaction provided. Analysis and explanation. The gene ENSG00000204228 is involved in several enzymatic activities related to the mitochondrial fatty acid synthase (mtFAS) and steroid metabolism, specifically the NAD-dependent conversion of (3R)-3-hydroxyacyl-CoA to 3-oxoacyl-CoA, the conversion of 17beta-estradiol to estrone, testosterone to androst-4-ene-3,17-dione, and 17beta-hydroxy-5alpha-androstan-3-one to 5alpha-androstan-3,17-dione. However, the provided reaction is the reduction of 4-androstene-3,17-dione to testosterone using NADPH, which is not mentioned as one of the catalytic activities associated with this gene. Thus, based on the annotation of the gene, it is not relevant to the provided reaction.| No|

**Comment by hhl-24** [comment]
ENSG00000196139 for MAR01325: NAD+ + prostaglandin F2alpha --> H+ + NADH + prostaglandin H2，Reducing prostaglandin is NADP-dependent, copy this reaction and replace NAD with NADP.

**Comment by JHL-452b** [comment]
Yeah, Agree to remove ENSG00000196139 for MAR01325. But the reduction of prostaglandin with NADP+ has already in Human-GEM. You can refer to [MAR01326](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR01326). So, I think there is no need to replace NAD+ with NADP+ in MAR01325.

**Comment by hhl-24** [comment]
Agree with you.

**Comment by JHL-452b** [comment]
Do you have any different opintions in this issue? @feiranl

**Comment by feiranl** [comment]
Looks good to me! Please go ahead to make commits!

**Comment by JHL-452b** [comment]
Fixed by #935
