### ISSUE TITLE
feat: create a centralized and comprehensive collection of curated enzyme complexes for modeling human metabolism

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#89]
### Description of the issue:
* A milestone of **humanGEM** model curation has been achieved with the release of [Human1](https://github.com/SysBioChalmers/human-GEM/releases/tag/v1.0.0-beta). However, some topics still worth to be revisited, such as the enzyme complex information that deserves a better way of documentation.
* One of the significant progress obtained in Human1 is the incorporation of enzyme complexes, which are derived from a variety of sources: [**CORUM**](http://mips.helmholtz-muenchen.de/corum/), **iHsa**, **Recon3D** and others.
* It is tempting to assemble the various sources of human enzyme complexes into a centralized and comprehensive resource that can thus be continuously refined for modeling purpose, as well as wider utilization.

#### Expected feature/value/output:
* Parse all grRules to get a list of unique complexes, but leave out the exceptional cases whose `grRules` have `or` relations inside parentheses, e.g. `(gene1 or gene2) and (gene3 or gene4)`
* Focus on the manageable cases at the moment and organize them into a defined structure with unique enzyme complexes, associated subunits, original reference publications, source database or GEM name and the reactions that they catalyze
* The data structure for enzyme complexes should be easy to append, remove and modify, if new literatures and experimental evidence is available
* In order to assist the implementation, a tailored function need be developed for updating information from this data structure to the model, whenever the enzyme complex information is updated

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
The expected changes from issue is too complicated to implement, a feasible solution is thus required.

**Comment by haowang-bioinfo** [comment]
better rely on external resources (e.g. [Complex Portal](https://www.ebi.ac.uk/complexportal/home))
