### ISSUE TITLE
function(prepHumanModelForftINIT) 

### ISSUE THREAD

**Issue by phoebe000716** [SysBioChalmers/Human-GEM#897]
Hello, sorry to ask a running problem, when I run this function, will always stay here, stay for 16 h without the next step, the tutorial is written on 2~3h, when I look at the cpu occupancy, found that it is not like computing, how to solve this problem? It will stop at the detection of this reaction
PASS: [ER] Ubiquinol-to-ATP
PASS: [SU] Beta oxidation of saturated FA
PASS: [SU] Beta oxidation of long-chain FA
......

**Comment by JHL-452b** [comment]
I suspect it may be the solver's problem, so I suggest using Gurobi. Some people have encountered similar problems, you can refer to #826.
