### ISSUE TITLE
Clarification about how proteomics data is considered in ftINIT

### ISSUE THREAD

**Issue by nnursimulu** [SysBioChalmers/Human-GEM#926]
Dear code developers and maintainers,

I am interested in performing metabolic reconstruction using ftINIT and proteomics data. However, I am afraid I am finding little guidance for this. Could you please help me out?  In particular,

1. I did find that for making reconstructions using Human Protein Atlas data, I first need to process the data using the function parseHPA. I downloaded sample information from the Human Protein Atlas; however the function appears to rely on the existence of a column called "Expression type". This appears missing in my downloads. Can you please clarify what value this should take?
2. The level of expression ("Level") appears to be one from a set of well-defined values: "Medium", "High", "Low" for instance. Is this relative to the abundance of other proteins in the same sample?
3. Can you please direct me to a resource which explains how the discrete values (as mentioned in 2) are utilized in metabolic reconstruction?

I would be very grateful for your help!

**Comment by feiranl** [comment]
@johan-gson Hi, Johan. Maybe you can answer this? Thanks!

**Comment by johan-gson** [comment]
Hi, for Human Protein Atlas data you use ScoreComplexModel just as for RNA-Seq. I have never done this, but you should be able to supply the HPA data and skip the RNA-Seq

**Comment by johan-gson** [comment]
ftINIT and tINIT should be identical in this regard

**Comment by nnursimulu** [comment]
Thank you very much.
