### ISSUE TITLE
Five genes are not associated with any reactions in the `develop` branch

### ISSUE THREAD

**Issue by JHL-452b** [SysBioChalmers/Human-GEM#938]
In the `develop` branch, I identified five genes—`ENSG00000116882`, `ENSG00000124302`, `ENSG00000133048`, `ENSG00000163684`, and `ENSG00000175229`—that are currently unassociated with any reactions within the model. It appears that these genes were not accounted for in the merge process due to concurrent curation efforts across multiple pull requests.
- `ENSG00000116882`: #915 and #885 ;
- `ENSG00000124302`: #889 and #907 ;
- `ENSG00000133048`: #936 and #931 ;
- `ENSG00000163684`: #935 and #914 ;
- `ENSG00000175229`: #899 and #907 ;

**Comment by feiranl** [comment]
LGTM! please go ahead and make changes
